// QA OPS-003: an off-provider archive must restore every function, policy
// and row. Runs the real export (scripts/offsite-backup.mjs exportCatalog,
// exportDdl, exportData) against a synthetic source database and the real
// restore (scripts/offsite-restore.mjs applySchema, applyData) through psql
// into a fresh database on the same disposable PostgreSQL.
//
// The two defects it pins:
//   * functions are created alphabetically, and a LANGUAGE sql body is
//     checked at CREATE, so admin_operations_can_read() (which calls
//     current_profile_id()) failed and took its policies with it;
//   * a GENERATED ALWAYS identity column refuses the archived id without
//     OVERRIDING SYSTEM VALUE, so the whole table (clerk_continuity_events,
//     14 of 14 rows) was skipped, and an archived identity sequence took the
//     real one's name so the setval went to an orphan.
// Synthetic schema and rows only.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { pgSkip, withSlotWait } from '../credential-portal/postgresFixture.mjs';
import { startPostgres } from './pg.mjs';

const SOURCE = `
  create table public.profiles (id uuid primary key, auth_user_id text unique);
  -- Alphabetically before the function it calls: the order that broke.
  create function public.current_profile_id() returns uuid language sql stable
    as $$ select id from public.profiles where auth_user_id = current_setting('request.jwt.claim.sub', true) $$;
  create function public.admin_operations_can_read() returns boolean language sql stable
    as $$ select public.current_profile_id() is not null $$;
  create table public.continuity_events (id bigint generated always as identity primary key,
    profile_id uuid references public.profiles(id), kind text not null, created_at timestamptz default now());
  create table public.ledger (id bigint generated by default as identity primary key, note text);
  create function public.continuity_prefix_is_available(p text) returns boolean language sql stable
    as $$ select not exists (select 1 from public.continuity_events e where e.kind = p) $$;
  create table public.admin_notes (id uuid primary key default gen_random_uuid(), body text);
  alter table public.admin_notes enable row level security;
  create policy admin_read on public.admin_notes for select to authenticated using (public.admin_operations_can_read());
  alter table public.continuity_events enable row level security;
  create policy events_admin_read on public.continuity_events for select to authenticated using (public.admin_operations_can_read());
  insert into public.profiles values ('00000000-0000-4000-8000-0000000000f1', 'user_synthetic_1'), ('00000000-0000-4000-8000-0000000000f2', 'user_synthetic_2');
  insert into public.continuity_events (profile_id, kind) select '00000000-0000-4000-8000-0000000000f1', 'bound-' || g from generate_series(1, 14) g;
  -- A gap, so the restored sequence must follow max(id), not the row count.
  delete from public.continuity_events where id = 3;
  insert into public.continuity_events (profile_id, kind) values ('00000000-0000-4000-8000-0000000000f2', 'bound-15');
  insert into public.ledger (note) select 'note ' || g from generate_series(1, 5) g;
  insert into public.admin_notes (body) values ('Synthetic admin note');
`;

function jsonExecutor(pg, db) {
  // The management API answers a query with typed JSON rows; so does this.
  return async (query) => JSON.parse(await pg.sql(`select coalesce(json_agg(x), '[]'::json) from (${query.trim().replace(/;$/, '')}) x`, { db }) || '[]');
}

async function exportArchive(pg, dir) {
  const { exportCatalog, exportDdl, exportData } = await import('../../scripts/offsite-backup.mjs');
  const sql = jsonExecutor(pg, 'src');
  const catalog = await exportCatalog(sql);
  const ddl = await exportDdl(sql, catalog);
  fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
  const data = await exportData(sql, catalog, path.join(dir, 'data'));
  return { catalog, ddl: { statements: ddl.statements, counts: ddl.counts, sections: ddl.sections, foreign_keys: ddl.foreignKeys, triggers: ddl.triggers }, sqlText: ddl.sqlText, manifest: { tables: data.tables } };
}

async function restore(pg, db, archive, dir) {
  process.env.PSQL = path.join(pg.bin, 'psql');
  const { psqlExecutor, applySchema, applyData } = await import('../../scripts/offsite-restore.mjs');
  const sql = psqlExecutor(`postgresql:///${db}?host=${encodeURIComponent(pg.socket)}&port=${pg.port}&user=postgres`);
  const summary = { failures: [], notes: [] };
  await applySchema(sql, archive.ddl, summary, archive.catalog);
  await applyData(sql, dir, archive.manifest, archive.ddl, archive.catalog, null, summary);
  return summary;
}

const functionsIn = (pg, db) => pg.rows(`select p.oid::regprocedure::text as f from pg_proc p where p.pronamespace = 'public'::regnamespace order by 1`, { db });
const policiesIn = (pg, db) => pg.rows(`select tablename, policyname from pg_policies where schemaname = 'public' order by 1, 2`, { db });

test('an archive restores every function, policy and identity row, and new rows get fresh ids', { skip: pgSkip(), timeout: withSlotWait(180000) }, async (t) => {
  const pg = await startPostgres(58472, 'offsite-restore');
  t.after(() => pg.close());
  await pg.sql(`create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;`);
  for (const db of ['src', 'dst']) await pg.sql(`create database ${db}`);
  await pg.sql(SOURCE, { db: 'src' });

  const dir = fs.mkdtempSync(path.join(pg.root, 'archive-'));
  const archive = await exportArchive(pg, dir);

  // The backup no longer archives an identity column's own sequence: the
  // table's identity makes it, and a second copy would take its name.
  const sequenceNames = archive.ddl.statements.filter((s) => s.section === 'sequences' || s.section === 'sequence_values').map((s) => s.name);
  assert.deepEqual(sequenceNames, [], 'identity-owned sequences are not archived as sequences');
  assert.match(archive.sqlText, /SET check_function_bodies = off;/, 'the readable ddl.sql can be run by hand too');

  const summary = await restore(pg, 'dst', archive, dir);
  assert.deepEqual(summary.failures, []);
  assert.deepEqual(await functionsIn(pg, 'dst'), await functionsIn(pg, 'src'), 'every function exists on the target');
  assert.deepEqual(await policiesIn(pg, 'dst'), await policiesIn(pg, 'src'), 'every policy exists on the target');
  for (const table of ['continuity_events', 'ledger', 'profiles', 'admin_notes']) {
    assert.equal(await pg.sql(`select count(*) from public.${table}`, { db: 'dst' }), await pg.sql(`select count(*) from public.${table}`, { db: 'src' }), table);
  }
  assert.equal(await pg.sql(`select string_agg(id::text, ',' order by id) from public.continuity_events`, { db: 'dst' }),
    await pg.sql(`select string_agg(id::text, ',' order by id) from public.continuity_events`, { db: 'src' }), 'the archived ids are kept');

  // A new row after the restore gets the next id, not a collision.
  assert.equal(await pg.sql(`insert into public.continuity_events (kind) values ('after-restore') returning id`, { db: 'dst' }), '16');
  assert.equal(await pg.sql(`insert into public.ledger (note) values ('after-restore') returning id`, { db: 'dst' }), '6');
  assert.equal(await pg.sql(`select count(*) from pg_class where relkind = 'S' and relname like '%seq1'`, { db: 'dst' }), '0', 'no orphan sequence');
});

test('an archive written before the fix, with the identity sequences in it, still restores correctly', { skip: pgSkip(), timeout: withSlotWait(180000) }, async (t) => {
  const pg = await startPostgres(58473, 'offsite-restore-old');
  t.after(() => pg.close());
  await pg.sql(`create role anon nologin; create role authenticated nologin; create role service_role nologin bypassrls;`);
  for (const db of ['src', 'dst']) await pg.sql(`create database ${db}`);
  await pg.sql(SOURCE, { db: 'src' });
  const dir = fs.mkdtempSync(path.join(pg.root, 'archive-'));
  const archive = await exportArchive(pg, dir);
  // What the old export wrote for the two identity sequences (pg_sequences
  // lists them), ahead of the tables, plus their setval after the data.
  const old = [];
  for (const [name, last] of [['continuity_events_id_seq', 15], ['ledger_id_seq', 5]]) {
    old.push({ section: 'sequences', name, sql: `CREATE SEQUENCE IF NOT EXISTS public.${name} AS bigint INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;` });
    old.push({ section: 'sequence_values', name, sql: `SELECT setval('public.${name}', ${last}, true);` });
  }
  archive.ddl.statements = [...old, ...archive.ddl.statements];

  const summary = await restore(pg, 'dst', archive, dir);
  assert.deepEqual(summary.failures, []);
  assert.equal(await pg.sql(`select count(*) from public.continuity_events`, { db: 'dst' }), '14');
  assert.equal(await pg.sql(`select count(*) from pg_class where relkind = 'S' and relname like '%seq1'`, { db: 'dst' }), '0', 'no orphan sequence took the identity name');
  assert.equal(await pg.sql(`insert into public.continuity_events (kind) values ('after-restore') returning id`, { db: 'dst' }), '16');
});
