#!/usr/bin/env bash
# One-shot helper to wire up the Clerk ↔ Supabase JWT template.
#
# Prompts for the two secrets that can't be retrieved programmatically
# (Clerk secret key + Supabase JWT secret), creates the "supabase" JWT
# template in Clerk via the Backend API, and stashes both secrets in
# .env.local (chmod 600, already gitignored).
#
# See SETUP-INSTRUCTIONS.md for where to find each secret.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.local"
GITIGNORE="$SCRIPT_DIR/.gitignore"
CLERK_API="https://api.clerk.com/v1/jwt_templates"

require() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command '$1' not found in PATH." >&2
    exit 1
  }
}
require curl
require python3

echo "==> CredentialDOMD: Clerk ↔ Supabase JWT template setup"
echo

# ── 1. Clerk secret key ─────────────────────────────────────────────
read -r -s -p "Paste Clerk secret key (sk_test_… or sk_live_…): " CLERK_SECRET_KEY
echo
if [[ -z "$CLERK_SECRET_KEY" ]]; then
  echo "Error: Clerk secret key is empty." >&2
  exit 1
fi
if [[ ! "$CLERK_SECRET_KEY" =~ ^sk_(test|live)_ ]]; then
  echo "Warning: key doesn't start with sk_test_/sk_live_. Continuing anyway." >&2
fi

# ── 2. Supabase JWT secret ──────────────────────────────────────────
read -r -s -p "Paste Supabase JWT secret: " SUPABASE_JWT_SECRET
echo
if [[ -z "$SUPABASE_JWT_SECRET" ]]; then
  echo "Error: Supabase JWT secret is empty." >&2
  exit 1
fi

# ── 3. Build request body (python3 handles JSON escaping safely) ────
REQUEST_BODY=$(SIGNING_KEY="$SUPABASE_JWT_SECRET" python3 - <<'PY'
import json, os
print(json.dumps({
    "name": "supabase",
    "signing_algorithm": "HS256",
    "custom_signing_key": True,
    "signing_key": os.environ["SIGNING_KEY"],
    "claims": {
        "sub": "{{user.id}}",
        "email": "{{user.primary_email_address}}",
        "aud": "authenticated",
        "role": "authenticated",
    },
}))
PY
)

echo "==> Calling Clerk Backend API to create 'supabase' JWT template…"
RESPONSE=$(curl -sS -w $'\n%{http_code}' \
  -X POST "$CLERK_API" \
  -H "Authorization: Bearer $CLERK_SECRET_KEY" \
  -H "Content-Type: application/json" \
  -d "$REQUEST_BODY")

HTTP_CODE=$(printf '%s' "$RESPONSE" | tail -n1)
BODY=$(printf '%s' "$RESPONSE" | sed '$d')

if [[ "$HTTP_CODE" != "200" && "$HTTP_CODE" != "201" ]]; then
  echo "Error: Clerk API returned HTTP $HTTP_CODE" >&2
  echo "$BODY" >&2
  if [[ "$HTTP_CODE" == "422" ]]; then
    echo >&2
    echo "Hint: 422 usually means a 'supabase' template already exists." >&2
    echo "      List existing templates:" >&2
    echo "        curl -H \"Authorization: Bearer \$CLERK_SECRET_KEY\" $CLERK_API" >&2
    echo "      Then either delete the old one or PATCH it instead of POSTing." >&2
  fi
  exit 1
fi

TEMPLATE_ID=$(printf '%s' "$BODY" \
  | python3 -c 'import sys,json; print(json.load(sys.stdin).get("id",""))')

# ── 4. Persist secrets to .env.local (mode 600) ─────────────────────
update_env_var() {
  local key="$1" value="$2" file="$3"
  KEY="$key" VALUE="$value" FILE="$file" python3 - <<'PY'
import os
key, value, path = os.environ["KEY"], os.environ["VALUE"], os.environ["FILE"]
try:
    with open(path) as f:
        lines = f.readlines()
except FileNotFoundError:
    lines = []
prefix = key + "="
out, replaced = [], False
for line in lines:
    if line.startswith(prefix):
        out.append(f"{key}={value}\n")
        replaced = True
    else:
        out.append(line)
if not replaced:
    if out and not out[-1].endswith("\n"):
        out[-1] = out[-1] + "\n"
    out.append(f"{key}={value}\n")
with open(path, "w") as f:
    f.writelines(out)
PY
}

if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<'EOF'
# Generated by setup-clerk-supabase.sh — DO NOT COMMIT.
# Server-side secrets only. The browser bundle reads VITE_* vars from .env.
EOF
fi

update_env_var "CLERK_SECRET_KEY"     "$CLERK_SECRET_KEY"     "$ENV_FILE"
update_env_var "SUPABASE_JWT_SECRET"  "$SUPABASE_JWT_SECRET"  "$ENV_FILE"
chmod 600 "$ENV_FILE"

# Sanity-check that .env.local is gitignored (it should be — pattern is in .gitignore).
if [[ -f "$GITIGNORE" ]] \
   && ! grep -qE '^\.env\.local$|^\.env\.\*\.local$|^\*\.local$' "$GITIGNORE"; then
  printf '\n.env.local\n' >> "$GITIGNORE"
  echo "==> Added .env.local to .gitignore"
fi

echo
echo "✓ JWT template created."
echo "  Template ID: $TEMPLATE_ID"
echo "  Name:        supabase"
echo "  Algorithm:   HS256"
echo
echo "✓ Secrets saved to: $ENV_FILE (chmod 600)"
echo "  Keys: CLERK_SECRET_KEY, SUPABASE_JWT_SECRET"
echo
echo "Verify in the Clerk dashboard:"
echo "  https://dashboard.clerk.com → JWT Templates → 'supabase'"
