// Audit additions — codes a locum neurosurgeon logs daily that the curated
// files lacked (2026 CMS audit, workflow wf_7bb960e8-5df). Values come from
// rvuData.js (generated from the CMS file); these entries provide search
// metadata. Enrich synonyms over time as real usage shows gaps.

export const ADDITIONAL_CODES = [
  {"code": "61210", "shortDesc": "Burr hole for EVD / ventricular catheter placement", "category": "Neurosurgery", "subcategory": "Bedside Procedures", "synonyms": ["EVD placement", "external ventricular drain", "burr hole EVD", "ventriculostomy catheter", "EVD burr hole", "ICP monitor via burr hole", "ventricular catheter placement"], "keywords": ["burr", "hole", "ventricular", "catheter", "EVD", "ventriculostomy", "ICP", "reservoir"]},
  {"code": "61107", "shortDesc": "Twist drill hole for ventricular catheter / ICP monitor", "category": "Neurosurgery", "subcategory": "Bedside Procedures", "synonyms": ["twist drill EVD", "bedside EVD", "twist drill ICP monitor", "twist drill ventriculostomy", "bolt placement", "ICP bolt"], "keywords": ["twist", "drill", "ventricular", "catheter", "ICP", "bolt", "monitor", "bedside"]},
  {"code": "99242", "shortDesc": "Office consultation, straightforward MDM (status I on Medicare; RUC work value used by commercial payers)", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["office", "consultation", "straightforward", "status", "medicare", "work", "value", "used"]},
  {"code": "99243", "shortDesc": "Office consultation, low MDM", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["office", "consultation"]},
  {"code": "99244", "shortDesc": "Office consultation, moderate MDM", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["office", "consultation", "moderate"]},
  {"code": "99245", "shortDesc": "Office consultation, high MDM", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["office", "consultation", "high"]},
  {"code": "99252", "shortDesc": "Inpatient/observation consultation, straightforward MDM", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["inpatient", "observation", "consultation", "straightforward"]},
  {"code": "99253", "shortDesc": "Inpatient/observation consultation, low MDM", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["inpatient", "observation", "consultation"]},
  {"code": "99254", "shortDesc": "Inpatient/observation consultation, moderate MDM \u2014 the workhorse inpatient neurosurgery consult", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["inpatient", "observation", "consultation", "moderate", "workhorse", "neurosurgery", "consult"]},
  {"code": "99255", "shortDesc": "Inpatient/observation consultation, high MDM", "category": "E/M consult", "subcategory": "", "synonyms": [], "keywords": ["inpatient", "observation", "consultation", "high"]},
  {"code": "99234", "shortDesc": "Hospital inpatient/observation care, admit and discharge same date, straightforward/low MDM", "category": "E/M", "subcategory": "Hospital Visit", "synonyms": [], "keywords": ["hospital", "inpatient", "observation", "care", "admit", "discharge", "same", "date"]},
  {"code": "99235", "shortDesc": "Hospital inpatient/observation care, admit and discharge same date, moderate MDM", "category": "E/M", "subcategory": "Hospital Visit", "synonyms": [], "keywords": ["hospital", "inpatient", "observation", "care", "admit", "discharge", "same", "date"]},
  {"code": "99236", "shortDesc": "Hospital inpatient/observation care, same-day admit and discharge, high MDM", "category": "E/M", "subcategory": "Hospital Visit", "synonyms": [], "keywords": ["hospital", "inpatient", "observation", "care", "admit", "discharge", "same", "date"]},
  {"code": "G0316", "shortDesc": "Prolonged inpatient/observation E/M, each additional 15 min (Medicare; ZZZ add-on)", "category": "E/M", "subcategory": "Prolonged Services", "synonyms": [], "keywords": ["prolonged", "inpatient", "observation", "medicare"]},
  {"code": "99418", "shortDesc": "Prolonged inpatient/observation E/M, each additional 15 min (add-on; status I on Medicare)", "category": "E/M", "subcategory": "Prolonged Services", "synonyms": [], "keywords": ["prolonged", "inpatient", "observation", "commercial", "payers", "status", "medicare"]},
  {"code": "99497", "shortDesc": "Advance care planning, first 30 minutes, face-to-face", "category": "E/M", "subcategory": "Care Management", "synonyms": [], "keywords": ["advance", "care", "planning", "minutes", "face"]},
  {"code": "99498", "shortDesc": "Advance care planning, each additional 30 minutes (ZZZ add-on)", "category": "E/M", "subcategory": "Care Management", "synonyms": [], "keywords": ["advance", "care", "planning", "minutes"]},
  {"code": "99024", "shortDesc": "Postoperative follow-up visit within global period (status B, tracking only \u2014 exclude from wRVU sums)", "category": "E/M", "subcategory": "Global Period Tracking", "synonyms": [], "keywords": ["postoperative", "follow", "visit", "within", "global", "period", "status", "tracking"]},
  {"code": "61215", "shortDesc": "Insertion of subcutaneous reservoir/pump for ventricular catheter (Ommaya)", "fullDesc": "Insertion of subcutaneous reservoir, pump or continuous infusion system for connection to ventricular catheter", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": ["Ommaya reservoir placement", "Ommaya"], "keywords": ["insertion", "subcutaneous", "reservoir", "pump", "connection", "ventricular", "catheter", "ommaya"]},
  {"code": "61070", "shortDesc": "Puncture of shunt tubing or reservoir for aspiration or injection (shunt tap)", "category": "Neurosurgery", "subcategory": "CSF/Shunt", "synonyms": [], "keywords": ["puncture", "shunt", "tubing", "reservoir", "aspiration", "injection"]},
  {"code": "61020", "shortDesc": "Ventricular puncture via previous burr hole, fontanelle or reservoir, without injection", "fullDesc": "Ventricular puncture through previous burr hole, fontanelle, suture, or implanted ventricular catheter/reservoir; without injection", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": ["Ommaya tap", "reservoir tap", "ventricular tap through reservoir"], "keywords": ["ventricular", "puncture", "through", "previous", "burr", "hole", "fontanelle", "suture", "reservoir"]},
  {"code": "61105", "shortDesc": "Twist drill hole for subdural or ventricular puncture", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["twist", "drill", "hole", "subdural", "ventricular", "puncture"]},
  {"code": "62270", "shortDesc": "Spinal puncture, lumbar, diagnostic", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["spinal", "puncture", "lumbar", "diagnostic"]},
  {"code": "62272", "shortDesc": "Spinal puncture, therapeutic, for CSF drainage (lumbar drain)", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["spinal", "puncture", "therapeutic", "drainage", "lumbar", "drain"]},
  {"code": "62273", "shortDesc": "Injection, epidural, of blood or clot patch", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["injection", "epidural", "blood", "clot", "patch"]},
  {"code": "62328", "shortDesc": "Spinal puncture, lumbar, diagnostic; with fluoroscopic or CT guidance", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["spinal", "puncture", "lumbar", "diagnostic", "fluoroscopic", "guidance"]},
  {"code": "62329", "shortDesc": "Spinal puncture, therapeutic CSF drainage; with fluoroscopic or CT guidance (companion to 62328)", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["spinal", "puncture", "therapeutic", "drainage", "fluoroscopic", "guidance", "companion"]},
  {"code": "20660", "shortDesc": "Application of cranial tongs, caliper, or stereotactic frame, including removal (separate procedure)", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": ["Gardner-Wells tongs", "halo ring application", "stereotactic frame placement"], "keywords": ["application", "cranial", "tongs", "caliper", "stereotactic", "frame", "removal", "separate"]},
  {"code": "20661", "shortDesc": "Application of halo, including removal; cranial", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["application", "halo", "removal", "cranial"]},
  {"code": "20665", "shortDesc": "Removal of tongs or halo applied by another individual", "category": "Neurosurgery", "subcategory": "Bedside/ICU", "synonyms": [], "keywords": ["removal", "tongs", "halo", "applied", "another", "individual"]},
  {"code": "10180", "shortDesc": "Incision and drainage, complex, postoperative wound infection (010 global)", "category": "Surgery", "subcategory": "Wound Care", "synonyms": [], "keywords": ["incision", "drainage", "complex", "postoperative", "wound", "infection", "global"]},
  {"code": "12020", "shortDesc": "Treatment of superficial wound dehiscence; simple closure", "category": "Surgery", "subcategory": "Wound Care", "synonyms": [], "keywords": ["treatment", "superficial", "wound", "dehiscence", "simple", "closure"]},
  {"code": "13160", "shortDesc": "Secondary closure of surgical wound or dehiscence, extensive or complicated", "category": "Surgery", "subcategory": "Wound Care", "synonyms": ["wound dehiscence closure", "secondary wound closure"], "keywords": ["secondary", "closure", "surgical", "wound", "dehiscence", "extensive", "complicated"]},
  {"code": "20670", "shortDesc": "Removal of implant; superficial (010 global)", "category": "Surgery", "subcategory": "Wound Care", "synonyms": [], "keywords": ["removal", "implant", "superficial", "global"]},
  {"code": "20680", "shortDesc": "Removal of implant; deep (in cmsBase.js but had no RVU_DATA entry; 090 global)", "category": "Surgery", "subcategory": "Wound Care", "synonyms": [], "keywords": ["removal", "implant", "deep", "cmsbase", "data", "entry", "global"]},
  {"code": "62000", "shortDesc": "Elevation of depressed skull fracture; simple, extradural", "category": "Neurosurgery", "subcategory": "Cranial Trauma", "synonyms": [], "keywords": ["elevation", "depressed", "skull", "fracture", "simple", "extradural"]},
  {"code": "62005", "shortDesc": "Elevation of depressed skull fracture; compound or comminuted, extradural", "category": "Neurosurgery", "subcategory": "Cranial Trauma", "synonyms": [], "keywords": ["elevation", "depressed", "skull", "fracture", "compound", "comminuted", "extradural"]},
  {"code": "62010", "shortDesc": "Elevation of depressed skull fracture; with repair of dura and/or debridement of brain", "category": "Neurosurgery", "subcategory": "Cranial Trauma", "synonyms": [], "keywords": ["elevation", "depressed", "skull", "fracture", "repair", "dura", "debridement", "brain"]},
  {"code": "61316", "shortDesc": "Incision and subcutaneous placement of cranial bone graft (ZZZ add-on to craniectomy)", "category": "Neurosurgery", "subcategory": "Cranial Trauma (add-on)", "synonyms": [], "keywords": ["incision", "subcutaneous", "placement", "cranial", "bone", "graft", "craniectomy"]},
  {"code": "62143", "shortDesc": "Replace bone flap/prosthetic plate of skull (later encounter)", "fullDesc": "Replacement of bone flap or prosthetic plate of skull", "category": "Neurosurgery", "subcategory": "Cranioplasty", "synonyms": ["cranioplasty bone flap replacement", "put back bone flap", "autologous bone flap cranioplasty", "delayed cranioplasty with stored flap", "replace prosthetic plate"], "keywords": ["replacement", "bone", "flap", "prosthetic", "plate", "skull", "cranioplasty", "staged"]},
  {"code": "62142", "shortDesc": "Removal of bone flap or prosthetic plate of skull", "fullDesc": "Removal of bone flap or prosthetic plate of skull", "category": "Neurosurgery", "subcategory": "Cranioplasty", "synonyms": ["bone flap removal", "removal of infected bone flap", "explant cranioplasty plate", "remove prosthetic plate skull"], "keywords": ["removal", "bone", "flap", "prosthetic", "plate", "skull", "infected"]},
  {"code": "62140", "shortDesc": "Cranioplasty for skull defect; up to 5 cm diameter", "fullDesc": "Cranioplasty for skull defect; up to 5 cm diameter", "category": "Neurosurgery", "subcategory": "Cranioplasty", "synonyms": ["cranioplasty small defect", "titanium mesh cranioplasty small", "PEEK cranioplasty small defect"], "keywords": ["cranioplasty", "skull", "defect", "diameter"]},
  {"code": "62141", "shortDesc": "Cranioplasty for skull defect; larger than 5 cm diameter", "fullDesc": "Cranioplasty for skull defect; larger than 5 cm diameter", "category": "Neurosurgery", "subcategory": "Cranioplasty", "synonyms": ["cranioplasty large defect", "custom implant cranioplasty", "PEEK cranioplasty", "titanium cranioplasty large defect"], "keywords": ["cranioplasty", "skull", "defect", "larger", "diameter"]},
  {"code": "22513", "shortDesc": "Percutaneous vertebral augmentation (kyphoplasty), thoracic (CY2026 value; CY2025 was 8.65)", "category": "Neurosurgery", "subcategory": "Spine Augmentation", "synonyms": [], "keywords": ["percutaneous", "vertebral", "augmentation", "kyphoplasty", "thoracic", "value"]},
  {"code": "22514", "shortDesc": "Percutaneous vertebral augmentation (kyphoplasty), lumbar (CY2026 value; CY2025 was 7.99)", "category": "Neurosurgery", "subcategory": "Spine Augmentation", "synonyms": [], "keywords": ["percutaneous", "vertebral", "augmentation", "kyphoplasty", "lumbar", "value"]},
  {"code": "22515", "shortDesc": "Percutaneous vertebral augmentation; each additional vertebral body (ZZZ add-on)", "category": "Neurosurgery", "subcategory": "Spine Augmentation (add-on)", "synonyms": [], "keywords": ["percutaneous", "vertebral", "augmentation", "body"]},
  {"code": "22510", "shortDesc": "Percutaneous vertebroplasty, cervicothoracic", "category": "Neurosurgery", "subcategory": "Spine Augmentation", "synonyms": [], "keywords": ["percutaneous", "vertebroplasty", "cervicothoracic"]},
  {"code": "22511", "shortDesc": "Percutaneous vertebroplasty, lumbosacral", "category": "Neurosurgery", "subcategory": "Spine Augmentation", "synonyms": [], "keywords": ["percutaneous", "vertebroplasty", "lumbosacral"]},
  {"code": "22512", "shortDesc": "Percutaneous vertebroplasty; each additional vertebral body (ZZZ add-on)", "category": "Neurosurgery", "subcategory": "Spine Augmentation (add-on)", "synonyms": [], "keywords": ["percutaneous", "vertebroplasty", "vertebral", "body"]},
  {"code": "22310", "shortDesc": "Closed treatment of vertebral body fracture without manipulation, including casting or bracing", "fullDesc": "Closed treatment of vertebral body fracture(s), without manipulation, requiring and including casting or bracing", "category": "Neurosurgery", "subcategory": "Spine Trauma", "synonyms": ["non-operative vertebral fracture management", "TLSO for compression fracture", "collar for cervical fracture"], "keywords": ["closed", "treatment", "vertebral", "body", "fracture", "without", "manipulation", "casting", "bracing"]},
  {"code": "63081", "shortDesc": "Vertebral corpectomy, anterior approach with cord/root decompression; cervical, single segment", "category": "Neurosurgery", "subcategory": "Spine Decompression", "synonyms": [], "keywords": ["vertebral", "corpectomy", "anterior", "approach", "cord", "root", "decompression", "cervical"]},
  {"code": "63082", "shortDesc": "Vertebral corpectomy, cervical, each additional segment (ZZZ add-on)", "category": "Neurosurgery", "subcategory": "Spine Decompression (add-on)", "synonyms": [], "keywords": ["vertebral", "corpectomy", "cervical", "segment"]},
  {"code": "63052", "shortDesc": "Laminectomy/facetectomy at fused TLIF/PLIF level, single (add-on)", "fullDesc": "Laminectomy, facetectomy, or foraminotomy (unilateral or bilateral with decompression of spinal cord, cauda equina and/or nerve root[s]), during posterior interbody arthrodesis, lumbar; single vertebral segment (add-on to 22630, 22632, 22633, 22634)", "category": "Neurosurgery", "subcategory": "Spine Decompression (add-on)", "synonyms": ["decompression with TLIF", "decompression with PLIF", "laminectomy at fused interspace", "decompression at the fusion level"], "keywords": ["laminectomy", "facetectomy", "foraminotomy", "during", "posterior", "interbody", "arthrodesis", "lumbar", "TLIF", "PLIF"]},
  {"code": "63053", "shortDesc": "Laminectomy/facetectomy fused TLIF/PLIF level, each additional", "fullDesc": "Laminectomy, facetectomy, or foraminotomy (unilateral or bilateral with decompression of spinal cord, cauda equina and/or nerve root[s]), during posterior interbody arthrodesis, lumbar; each additional segment (add-on)", "category": "Neurosurgery", "subcategory": "Spine Decompression (add-on)", "synonyms": ["decompression with TLIF additional level", "decompression with PLIF additional level"], "keywords": ["laminectomy", "facetectomy", "foraminotomy", "during", "posterior", "interbody", "arthrodesis", "segment", "additional"]},
  // Codes the prompt (cptConstructs.js) instructs the model to use but the catalog lacked; every one
  // vanished silently at re-validation before the cptCoderRules post-pass surfaced unknown codes.
  // Descriptors: AMA CPT; work RVU from rvuData.js (CY2026 PFS July release).
  {"code": "22632", "shortDesc": "Arthrodesis posterior interbody lumbar, each additional interspace (add-on)", "fullDesc": "Arthrodesis, posterior interbody technique, including laminectomy and/or discectomy to prepare interspace (other than for decompression), lumbar; each additional interspace (add-on to 22630)", "category": "Neurosurgery", "subcategory": "Spinal Fusion - Lumbar", "synonyms": ["PLIF additional level", "PLIF each additional interspace"], "keywords": ["arthrodesis", "posterior", "interbody", "lumbar", "additional", "interspace", "PLIF"]},
  {"code": "22843", "shortDesc": "Posterior segmental instrumentation, 7-12 vertebrae (add-on)", "fullDesc": "Posterior segmental instrumentation (eg, pedicle fixation, dual rods with multiple hooks and sublaminar wires); 7 to 12 vertebral segments (add-on)", "category": "Neurosurgery", "subcategory": "Spinal Instrumentation (add-on)", "synonyms": ["pedicle screws 7-12 segments", "long segment posterior instrumentation", "posterior segmental instrumentation 7 to 12"], "keywords": ["posterior", "segmental", "instrumentation", "pedicle", "screws", "7", "12", "vertebral", "segments"]},
  {"code": "22844", "shortDesc": "Posterior segmental instrumentation, 13 or more vertebrae (add-on)", "fullDesc": "Posterior segmental instrumentation (eg, pedicle fixation, dual rods with multiple hooks and sublaminar wires); 13 or more vertebral segments (add-on)", "category": "Neurosurgery", "subcategory": "Spinal Instrumentation (add-on)", "synonyms": ["pedicle screws 13 or more segments", "deformity long construct instrumentation"], "keywords": ["posterior", "segmental", "instrumentation", "pedicle", "screws", "13", "vertebral", "segments", "deformity"]},
  {"code": "22846", "shortDesc": "Anterior instrumentation, 4-7 vertebrae (add-on)", "fullDesc": "Anterior instrumentation; 4 to 7 vertebral segments (add-on)", "category": "Neurosurgery", "subcategory": "Spinal Instrumentation (add-on)", "synonyms": ["anterior cervical plate 4-7 vertebrae", "long anterior plate", "3-level ACDF plate", "anterior plate 4-7 segments"], "keywords": ["anterior", "instrumentation", "plate", "4", "7", "vertebral", "segments", "ACDF"]},
  {"code": "61782", "shortDesc": "Stereotactic navigation, cranial extradural (add-on)", "fullDesc": "Stereotactic computer-assisted (navigational) procedure; cranial, extradural (add-on)", "category": "Neurosurgery", "subcategory": "Operative Adjunct (add-on)", "synonyms": ["navigation extradural", "stealth extradural", "neuronavigation extradural", "navigation for extradural skull base"], "keywords": ["stereotactic", "navigation", "computer-assisted", "cranial", "extradural", "stealth"]},
  {"code": "63046", "shortDesc": "Laminectomy with facetectomy/foraminotomy, single segment, thoracic", "fullDesc": "Laminectomy, facetectomy and foraminotomy (unilateral or bilateral with decompression of spinal cord, cauda equina and/or nerve root[s], [eg, spinal or lateral recess stenosis]), single vertebral segment; thoracic", "category": "Neurosurgery", "subcategory": "Spinal Decompression", "synonyms": ["thoracic laminectomy with foraminotomy", "thoracic decompression laminectomy facetectomy", "thoracic laminectomy"], "keywords": ["laminectomy", "facetectomy", "foraminotomy", "thoracic", "single", "segment", "decompression"]},
  {"code": "63707", "shortDesc": "Repair of dural/CSF leak, not requiring laminectomy", "category": "Neurosurgery", "subcategory": "Spine", "synonyms": [], "keywords": ["repair", "dural", "leak", "requiring", "laminectomy"]},
  {"code": "63709", "shortDesc": "Repair of dural/CSF leak or pseudomeningocele, with laminectomy", "category": "Neurosurgery", "subcategory": "Spine", "synonyms": [], "keywords": ["repair", "dural", "leak", "pseudomeningocele", "laminectomy"]},
  {"code": "63650", "shortDesc": "Percutaneous implantation of epidural neurostimulator electrode array (SCS trial or permanent lead)", "fullDesc": "Percutaneous implantation of neurostimulator electrode array, epidural", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": ["spinal cord stimulator trial", "SCS trial lead", "percutaneous SCS lead"], "keywords": ["percutaneous", "implantation", "epidural", "neurostimulator", "electrode", "array", "trial", "permanent"]},
  {"code": "63655", "shortDesc": "Laminectomy for implantation of neurostimulator electrodes, plate/paddle, epidural", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["laminectomy", "implantation", "neurostimulator", "electrodes", "plate", "paddle", "epidural"]},
  {"code": "63661", "shortDesc": "Removal of spinal neurostimulator percutaneous electrode array(s), incl fluoroscopy", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["removal", "spinal", "neurostimulator", "percutaneous", "electrode", "array", "incl", "fluoroscopy"]},
  {"code": "63662", "shortDesc": "Removal of spinal neurostimulator plate/paddle electrode(s) placed via laminotomy/laminectomy (090 global)", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["removal", "spinal", "neurostimulator", "plate", "paddle", "electrode", "placed", "laminotomy"]},
  {"code": "63663", "shortDesc": "Revision incl replacement of spinal neurostimulator percutaneous electrode array(s) (010 global)", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["revision", "incl", "replacement", "spinal", "neurostimulator", "percutaneous", "electrode", "array"]},
  {"code": "63664", "shortDesc": "Revision incl replacement of spinal neurostimulator plate/paddle electrode(s) (090 global)", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["revision", "incl", "replacement", "spinal", "neurostimulator", "plate", "paddle", "electrode"]},
  {"code": "63685", "shortDesc": "Insertion or replacement of spinal neurostimulator pulse generator/receiver (010 global)", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["insertion", "replacement", "spinal", "neurostimulator", "pulse", "generator", "receiver", "global"]},
  {"code": "63688", "shortDesc": "Revision or removal of implanted spinal neurostimulator pulse generator/receiver (010 global)", "category": "Neurosurgery", "subcategory": "Neurostimulator", "synonyms": [], "keywords": ["revision", "removal", "implanted", "spinal", "neurostimulator", "pulse", "generator", "receiver"]},
  {"code": "69990", "shortDesc": "Microsurgical technique, operating microscope (ZZZ add-on)", "fullDesc": "Microsurgical techniques, requiring use of operating microscope (List separately in addition to code for primary procedure). CMS status R: Medicare pays it only with the primaries in Pub 100-04 Ch 12 Sec 20.4.5 (61304-61546, 61550-61711, 62010-62100, 63081-63308, 63704-63710 and the listed nerve repair codes); NCCI Policy Manual Ch VIII Sec F.1 bundles it into every other procedure.", "category": "Neurosurgery", "subcategory": "Operative Adjunct (add-on)", "synonyms": ["operating microscope", "microscope", "microsurgical", "microdissection", "microsurgery"], "keywords": ["microsurgical", "techniques", "operating", "microscope", "status", "separately", "payable"]},
  {"code": "22854", "shortDesc": "Biomechanical device with integral anterior instrumentation into corpectomy defect, each (add-on)", "fullDesc": "Insertion of intervertebral biomechanical device(s) (eg, synthetic cage, mesh) with integral anterior instrumentation for device anchoring (eg, screws, flanges), when performed, to vertebral corpectomy(ies) defect, in conjunction with interbody arthrodesis, each contiguous defect (add-on)", "category": "Neurosurgery", "subcategory": "Spinal Instrumentation (add-on)", "synonyms": ["corpectomy cage with integral plate", "expandable cage corpectomy"], "keywords": ["insertion", "intervertebral", "biomechanical", "device", "integral", "anterior", "instrumentation", "vertebral", "corpectomy"]},
  {"code": "22859", "shortDesc": "Biomechanical device into disc space or vertebral defect WITHOUT arthrodesis, each (add-on)", "fullDesc": "Insertion of intervertebral biomechanical device(s) (eg, synthetic cage, mesh, methylmethacrylate) to intervertebral disc space or vertebral body defect without interbody arthrodesis, each contiguous defect (add-on)", "category": "Neurosurgery", "subcategory": "Spinal Instrumentation (add-on)", "synonyms": ["cage without fusion", "methylmethacrylate vertebral defect"], "keywords": ["insertion", "intervertebral", "biomechanical", "device", "otherwise", "specified", "interspace", "without arthrodesis"]},
  {"code": "20930", "shortDesc": "Allograft, morselized, or osteopromotive material, spine surgery only (add-on; status B, no work RVU)", "category": "Neurosurgery", "subcategory": "Bone Graft (add-on)", "synonyms": ["morselized allograft", "DBM", "bone graft extender"], "keywords": ["allograft", "morselized", "osteopromotive", "material", "spine", "surgery", "only", "bundled"]},
  {"code": "20931", "shortDesc": "Allograft, structural, spine surgery only (ZZZ add-on)", "category": "Neurosurgery", "subcategory": "Bone Graft (add-on)", "synonyms": [], "keywords": ["allograft", "structural", "spine", "surgery", "only"]},
  {"code": "20936", "shortDesc": "Autograft, local (same incision), spine surgery only (bundled, no separate work value)", "category": "Neurosurgery", "subcategory": "Bone Graft (add-on)", "synonyms": [], "keywords": ["autograft", "local", "same", "incision", "spine", "surgery", "only", "bundled"]},
  {"code": "20937", "shortDesc": "Autograft, morselized, through separate skin/fascial incision (ZZZ add-on)", "category": "Neurosurgery", "subcategory": "Bone Graft (add-on)", "synonyms": [], "keywords": ["autograft", "morselized", "through", "separate", "skin", "fascial", "incision"]},
  {"code": "20938", "shortDesc": "Autograft, structural bicortical/tricortical, through separate skin/fascial incision (ZZZ add-on)", "category": "Neurosurgery", "subcategory": "Bone Graft (add-on)", "synonyms": [], "keywords": ["autograft", "structural", "bicortical", "tricortical", "through", "separate", "skin", "fascial"]},
  {"code": "61512", "shortDesc": "Craniectomy for excision of supratentorial meningioma (the code the 61526 'meningioma supratentorial' label ac", "category": "Cranial 61xxx", "subcategory": "", "synonyms": [], "keywords": ["craniectomy", "excision", "supratentorial", "meningioma", "code", "label", "actually", "belongs"]},
  {"code": "61697", "shortDesc": "Complex intracranial aneurysm, carotid circulation", "category": "Cranial 61xxx", "subcategory": "", "synonyms": [], "keywords": ["complex", "intracranial", "aneurysm", "carotid", "circulation"]},
  {"code": "61698", "shortDesc": "Complex intracranial aneurysm, vertebrobasilar circulation", "category": "Cranial 61xxx", "subcategory": "", "synonyms": [], "keywords": ["complex", "intracranial", "aneurysm", "vertebrobasilar", "circulation"]},
  {"code": "61702", "shortDesc": "Simple intracranial aneurysm, vertebrobasilar circulation", "category": "Cranial 61xxx", "subcategory": "", "synonyms": [], "keywords": ["simple", "intracranial", "aneurysm", "vertebrobasilar", "circulation"]},
  {"code": "22858", "shortDesc": "Total disc arthroplasty, cervical, second level (add-on to 22856)", "fullDesc": "Total disc arthroplasty (artificial disc), anterior approach, including discectomy with end plate preparation; second level, cervical (add-on)", "category": "Spine fusion 22xxx", "subcategory": "", "synonyms": ["two-level cervical disc replacement second level", "cervical arthroplasty additional level"], "keywords": ["second", "level", "cervical", "total", "disc", "arthroplasty", "arthroplasty add-on"]},

  // Diagnostic angiography \u2014 catheter-based, cervicocerebral + peripheral (support ticket:
  // "angiogram" returned no results; codes were missing entirely, not just unsearchable).
  // Cervicocerebral series used by neurosurgery/neuro-IR for diagnostic cerebral angiograms.
  {"code": "36221", "shortDesc": "Non-selective catheterization, thoracic aorta, with diagnostic angiography of the aortic arch", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Cervicocerebral)", "synonyms": ["aortic arch angiogram", "arch aortogram", "diagnostic angiogram", "cerebral angiogram"], "keywords": ["angiogram", "angiography", "aorta", "arch", "catheter", "nonselective", "diagnostic"]},
  {"code": "36222", "shortDesc": "Selective catheterization, common carotid or innominate artery, unilateral, with angiography of the extracranial carotid circulation", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Cervicocerebral)", "synonyms": ["carotid angiogram", "cerebral angiogram", "extracranial carotid angiogram", "diagnostic cerebral angiogram"], "keywords": ["angiogram", "angiography", "carotid", "cerebral", "catheter", "selective", "extracranial"]},
  {"code": "36223", "shortDesc": "Selective catheterization, common carotid or innominate artery, unilateral, with angiography of cervicocerebral circulation including intracranial carotid circulation", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Cervicocerebral)", "synonyms": ["cerebral angiogram", "intracranial angiogram", "carotid angiogram", "diagnostic cerebral angiogram"], "keywords": ["angiogram", "angiography", "carotid", "cerebral", "intracranial", "catheter", "selective"]},
  {"code": "36224", "shortDesc": "Selective catheterization, internal carotid artery, unilateral, with angiography of intracranial carotid circulation", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Cervicocerebral)", "synonyms": ["cerebral angiogram", "internal carotid angiogram", "intracranial angiogram", "diagnostic cerebral angiogram"], "keywords": ["angiogram", "angiography", "internal", "carotid", "cerebral", "intracranial", "catheter", "selective"]},
  {"code": "36225", "shortDesc": "Selective catheterization, subclavian or innominate artery, unilateral, for vertebral angiography", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Cervicocerebral)", "synonyms": ["vertebral angiogram access", "subclavian angiogram"], "keywords": ["angiogram", "angiography", "subclavian", "vertebral", "catheter", "selective"]},
  {"code": "36226", "shortDesc": "Selective catheterization, vertebral artery, unilateral, with angiography of ipsilateral vertebral circulation", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Cervicocerebral)", "synonyms": ["vertebral angiogram", "posterior circulation angiogram", "vertebrobasilar angiogram"], "keywords": ["angiogram", "angiography", "vertebral", "posterior", "circulation", "catheter", "selective"]},
  {"code": "36227", "shortDesc": "Selective catheterization, external carotid artery, unilateral, with angiography (add-on to cerebral angiogram)", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (add-on)", "synonyms": ["external carotid angiogram"], "keywords": ["angiogram", "angiography", "external", "carotid", "catheter", "selective", "add-on"]},
  {"code": "36228", "shortDesc": "Selective catheterization of each additional intracranial branch (e.g. ophthalmic, PICA, PCA) for angiography (add-on to cerebral angiogram)", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (add-on)", "synonyms": ["intracranial branch angiogram"], "keywords": ["angiogram", "angiography", "intracranial", "branch", "catheter", "selective", "add-on"]},
  // Peripheral / lower-extremity diagnostic angiography, used across vascular surgery,
  // cardiology, and IR.
  {"code": "36245", "shortDesc": "Selective catheterization, first order abdominal, pelvic, or lower extremity artery, unilateral", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Peripheral)", "synonyms": ["lower extremity angiogram", "peripheral angiogram", "runoff angiogram"], "keywords": ["angiogram", "angiography", "lower", "extremity", "peripheral", "catheter", "selective"]},
  {"code": "36246", "shortDesc": "Selective catheterization, second order abdominal, pelvic, or lower extremity artery, unilateral", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Peripheral)", "synonyms": ["lower extremity angiogram", "peripheral angiogram", "runoff angiogram"], "keywords": ["angiogram", "angiography", "lower", "extremity", "peripheral", "catheter", "selective"]},
  {"code": "36247", "shortDesc": "Selective catheterization, third order or more selective abdominal, pelvic, or lower extremity artery, unilateral", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (Peripheral)", "synonyms": ["lower extremity angiogram", "peripheral angiogram", "runoff angiogram"], "keywords": ["angiogram", "angiography", "lower", "extremity", "peripheral", "catheter", "selective"]},
  {"code": "36248", "shortDesc": "Additional second or third order abdominal, pelvic, or lower extremity artery catheterization, each (add-on)", "category": "Interventional Radiology", "subcategory": "Diagnostic Angiography (add-on)", "synonyms": ["peripheral angiogram add-on"], "keywords": ["angiogram", "angiography", "peripheral", "catheter", "selective", "add-on"]},
  {"code": "75625", "shortDesc": "Aortography, abdominal, radiological supervision and interpretation (abdominal aortogram)", "category": "Radiology", "subcategory": "Diagnostic Angiography", "synonyms": ["abdominal aortogram", "aortogram"], "keywords": ["angiogram", "angiography", "aortogram", "abdominal", "aorta"]},
  {"code": "75710", "shortDesc": "Angiography, extremity, unilateral, radiological supervision and interpretation", "category": "Radiology", "subcategory": "Diagnostic Angiography", "synonyms": ["extremity angiogram", "arm angiogram", "leg angiogram", "runoff angiogram"], "keywords": ["angiogram", "angiography", "extremity", "arm", "leg", "unilateral"]},
  {"code": "75716", "shortDesc": "Angiography, extremity, bilateral, radiological supervision and interpretation", "category": "Radiology", "subcategory": "Diagnostic Angiography", "synonyms": ["bilateral extremity angiogram", "runoff angiogram"], "keywords": ["angiogram", "angiography", "extremity", "bilateral"]},
  // Cardiology angiogram \u2014 was in rvuData.js but never wired into CMS_BASE/ADDITIONAL, so it
  // never actually showed up in search despite having RVU data.
  {"code": "93454", "shortDesc": "Coronary artery angiography, catheter placement and radiological supervision and interpretation (coronary angiogram)", "category": "Medicine", "subcategory": "Cardiovascular", "synonyms": ["coronary angiogram", "cardiac catheterization angiogram"], "keywords": ["angiogram", "angiography", "coronary", "cardiac", "catheterization"]},
  // Existing angiography entries \u2014 enriched with an "angiogram" synonym since the noun form
  // ("angiogram") is not a substring of "angiography" and the plain CMS entries had no
  // synonyms array, so a search for "angiogram" matched none of them.
  {"code": "70496", "shortDesc": "CT angiography head", "category": "Radiology", "subcategory": "Head/Neck", "synonyms": ["CT angiogram", "head angiogram", "cerebral angiogram", "CTA head"], "keywords": ["angiogram", "angiography", "head", "cerebral", "CT"]},
  {"code": "70498", "shortDesc": "CT angiography neck", "category": "Radiology", "subcategory": "Head/Neck", "synonyms": ["CT angiogram", "neck angiogram", "carotid angiogram", "CTA neck"], "keywords": ["angiogram", "angiography", "neck", "carotid", "CT"]},
  {"code": "70544", "shortDesc": "MR angiography head without contrast", "category": "Radiology", "subcategory": "Head/Neck", "synonyms": ["MR angiogram", "MRA head", "head angiogram", "cerebral angiogram"], "keywords": ["angiogram", "angiography", "head", "cerebral", "MR", "MRI"]},
  {"code": "70549", "shortDesc": "MR angiography neck with contrast", "category": "Radiology", "subcategory": "Head/Neck", "synonyms": ["MR angiogram", "MRA neck", "neck angiogram", "carotid angiogram"], "keywords": ["angiogram", "angiography", "neck", "carotid", "MR", "MRI"]},
  {"code": "71275", "shortDesc": "CT angiography chest (CTA PE)", "category": "Radiology", "subcategory": "Chest", "synonyms": ["CT angiogram", "chest angiogram", "pulmonary angiogram", "CTA chest"], "keywords": ["angiogram", "angiography", "chest", "pulmonary", "CT"]},
  {"code": "93458", "shortDesc": "Left heart catheterization with angiography", "category": "Medicine", "subcategory": "Cardiovascular", "synonyms": ["coronary angiogram", "left heart angiogram", "cardiac catheterization angiogram"], "keywords": ["angiogram", "angiography", "coronary", "cardiac", "catheterization", "left", "heart"]},
  // CABG concomitant-procedure add-ons, ticket 63cf43b7: a combined CABG with a Cox-Maze,
  // LAA exclusion, and endoscopic vein harvest had nowhere to go in the catalog because
  // these codes were never added, so the coder could not select them no matter what it saw.
  {"code": "33517", "shortDesc": "CABG combining an arterial and single venous graft (add-on)", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["CABG arterial and venous graft", "combined arterial venous bypass graft", "vein graft add-on to CABG"], "keywords": ["cabg", "coronary", "bypass", "arterial", "venous", "vein", "graft", "add-on"]},
  // Standalone maze family (no other cardiac procedure in the session), so the
  // model can select the primary the CPT parenthetical under 33267-33269 names.
  {"code": "33254", "shortDesc": "Atrial ablation and reconstruction, limited (modified maze), standalone", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["limited maze standalone", "modified maze procedure", "limited atrial ablation"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "limited", "standalone"]},
  {"code": "33255", "shortDesc": "Atrial ablation and reconstruction, extensive (Cox-Maze), without cardiopulmonary bypass, standalone", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["Cox-Maze off pump standalone", "extensive maze without bypass"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "cox", "extensive", "without", "bypass", "standalone"]},
  {"code": "33256", "shortDesc": "Atrial ablation and reconstruction, extensive (Cox-Maze), with cardiopulmonary bypass, standalone", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["Cox-Maze on pump standalone", "extensive maze with bypass", "Cox Maze IV standalone"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "cox", "extensive", "bypass", "standalone"]},
  {"code": "33265", "shortDesc": "Atrial ablation, limited (modified maze), endoscopic, standalone", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["thoracoscopic limited maze", "endoscopic modified maze", "VATS limited ablation"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "limited", "endoscopic", "thoracoscopic", "vats"]},
  {"code": "33266", "shortDesc": "Atrial ablation, extensive (Cox-Maze), endoscopic, standalone", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["thoracoscopic Cox-Maze", "endoscopic extensive maze", "VATS maze"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "cox", "extensive", "endoscopic", "thoracoscopic", "vats"]},
  {"code": "33257", "shortDesc": "Limited atrial ablation add-on, without bypass, at time of other cardiac surgery", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["limited atrial ablation add-on", "modified maze add-on without bypass"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "limited", "bypass", "add-on"]},
  {"code": "33258", "shortDesc": "Limited atrial ablation add-on, with bypass, at time of other cardiac surgery", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["limited atrial ablation add-on with bypass", "modified maze add-on with bypass"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "limited", "bypass", "add-on"]},
  {"code": "33259", "shortDesc": "Extensive atrial ablation add-on (Cox-Maze), with bypass, at time of other cardiac surgery", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["Cox-Maze add-on", "Cox Maze IV add-on", "modified Cox Maze", "extensive atrial ablation add-on", "AtriCure maze add-on"], "keywords": ["ablation", "atrial", "arrhythmia", "maze", "cox", "extensive", "bypass", "add-on", "atricure"]},
  // LAA exclusion is three codes by approach and company (CPT 2022, ticket 63cf43b7 follow-up):
  // 33267 open and standalone (090 global; CPT: only when no other sternotomy/thoracotomy
  // procedure is performed), +33268 open at the time of another sternotomy/thoracotomy
  // procedure (ZZZ add-on), 33269 thoracoscopic (090). The CPT parenthetical bars all three
  // with the maze family 33254-33259/33265/33266 and the mitral codes 33420-33430; the
  // deterministic pass in cptCoderRules.js enforces that.
  {"code": "33267", "shortDesc": "LAA exclusion, open, standalone (no other sternotomy/thoracotomy procedure), any method", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["LAA exclusion standalone", "left atrial appendage clip standalone", "isolated LAA ligation", "LAA exclusion open"], "keywords": ["left", "atrial", "appendage", "exclusion", "clip", "ligation", "open", "standalone", "atricure"]},
  {"code": "33268", "shortDesc": "LAA exclusion, open, at time of other sternotomy/thoracotomy procedure, any method (ZZZ add-on)", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["LAA exclusion add-on", "concomitant LAA exclusion", "left atrial appendage clip with CABG", "AtriCure clip add-on", "LAA ligation add-on"], "keywords": ["left", "atrial", "appendage", "exclusion", "clip", "ligation", "add-on", "concomitant", "atricure", "sternotomy"]},
  {"code": "33269", "shortDesc": "LAA exclusion, thoracoscopic (VATS), any method", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["thoracoscopic LAA exclusion", "VATS LAA clip", "thoracoscopic left atrial appendage ligation", "VATS AtriCure clip"], "keywords": ["left", "atrial", "appendage", "exclusion", "clip", "thoracoscopic", "vats", "atricure"]},
  {"code": "33508", "shortDesc": "Endoscopic vein harvest for CABG, single graft (add-on)", "category": "Surgery", "subcategory": "Cardiovascular", "synonyms": ["endoscopic vein harvest", "EVH", "endoscopic saphenous vein harvest"], "keywords": ["endoscopic", "vein", "harvest", "coronary", "bypass", "graft", "add-on"]},
  // Diagnostic transesophageal echocardiography, the surgeon-performed intraoperative TEE
  // (ticket 63cf43b7, "I do the TEE"). 93312 is the complete study (probe placement, image
  // acquisition, interpretation and report); 93313 placement only; 93314 acquisition,
  // interpretation and report only. PFS work RVU is identical on the global and -26 lines,
  // so the catalog value is the professional-component value. 93318 (TEE for monitoring
  // purposes) is deliberately NOT here: its global PFS line is status C with no work value,
  // and NCCI Policy Manual Ch II Sec B lists it inside the anesthesia service.
  {"code": "93312", "shortDesc": "TEE, complete: probe placement, image acquisition, interpretation and report (bill -26 in the hospital)", "category": "Medicine", "subcategory": "Cardiovascular", "synonyms": ["transesophageal echocardiogram", "TEE", "intraoperative TEE", "diagnostic TEE", "transesophageal echo complete"], "keywords": ["transesophageal", "echocardiography", "echocardiogram", "tee", "intraoperative", "diagnostic", "probe", "interpretation", "report"]},
  {"code": "93313", "shortDesc": "TEE, placement of transesophageal probe only", "category": "Medicine", "subcategory": "Cardiovascular", "synonyms": ["TEE probe placement", "transesophageal probe placement only"], "keywords": ["transesophageal", "echocardiography", "tee", "probe", "placement"]},
  {"code": "93314", "shortDesc": "TEE, image acquisition, interpretation and report only (probe placed by another physician)", "category": "Medicine", "subcategory": "Cardiovascular", "synonyms": ["TEE interpretation only", "transesophageal echo interpretation and report"], "keywords": ["transesophageal", "echocardiography", "tee", "interpretation", "report", "acquisition"]},
];
