// CMS Base CPT Codes — Broad coverage across all sections
// Short descriptions from CMS PFS Relative Value Files
// These provide baseline coverage; curated specialty files override with richer data

export const CMS_BASE_CODES = [
  // ═══════════════════════════════════════════════════════════════
  // E/M — EVALUATION & MANAGEMENT
  // ═══════════════════════════════════════════════════════════════
  { code: "99202", shortDesc: "Office/outpatient visit new, straightforward", category: "E/M", subcategory: "Office Visit" },
  { code: "99203", shortDesc: "Office/outpatient visit new, low complexity", category: "E/M", subcategory: "Office Visit" },
  { code: "99204", shortDesc: "Office/outpatient visit new, moderate complexity", category: "E/M", subcategory: "Office Visit" },
  { code: "99205", shortDesc: "Office/outpatient visit new, high complexity", category: "E/M", subcategory: "Office Visit" },
  { code: "99211", shortDesc: "Office/outpatient visit est, minimal", category: "E/M", subcategory: "Office Visit" },
  { code: "99212", shortDesc: "Office/outpatient visit est, straightforward", category: "E/M", subcategory: "Office Visit" },
  { code: "99213", shortDesc: "Office/outpatient visit est, low complexity", category: "E/M", subcategory: "Office Visit" },
  { code: "99214", shortDesc: "Office/outpatient visit est, moderate complexity", category: "E/M", subcategory: "Office Visit" },
  { code: "99215", shortDesc: "Office/outpatient visit est, high complexity", category: "E/M", subcategory: "Office Visit" },
  { code: "99221", shortDesc: "Initial hospital care, straightforward/low", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99222", shortDesc: "Initial hospital care, moderate complexity", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99223", shortDesc: "Initial hospital care, high complexity", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99231", shortDesc: "Subsequent hospital care, straightforward/low", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99232", shortDesc: "Subsequent hospital care, moderate complexity", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99233", shortDesc: "Subsequent hospital care, high complexity", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99238", shortDesc: "Hospital discharge day, 30 min or less", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99239", shortDesc: "Hospital discharge day, more than 30 min", category: "E/M", subcategory: "Hospital Visit" },
  { code: "99241", shortDesc: "Office consultation, straightforward", category: "E/M", subcategory: "Consultation" },
  { code: "99242", shortDesc: "Office consultation, straightforward", category: "E/M", subcategory: "Consultation" },
  { code: "99243", shortDesc: "Office consultation, low complexity", category: "E/M", subcategory: "Consultation" },
  { code: "99244", shortDesc: "Office consultation, moderate complexity", category: "E/M", subcategory: "Consultation" },
  { code: "99245", shortDesc: "Office consultation, high complexity", category: "E/M", subcategory: "Consultation" },
  { code: "99252", shortDesc: "Inpatient/observation consultation, straightforward", category: "E/M", subcategory: "Consultation" },
  { code: "99253", shortDesc: "Inpatient/observation consultation, low", category: "E/M", subcategory: "Consultation" },
  { code: "99254", shortDesc: "Inpatient/observation consultation, moderate", category: "E/M", subcategory: "Consultation" },
  { code: "99255", shortDesc: "Inpatient/observation consultation, high", category: "E/M", subcategory: "Consultation" },
  { code: "99281", shortDesc: "Emergency dept visit, straightforward", category: "E/M", subcategory: "Emergency" },
  { code: "99282", shortDesc: "Emergency dept visit, low complexity", category: "E/M", subcategory: "Emergency" },
  { code: "99283", shortDesc: "Emergency dept visit, moderate complexity", category: "E/M", subcategory: "Emergency" },
  { code: "99284", shortDesc: "Emergency dept visit, moderate/high complexity", category: "E/M", subcategory: "Emergency" },
  { code: "99285", shortDesc: "Emergency dept visit, high complexity", category: "E/M", subcategory: "Emergency" },
  { code: "99291", shortDesc: "Critical care, first 30-74 minutes", category: "E/M", subcategory: "Critical Care" },
  { code: "99292", shortDesc: "Critical care, each additional 30 min", category: "E/M", subcategory: "Critical Care" },
  { code: "99304", shortDesc: "Nursing facility care, initial, low", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99305", shortDesc: "Nursing facility care, initial, moderate", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99306", shortDesc: "Nursing facility care, initial, high", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99307", shortDesc: "Nursing facility care, subsequent, straightforward", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99308", shortDesc: "Nursing facility care, subsequent, low", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99309", shortDesc: "Nursing facility care, subsequent, moderate", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99310", shortDesc: "Nursing facility care, subsequent, high", category: "E/M", subcategory: "Nursing Facility" },
  { code: "99341", shortDesc: "Home/residence visit new, low", category: "E/M", subcategory: "Home Visit" },
  { code: "99342", shortDesc: "Home/residence visit new, moderate", category: "E/M", subcategory: "Home Visit" },
  { code: "99344", shortDesc: "Home/residence visit new, high", category: "E/M", subcategory: "Home Visit" },
  { code: "99347", shortDesc: "Home/residence visit est, straightforward", category: "E/M", subcategory: "Home Visit" },
  { code: "99348", shortDesc: "Home/residence visit est, low", category: "E/M", subcategory: "Home Visit" },
  { code: "99349", shortDesc: "Home/residence visit est, moderate", category: "E/M", subcategory: "Home Visit" },
  { code: "99350", shortDesc: "Home/residence visit est, high", category: "E/M", subcategory: "Home Visit" },
  { code: "99381", shortDesc: "Preventive visit new, infant", category: "E/M", subcategory: "Preventive" },
  { code: "99391", shortDesc: "Preventive visit est, infant", category: "E/M", subcategory: "Preventive" },
  { code: "99385", shortDesc: "Preventive visit new, 18-39 yrs", category: "E/M", subcategory: "Preventive" },
  { code: "99386", shortDesc: "Preventive visit new, 40-64 yrs", category: "E/M", subcategory: "Preventive" },
  { code: "99395", shortDesc: "Preventive visit est, 18-39 yrs", category: "E/M", subcategory: "Preventive" },
  { code: "99396", shortDesc: "Preventive visit est, 40-64 yrs", category: "E/M", subcategory: "Preventive" },
  { code: "99397", shortDesc: "Preventive visit est, 65+ yrs", category: "E/M", subcategory: "Preventive" },
  { code: "99495", shortDesc: "Transitional care mgmt, face-to-face within 7 days", category: "E/M", subcategory: "Care Management" },
  { code: "99496", shortDesc: "Transitional care mgmt, face-to-face within 14 days", category: "E/M", subcategory: "Care Management" },

  // ═══════════════════════════════════════════════════════════════
  // ANESTHESIA
  // ═══════════════════════════════════════════════════════════════
  { code: "00100", shortDesc: "Anesthesia for salivary gland procedures", category: "Anesthesia", subcategory: "Head" },
  { code: "00142", shortDesc: "Anesthesia for lens surgery", category: "Anesthesia", subcategory: "Head" },
  { code: "00160", shortDesc: "Anesthesia for nose/sinus surgery", category: "Anesthesia", subcategory: "Head" },
  { code: "00210", shortDesc: "Anesthesia for intracranial procedures", category: "Anesthesia", subcategory: "Head" },
  { code: "00300", shortDesc: "Anesthesia for head/neck/throat procedures", category: "Anesthesia", subcategory: "Neck" },
  { code: "00400", shortDesc: "Anesthesia for integumentary system, anterior trunk", category: "Anesthesia", subcategory: "Thorax" },
  { code: "00500", shortDesc: "Anesthesia for esophageal procedures", category: "Anesthesia", subcategory: "Thorax" },
  { code: "00520", shortDesc: "Anesthesia for thoracic spine/cord procedures", category: "Anesthesia", subcategory: "Spine" },
  { code: "00600", shortDesc: "Anesthesia for cervical spine procedures", category: "Anesthesia", subcategory: "Spine" },
  { code: "00604", shortDesc: "Anesthesia for cervical spine with cord", category: "Anesthesia", subcategory: "Spine" },
  { code: "00630", shortDesc: "Anesthesia for lumbar spine procedures", category: "Anesthesia", subcategory: "Spine" },
  { code: "00635", shortDesc: "Anesthesia for lumbar/sacral laminectomy", category: "Anesthesia", subcategory: "Spine" },
  { code: "00670", shortDesc: "Anesthesia for extensive spine procedures", category: "Anesthesia", subcategory: "Spine" },
  { code: "00700", shortDesc: "Anesthesia for upper abdominal procedures", category: "Anesthesia", subcategory: "Abdomen" },
  { code: "00800", shortDesc: "Anesthesia for lower abdominal procedures", category: "Anesthesia", subcategory: "Abdomen" },
  { code: "00902", shortDesc: "Anesthesia for anorectal procedures", category: "Anesthesia", subcategory: "Perineum" },
  { code: "01200", shortDesc: "Anesthesia for hip procedures, open", category: "Anesthesia", subcategory: "Lower Extremity" },
  { code: "01402", shortDesc: "Anesthesia for knee arthroplasty", category: "Anesthesia", subcategory: "Lower Extremity" },
  { code: "01480", shortDesc: "Anesthesia for ankle/foot procedures", category: "Anesthesia", subcategory: "Lower Extremity" },
  { code: "01996", shortDesc: "Daily hospital management of epidural/subarachnoid", category: "Anesthesia", subcategory: "Other" },

  // ═══════════════════════════════════════════════════════════════
  // SURGERY — INTEGUMENTARY
  // ═══════════════════════════════════════════════════════════════
  { code: "10060", shortDesc: "I&D abscess, simple", category: "Surgery", subcategory: "Integumentary" },
  { code: "10061", shortDesc: "I&D abscess, complicated", category: "Surgery", subcategory: "Integumentary" },
  { code: "10120", shortDesc: "Incision/removal of foreign body, simple", category: "Surgery", subcategory: "Integumentary" },
  { code: "10140", shortDesc: "I&D hematoma/seroma", category: "Surgery", subcategory: "Integumentary" },
  { code: "10160", shortDesc: "Puncture aspiration abscess/cyst", category: "Surgery", subcategory: "Integumentary" },
  { code: "11042", shortDesc: "Debridement subcutaneous tissue, first 20 sq cm", category: "Surgery", subcategory: "Integumentary" },
  { code: "11043", shortDesc: "Debridement muscle/fascia, first 20 sq cm", category: "Surgery", subcategory: "Integumentary" },
  { code: "11044", shortDesc: "Debridement bone, first 20 sq cm", category: "Surgery", subcategory: "Integumentary" },
  { code: "11102", shortDesc: "Tangential biopsy skin, single lesion", category: "Surgery", subcategory: "Integumentary" },
  { code: "11104", shortDesc: "Punch biopsy skin, single lesion", category: "Surgery", subcategory: "Integumentary" },
  { code: "11106", shortDesc: "Incisional biopsy skin, single lesion", category: "Surgery", subcategory: "Integumentary" },
  { code: "11400", shortDesc: "Excision benign lesion, 0.5 cm or less", category: "Surgery", subcategory: "Integumentary" },
  { code: "11600", shortDesc: "Excision malignant lesion, 0.5 cm or less", category: "Surgery", subcategory: "Integumentary" },
  { code: "12001", shortDesc: "Simple repair wound, 2.5 cm or less", category: "Surgery", subcategory: "Integumentary" },
  { code: "12002", shortDesc: "Simple repair wound, 2.6-7.5 cm", category: "Surgery", subcategory: "Integumentary" },
  { code: "12031", shortDesc: "Intermediate repair wound, 2.5 cm or less", category: "Surgery", subcategory: "Integumentary" },
  { code: "12051", shortDesc: "Intermediate repair wound face, 2.5 cm or less", category: "Surgery", subcategory: "Integumentary" },
  { code: "13100", shortDesc: "Complex repair wound trunk, 1.1-2.5 cm", category: "Surgery", subcategory: "Integumentary" },
  { code: "13131", shortDesc: "Complex repair wound face, 1.1-2.5 cm", category: "Surgery", subcategory: "Integumentary" },

  // ═══════════════════════════════════════════════════════════════
  // SURGERY — MUSCULOSKELETAL
  // ═══════════════════════════════════════════════════════════════
  { code: "20200", shortDesc: "Biopsy muscle, superficial", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20220", shortDesc: "Biopsy bone, trocar/needle", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20225", shortDesc: "Biopsy bone, trocar/needle, deep", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20240", shortDesc: "Biopsy bone, excisional, superficial", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20245", shortDesc: "Biopsy bone, excisional, deep", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20520", shortDesc: "Removal of foreign body, muscle", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20526", shortDesc: "Injection therapeutic, carpal tunnel", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20550", shortDesc: "Injection tendon sheath/ligament", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20551", shortDesc: "Injection tendon origin/insertion", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20600", shortDesc: "Arthrocentesis small joint", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20605", shortDesc: "Arthrocentesis intermediate joint", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20610", shortDesc: "Arthrocentesis major joint/bursa", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "20680", shortDesc: "Removal of implant, deep", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "27130", shortDesc: "Total hip arthroplasty", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "27236", shortDesc: "ORIF femoral neck fracture", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "27244", shortDesc: "ORIF intertrochanteric femur fracture", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "27245", shortDesc: "ORIF intertrochanteric femur fx, intramedullary", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "27447", shortDesc: "Total knee arthroplasty", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "27752", shortDesc: "ORIF tibial shaft fracture", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "29881", shortDesc: "Knee arthroscopy with meniscectomy", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "29882", shortDesc: "Knee arthroscopy with meniscus repair", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "29888", shortDesc: "Knee arthroscopy with ACL reconstruction", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "29826", shortDesc: "Shoulder arthroscopy with decompression", category: "Surgery", subcategory: "Musculoskeletal" },
  { code: "29827", shortDesc: "Shoulder arthroscopy with rotator cuff repair", category: "Surgery", subcategory: "Musculoskeletal" },

  // ═══════════════════════════════════════════════════════════════
  // SURGERY — RESPIRATORY / CARDIOVASCULAR
  // ═══════════════════════════════════════════════════════════════
  { code: "31231", shortDesc: "Nasal endoscopy, diagnostic", category: "Surgery", subcategory: "Respiratory" },
  { code: "31237", shortDesc: "Nasal endoscopy with biopsy", category: "Surgery", subcategory: "Respiratory" },
  { code: "31240", shortDesc: "Nasal endoscopy with concha bullosa removal", category: "Surgery", subcategory: "Respiratory" },
  { code: "31254", shortDesc: "Nasal endoscopy with ethmoidectomy", category: "Surgery", subcategory: "Respiratory" },
  { code: "31255", shortDesc: "Nasal endoscopy with total ethmoidectomy", category: "Surgery", subcategory: "Respiratory" },
  { code: "31256", shortDesc: "Nasal endoscopy with maxillary antrostomy", category: "Surgery", subcategory: "Respiratory" },
  { code: "31267", shortDesc: "Nasal endoscopy with frontal sinus exploration", category: "Surgery", subcategory: "Respiratory" },
  { code: "31575", shortDesc: "Laryngoscopy, flexible, diagnostic", category: "Surgery", subcategory: "Respiratory" },
  { code: "31622", shortDesc: "Bronchoscopy, diagnostic", category: "Surgery", subcategory: "Respiratory" },
  { code: "31624", shortDesc: "Bronchoscopy with bronchial alveolar lavage", category: "Surgery", subcategory: "Respiratory" },
  { code: "31625", shortDesc: "Bronchoscopy with biopsy", category: "Surgery", subcategory: "Respiratory" },
  { code: "32096", shortDesc: "Thoracotomy with biopsy", category: "Surgery", subcategory: "Respiratory" },
  { code: "32480", shortDesc: "Lobectomy, total or partial", category: "Surgery", subcategory: "Respiratory" },
  { code: "32551", shortDesc: "Tube thoracostomy, chest tube", category: "Surgery", subcategory: "Respiratory" },
  { code: "32666", shortDesc: "VATS with wedge resection", category: "Surgery", subcategory: "Respiratory" },
  { code: "33208", shortDesc: "Pacemaker insertion, dual chamber", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "33249", shortDesc: "ICD system insertion/replacement", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "33361", shortDesc: "TAVR, transfemoral", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "33405", shortDesc: "Aortic valve replacement, open", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "33430", shortDesc: "Mitral valve replacement", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "33533", shortDesc: "CABG single arterial graft", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "33534", shortDesc: "CABG two arterial grafts", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "34812", shortDesc: "Femoral artery exposure for endovascular", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "35301", shortDesc: "Carotid endarterectomy", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "36555", shortDesc: "Central venous catheter insertion, under 5 yrs", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "36556", shortDesc: "Central venous catheter insertion, 5 yrs+", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "36558", shortDesc: "Central venous catheter insertion, tunneled", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "36561", shortDesc: "Tunneled catheter with subcutaneous port", category: "Surgery", subcategory: "Cardiovascular" },
  { code: "36620", shortDesc: "Arterial catheterization, percutaneous", category: "Surgery", subcategory: "Cardiovascular" },

  // ═══════════════════════════════════════════════════════════════
  // SURGERY — DIGESTIVE
  // ═══════════════════════════════════════════════════════════════
  { code: "43235", shortDesc: "EGD, diagnostic", category: "Surgery", subcategory: "Digestive" },
  { code: "43239", shortDesc: "EGD with biopsy", category: "Surgery", subcategory: "Digestive" },
  { code: "43246", shortDesc: "EGD with PEG tube placement", category: "Surgery", subcategory: "Digestive" },
  { code: "43247", shortDesc: "EGD with foreign body removal", category: "Surgery", subcategory: "Digestive" },
  { code: "43248", shortDesc: "EGD with dilation", category: "Surgery", subcategory: "Digestive" },
  { code: "43280", shortDesc: "Laparoscopic fundoplication", category: "Surgery", subcategory: "Digestive" },
  { code: "43659", shortDesc: "Laparoscopic gastric restrictive procedure", category: "Surgery", subcategory: "Digestive" },
  { code: "44120", shortDesc: "Small bowel resection", category: "Surgery", subcategory: "Digestive" },
  { code: "44140", shortDesc: "Colectomy, partial, with anastomosis", category: "Surgery", subcategory: "Digestive" },
  { code: "44180", shortDesc: "Laparoscopic enterolysis", category: "Surgery", subcategory: "Digestive" },
  { code: "44950", shortDesc: "Appendectomy", category: "Surgery", subcategory: "Digestive" },
  { code: "44970", shortDesc: "Laparoscopic appendectomy", category: "Surgery", subcategory: "Digestive" },
  { code: "45378", shortDesc: "Colonoscopy, diagnostic", category: "Surgery", subcategory: "Digestive" },
  { code: "45380", shortDesc: "Colonoscopy with biopsy", category: "Surgery", subcategory: "Digestive" },
  { code: "45385", shortDesc: "Colonoscopy with polypectomy", category: "Surgery", subcategory: "Digestive" },
  { code: "47562", shortDesc: "Laparoscopic cholecystectomy", category: "Surgery", subcategory: "Digestive" },
  { code: "47563", shortDesc: "Laparoscopic cholecystectomy with cholangiography", category: "Surgery", subcategory: "Digestive" },
  { code: "49320", shortDesc: "Diagnostic laparoscopy", category: "Surgery", subcategory: "Digestive" },
  { code: "49505", shortDesc: "Inguinal hernia repair, initial", category: "Surgery", subcategory: "Digestive" },
  { code: "49507", shortDesc: "Inguinal hernia repair, incarcerated", category: "Surgery", subcategory: "Digestive" },
  { code: "49585", shortDesc: "Umbilical hernia repair, under 5 yrs", category: "Surgery", subcategory: "Digestive" },
  { code: "49650", shortDesc: "Laparoscopic inguinal hernia repair", category: "Surgery", subcategory: "Digestive" },

  // ═══════════════════════════════════════════════════════════════
  // SURGERY — URINARY / GENITAL
  // ═══════════════════════════════════════════════════════════════
  { code: "50060", shortDesc: "Nephrolithotomy, removal of calculus", category: "Surgery", subcategory: "Urinary" },
  { code: "50590", shortDesc: "Lithotripsy, extracorporeal shockwave", category: "Surgery", subcategory: "Urinary" },
  { code: "51102", shortDesc: "Aspiration of bladder, trocar", category: "Surgery", subcategory: "Urinary" },
  { code: "52000", shortDesc: "Cystourethroscopy", category: "Surgery", subcategory: "Urinary" },
  { code: "52234", shortDesc: "Cystoscopy with tumor fulguration, small", category: "Surgery", subcategory: "Urinary" },
  { code: "52310", shortDesc: "Cystoscopy with stone removal", category: "Surgery", subcategory: "Urinary" },
  { code: "52601", shortDesc: "TURP, prostatectomy", category: "Surgery", subcategory: "Urinary" },
  { code: "55700", shortDesc: "Prostate biopsy, needle", category: "Surgery", subcategory: "Urinary" },
  { code: "55866", shortDesc: "Laparoscopic prostatectomy", category: "Surgery", subcategory: "Urinary" },
  { code: "57421", shortDesc: "Colposcopy of vagina with biopsy", category: "Surgery", subcategory: "Female Genital" },
  { code: "57452", shortDesc: "Colposcopy of cervix with biopsy", category: "Surgery", subcategory: "Female Genital" },
  { code: "58100", shortDesc: "Endometrial biopsy", category: "Surgery", subcategory: "Female Genital" },
  { code: "58150", shortDesc: "Total abdominal hysterectomy", category: "Surgery", subcategory: "Female Genital" },
  { code: "58260", shortDesc: "Vaginal hysterectomy", category: "Surgery", subcategory: "Female Genital" },
  { code: "58558", shortDesc: "Hysteroscopy with biopsy", category: "Surgery", subcategory: "Female Genital" },
  { code: "58571", shortDesc: "Laparoscopic hysterectomy, total", category: "Surgery", subcategory: "Female Genital" },
  { code: "58661", shortDesc: "Laparoscopy with removal of adnexal structures", category: "Surgery", subcategory: "Female Genital" },
  { code: "59400", shortDesc: "Obstetric care, vaginal delivery", category: "Surgery", subcategory: "Maternity" },
  { code: "59510", shortDesc: "Cesarean delivery", category: "Surgery", subcategory: "Maternity" },
  { code: "59610", shortDesc: "VBAC after previous C-section", category: "Surgery", subcategory: "Maternity" },

  // ═══════════════════════════════════════════════════════════════
  // RADIOLOGY
  // ═══════════════════════════════════════════════════════════════
  { code: "70551", shortDesc: "MRI brain without contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70553", shortDesc: "MRI brain without and with contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70540", shortDesc: "MRI orbit/face/neck without contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70336", shortDesc: "MRI TMJ", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70450", shortDesc: "CT head/brain without contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70460", shortDesc: "CT head/brain with contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70496", shortDesc: "CT angiography head", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70498", shortDesc: "CT angiography neck", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70544", shortDesc: "MR angiography head without contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "70549", shortDesc: "MR angiography neck with contrast", category: "Radiology", subcategory: "Head/Neck" },
  { code: "71045", shortDesc: "X-ray chest, single view", category: "Radiology", subcategory: "Chest" },
  { code: "71046", shortDesc: "X-ray chest, 2 views", category: "Radiology", subcategory: "Chest" },
  { code: "71250", shortDesc: "CT chest without contrast", category: "Radiology", subcategory: "Chest" },
  { code: "71260", shortDesc: "CT chest with contrast", category: "Radiology", subcategory: "Chest" },
  { code: "71275", shortDesc: "CT angiography chest (CTA PE)", category: "Radiology", subcategory: "Chest" },
  { code: "72141", shortDesc: "MRI cervical spine without contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72146", shortDesc: "MRI thoracic spine without contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72148", shortDesc: "MRI lumbar spine without contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72156", shortDesc: "MRI cervical spine without and with contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72158", shortDesc: "MRI lumbar spine without and with contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72125", shortDesc: "CT cervical spine without contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72131", shortDesc: "CT lumbar spine without contrast", category: "Radiology", subcategory: "Spine" },
  { code: "72197", shortDesc: "MRI pelvis without and with contrast", category: "Radiology", subcategory: "Spine" },
  { code: "73721", shortDesc: "MRI knee without contrast", category: "Radiology", subcategory: "Extremity" },
  { code: "73221", shortDesc: "MRI shoulder without contrast", category: "Radiology", subcategory: "Extremity" },
  { code: "74150", shortDesc: "CT abdomen without contrast", category: "Radiology", subcategory: "Abdomen" },
  { code: "74177", shortDesc: "CT abdomen/pelvis with contrast", category: "Radiology", subcategory: "Abdomen" },
  { code: "74178", shortDesc: "CT abdomen/pelvis without and with contrast", category: "Radiology", subcategory: "Abdomen" },
  { code: "76536", shortDesc: "Ultrasound head/neck soft tissue", category: "Radiology", subcategory: "Ultrasound" },
  { code: "76700", shortDesc: "Ultrasound abdomen, complete", category: "Radiology", subcategory: "Ultrasound" },
  { code: "76770", shortDesc: "Ultrasound retroperitoneal, complete", category: "Radiology", subcategory: "Ultrasound" },
  { code: "76856", shortDesc: "Ultrasound pelvis, complete", category: "Radiology", subcategory: "Ultrasound" },
  { code: "77263", shortDesc: "Treatment planning, complex", category: "Radiology", subcategory: "Radiation Oncology" },
  { code: "77385", shortDesc: "IMRT delivery, simple", category: "Radiology", subcategory: "Radiation Oncology" },
  { code: "77386", shortDesc: "IMRT delivery, complex", category: "Radiology", subcategory: "Radiation Oncology" },

  // ═══════════════════════════════════════════════════════════════
  // PATHOLOGY & LAB
  // ═══════════════════════════════════════════════════════════════
  { code: "80048", shortDesc: "Basic metabolic panel", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "80050", shortDesc: "General health panel", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "80053", shortDesc: "Comprehensive metabolic panel", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "80061", shortDesc: "Lipid panel", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "80069", shortDesc: "Renal function panel", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "80076", shortDesc: "Hepatic function panel", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "82565", shortDesc: "Creatinine, blood", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "82607", shortDesc: "Cyanocobalamin (vitamin B-12)", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "82728", shortDesc: "Ferritin", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "82947", shortDesc: "Glucose, blood", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "83036", shortDesc: "Hemoglobin A1c", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "84443", shortDesc: "TSH (thyroid stimulating hormone)", category: "Pathology/Lab", subcategory: "Chemistry" },
  { code: "85025", shortDesc: "CBC with differential, automated", category: "Pathology/Lab", subcategory: "Hematology" },
  { code: "85027", shortDesc: "CBC, automated", category: "Pathology/Lab", subcategory: "Hematology" },
  { code: "85610", shortDesc: "Prothrombin time (PT)", category: "Pathology/Lab", subcategory: "Hematology" },
  { code: "85730", shortDesc: "Partial thromboplastin time (PTT)", category: "Pathology/Lab", subcategory: "Hematology" },
  { code: "86140", shortDesc: "C-reactive protein (CRP)", category: "Pathology/Lab", subcategory: "Immunology" },
  { code: "86200", shortDesc: "Cyclic citrullinated peptide antibody", category: "Pathology/Lab", subcategory: "Immunology" },
  { code: "86580", shortDesc: "TB skin test (PPD)", category: "Pathology/Lab", subcategory: "Immunology" },
  { code: "87070", shortDesc: "Culture, bacterial, any source", category: "Pathology/Lab", subcategory: "Microbiology" },
  { code: "87081", shortDesc: "Culture, screening only", category: "Pathology/Lab", subcategory: "Microbiology" },
  { code: "87491", shortDesc: "Chlamydia, amplified probe", category: "Pathology/Lab", subcategory: "Microbiology" },
  { code: "87591", shortDesc: "Neisseria gonorrhoeae, amplified probe", category: "Pathology/Lab", subcategory: "Microbiology" },
  { code: "87804", shortDesc: "Influenza A&B rapid test", category: "Pathology/Lab", subcategory: "Microbiology" },
  { code: "87880", shortDesc: "Strep A rapid test", category: "Pathology/Lab", subcategory: "Microbiology" },
  { code: "88305", shortDesc: "Surgical pathology, gross and micro exam", category: "Pathology/Lab", subcategory: "Pathology" },
  { code: "88307", shortDesc: "Surgical pathology, complex", category: "Pathology/Lab", subcategory: "Pathology" },
  { code: "88312", shortDesc: "Special stain, Group I", category: "Pathology/Lab", subcategory: "Pathology" },
  { code: "88342", shortDesc: "Immunohistochemistry, each antibody", category: "Pathology/Lab", subcategory: "Pathology" },

  // ═══════════════════════════════════════════════════════════════
  // MEDICINE
  // ═══════════════════════════════════════════════════════════════
  { code: "90471", shortDesc: "Immunization administration, 1st vaccine", category: "Medicine", subcategory: "Immunizations" },
  { code: "90472", shortDesc: "Immunization administration, each additional", category: "Medicine", subcategory: "Immunizations" },
  { code: "90658", shortDesc: "Influenza vaccine, intramuscular", category: "Medicine", subcategory: "Immunizations" },
  { code: "90715", shortDesc: "Tdap vaccine", category: "Medicine", subcategory: "Immunizations" },
  { code: "90832", shortDesc: "Psychotherapy, 30 min", category: "Medicine", subcategory: "Psychiatry" },
  { code: "90834", shortDesc: "Psychotherapy, 45 min", category: "Medicine", subcategory: "Psychiatry" },
  { code: "90837", shortDesc: "Psychotherapy, 60 min", category: "Medicine", subcategory: "Psychiatry" },
  { code: "90791", shortDesc: "Psychiatric diagnostic evaluation", category: "Medicine", subcategory: "Psychiatry" },
  { code: "92012", shortDesc: "Ophthalmologic exam est patient, intermediate", category: "Medicine", subcategory: "Ophthalmology" },
  { code: "92014", shortDesc: "Ophthalmologic exam est patient, comprehensive", category: "Medicine", subcategory: "Ophthalmology" },
  { code: "92507", shortDesc: "Speech/language treatment", category: "Medicine", subcategory: "Speech" },
  { code: "93000", shortDesc: "Electrocardiogram (ECG/EKG), 12-lead", category: "Medicine", subcategory: "Cardiovascular" },
  { code: "93010", shortDesc: "ECG interpretation only", category: "Medicine", subcategory: "Cardiovascular" },
  { code: "93306", shortDesc: "Echocardiography, TTE, complete", category: "Medicine", subcategory: "Cardiovascular" },
  { code: "93451", shortDesc: "Right heart catheterization", category: "Medicine", subcategory: "Cardiovascular" },
  { code: "93458", shortDesc: "Left heart catheterization with angiography", category: "Medicine", subcategory: "Cardiovascular" },
  { code: "94010", shortDesc: "Spirometry", category: "Medicine", subcategory: "Pulmonary" },
  { code: "94060", shortDesc: "Spirometry before and after bronchodilator", category: "Medicine", subcategory: "Pulmonary" },
  { code: "94760", shortDesc: "Pulse oximetry", category: "Medicine", subcategory: "Pulmonary" },
  { code: "95004", shortDesc: "Allergy percutaneous tests", category: "Medicine", subcategory: "Allergy" },
  { code: "95165", shortDesc: "Allergy immunotherapy, multiple antigens", category: "Medicine", subcategory: "Allergy" },
  { code: "95700", shortDesc: "EEG without video, 2-12 hours", category: "Medicine", subcategory: "Neurology" },
  { code: "95816", shortDesc: "EEG, awake and asleep", category: "Medicine", subcategory: "Neurology" },
  { code: "95819", shortDesc: "EEG, awake and asleep with stimulation", category: "Medicine", subcategory: "Neurology" },
  { code: "95907", shortDesc: "Nerve conduction study, 1-2 studies", category: "Medicine", subcategory: "Neurology" },
  { code: "95908", shortDesc: "Nerve conduction study, 3-4 studies", category: "Medicine", subcategory: "Neurology" },
  { code: "95909", shortDesc: "Nerve conduction study, 5-6 studies", category: "Medicine", subcategory: "Neurology" },
  { code: "95910", shortDesc: "Nerve conduction study, 7-8 studies", category: "Medicine", subcategory: "Neurology" },
  { code: "95860", shortDesc: "EMG, 1 extremity, limited", category: "Medicine", subcategory: "Neurology" },
  { code: "95861", shortDesc: "EMG, 2 extremities, limited", category: "Medicine", subcategory: "Neurology" },
  { code: "95886", shortDesc: "EMG, complete, each extremity", category: "Medicine", subcategory: "Neurology" },
  { code: "96360", shortDesc: "IV infusion, hydration, first hour", category: "Medicine", subcategory: "Infusion" },
  { code: "96365", shortDesc: "IV infusion, therapeutic, first hour", category: "Medicine", subcategory: "Infusion" },
  { code: "96372", shortDesc: "Therapeutic injection, subcutaneous/IM", category: "Medicine", subcategory: "Infusion" },
  { code: "96374", shortDesc: "Therapeutic injection, IV push", category: "Medicine", subcategory: "Infusion" },
  { code: "96413", shortDesc: "Chemotherapy infusion, first hour", category: "Medicine", subcategory: "Infusion" },
  { code: "97110", shortDesc: "Physical therapy, therapeutic exercises", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97112", shortDesc: "Physical therapy, neuromuscular reeducation", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97140", shortDesc: "Manual therapy techniques", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97161", shortDesc: "PT evaluation, low complexity", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97162", shortDesc: "PT evaluation, moderate complexity", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97163", shortDesc: "PT evaluation, high complexity", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97530", shortDesc: "Therapeutic activities", category: "Medicine", subcategory: "Physical Therapy" },
  { code: "97542", shortDesc: "Wheelchair management training", category: "Medicine", subcategory: "Physical Therapy" },
];
