// Neurosurgery CPT Codes — Curated Dataset with Rich Synonyms
// Covers cranial, spine, and peripheral nerve procedures
// Cross-reference against current AMA CPT codebook annually

export const NEUROSURGERY_CODES = [

  // ═══════════════════════════════════════════════════════════════════════════
  // CRANIOTOMY - TRAUMA
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "61108", shortDesc: "Twist drill hole for subdural/intracerebral drainage", fullDesc: "Twist drill hole(s) for subdural, intracerebral, or subarachnoid hemorrhage or cyst aspiration", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["twist drill evacuation", "twist drill subdural", "twist drill hole SDH", "subdural tap", "twist drill cSDH", "bedside subdural drain", "twist drill aspiration"], keywords: ["twist drill", "subdural", "intracerebral", "subarachnoid", "hemorrhage", "cyst", "aspiration", "drainage", "hematoma"], relatedCodes: ["61120", "61140", "61154"] },
  { code: "61120", shortDesc: "Burr hole for ventricular puncture", fullDesc: "Burr hole(s) for ventricular puncture (including injection of gas, contrast media, dye, or radioactive material)", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["ventricular tap", "burr hole ventriculostomy", "ventricular puncture", "burr hole ICP monitor", "emergency ventriculostomy", "burr hole EVD", "external ventricular drain"], keywords: ["burr hole", "ventricular", "puncture", "ventriculostomy", "ICP", "EVD"], relatedCodes: ["61108", "61210", "62220"] },
  { code: "61140", shortDesc: "Burr hole for hematoma evacuation, extradural/subdural", fullDesc: "Burr hole(s) or trephine; with evacuation and/or drainage of hematoma, extradural or subdural", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["burr hole SDH evacuation", "burr hole subdural hematoma", "burr hole EDH", "burr hole epidural hematoma", "burr hole hematoma drainage", "trephine subdural", "burr hole cSDH", "burr hole chronic subdural", "burr hole acute subdural"], keywords: ["burr hole", "trephine", "evacuation", "drainage", "hematoma", "extradural", "epidural", "subdural"], relatedCodes: ["61108", "61154", "61312"] },
  { code: "61150", shortDesc: "Burr hole with drainage of brain abscess/cyst", fullDesc: "Burr hole(s) or trephine; with drainage of brain abscess or cyst", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["burr hole brain abscess", "burr hole abscess drainage", "burr hole cyst drainage", "trephine abscess", "burr hole cerebral abscess"], keywords: ["burr hole", "trephine", "drainage", "brain abscess", "cyst", "cerebral abscess"], relatedCodes: ["61108", "61140", "61514"] },
  { code: "61154", shortDesc: "Burr hole with evacuation of hematoma, intracerebral", fullDesc: "Burr hole(s) with evacuation and/or drainage of hematoma, intracerebral", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["burr hole ICH evacuation", "burr hole intracerebral hematoma", "burr hole brain hemorrhage", "burr hole hemorrhagic stroke", "trephine ICH", "burr hole intraparenchymal hematoma"], keywords: ["burr hole", "evacuation", "drainage", "hematoma", "intracerebral", "hemorrhage", "ICH"], relatedCodes: ["61108", "61140", "61313"] },
  { code: "61156", shortDesc: "Burr hole with aspiration of hematoma/cyst, infratentorial", fullDesc: "Burr hole(s) with aspiration of hematoma or cyst, infratentorial", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["burr hole posterior fossa hematoma", "burr hole cerebellar hematoma", "burr hole infratentorial", "posterior fossa burr hole", "burr hole cerebellar hemorrhage"], keywords: ["burr hole", "aspiration", "hematoma", "cyst", "infratentorial", "posterior fossa", "cerebellar"], relatedCodes: ["61154", "61314", "61315"] },
  { code: "61304", shortDesc: "Craniectomy/craniotomy, exploratory, supratentorial", fullDesc: "Craniectomy or craniotomy, exploratory; supratentorial", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["exploratory craniotomy supratentorial", "exploratory craniectomy", "diagnostic craniotomy", "supratentorial exploration"], keywords: ["craniectomy", "craniotomy", "exploratory", "supratentorial"], relatedCodes: ["61305", "61312", "61313"] },
  { code: "61305", shortDesc: "Craniectomy/craniotomy, exploratory, infratentorial", fullDesc: "Craniectomy or craniotomy, exploratory; infratentorial (posterior fossa)", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["exploratory craniotomy posterior fossa", "exploratory craniectomy infratentorial", "posterior fossa exploration", "suboccipital exploration"], keywords: ["craniectomy", "craniotomy", "exploratory", "infratentorial", "posterior fossa"], relatedCodes: ["61304", "61314", "61315"] },
  { code: "61312", shortDesc: "Craniotomy evacuate hematoma supratentorial, extradural", fullDesc: "Craniectomy or craniotomy for evacuation of hematoma, supratentorial; extradural (epidural)", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["craniotomy EDH", "craniotomy epidural hematoma", "crani for epidural", "craniectomy extradural hematoma", "craniotomy acute EDH", "EDH evacuation craniotomy", "crani EDH evac", "supratentorial EDH evacuation", "epidural hematoma evacuation"], keywords: ["craniectomy", "craniotomy", "evacuation", "hematoma", "supratentorial", "extradural", "epidural", "EDH"], relatedCodes: ["61313", "61314", "61140", "61322"] },
  { code: "61313", shortDesc: "Craniotomy evacuate hematoma supratentorial, subdural", fullDesc: "Craniectomy or craniotomy for evacuation of hematoma, supratentorial; subdural", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["craniotomy SDH", "craniotomy subdural hematoma", "crani for subdural", "SDH evacuation craniotomy", "craniotomy acute SDH", "craniotomy chronic subdural", "crani SDH evac", "subdural hematoma evacuation", "craniectomy subdural"], keywords: ["craniectomy", "craniotomy", "evacuation", "hematoma", "supratentorial", "subdural", "SDH"], relatedCodes: ["61312", "61314", "61140", "61322"] },
  { code: "61314", shortDesc: "Craniotomy evacuate hematoma infratentorial, extradural/subdural", fullDesc: "Craniectomy or craniotomy for evacuation of hematoma, infratentorial; extradural or subdural", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["craniotomy posterior fossa hematoma", "craniectomy infratentorial hematoma", "posterior fossa EDH evacuation", "posterior fossa SDH evacuation", "infratentorial hematoma evacuation", "suboccipital crani hematoma", "suboccipital craniectomy hematoma evacuation", "posterior fossa subdural evacuation", "suboccipital crani for hematoma"], keywords: ["craniectomy", "craniotomy", "evacuation", "hematoma", "infratentorial", "posterior fossa", "extradural", "subdural", "suboccipital"], relatedCodes: ["61312", "61313", "61315", "61156"] },
  { code: "61315", shortDesc: "Craniotomy evacuate hematoma infratentorial, intracerebral", fullDesc: "Craniectomy or craniotomy for evacuation of hematoma, infratentorial; intracerebral", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["craniotomy cerebellar hemorrhage", "craniectomy cerebellar hematoma", "posterior fossa ICH evacuation", "cerebellar ICH craniotomy", "infratentorial intracerebral hematoma", "cerebellar hemorrhage evacuation", "suboccipital crani cerebellar hematoma"], keywords: ["craniectomy", "craniotomy", "evacuation", "hematoma", "infratentorial", "intracerebral", "cerebellar", "posterior fossa"], relatedCodes: ["61312", "61313", "61314", "61156"] },
  { code: "61322", shortDesc: "Decompressive craniectomy, subtemporal", fullDesc: "Decompressive craniotomy or craniectomy, subtemporal", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["decompressive craniectomy", "subtemporal decompression", "decompressive crani", "hemicraniectomy", "trauma decompressive craniectomy", "DC subtemporal", "decompressive hemicraniectomy"], keywords: ["decompressive", "craniectomy", "craniotomy", "subtemporal", "decompression", "ICP", "herniation", "hemicraniectomy"], relatedCodes: ["61323", "61312", "61313"] },
  { code: "61323", shortDesc: "Decompressive craniectomy, suboccipital", fullDesc: "Decompressive craniotomy or craniectomy, suboccipital; for intracranial hypertension, including dura enlargement when performed", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["decompressive craniectomy posterior fossa", "suboccipital decompressive craniectomy", "posterior fossa decompression", "DC suboccipital", "suboccipital decompression ICP"], keywords: ["decompressive", "craniectomy", "craniotomy", "suboccipital", "intracranial hypertension", "posterior fossa", "ICP"], relatedCodes: ["61322", "61343", "61314"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // CRANIOTOMY - TUMOR
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "61500", shortDesc: "Craniectomy for excision of tumor/bone lesion of skull", fullDesc: "Craniectomy; with excision of tumor or other bone lesion of skull", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["craniectomy skull tumor", "skull tumor excision", "cranial bone tumor", "skull lesion excision", "calvarial tumor excision"], keywords: ["craniectomy", "excision", "tumor", "bone lesion", "skull"], relatedCodes: ["61501", "61510"] },
  { code: "61501", shortDesc: "Craniectomy for osteomyelitis", fullDesc: "Craniectomy; for osteomyelitis", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["craniectomy osteomyelitis", "skull osteomyelitis surgery", "cranial osteomyelitis excision", "infected bone flap removal"], keywords: ["craniectomy", "osteomyelitis", "skull", "infection"], relatedCodes: ["61500"] },
  { code: "61510", shortDesc: "Craniotomy for excision of supratentorial brain tumor", fullDesc: "Craniectomy, trephination, bone flap craniotomy; for excision of brain tumor, supratentorial, except meningioma", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["craniotomy brain tumor", "supratentorial tumor excision", "brain tumor surgery", "craniotomy glioma", "craniotomy metastasis", "craniotomy GBM", "crani for tumor", "brain tumor resection", "craniotomy astrocytoma", "awake craniotomy tumor", "craniotomy brain met"], keywords: ["craniectomy", "craniotomy", "excision", "brain tumor", "supratentorial", "glioma", "metastasis", "GBM", "resection"], relatedCodes: ["61512", "61518", "61521"] },
  { code: "61512", shortDesc: "Craniotomy for excision of meningioma, supratentorial", fullDesc: "Craniectomy, trephination, bone flap craniotomy; for excision of meningioma, supratentorial", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["craniotomy meningioma", "meningioma resection", "supratentorial meningioma excision", "meningioma surgery", "convexity meningioma", "falcine meningioma", "parasagittal meningioma", "sphenoid wing meningioma", "olfactory groove meningioma", "tuberculum sellae meningioma"], keywords: ["craniectomy", "craniotomy", "excision", "meningioma", "supratentorial"], relatedCodes: ["61510", "61519"] },
  { code: "61514", shortDesc: "Craniotomy for excision of brain abscess, supratentorial", fullDesc: "Craniectomy, trephination, bone flap craniotomy; for excision of brain abscess, supratentorial", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["craniotomy brain abscess", "brain abscess excision", "cerebral abscess craniotomy", "brain abscess surgery"], keywords: ["craniectomy", "craniotomy", "excision", "brain abscess", "supratentorial"], relatedCodes: ["61510", "61150"] },
  { code: "61516", shortDesc: "Craniotomy for excision/fenestration of cyst, supratentorial", fullDesc: "Craniectomy, trephination, bone flap craniotomy; for excision or fenestration of cyst, supratentorial", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["craniotomy brain cyst", "craniotomy arachnoid cyst", "cyst fenestration craniotomy", "brain cyst surgery", "craniotomy colloid cyst"], keywords: ["craniectomy", "craniotomy", "excision", "fenestration", "cyst", "supratentorial", "arachnoid cyst"], relatedCodes: ["61510", "61524", "62162"] },
  { code: "61518", shortDesc: "Craniectomy for infratentorial brain tumor", fullDesc: "Craniectomy for excision of brain tumor, infratentorial or posterior fossa; except meningioma, cerebellopontine angle tumor, or midline tumor at base of skull", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["posterior fossa craniotomy tumor", "infratentorial tumor excision", "cerebellar tumor craniotomy", "suboccipital craniotomy tumor", "posterior fossa glioma", "cerebellar metastasis craniotomy"], keywords: ["craniectomy", "excision", "brain tumor", "infratentorial", "posterior fossa", "cerebellar"], relatedCodes: ["61510", "61519", "61520", "61521"] },
  { code: "61519", shortDesc: "Craniectomy for infratentorial meningioma", fullDesc: "Craniectomy for excision of brain tumor, infratentorial or posterior fossa; meningioma", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["posterior fossa meningioma", "infratentorial meningioma excision", "tentorial meningioma", "foramen magnum meningioma", "petroclival meningioma", "suboccipital meningioma"], keywords: ["craniectomy", "excision", "meningioma", "infratentorial", "posterior fossa", "tentorial"], relatedCodes: ["61512", "61518", "61520"] },
  { code: "61520", shortDesc: "Craniectomy for excision of CPA tumor", fullDesc: "Craniectomy for excision of brain tumor, infratentorial or posterior fossa; cerebellopontine angle tumor", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["CPA tumor excision", "acoustic neuroma surgery", "vestibular schwannoma excision", "cerebellopontine angle tumor", "retrosigmoid craniotomy", "CPA schwannoma", "acoustic neuroma craniotomy"], keywords: ["craniectomy", "excision", "brain tumor", "cerebellopontine angle", "CPA", "acoustic neuroma", "vestibular schwannoma", "retrosigmoid"], relatedCodes: ["61518", "61519", "61526"] },
  { code: "61521", shortDesc: "Craniectomy for midline tumor at skull base", fullDesc: "Craniectomy for excision of brain tumor, infratentorial or posterior fossa; midline tumor at base of skull", category: "Neurosurgery", subcategory: "Craniotomy - Tumor", synonyms: ["midline skull base tumor", "clivus tumor excision", "brainstem tumor surgery", "fourth ventricle tumor", "medulloblastoma surgery", "ependymoma posterior fossa"], keywords: ["craniectomy", "excision", "brain tumor", "midline", "skull base", "infratentorial", "brainstem", "fourth ventricle"], relatedCodes: ["61518", "61519", "61520"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // CRANIOTOMY - VASCULAR
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "61624", shortDesc: "Transcatheter embolization/occlusion, intracranial", fullDesc: "Transcatheter permanent occlusion or embolization, percutaneous, any method; central nervous system (intracranial)", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["intracranial embolization", "AVM embolization", "aneurysm coiling", "endovascular coiling", "cerebral embolization", "CNS embolization", "tumor embolization intracranial", "preop embolization"], keywords: ["transcatheter", "occlusion", "embolization", "intracranial", "endovascular", "coiling"], relatedCodes: ["61626", "61680", "61700"] },
  { code: "61680", shortDesc: "Intracranial AVM surgery, supratentorial simple", fullDesc: "Surgery of intracranial arteriovenous malformation; supratentorial, simple", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["AVM excision simple", "supratentorial AVM surgery", "brain AVM resection", "craniotomy AVM", "arteriovenous malformation excision"], keywords: ["surgery", "intracranial", "arteriovenous malformation", "AVM", "supratentorial", "simple"], relatedCodes: ["61682", "61684", "61686"] },
  { code: "61682", shortDesc: "Intracranial AVM surgery, supratentorial complex", fullDesc: "Surgery of intracranial arteriovenous malformation; supratentorial, complex", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["AVM excision complex", "complex AVM surgery", "large AVM excision", "eloquent cortex AVM"], keywords: ["surgery", "intracranial", "AVM", "supratentorial", "complex"], relatedCodes: ["61680", "61684", "61686"] },
  { code: "61684", shortDesc: "Intracranial AVM surgery, infratentorial simple", fullDesc: "Surgery of intracranial arteriovenous malformation; infratentorial, simple", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["posterior fossa AVM simple", "cerebellar AVM excision", "infratentorial AVM surgery"], keywords: ["surgery", "AVM", "infratentorial", "simple", "posterior fossa", "cerebellar"], relatedCodes: ["61680", "61686"] },
  { code: "61686", shortDesc: "Intracranial AVM surgery, infratentorial complex", fullDesc: "Surgery of intracranial arteriovenous malformation; infratentorial, complex", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["posterior fossa AVM complex", "cerebellar AVM complex", "brainstem AVM excision"], keywords: ["surgery", "AVM", "infratentorial", "complex", "posterior fossa"], relatedCodes: ["61682", "61684"] },
  { code: "61690", shortDesc: "Intracranial AVM surgery, dural simple", fullDesc: "Surgery of intracranial arteriovenous malformation; dural, simple (eg, meningeal)", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["dural AVM excision", "dural arteriovenous fistula surgery", "dAVF surgery simple", "DAVF excision simple"], keywords: ["surgery", "AVM", "dural", "simple", "meningeal", "fistula", "dAVF"], relatedCodes: ["61692", "61680"] },
  { code: "61692", shortDesc: "Intracranial AVM surgery, dural complex", fullDesc: "Surgery of intracranial arteriovenous malformation; dural, complex (eg, transverse/sigmoid sinus)", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["dural AVM excision complex", "complex dAVF surgery", "transverse sinus dAVF", "sigmoid sinus dAVF", "DAVF excision complex"], keywords: ["surgery", "AVM", "dural", "complex", "transverse sinus", "sigmoid sinus", "dAVF"], relatedCodes: ["61690", "61686"] },
  { code: "61697", shortDesc: "Surgery complex intracranial aneurysm, carotid circulation", fullDesc: "Surgery of complex intracranial aneurysm, intracranial approach; carotid circulation", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["aneurysm clipping complex carotid", "complex anterior circulation aneurysm", "giant aneurysm clipping", "complex ICA aneurysm", "complex MCA aneurysm", "fusiform aneurysm surgery"], keywords: ["surgery", "complex", "intracranial aneurysm", "carotid circulation", "clipping", "anterior circulation"], relatedCodes: ["61698", "61700"] },
  { code: "61698", shortDesc: "Surgery complex intracranial aneurysm, vertebrobasilar", fullDesc: "Surgery of complex intracranial aneurysm, intracranial approach; vertebrobasilar circulation", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["complex basilar aneurysm", "complex posterior circulation aneurysm", "basilar tip aneurysm complex", "PICA aneurysm complex"], keywords: ["surgery", "complex", "intracranial aneurysm", "vertebrobasilar", "posterior circulation"], relatedCodes: ["61697", "61702"] },
  { code: "61700", shortDesc: "Surgery simple intracranial aneurysm, carotid circulation", fullDesc: "Surgery of simple intracranial aneurysm, intracranial approach; carotid circulation", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["aneurysm clipping", "MCA aneurysm clipping", "AComm aneurysm clipping", "PComm aneurysm clipping", "ICA aneurysm clipping", "pterional craniotomy aneurysm", "anterior circulation aneurysm", "SAH aneurysm clipping", "craniotomy aneurysm clipping"], keywords: ["surgery", "simple", "intracranial aneurysm", "carotid circulation", "clipping", "anterior circulation", "SAH"], relatedCodes: ["61697", "61702", "61711"] },
  { code: "61702", shortDesc: "Surgery simple intracranial aneurysm, vertebrobasilar", fullDesc: "Surgery of simple intracranial aneurysm, intracranial approach; vertebrobasilar circulation", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["aneurysm clipping posterior circulation", "PICA aneurysm clipping", "basilar tip aneurysm simple", "vertebral aneurysm clipping"], keywords: ["surgery", "simple", "intracranial aneurysm", "vertebrobasilar", "posterior circulation"], relatedCodes: ["61698", "61700"] },
  { code: "61711", shortDesc: "EC-IC arterial bypass anastomosis", fullDesc: "Anastomosis, arterial, extracranial-intracranial (eg, middle cerebral/cortical) arteries", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["EC-IC bypass", "STA-MCA bypass", "extracranial-intracranial bypass", "cerebral revascularization", "STA-MCA anastomosis", "moyamoya bypass", "ECIC bypass", "brain bypass"], keywords: ["anastomosis", "arterial", "extracranial-intracranial", "bypass", "STA-MCA", "revascularization", "moyamoya"], relatedCodes: ["61697", "61700"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUBOCCIPITAL PROCEDURES
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "61343", shortDesc: "Suboccipital craniectomy with cervical laminectomy (Chiari)", fullDesc: "Craniectomy, suboccipital with cervical laminectomy for decompression of medulla and spinal cord, with or without dural graft (eg, Arnold-Chiari malformation)", category: "Neurosurgery", subcategory: "Craniotomy - Trauma", synonyms: ["Chiari decompression", "Chiari malformation surgery", "Arnold-Chiari decompression", "suboccipital decompression", "foramen magnum decompression", "Chiari I decompression", "suboccipital craniectomy C1 laminectomy", "Chiari with duraplasty", "craniocervical decompression", "Chiari crani", "FMD Chiari"], keywords: ["craniectomy", "suboccipital", "cervical laminectomy", "decompression", "medulla", "spinal cord", "Arnold-Chiari", "Chiari", "foramen magnum", "duraplasty"], relatedCodes: ["61323", "61305"] },
  { code: "61458", shortDesc: "Suboccipital craniectomy for cranial nerve exploration/decompression", fullDesc: "Craniectomy, suboccipital; for exploration or decompression of cranial nerves", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["cranial nerve decompression", "MVD", "microvascular decompression", "MVD trigeminal neuralgia", "MVD hemifacial spasm", "Jannetta procedure", "trigeminal nerve decompression", "MVD glossopharyngeal neuralgia"], keywords: ["craniectomy", "suboccipital", "exploration", "decompression", "cranial nerves", "MVD", "microvascular decompression"], relatedCodes: ["61460", "61470", "61480"] },
  { code: "61460", shortDesc: "Suboccipital craniectomy for section of cranial nerve(s)", fullDesc: "Craniectomy, suboccipital; for section of one or more cranial nerves", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["cranial nerve section", "cranial nerve rhizotomy", "vestibular nerve section", "vestibular neurectomy", "CN section suboccipital"], keywords: ["craniectomy", "suboccipital", "section", "cranial nerves", "rhizotomy"], relatedCodes: ["61458", "61470"] },
  { code: "61470", shortDesc: "Suboccipital craniectomy for medullary tractotomy", fullDesc: "Craniectomy, suboccipital; for medullary tractotomy", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["medullary tractotomy", "suboccipital tractotomy", "brainstem tractotomy", "trigeminal tractotomy", "nucleus caudalis DREZ"], keywords: ["craniectomy", "suboccipital", "medullary", "tractotomy", "brainstem"], relatedCodes: ["61458", "61460", "61480"] },
  { code: "61480", shortDesc: "Suboccipital craniectomy for mesencephalic tractotomy/pedunculotomy", fullDesc: "Craniectomy, suboccipital; for mesencephalic tractotomy or pedunculotomy", category: "Neurosurgery", subcategory: "Craniotomy - Vascular", synonyms: ["mesencephalic tractotomy", "pedunculotomy", "midbrain tractotomy", "mesencephalotomy"], keywords: ["craniectomy", "suboccipital", "mesencephalic", "tractotomy", "pedunculotomy", "midbrain"], relatedCodes: ["61458", "61470"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // VP SHUNT / CSF PROCEDURES
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "62160", shortDesc: "Neuroendoscopy, catheter placement and biopsy", fullDesc: "Neuroendoscopy, intracranial; for placement or replacement of ventricular catheter and target biopsy", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["neuroendoscopy catheter placement", "endoscopic ventricular catheter", "endoscopic biopsy", "neuroendoscopic biopsy"], keywords: ["neuroendoscopy", "intracranial", "ventricular catheter", "biopsy", "endoscopic"], relatedCodes: ["62161", "62162", "62165"] },
  { code: "62161", shortDesc: "Neuroendoscopy with adhesion dissection/cyst fenestration/tumor", fullDesc: "Neuroendoscopy, intracranial; with dissection of adhesions, fenestration of septum pellucidum or intraventricular cyst, removal of foreign body, or excision of tumor", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["endoscopic septostomy", "endoscopic cyst fenestration", "endoscopic colloid cyst removal", "endoscopic intraventricular tumor", "septum pellucidum fenestration"], keywords: ["neuroendoscopy", "adhesions", "fenestration", "septum pellucidum", "cyst", "tumor"], relatedCodes: ["62160", "62162"] },
  { code: "62165", shortDesc: "Neuroendoscopy for pituitary tumor, transsphenoidal", fullDesc: "Neuroendoscopy, intracranial, with excision of pituitary tumor, transnasal or trans-sphenoidal approach", category: "Neurosurgery", subcategory: "Endoscopic Procedure", synonyms: ["endoscopic transsphenoidal pituitary", "endoscopic pituitary surgery", "endoscopic endonasal pituitary", "EEA pituitary", "endoscopic pituitary adenoma", "transsphenoidal pituitary surgery", "endoscopic sellar surgery"], keywords: ["neuroendoscopy", "pituitary tumor", "transnasal", "trans-sphenoidal", "endoscopic", "EEA"], relatedCodes: ["62160", "62161"] },
  { code: "62200", shortDesc: "Endoscopic third ventriculostomy (ETV)", fullDesc: "Ventriculocisternostomy, third ventricle; stereotactic, neuroendoscopic method", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["endoscopic third ventriculostomy", "ETV", "third ventriculostomy", "neuroendoscopic ETV", "ETV for hydrocephalus"], keywords: ["ventriculocisternostomy", "third ventricle", "stereotactic", "neuroendoscopic", "ETV", "hydrocephalus"], relatedCodes: ["62220", "62223"] },
  { code: "62220", shortDesc: "Shunt creation, ventriculo-atrial (VA shunt)", fullDesc: "Creation of shunt; ventriculo-atrial, -jugular, -auricular", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["VA shunt", "ventriculoatrial shunt", "ventriculojugular shunt", "VA shunt placement"], keywords: ["creation", "shunt", "ventriculo-atrial", "VA shunt", "hydrocephalus"], relatedCodes: ["62223", "62230"] },
  { code: "62223", shortDesc: "Shunt creation, ventriculoperitoneal (VP shunt)", fullDesc: "Creation of shunt; ventriculo-peritoneal, -pleural, other terminus", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["VP shunt", "ventriculoperitoneal shunt", "VP shunt placement", "VP shunt insertion", "VP shunt creation", "shunt for hydrocephalus", "hydrocephalus shunt", "VPS placement", "new VP shunt"], keywords: ["creation", "shunt", "ventriculo-peritoneal", "VP shunt", "hydrocephalus"], relatedCodes: ["62220", "62225", "62230", "62256", "62258"] },
  { code: "62225", shortDesc: "Replacement/irrigation of ventricular catheter", fullDesc: "Replacement or irrigation, ventricular catheter", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["proximal shunt revision", "ventricular catheter replacement", "shunt proximal revision", "VP shunt proximal revision", "shunt irrigation"], keywords: ["replacement", "irrigation", "ventricular catheter", "shunt revision", "proximal"], relatedCodes: ["62223", "62230"] },
  { code: "62230", shortDesc: "Replacement/revision of CSF shunt valve or distal catheter", fullDesc: "Replacement or revision of cerebrospinal fluid shunt, obstructed valve, or distal catheter in shunt system", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["distal shunt revision", "shunt valve replacement", "VP shunt distal revision", "peritoneal catheter revision", "shunt valve revision", "shunt obstruction revision"], keywords: ["replacement", "revision", "shunt", "obstructed valve", "distal catheter", "CSF"], relatedCodes: ["62223", "62225", "62256"] },
  { code: "62252", shortDesc: "Reprogramming of programmable CSF shunt", fullDesc: "Reprogramming of programmable cerebrospinal fluid shunt", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["shunt reprogramming", "VP shunt programming", "programmable valve adjustment", "shunt valve reprogramming", "Codman valve reprogramming", "Strata valve adjustment"], keywords: ["reprogramming", "programmable", "shunt", "valve", "adjustment"], relatedCodes: ["62223", "62230"] },
  { code: "62256", shortDesc: "Removal of complete CSF shunt system", fullDesc: "Removal of complete cerebrospinal fluid shunt system; without replacement", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["shunt removal", "VP shunt removal", "shunt explant", "CSF shunt removal", "shunt takedown", "VPS removal"], keywords: ["removal", "shunt system", "without replacement", "explant"], relatedCodes: ["62258", "62223"] },
  { code: "62258", shortDesc: "Removal and replacement of complete CSF shunt system", fullDesc: "Removal of complete cerebrospinal fluid shunt system; with replacement by similar or other shunt at same operation", category: "Neurosurgery", subcategory: "VP Shunt", synonyms: ["shunt replacement", "VP shunt replacement", "complete shunt revision", "VP shunt exchange", "infected shunt replacement", "VPS replacement"], keywords: ["removal", "replacement", "shunt system", "same operation"], relatedCodes: ["62256", "62223"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEREOTACTIC / FUNCTIONAL
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "61720", shortDesc: "Stereotactic lesion creation, globus pallidus", fullDesc: "Creation of lesion by stereotactic method, including burr hole(s) and localizing and recording techniques; globus pallidus", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["stereotactic pallidotomy", "pallidotomy", "GPi lesion", "GPi ablation"], keywords: ["stereotactic", "lesion creation", "globus pallidus", "pallidotomy"], relatedCodes: ["61735", "61863"] },
  { code: "61735", shortDesc: "Stereotactic lesion creation, subcortical (thalamus, STN)", fullDesc: "Creation of lesion by stereotactic method; subcortical structure(s) other than globus pallidus (eg, thalamus, subthalamic nucleus, caudate)", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["stereotactic thalamotomy", "thalamotomy", "VIM thalamotomy", "stereotactic cingulotomy", "stereotactic ablation thalamus"], keywords: ["stereotactic", "lesion creation", "subcortical", "thalamus", "subthalamic nucleus", "thalamotomy"], relatedCodes: ["61720", "61867"] },
  { code: "61751", shortDesc: "Stereotactic biopsy with CT/MRI guidance", fullDesc: "Stereotactic biopsy, aspiration, or excision of intracranial lesion; with computed tomography and/or magnetic resonance guidance", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["stereotactic brain biopsy", "CT guided brain biopsy", "MRI guided stereotactic biopsy", "frame-based biopsy", "image-guided stereotactic biopsy", "stereotactic needle biopsy brain", "brain biopsy stereotactic"], keywords: ["stereotactic", "biopsy", "aspiration", "excision", "intracranial lesion", "CT guided", "MRI guided"], relatedCodes: ["61750", "61720"] },
  { code: "61760", shortDesc: "Stereotactic depth electrode implant for seizure monitoring", fullDesc: "Stereotactic implantation of depth electrodes into cerebrum for long-term seizure monitoring", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["SEEG electrode implantation", "stereo EEG", "depth electrode placement", "sEEG", "stereoelectroencephalography", "epilepsy depth electrode", "invasive EEG monitoring"], keywords: ["stereotactic", "depth electrodes", "cerebrum", "seizure monitoring", "epilepsy", "SEEG"], relatedCodes: ["61863", "61886"] },
  { code: "61781", shortDesc: "Stereotactic navigation, cranial intradural (add-on)", fullDesc: "Stereotactic computer-assisted (navigational) procedure; cranial, intradural (add-on)", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["neuronavigation cranial", "stereotactic navigation", "image-guided surgery cranial", "StealthStation", "BrainLab navigation", "IGS cranial"], keywords: ["stereotactic", "computer-assisted", "navigational", "cranial", "intradural", "add-on", "neuronavigation"], relatedCodes: ["61782", "61783"] },
  { code: "61783", shortDesc: "Stereotactic navigation, spinal (add-on)", fullDesc: "Stereotactic computer-assisted (navigational) procedure; spinal (add-on)", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["neuronavigation spinal", "spinal navigation", "image-guided spine surgery", "O-arm navigation", "IGS spine"], keywords: ["stereotactic", "navigational", "spinal", "add-on", "spine navigation"], relatedCodes: ["61781", "61782"] },
  { code: "61790", shortDesc: "Stereotactic percutaneous lesion, gasserian ganglion", fullDesc: "Creation of lesion by stereotactic method, percutaneous, by neurolytic agent; gasserian ganglion of trigeminal nerve", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["stereotactic trigeminal rhizotomy", "radiofrequency trigeminal rhizotomy", "percutaneous trigeminal RF", "gasserian ganglion ablation", "trigeminal RF rhizotomy", "trigeminal neuralgia stereotactic"], keywords: ["stereotactic", "percutaneous", "gasserian ganglion", "trigeminal nerve", "radiofrequency", "rhizotomy"], relatedCodes: ["61791", "61458"] },
  { code: "61796", shortDesc: "Stereotactic radiosurgery, 1 simple cranial lesion", fullDesc: "Stereotactic radiosurgery (particle beam, gamma ray, or linear accelerator); 1 simple cranial lesion", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["Gamma Knife", "stereotactic radiosurgery", "SRS", "CyberKnife cranial", "LINAC radiosurgery", "Gamma Knife radiosurgery", "SRS brain lesion", "radiosurgery brain met", "GKS"], keywords: ["stereotactic radiosurgery", "gamma ray", "linear accelerator", "simple", "cranial lesion", "Gamma Knife", "SRS"], relatedCodes: ["61797", "61798"] },
  { code: "61798", shortDesc: "Stereotactic radiosurgery, 1 complex cranial lesion", fullDesc: "Stereotactic radiosurgery (particle beam, gamma ray, or linear accelerator); 1 complex cranial lesion", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["Gamma Knife complex", "SRS complex lesion", "SRS AVM", "SRS meningioma", "SRS acoustic neuroma", "Gamma Knife AVM", "CyberKnife complex"], keywords: ["stereotactic radiosurgery", "complex", "cranial lesion", "Gamma Knife", "SRS"], relatedCodes: ["61796", "61799"] },
  { code: "61863", shortDesc: "DBS electrode implant without MER, first array", fullDesc: "Stereotactic implantation of neurostimulator electrode array in subcortical site; without use of intraoperative microelectrode recording; first array", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["DBS electrode implant", "DBS lead placement", "deep brain stimulator electrode", "DBS implant single", "DBS without MER", "deep brain stimulation electrode"], keywords: ["stereotactic", "neurostimulator", "electrode array", "subcortical", "DBS", "first array"], relatedCodes: ["61864", "61867", "61885", "61886"] },
  { code: "61867", shortDesc: "DBS electrode implant with MER, first array", fullDesc: "Stereotactic implantation of neurostimulator electrode array in subcortical site; with use of intraoperative microelectrode recording; first array", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["DBS electrode with MER", "DBS with microelectrode recording", "awake DBS with recording", "DBS MER first side"], keywords: ["stereotactic", "neurostimulator", "electrode array", "subcortical", "DBS", "microelectrode recording", "MER"], relatedCodes: ["61868", "61863", "61885", "61886"] },
  { code: "61885", shortDesc: "Cranial neurostimulator pulse generator, single array", fullDesc: "Insertion or replacement of cranial neurostimulator pulse generator or receiver; with connection to a single electrode array", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["DBS generator implant single", "DBS IPG placement", "DBS battery implant", "neurostimulator generator single", "IPG implant single lead"], keywords: ["insertion", "replacement", "neurostimulator", "pulse generator", "single electrode array", "DBS", "IPG"], relatedCodes: ["61886", "61863", "61867"] },
  { code: "61886", shortDesc: "Cranial neurostimulator pulse generator, dual/multiple array", fullDesc: "Insertion or replacement of cranial neurostimulator pulse generator or receiver; with connection to 2 or more electrode arrays", category: "Neurosurgery", subcategory: "Stereotactic/Functional", synonyms: ["DBS generator implant dual", "DBS IPG bilateral", "bilateral DBS generator", "DBS battery implant dual", "neurostimulator generator dual"], keywords: ["insertion", "replacement", "neurostimulator", "pulse generator", "dual", "multiple", "DBS", "IPG", "bilateral"], relatedCodes: ["61885", "61863", "61867"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPINAL FUSION - CERVICAL
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "22551", shortDesc: "Arthrodesis anterior interbody cervical below C2", fullDesc: "Arthrodesis, anterior interbody, including disc space preparation, discectomy, osteophytectomy and decompression of spinal cord and/or nerve roots; cervical below C2", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["ACDF", "anterior cervical discectomy and fusion", "ACDF single level", "cervical fusion anterior", "anterior cervical fusion", "cervical discectomy fusion", "ACDF C5-C6", "ACDF C6-C7", "ACDF C4-C5", "anterior interbody fusion cervical"], keywords: ["arthrodesis", "anterior", "interbody", "cervical", "discectomy", "ACDF", "fusion", "decompression"], relatedCodes: ["22552", "22845", "22853"] },
  { code: "22552", shortDesc: "Arthrodesis anterior interbody cervical each additional (add-on)", fullDesc: "Arthrodesis, anterior interbody, including disc space preparation, discectomy, osteophytectomy and decompression; cervical below C2, each additional interspace (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["ACDF additional level", "multi-level ACDF", "two-level ACDF", "three-level ACDF", "additional cervical level fusion"], keywords: ["arthrodesis", "anterior", "interbody", "cervical", "additional interspace", "add-on", "ACDF"], relatedCodes: ["22551", "22845"] },
  { code: "22554", shortDesc: "Arthrodesis anterior interbody cervical", fullDesc: "Arthrodesis, anterior interbody technique, including minimal discectomy to prepare interspace (other than for decompression); cervical below C2", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["anterior cervical fusion minimal disc", "cervical corpectomy fusion", "anterior cervical arthrodesis", "ACF"], keywords: ["arthrodesis", "anterior", "interbody", "cervical", "minimal discectomy"], relatedCodes: ["22551", "22585"] },
  { code: "22600", shortDesc: "Arthrodesis posterior/posterolateral cervical", fullDesc: "Arthrodesis, posterior or posterolateral technique, single level; cervical below C2 segment", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["posterior cervical fusion", "posterolateral cervical fusion", "cervical posterior fusion", "posterior cervical arthrodesis", "C1-C2 fusion posterior"], keywords: ["arthrodesis", "posterior", "posterolateral", "cervical", "fusion"], relatedCodes: ["22614", "22590", "22842"] },
  { code: "22590", shortDesc: "Arthrodesis posterior atlantoaxial (C1-C2)", fullDesc: "Arthrodesis, posterior technique, craniocervical (occiput-C2)", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["occiput to C2 fusion", "occipitocervical fusion", "craniocervical fusion", "occiput-C2 arthrodesis", "posterior craniocervical fusion"], keywords: ["arthrodesis", "posterior", "craniocervical", "occiput", "C2", "occipitocervical"], relatedCodes: ["22595", "22600"] },
  { code: "22595", shortDesc: "Arthrodesis posterior atlantoaxial (C1-C2)", fullDesc: "Arthrodesis, posterior technique, atlas-axis (C1-C2)", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["C1-C2 fusion", "atlantoaxial fusion", "atlas-axis fusion", "posterior C1-C2 arthrodesis", "C1-C2 posterior fusion", "Harms fusion", "Goel-Harms technique"], keywords: ["arthrodesis", "posterior", "atlas-axis", "C1-C2", "atlantoaxial", "fusion"], relatedCodes: ["22590", "22600"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPINAL FUSION - THORACIC
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "22556", shortDesc: "Arthrodesis anterior interbody thoracic", fullDesc: "Arthrodesis, anterior interbody technique, including minimal discectomy; thoracic", category: "Neurosurgery", subcategory: "Spinal Fusion - Thoracic", synonyms: ["anterior thoracic fusion", "thoracic interbody fusion", "anterior thoracic arthrodesis", "thoracotomy fusion"], keywords: ["arthrodesis", "anterior", "interbody", "thoracic", "fusion"], relatedCodes: ["22610", "22585"] },
  { code: "22610", shortDesc: "Arthrodesis posterior/posterolateral thoracic", fullDesc: "Arthrodesis, posterior or posterolateral technique, single level; thoracic (with lateral transverse technique, when performed)", category: "Neurosurgery", subcategory: "Spinal Fusion - Thoracic", synonyms: ["posterior thoracic fusion", "posterolateral thoracic fusion", "thoracic posterior fusion"], keywords: ["arthrodesis", "posterior", "posterolateral", "thoracic", "fusion"], relatedCodes: ["22556", "22614"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPINAL FUSION - LUMBAR
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "22533", shortDesc: "Arthrodesis lateral extracavitary lumbar (LLIF/XLIF)", fullDesc: "Arthrodesis, lateral extracavitary technique, including minimal discectomy; lumbar", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["LLIF", "XLIF", "lateral lumbar interbody fusion", "lateral approach fusion", "direct lateral interbody fusion", "DLIF", "lateral fusion lumbar", "extreme lateral interbody fusion"], keywords: ["arthrodesis", "lateral", "extracavitary", "lumbar", "LLIF", "XLIF", "DLIF", "interbody fusion"], relatedCodes: ["22558", "22612", "22853"] },
  { code: "22558", shortDesc: "Arthrodesis anterior interbody lumbar (ALIF)", fullDesc: "Arthrodesis, anterior interbody technique, including minimal discectomy; lumbar", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["ALIF", "anterior lumbar interbody fusion", "anterior lumbar fusion", "anterior approach lumbar", "ALIF L5-S1", "ALIF L4-L5"], keywords: ["arthrodesis", "anterior", "interbody", "lumbar", "ALIF", "fusion"], relatedCodes: ["22533", "22612", "22853"] },
  { code: "22612", shortDesc: "Arthrodesis posterior/posterolateral lumbar", fullDesc: "Arthrodesis, posterior or posterolateral technique, single level; lumbar (with lateral transverse technique, when performed)", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["posterior lumbar fusion", "posterolateral lumbar fusion", "PLF", "lumbar posterior fusion", "lumbar posterolateral arthrodesis", "intertransverse fusion lumbar"], keywords: ["arthrodesis", "posterior", "posterolateral", "lumbar", "fusion", "PLF"], relatedCodes: ["22614", "22630", "22633"] },
  { code: "22614", shortDesc: "Arthrodesis posterior/posterolateral each additional level (add-on)", fullDesc: "Arthrodesis, posterior or posterolateral technique; each additional vertebral segment (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["additional fusion level", "multi-level posterior fusion", "additional vertebral segment fusion"], keywords: ["arthrodesis", "posterior", "posterolateral", "additional", "vertebral segment", "add-on"], relatedCodes: ["22612", "22600", "22610"] },
  { code: "22630", shortDesc: "Arthrodesis posterior interbody lumbar (PLIF)", fullDesc: "Arthrodesis, posterior interbody technique, including laminectomy and/or discectomy to prepare interspace; single interspace, lumbar", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["PLIF", "posterior lumbar interbody fusion", "posterior interbody fusion", "PLIF single level", "lumbar PLIF"], keywords: ["arthrodesis", "posterior", "interbody", "lumbar", "laminectomy", "discectomy", "PLIF"], relatedCodes: ["22632", "22633", "22612"] },
  { code: "22633", shortDesc: "Arthrodesis combined posterior interbody + posterolateral lumbar", fullDesc: "Arthrodesis, combined posterior or posterolateral technique with posterior interbody technique including laminectomy and/or discectomy; single interspace and segment, lumbar", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["TLIF", "transforaminal lumbar interbody fusion", "combined posterior fusion", "TLIF single level", "360 lumbar fusion", "circumferential fusion lumbar", "posterolateral with interbody"], keywords: ["arthrodesis", "combined", "posterior", "interbody", "posterolateral", "lumbar", "TLIF", "circumferential"], relatedCodes: ["22634", "22612", "22630"] },
  { code: "22634", shortDesc: "Combined posterior interbody + posterolateral each additional (add-on)", fullDesc: "Arthrodesis, combined posterior or posterolateral technique with posterior interbody; each additional interspace and segment, lumbar (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["additional TLIF level", "multi-level TLIF", "additional combined fusion level"], keywords: ["arthrodesis", "combined", "posterior", "interbody", "additional", "lumbar", "add-on", "TLIF"], relatedCodes: ["22633", "22614"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPINAL INSTRUMENTATION
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "22840", shortDesc: "Posterior non-segmental instrumentation (add-on)", fullDesc: "Posterior non-segmental instrumentation (eg, Harrington rod technique, pedicle fixation across 1 interspace, atlantoaxial transarticular screw fixation, sublaminar wiring at C1, facet screw fixation) (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["posterior instrumentation non-segmental", "Harrington rod", "C1-C2 screw fixation", "transarticular screw", "facet screw", "sublaminar wiring"], keywords: ["posterior", "non-segmental", "instrumentation", "Harrington", "transarticular", "facet screw", "add-on"], relatedCodes: ["22842", "22595"] },
  { code: "22842", shortDesc: "Posterior segmental instrumentation 3-6 levels (add-on)", fullDesc: "Posterior segmental instrumentation (eg, pedicle fixation, dual rods with multiple hooks and sublaminar wires); 3 to 6 vertebral segments (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["posterior segmental instrumentation", "pedicle screw fixation 3-6 levels", "posterior rods and screws", "pedicle screw construct", "posterior spinal instrumentation"], keywords: ["posterior", "segmental", "instrumentation", "pedicle fixation", "dual rods", "add-on"], relatedCodes: ["22840", "22843", "22844"] },
  { code: "22845", shortDesc: "Anterior instrumentation 2-3 levels (add-on)", fullDesc: "Anterior instrumentation; 2 to 3 vertebral segments (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Cervical", synonyms: ["anterior plate", "anterior cervical plate", "cervical plate and screws", "anterior instrumentation", "anterior plate 2-3 levels"], keywords: ["anterior", "instrumentation", "vertebral segments", "plate", "add-on"], relatedCodes: ["22846", "22551"] },
  { code: "22853", shortDesc: "Insertion of interbody biomechanical device, lateral approach (add-on)", fullDesc: "Insertion of interbody biomechanical device(s) to intervertebral disc space, lateral approach (add-on)", category: "Neurosurgery", subcategory: "Spinal Fusion - Lumbar", synonyms: ["lateral interbody cage", "LLIF cage", "XLIF cage", "lateral cage placement", "interbody device lateral"], keywords: ["insertion", "interbody", "biomechanical device", "lateral approach", "cage", "add-on"], relatedCodes: ["22533", "22857"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // SPINAL DECOMPRESSION
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "63001", shortDesc: "Laminectomy for exploration/decompression, cervical 1-2 segments", fullDesc: "Laminectomy with exploration and/or decompression of spinal cord and/or cauda equina, without facetectomy, foraminotomy or discectomy; 1 or 2 vertebral segments, cervical", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["cervical laminectomy", "cervical decompression laminectomy", "cervical lami 1-2 levels", "posterior cervical decompression"], keywords: ["laminectomy", "exploration", "decompression", "spinal cord", "cervical", "1-2 segments"], relatedCodes: ["63015", "63020", "63045"] },
  { code: "63003", shortDesc: "Laminectomy for exploration/decompression, thoracic 1-2 segments", fullDesc: "Laminectomy with exploration and/or decompression; 1 or 2 vertebral segments, thoracic", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["thoracic laminectomy", "thoracic decompression laminectomy", "thoracic lami"], keywords: ["laminectomy", "decompression", "thoracic", "1-2 segments"], relatedCodes: ["63016", "63001"] },
  { code: "63005", shortDesc: "Laminectomy for exploration/decompression, lumbar 1-2 segments", fullDesc: "Laminectomy with exploration and/or decompression; 1 or 2 vertebral segments, lumbar, except for spondylolisthesis", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["lumbar laminectomy", "lumbar decompression", "lumbar lami", "lumbar stenosis decompression", "lumbar laminectomy decompression", "laminectomy L4-L5", "laminectomy L3-L4"], keywords: ["laminectomy", "decompression", "lumbar", "1-2 segments", "stenosis"], relatedCodes: ["63017", "63012", "63047"] },
  { code: "63012", shortDesc: "Laminectomy for decompression, lumbar with spondylolisthesis", fullDesc: "Laminectomy with removal of abnormal facets and/or pars inter-articularis with decompression of cauda equina and nerve roots for spondylolisthesis, lumbar", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["Gill procedure", "laminectomy spondylolisthesis", "spondylolisthesis decompression", "pars decompression lumbar"], keywords: ["laminectomy", "facets", "pars inter-articularis", "decompression", "spondylolisthesis", "lumbar"], relatedCodes: ["63005", "22633"] },
  { code: "63015", shortDesc: "Laminectomy for decompression, cervical more than 2 segments", fullDesc: "Laminectomy with exploration and/or decompression; more than 2 vertebral segments, cervical", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["cervical laminectomy multi-level", "multilevel cervical decompression", "3+ level cervical lami", "cervical laminectomy stenosis"], keywords: ["laminectomy", "decompression", "cervical", "more than 2 segments", "multilevel"], relatedCodes: ["63001", "63045"] },
  { code: "63017", shortDesc: "Laminectomy for decompression, lumbar more than 2 segments", fullDesc: "Laminectomy with exploration and/or decompression; more than 2 vertebral segments, lumbar", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["lumbar laminectomy multi-level", "multilevel lumbar decompression", "3+ level lumbar lami", "multilevel lumbar stenosis decompression"], keywords: ["laminectomy", "decompression", "lumbar", "more than 2 segments", "multilevel"], relatedCodes: ["63005", "63047"] },
  { code: "63020", shortDesc: "Laminotomy/hemilaminectomy with discectomy, cervical", fullDesc: "Laminotomy (hemilaminectomy), with decompression of nerve root(s), including partial facetectomy, foraminotomy and/or excision of herniated intervertebral disc; 1 interspace, cervical", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["cervical foraminotomy", "cervical discectomy posterior", "posterior cervical discectomy", "cervical hemilaminectomy", "cervical laminoforaminotomy", "keyhole foraminotomy cervical"], keywords: ["laminotomy", "hemilaminectomy", "decompression", "nerve root", "foraminotomy", "discectomy", "cervical"], relatedCodes: ["63035", "63001"] },
  { code: "63030", shortDesc: "Laminotomy/hemilaminectomy with discectomy, lumbar", fullDesc: "Laminotomy (hemilaminectomy), with decompression of nerve root(s), including partial facetectomy, foraminotomy and/or excision of herniated intervertebral disc; 1 interspace, lumbar", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["lumbar microdiscectomy", "lumbar discectomy", "lumbar hemilaminectomy", "microdiscectomy", "micro decompression", "lumbar laminotomy", "disc herniation surgery lumbar", "lumbar disc surgery", "microlumbar discectomy", "MLD"], keywords: ["laminotomy", "hemilaminectomy", "decompression", "nerve root", "foraminotomy", "discectomy", "lumbar", "microdiscectomy"], relatedCodes: ["63035", "63005", "63047"] },
  { code: "63035", shortDesc: "Laminotomy each additional interspace (add-on)", fullDesc: "Laminotomy (hemilaminectomy); each additional interspace, cervical or lumbar (add-on)", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["additional level microdiscectomy", "additional interspace laminotomy", "additional level decompression"], keywords: ["laminotomy", "additional interspace", "cervical", "lumbar", "add-on"], relatedCodes: ["63020", "63030"] },
  { code: "63045", shortDesc: "Laminectomy with facetectomy/foraminotomy, cervical", fullDesc: "Laminectomy, facetectomy and foraminotomy (unilateral or bilateral with decompression of spinal cord, cauda equina and/or nerve root(s)); single vertebral segment, cervical", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["cervical laminectomy with foraminotomy", "cervical facetectomy foraminotomy", "unilateral cervical foraminotomy", "bilateral cervical foraminotomy"], keywords: ["laminectomy", "facetectomy", "foraminotomy", "decompression", "cervical", "single segment"], relatedCodes: ["63048", "63001", "63020"] },
  { code: "63047", shortDesc: "Laminectomy with facetectomy/foraminotomy, lumbar", fullDesc: "Laminectomy, facetectomy and foraminotomy; single vertebral segment, lumbar", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["lumbar laminectomy with foraminotomy", "lumbar facetectomy foraminotomy", "lumbar foraminotomy", "lumbar stenosis surgery laminectomy foraminotomy"], keywords: ["laminectomy", "facetectomy", "foraminotomy", "lumbar", "single segment", "stenosis"], relatedCodes: ["63048", "63005", "63030"] },
  { code: "63048", shortDesc: "Laminectomy with facetectomy each additional segment (add-on)", fullDesc: "Laminectomy, facetectomy and foraminotomy; each additional segment, cervical, thoracic, or lumbar (add-on)", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["additional level laminectomy foraminotomy", "additional segment decompression"], keywords: ["laminectomy", "facetectomy", "foraminotomy", "additional segment", "add-on"], relatedCodes: ["63045", "63047"] },
  { code: "63050", shortDesc: "Cervical laminoplasty, 2 or more segments", fullDesc: "Laminoplasty, cervical, with decompression of the spinal cord, 2 or more vertebral segments", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["cervical laminoplasty", "open-door laminoplasty", "expansile laminoplasty", "cervical laminoplasty multilevel", "expansive laminoplasty cervical"], keywords: ["laminoplasty", "cervical", "decompression", "spinal cord", "2 or more segments", "open-door"], relatedCodes: ["63051", "63001", "63015"] },
  { code: "63051", shortDesc: "Cervical laminoplasty with reconstruction of posterior elements", fullDesc: "Laminoplasty, cervical, with decompression of the spinal cord; with reconstruction of the posterior elements, including 2 or more vertebral segments", category: "Neurosurgery", subcategory: "Spinal Decompression", synonyms: ["cervical laminoplasty with reconstruction", "laminoplasty with plating", "cervical laminoplasty mini-plate"], keywords: ["laminoplasty", "cervical", "decompression", "reconstruction", "posterior elements"], relatedCodes: ["63050"] },
  { code: "22856", shortDesc: "Total disc arthroplasty cervical", fullDesc: "Total disc arthroplasty (artificial disc), anterior approach, including discectomy; single interspace, cervical", category: "Neurosurgery", subcategory: "Spine - Minimally Invasive", synonyms: ["cervical disc replacement", "cervical ADR", "artificial disc cervical", "cervical total disc arthroplasty", "cervical disc arthroplasty", "Mobi-C", "Prestige disc", "ProDisc-C"], keywords: ["total disc arthroplasty", "artificial disc", "anterior approach", "discectomy", "cervical", "disc replacement"], relatedCodes: ["22858", "22551"] },
  { code: "22857", shortDesc: "Total disc arthroplasty lumbar", fullDesc: "Total disc arthroplasty (artificial disc), anterior approach, including discectomy; single interspace, lumbar", category: "Neurosurgery", subcategory: "Spine - Minimally Invasive", synonyms: ["lumbar disc replacement", "lumbar ADR", "artificial disc lumbar", "lumbar total disc arthroplasty", "lumbar disc arthroplasty", "ProDisc-L", "Charité disc"], keywords: ["total disc arthroplasty", "artificial disc", "anterior approach", "discectomy", "lumbar", "disc replacement"], relatedCodes: ["22558"] },

  // ═══════════════════════════════════════════════════════════════════════════
  // PERIPHERAL NERVE
  // ═══════════════════════════════════════════════════════════════════════════

  { code: "64400", shortDesc: "Nerve block, trigeminal nerve", fullDesc: "Injection, anesthetic agent; trigeminal nerve, any division or branch", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["trigeminal nerve block", "trigeminal injection", "V1 nerve block", "V2 nerve block", "V3 nerve block", "supraorbital nerve block", "infraorbital nerve block"], keywords: ["injection", "anesthetic", "trigeminal nerve", "nerve block"], relatedCodes: ["64402", "64405"] },
  { code: "64405", shortDesc: "Nerve block, greater occipital nerve", fullDesc: "Injection, anesthetic agent; greater occipital nerve", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["occipital nerve block", "GON block", "greater occipital nerve injection", "occipital injection"], keywords: ["injection", "anesthetic", "greater occipital nerve", "nerve block", "GON"], relatedCodes: ["64400"] },
  { code: "64415", shortDesc: "Nerve block, brachial plexus", fullDesc: "Injection, anesthetic agent; brachial plexus, single", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["brachial plexus block", "brachial plexus injection", "interscalene block", "supraclavicular block", "axillary block"], keywords: ["injection", "anesthetic", "brachial plexus", "nerve block", "interscalene"], relatedCodes: ["64416", "64450"] },
  { code: "64447", shortDesc: "Nerve block, femoral nerve", fullDesc: "Injection, anesthetic agent; femoral nerve, single", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["femoral nerve block", "femoral injection", "femoral block"], keywords: ["injection", "anesthetic", "femoral nerve", "nerve block"], relatedCodes: ["64450"] },
  { code: "64450", shortDesc: "Nerve block, other peripheral nerve", fullDesc: "Injection, anesthetic agent; other peripheral nerve or branch", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["peripheral nerve block", "nerve block other", "field block", "nerve injection"], keywords: ["injection", "anesthetic", "peripheral nerve", "nerve block"], relatedCodes: ["64400", "64415"] },
  { code: "64555", shortDesc: "Percutaneous neurostimulator electrode implant, peripheral nerve", fullDesc: "Percutaneous implantation of neurostimulator electrode array; peripheral nerve (excludes sacral nerve)", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["peripheral nerve stimulator electrode", "PNS electrode implant", "percutaneous nerve stimulator", "peripheral neurostimulation lead"], keywords: ["percutaneous", "neurostimulator", "electrode", "peripheral nerve", "PNS"], relatedCodes: ["64590", "64585"] },
  { code: "64568", shortDesc: "Vagus nerve stimulator electrode implant", fullDesc: "Implantation of cranial nerve (eg, vagus nerve) neurostimulator electrode array and pulse generator", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["VNS implant", "vagus nerve stimulator", "vagal nerve stimulator", "VNS electrode placement", "VNS generator implant", "vagus nerve stimulation"], keywords: ["implantation", "cranial nerve", "vagus nerve", "neurostimulator", "electrode", "pulse generator", "VNS"], relatedCodes: ["64569", "64570"] },
  { code: "64569", shortDesc: "Revision/replacement of vagus nerve stimulator electrode", fullDesc: "Revision or replacement of cranial nerve (eg, vagus nerve) neurostimulator electrode array", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["VNS electrode revision", "VNS lead replacement", "vagus nerve stimulator revision"], keywords: ["revision", "replacement", "cranial nerve", "vagus nerve", "neurostimulator", "electrode", "VNS"], relatedCodes: ["64568", "64570"] },
  { code: "64570", shortDesc: "Removal of vagus nerve stimulator electrode/generator", fullDesc: "Removal of cranial nerve (eg, vagus nerve) neurostimulator electrode array and pulse generator", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["VNS removal", "vagus nerve stimulator removal", "VNS explant"], keywords: ["removal", "cranial nerve", "vagus nerve", "neurostimulator", "electrode", "pulse generator", "VNS"], relatedCodes: ["64568", "64569"] },
  { code: "64702", shortDesc: "Neuroplasty, digital nerve", fullDesc: "Neuroplasty; digital, 1 or both, same digit", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["digital nerve repair", "digital neuroplasty", "digital nerve release"], keywords: ["neuroplasty", "digital", "nerve repair"], relatedCodes: ["64704", "64708"] },
  { code: "64713", shortDesc: "Neuroplasty, brachial plexus", fullDesc: "Neuroplasty, major peripheral nerve, arm or leg, open; brachial plexus", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["brachial plexus neuroplasty", "brachial plexus exploration", "brachial plexus neurolysis", "brachial plexus repair"], keywords: ["neuroplasty", "major peripheral nerve", "brachial plexus", "neurolysis"], relatedCodes: ["64714", "64718"] },
  { code: "64718", shortDesc: "Neuroplasty/transposition, ulnar nerve at elbow", fullDesc: "Neuroplasty and/or transposition; ulnar nerve at elbow", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["ulnar nerve transposition", "cubital tunnel release", "ulnar nerve decompression elbow", "ulnar nerve release", "ulnar nerve transposition elbow", "submuscular transposition"], keywords: ["neuroplasty", "transposition", "ulnar nerve", "elbow", "cubital tunnel"], relatedCodes: ["64719", "64721"] },
  { code: "64721", shortDesc: "Neuroplasty/transposition, median nerve at carpal tunnel", fullDesc: "Neuroplasty and/or transposition; median nerve at carpal tunnel", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["carpal tunnel release", "CTR", "carpal tunnel surgery", "median nerve decompression", "carpal tunnel decompression", "open carpal tunnel release"], keywords: ["neuroplasty", "transposition", "median nerve", "carpal tunnel", "CTR", "decompression"], relatedCodes: ["64718", "64719"] },
  { code: "64831", shortDesc: "Suture of digital nerve", fullDesc: "Suture of digital nerve, hand or foot; 1 nerve", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["digital nerve repair suture", "digital nerve suture", "nerve repair hand"], keywords: ["suture", "digital nerve", "hand", "foot", "nerve repair"], relatedCodes: ["64832", "64834"] },
  { code: "64856", shortDesc: "Suture of major peripheral nerve, arm or leg", fullDesc: "Suture of major peripheral nerve, arm or leg, except sciatic; including transposition", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["major nerve repair", "peripheral nerve repair", "nerve suture arm", "nerve suture leg", "nerve repair extremity"], keywords: ["suture", "major peripheral nerve", "arm", "leg", "transposition", "nerve repair"], relatedCodes: ["64857", "64859"] },
  { code: "64885", shortDesc: "Nerve graft, head or neck, up to 4 cm", fullDesc: "Nerve graft (includes obtaining graft), head or neck; up to 4 cm in length", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["nerve graft head", "nerve graft neck", "sural nerve graft head", "nerve interposition graft", "cranial nerve graft"], keywords: ["nerve graft", "head", "neck", "graft"], relatedCodes: ["64886", "64891"] },
  { code: "64891", shortDesc: "Nerve graft, single strand, arm or leg, up to 4 cm", fullDesc: "Nerve graft (includes obtaining graft), single strand, hand or foot; up to 4 cm length", category: "Neurosurgery", subcategory: "Peripheral Nerve", synonyms: ["nerve graft extremity", "sural nerve graft", "nerve interposition graft extremity", "nerve graft hand", "nerve graft foot"], keywords: ["nerve graft", "single strand", "hand", "foot", "graft"], relatedCodes: ["64885", "64892"] },
];
