// Skull base, head and neck, and peripheral nerve tumor CPT codes.
//
// Why this file exists: a physician dictated "resected a paraganglioma of the
// vagus nerve in the neck" and the coder had nothing to offer. Not one code
// for a nerve sheath tumor, not one for a soft tissue neck tumor, not one of
// the skull base family, which is core neurosurgery. The catalogue had been
// built from one surgeon's own case log, so anything he had not already billed
// did not exist as far as the coder was concerned.
//
// CMS ships a short descriptor for every code, and for most of the fee
// schedule that is enough. It is not enough here: 61605 and 61606 are both
// "Resect/excise cranial lesion", and 64790 and 64792 are both "Removal of
// nerve lesion". Those pairs differ by extradural versus intradural and by
// extent, which is 9 to 10 work RVU and the difference between a defensible
// claim and a wrong one. So these carry the real descriptors.
//
// Work RVUs are CMS CY2026 PFS, July release, from
// scripts/data/PPRRVU2026_Jul_nonQPP.csv. They are re-attached at merge time
// in index.js, so the numbers here are documentation, not the source.

export const SKULL_BASE_HEAD_NECK_CODES = [

  // ═══════════════════════════════════════════════════════════════════════
  // PERIPHERAL AND CRANIAL NERVE TUMORS
  // The family that was missing entirely. A vagal, brachial plexus or
  // sciatic nerve sheath tumor lives here.
  // ═══════════════════════════════════════════════════════════════════════
  { code: "64774", shortDesc: "Excision of neuroma, cutaneous nerve", fullDesc: "Excision of neuroma; cutaneous nerve, surgically identifiable", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["cutaneous neuroma excision", "skin nerve neuroma"], keywords: ["neuroma", "cutaneous", "excision", "nerve", "tumor"], relatedCodes: ["64776", "64782", "64784"] },
  { code: "64776", shortDesc: "Excision of neuroma, digital nerve", fullDesc: "Excision of neuroma; digital nerve, 1 or both, same digit", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["digital neuroma excision", "Morton neuroma digit"], keywords: ["neuroma", "digital", "finger", "toe", "excision"], relatedCodes: ["64778", "64774"] },
  { code: "64778", shortDesc: "Excision of neuroma, each additional digital nerve (add-on)", fullDesc: "Excision of neuroma; digital nerve, each additional digit (List separately in addition to code for primary procedure)", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["additional digital neuroma"], keywords: ["neuroma", "digital", "additional", "add-on"], relatedCodes: ["64776"] },
  { code: "64782", shortDesc: "Excision of neuroma, hand or foot, except digital", fullDesc: "Excision of neuroma; hand or foot, except digital nerve", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["neuroma hand", "neuroma foot"], keywords: ["neuroma", "hand", "foot", "excision"], relatedCodes: ["64783", "64784"] },
  { code: "64783", shortDesc: "Excision of neuroma, hand or foot, each additional nerve (add-on)", fullDesc: "Excision of neuroma; hand or foot, each additional nerve, except same digit (List separately in addition to code for primary procedure)", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["additional neuroma hand foot"], keywords: ["neuroma", "additional", "add-on"], relatedCodes: ["64782"] },
  { code: "64784", shortDesc: "Excision of neuroma, MAJOR peripheral nerve (except sciatic)", fullDesc: "Excision of neuroma; major peripheral nerve, except sciatic", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["major peripheral nerve neuroma", "brachial plexus neuroma", "vagus nerve neuroma"], keywords: ["neuroma", "major", "peripheral", "nerve", "excision", "plexus"], relatedCodes: ["64786", "64790"] },
  { code: "64786", shortDesc: "Excision of neuroma, sciatic nerve", fullDesc: "Excision of neuroma; sciatic nerve", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["sciatic neuroma excision"], keywords: ["neuroma", "sciatic", "excision"], relatedCodes: ["64784"] },
  { code: "64787", shortDesc: "Implantation of nerve end into bone or muscle (add-on)", fullDesc: "Implantation of nerve end into bone or muscle (List separately in addition to neuroma excision code)", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["targeted muscle reinnervation implant", "nerve end implantation"], keywords: ["implant", "nerve end", "bone", "muscle", "add-on"], relatedCodes: ["64784", "64786"] },
  { code: "64788", shortDesc: "Excision of neurofibroma or schwannoma, cutaneous nerve", fullDesc: "Excision of neurofibroma or neurilemmoma; cutaneous nerve", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["cutaneous schwannoma", "cutaneous neurofibroma", "neurilemmoma skin"], keywords: ["neurofibroma", "neurilemmoma", "neurolemmoma", "schwannoma", "cutaneous", "excision", "tumor"], relatedCodes: ["64790", "64792"] },
  { code: "64790", shortDesc: "Excision of neurofibroma or schwannoma, MAJOR peripheral nerve", fullDesc: "Excision of neurofibroma or neurilemmoma; major peripheral nerve", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["schwannoma major peripheral nerve", "brachial plexus schwannoma", "vagus nerve schwannoma", "peripheral nerve sheath tumor excision", "neurilemmoma major nerve"], keywords: ["neurofibroma", "neurilemmoma", "neurolemmoma", "schwannoma", "major", "peripheral", "nerve", "sheath", "tumor", "excision", "plexus", "vagus"], relatedCodes: ["64788", "64792", "64784"] },
  { code: "64792", shortDesc: "Excision of EXTENSIVE nerve sheath tumor (including malignant)", fullDesc: "Excision of neurofibroma or neurilemmoma; extensive (including malignant type)", category: "Neurosurgery", subcategory: "Nerve Tumor", synonyms: ["malignant peripheral nerve sheath tumor", "MPNST resection", "extensive neurofibroma", "plexiform neurofibroma resection"], keywords: ["neurofibroma", "neurilemmoma", "schwannoma", "extensive", "malignant", "MPNST", "excision", "tumor"], relatedCodes: ["64790"] },

  // ═══════════════════════════════════════════════════════════════════════
  // NECK SOFT TISSUE TUMORS
  // Size-gated on the TUMOR, not the incision. A parapharyngeal
  // paraganglioma taken through the neck lands here when it does not reach
  // the skull base.
  // ═══════════════════════════════════════════════════════════════════════
  { code: "21550", shortDesc: "Biopsy, soft tissue of neck or thorax", fullDesc: "Biopsy, soft tissue of neck or thorax", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["neck mass biopsy", "open neck biopsy"], keywords: ["biopsy", "neck", "thorax", "soft tissue"], relatedCodes: ["21552", "21555"] },
  { code: "21552", shortDesc: "Excision, neck tumor, SUBCUTANEOUS, 3 cm or greater", fullDesc: "Excision, tumor, soft tissue of neck or anterior thorax, subcutaneous; 3 cm or greater", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["subcutaneous neck mass excision large"], keywords: ["excision", "neck", "tumor", "subcutaneous", "soft tissue"], relatedCodes: ["21555", "21554"] },
  { code: "21554", shortDesc: "Excision, neck tumor, SUBFASCIAL (deep), 5 cm or greater", fullDesc: "Excision, tumor, soft tissue of neck or anterior thorax, subfascial (eg, intramuscular); 5 cm or greater", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["deep neck tumor excision large", "parapharyngeal tumor excision large", "glomus vagale neck excision", "vagal paraganglioma neck excision"], keywords: ["excision", "neck", "tumor", "subfascial", "deep", "parapharyngeal", "paraganglioma", "glomus"], relatedCodes: ["21556", "21558", "60600"] },
  { code: "21555", shortDesc: "Excision, neck tumor, SUBCUTANEOUS, less than 3 cm", fullDesc: "Excision, tumor, soft tissue of neck or anterior thorax, subcutaneous; less than 3 cm", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["subcutaneous neck mass excision small"], keywords: ["excision", "neck", "tumor", "subcutaneous"], relatedCodes: ["21552"] },
  { code: "21556", shortDesc: "Excision, neck tumor, SUBFASCIAL (deep), less than 5 cm", fullDesc: "Excision, tumor, soft tissue of neck or anterior thorax, subfascial (eg, intramuscular); less than 5 cm", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["deep neck tumor excision small", "parapharyngeal tumor excision small", "glomus vagale neck excision small"], keywords: ["excision", "neck", "tumor", "subfascial", "deep", "parapharyngeal", "paraganglioma", "glomus"], relatedCodes: ["21554", "60600"] },
  { code: "21557", shortDesc: "RADICAL resection, neck soft tissue tumor, less than 5 cm", fullDesc: "Radical resection of tumor (eg, sarcoma), soft tissue of neck or anterior thorax; less than 5 cm", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["radical neck soft tissue resection small", "neck sarcoma resection"], keywords: ["radical", "resection", "neck", "sarcoma", "malignant", "tumor"], relatedCodes: ["21558"] },
  { code: "21558", shortDesc: "RADICAL resection, neck soft tissue tumor, 5 cm or greater", fullDesc: "Radical resection of tumor (eg, sarcoma), soft tissue of neck or anterior thorax; 5 cm or greater", category: "Head and Neck", subcategory: "Neck Soft Tissue", synonyms: ["radical neck soft tissue resection large", "neck sarcoma resection large"], keywords: ["radical", "resection", "neck", "sarcoma", "malignant", "tumor"], relatedCodes: ["21557"] },
  { code: "21899", shortDesc: "Unlisted procedure, neck or thorax (carrier priced)", fullDesc: "Unlisted procedure, neck or thorax. Carrier priced: submit the operative note and name a comparison code.", category: "Head and Neck", subcategory: "Neck Soft Tissue", status: "C", synonyms: ["unlisted neck procedure"], keywords: ["unlisted", "neck", "thorax", "carrier priced"], relatedCodes: ["21554", "60600"] },

  // ═══════════════════════════════════════════════════════════════════════
  // CAROTID BODY AND NECK NODES
  // 60600 says CAROTID BODY. A glomus vagale is not one. It is here so the
  // coder can name it and say why it does or does not apply.
  // ═══════════════════════════════════════════════════════════════════════
  { code: "60600", shortDesc: "Excision carotid body tumor, WITHOUT carotid artery excision", fullDesc: "Excision of carotid body tumor; without excision of carotid artery. Descriptor is specific to the CAROTID BODY: a vagal paraganglioma (glomus vagale) is a different structure and is not this code.", category: "Head and Neck", subcategory: "Paraganglioma", synonyms: ["carotid body tumor excision", "chemodectoma carotid", "carotid paraganglioma resection"], keywords: ["carotid", "body", "tumor", "paraganglioma", "chemodectoma", "glomus", "excision", "neck"], relatedCodes: ["60605", "21554"] },
  { code: "60605", shortDesc: "Excision carotid body tumor, WITH carotid artery excision", fullDesc: "Excision of carotid body tumor; with excision of carotid artery", category: "Head and Neck", subcategory: "Paraganglioma", synonyms: ["carotid body tumor with carotid resection"], keywords: ["carotid", "body", "tumor", "artery", "excision", "resection"], relatedCodes: ["60600", "35509", "35601"] },
  { code: "38720", shortDesc: "Cervical lymphadenectomy, complete (radical neck dissection)", fullDesc: "Cervical lymphadenectomy (complete)", category: "Head and Neck", subcategory: "Neck Dissection", synonyms: ["radical neck dissection", "complete cervical lymphadenectomy"], keywords: ["neck", "dissection", "lymphadenectomy", "cervical", "nodes"], relatedCodes: ["38724"] },
  { code: "38724", shortDesc: "Cervical lymphadenectomy, MODIFIED radical neck dissection", fullDesc: "Cervical lymphadenectomy (modified radical neck dissection)", category: "Head and Neck", subcategory: "Neck Dissection", synonyms: ["modified radical neck dissection", "MRND"], keywords: ["neck", "dissection", "modified", "radical", "lymphadenectomy", "nodes"], relatedCodes: ["38720"] },

  // ═══════════════════════════════════════════════════════════════════════
  // GLOMUS TUMOR, AURAL
  // ═══════════════════════════════════════════════════════════════════════
  { code: "69550", shortDesc: "Excision aural glomus tumor, transcanal", fullDesc: "Excision aural glomus tumor; transcanal", category: "Head and Neck", subcategory: "Paraganglioma", synonyms: ["glomus tympanicum transcanal"], keywords: ["glomus", "aural", "tympanicum", "transcanal", "excision"], relatedCodes: ["69552", "69554"] },
  { code: "69552", shortDesc: "Excision aural glomus tumor, transmastoid", fullDesc: "Excision aural glomus tumor; transmastoid", category: "Head and Neck", subcategory: "Paraganglioma", synonyms: ["glomus jugulare transmastoid", "glomus tympanicum transmastoid"], keywords: ["glomus", "aural", "jugulare", "transmastoid", "excision"], relatedCodes: ["69550", "69554"] },
  { code: "69554", shortDesc: "Excision aural glomus tumor, EXTENDED (extratemporal)", fullDesc: "Excision aural glomus tumor; extended (extratemporal)", category: "Head and Neck", subcategory: "Paraganglioma", synonyms: ["glomus jugulare extended resection", "extratemporal glomus resection"], keywords: ["glomus", "jugulare", "extended", "extratemporal", "excision", "paraganglioma"], relatedCodes: ["69552", "61615", "61616"] },

  // ═══════════════════════════════════════════════════════════════════════
  // SKULL BASE: APPROACH
  // Skull base coding is three separately reportable parts: approach,
  // definitive procedure, and repair or reconstruction. Two surgeons
  // splitting them report modifier 62 on each.
  // ═══════════════════════════════════════════════════════════════════════
  { code: "61580", shortDesc: "Craniofacial approach, anterior fossa, extradural, no maxillectomy", fullDesc: "Craniofacial approach to anterior cranial fossa; extradural, including lateral rhinotomy, ethmoidectomy, sphenoidectomy, without maxillectomy or orbital exenteration", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["craniofacial approach anterior fossa"], keywords: ["craniofacial", "approach", "anterior", "fossa", "extradural", "skull base"], relatedCodes: ["61581", "61600"] },
  { code: "61581", shortDesc: "Craniofacial approach, anterior fossa, extradural, with maxillectomy", fullDesc: "Craniofacial approach to anterior cranial fossa; extradural, including lateral rhinotomy, orbital exenteration, ethmoidectomy, sphenoidectomy and/or maxillectomy", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["craniofacial approach with maxillectomy"], keywords: ["craniofacial", "approach", "maxillectomy", "orbital", "exenteration", "skull base"], relatedCodes: ["61580"] },
  { code: "61582", shortDesc: "Craniofacial approach, anterior fossa, extradural, with craniotomy", fullDesc: "Craniofacial approach to anterior cranial fossa; extradural, including unilateral or bifrontal craniotomy, elevation of frontal lobe(s), osteotomy of base of anterior cranial fossa", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["bifrontal craniofacial approach extradural"], keywords: ["craniofacial", "bifrontal", "craniotomy", "extradural", "anterior fossa"], relatedCodes: ["61583", "61600"] },
  { code: "61583", shortDesc: "Craniofacial approach, anterior fossa, INTRADURAL", fullDesc: "Craniofacial approach to anterior cranial fossa; intradural, including unilateral or bifrontal craniotomy, elevation or resection of frontal lobe, osteotomy of base of anterior cranial fossa", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["bifrontal craniofacial approach intradural"], keywords: ["craniofacial", "intradural", "bifrontal", "anterior fossa", "skull base"], relatedCodes: ["61582", "61601"] },
  { code: "61584", shortDesc: "Orbitocranial approach, anterior fossa, without orbital exenteration", fullDesc: "Orbitocranial approach to anterior cranial fossa, extradural, including supraorbital ridge osteotomy and elevation of frontal and/or temporal lobe(s); without orbital exenteration", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["orbitocranial approach", "supraorbital osteotomy approach"], keywords: ["orbitocranial", "supraorbital", "osteotomy", "approach", "anterior fossa"], relatedCodes: ["61585"] },
  { code: "61585", shortDesc: "Orbitocranial approach, anterior fossa, WITH orbital exenteration", fullDesc: "Orbitocranial approach to anterior cranial fossa, extradural, including supraorbital ridge osteotomy and elevation of frontal and/or temporal lobe(s); with orbital exenteration", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["orbitocranial with exenteration"], keywords: ["orbitocranial", "exenteration", "orbit", "approach"], relatedCodes: ["61584"] },
  { code: "61586", shortDesc: "Bicoronal transzygomatic/LeFort I approach, anterior fossa", fullDesc: "Bicoronal, transzygomatic and/or LeFort I osteotomy approach to anterior cranial fossa with or without internal fixation, without bone graft", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["transzygomatic approach", "LeFort I approach skull base"], keywords: ["bicoronal", "transzygomatic", "LeFort", "osteotomy", "approach"], relatedCodes: ["61580"] },
  { code: "61590", shortDesc: "Infratemporal PRE-auricular approach, middle fossa/parapharyngeal", fullDesc: "Infratemporal pre-auricular approach to middle cranial fossa (parapharyngeal space, infratemporal and midline skull base, nasopharynx), with or without disarticulation of the mandible, including parotidectomy, craniotomy, decompression and/or mobilization of the facial nerve and/or petrous carotid artery", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["infratemporal preauricular approach", "parapharyngeal skull base approach"], keywords: ["infratemporal", "preauricular", "parapharyngeal", "middle fossa", "approach", "petrous carotid"], relatedCodes: ["61591", "61605", "61606"] },
  { code: "61591", shortDesc: "Infratemporal POST-auricular approach, middle fossa/petrous apex", fullDesc: "Infratemporal post-auricular approach to middle cranial fossa (internal auditory meatus, petrous apex, tentorium, cavernous sinus, parasellar area, infratemporal fossa) including mastoidectomy, resection of sigmoid sinus, with or without decompression and/or mobilization of contents of auditory canal or facial nerve", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["infratemporal postauricular approach", "petrous apex approach"], keywords: ["infratemporal", "postauricular", "petrous apex", "mastoidectomy", "sigmoid sinus", "approach"], relatedCodes: ["61590", "61605"] },
  { code: "61592", shortDesc: "Orbitocranial zygomatic approach, middle fossa/cavernous sinus", fullDesc: "Orbitocranial zygomatic approach to middle cranial fossa (cavernous sinus and carotid artery, clivus, basilar artery or petrous apex), including osteotomy of zygoma, craniotomy, extra- or intradural elevation of temporal lobe", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["orbitozygomatic approach", "OZ craniotomy skull base"], keywords: ["orbitozygomatic", "zygomatic", "cavernous sinus", "clivus", "approach"], relatedCodes: ["61607", "61608"] },
  { code: "61595", shortDesc: "Transtemporal approach, posterior fossa/jugular foramen", fullDesc: "Transtemporal approach to posterior cranial fossa, jugular foramen or midline skull base, including mastoidectomy, decompression of sigmoid sinus and/or facial nerve, with or without mobilization", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["transtemporal approach jugular foramen", "translabyrinthine skull base approach"], keywords: ["transtemporal", "jugular foramen", "posterior fossa", "mastoidectomy", "approach", "glomus"], relatedCodes: ["61615", "61616", "61596"] },
  { code: "61596", shortDesc: "Transcochlear approach, posterior fossa/jugular foramen", fullDesc: "Transcochlear approach to posterior cranial fossa, jugular foramen or midline skull base, including labyrinthectomy, decompression, with or without mobilization of facial nerve and/or petrous carotid artery", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["transcochlear approach"], keywords: ["transcochlear", "labyrinthectomy", "jugular foramen", "approach"], relatedCodes: ["61595"] },
  { code: "61597", shortDesc: "Transcondylar (far lateral) approach, posterior fossa/foramen magnum", fullDesc: "Transcondylar (far lateral) approach to posterior cranial fossa, jugular foramen or midline skull base, including occipital condylectomy, mastoidectomy, resection of C1-C3 vertebral body(s), decompression of vertebral artery, with or without mobilization", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["far lateral approach", "transcondylar approach", "extreme lateral approach"], keywords: ["transcondylar", "far lateral", "condylectomy", "foramen magnum", "vertebral artery", "approach"], relatedCodes: ["61615", "61616"] },
  { code: "61598", shortDesc: "Transpetrosal approach, posterior fossa/clivus/foramen magnum", fullDesc: "Transpetrosal approach to posterior cranial fossa, clivus or foramen magnum, including ligation of superior petrosal sinus and/or sigmoid sinus", category: "Neurosurgery", subcategory: "Skull Base Approach", synonyms: ["transpetrosal approach", "petrosal approach clivus"], keywords: ["transpetrosal", "petrosal", "clivus", "foramen magnum", "approach"], relatedCodes: ["61616"] },

  // ═══════════════════════════════════════════════════════════════════════
  // SKULL BASE: DEFINITIVE RESECTION
  // Every pair is extradural then intradural, and CMS prints the same short
  // descriptor for both. Extradural is the lower number of each pair.
  // ═══════════════════════════════════════════════════════════════════════
  { code: "61600", shortDesc: "Resection lesion, anterior cranial fossa base, EXTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of base of anterior cranial fossa; extradural", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["anterior skull base resection extradural"], keywords: ["resection", "anterior fossa", "extradural", "skull base", "lesion"], relatedCodes: ["61601", "61580"] },
  { code: "61601", shortDesc: "Resection lesion, anterior cranial fossa base, INTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of base of anterior cranial fossa; intradural, including dural repair, with or without graft", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["anterior skull base resection intradural"], keywords: ["resection", "anterior fossa", "intradural", "dural repair", "skull base"], relatedCodes: ["61600"] },
  { code: "61605", shortDesc: "Resection lesion, infratemporal fossa/PARAPHARYNGEAL/petrous apex, EXTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of infratemporal fossa, parapharyngeal space, petrous apex; extradural", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["parapharyngeal space tumor resection", "infratemporal fossa tumor resection extradural", "glomus vagale skull base resection"], keywords: ["resection", "infratemporal", "parapharyngeal", "petrous apex", "extradural", "skull base", "paraganglioma", "glomus"], relatedCodes: ["61606", "61590", "61591"] },
  { code: "61606", shortDesc: "Resection lesion, infratemporal fossa/parapharyngeal/petrous apex, INTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of infratemporal fossa, parapharyngeal space, petrous apex; intradural, including dural repair, with or without graft", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["infratemporal fossa tumor resection intradural"], keywords: ["resection", "infratemporal", "parapharyngeal", "intradural", "dural repair", "skull base"], relatedCodes: ["61605"] },
  { code: "61607", shortDesc: "Resection lesion, parasellar/cavernous sinus/clivus, EXTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of parasellar area, cavernous sinus, clivus or midline skull base; extradural", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["cavernous sinus tumor resection extradural", "clival lesion resection extradural"], keywords: ["resection", "parasellar", "cavernous sinus", "clivus", "extradural", "skull base"], relatedCodes: ["61608", "61592"] },
  { code: "61608", shortDesc: "Resection lesion, parasellar/cavernous sinus/clivus, INTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of parasellar area, cavernous sinus, clivus or midline skull base; intradural, including dural repair, with or without graft", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["cavernous sinus tumor resection intradural", "clival chordoma intradural resection"], keywords: ["resection", "parasellar", "cavernous sinus", "clivus", "intradural", "skull base"], relatedCodes: ["61607"] },
  { code: "61613", shortDesc: "Obliteration of carotid aneurysm/AVM/CC fistula within cavernous sinus", fullDesc: "Obliteration of carotid aneurysm, arteriovenous malformation, or carotid-cavernous fistula by dissection within cavernous sinus", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["carotid cavernous fistula obliteration"], keywords: ["carotid", "cavernous", "aneurysm", "fistula", "obliteration"], relatedCodes: ["61607", "61608"] },
  { code: "61615", shortDesc: "Resection lesion, posterior fossa base/JUGULAR FORAMEN/C1-C3, EXTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of base of posterior cranial fossa, jugular foramen, foramen magnum, or C1-C3 vertebral bodies; extradural", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["jugular foramen tumor resection extradural", "glomus jugulare resection extradural", "foramen magnum lesion resection extradural"], keywords: ["resection", "jugular foramen", "foramen magnum", "posterior fossa", "extradural", "glomus", "paraganglioma", "skull base"], relatedCodes: ["61616", "61595", "61597"] },
  { code: "61616", shortDesc: "Resection lesion, posterior fossa base/jugular foramen/C1-C3, INTRADURAL", fullDesc: "Resection or excision of neoplastic, vascular or infectious lesion of base of posterior cranial fossa, jugular foramen, foramen magnum, or C1-C3 vertebral bodies; intradural, including dural repair, with or without graft", category: "Neurosurgery", subcategory: "Skull Base Resection", synonyms: ["jugular foramen tumor resection intradural", "glomus jugulare resection intradural"], keywords: ["resection", "jugular foramen", "foramen magnum", "intradural", "dural repair", "glomus", "skull base"], relatedCodes: ["61615"] },

  // ═══════════════════════════════════════════════════════════════════════
  // SKULL BASE: REPAIR
  // ═══════════════════════════════════════════════════════════════════════
  { code: "61618", shortDesc: "Secondary dural repair for CSF leak after skull base surgery, FREE graft", fullDesc: "Secondary repair of dura for cerebrospinal fluid leak, anterior, middle or posterior cranial fossa following surgery of the skull base; by free tissue graft (eg, pericranium, fascia, tensor fascia lata, adipose tissue, homologous or synthetic grafts)", category: "Neurosurgery", subcategory: "Skull Base Repair", synonyms: ["CSF leak repair free graft", "secondary dural repair skull base"], keywords: ["dural repair", "CSF leak", "free graft", "pericranium", "skull base"], relatedCodes: ["61619"] },
  { code: "61619", shortDesc: "Secondary dural repair for CSF leak after skull base surgery, PEDICLE flap", fullDesc: "Secondary repair of dura for cerebrospinal fluid leak, anterior, middle or posterior cranial fossa following surgery of the skull base; by local or regionalized vascularized pedicle flap or myocutaneous flap", category: "Neurosurgery", subcategory: "Skull Base Repair", synonyms: ["CSF leak repair vascularized flap"], keywords: ["dural repair", "CSF leak", "pedicle flap", "myocutaneous", "skull base"], relatedCodes: ["61618"] },
];
