// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/coverageText.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
/**
 * Coverage blocks with times, read straight from an agreement's text.
 *
 * The agreement analyzer asks the model for each block's startTime and
 * endTime (agreementPrompt.js), but a model can drop a time or hand back the
 * day before as the end date. When the agreement's text is at hand (a Word
 * or text upload), the blocks it states with times are read here too, and
 * any time the model left out is filled from them (withStatedTimes). Reads:
 *
 *   October 16, 2026 (4pm) to October 19, 2026 (7am)
 *   Nov 12, 2026 at 6:00 AM through Nov 19, 2026 at 6:00 AM
 *   10/16/2026 4pm - 10/19/2026 7am
 *   2026-10-16 16:00 to 2026-10-19 07:00
 *
 * Only what the text states: a block without a stated time is left to the
 * model, and nothing is guessed.
 */
import { toClock, validZone, periodProblem, timedBlockLabel } from "./coverageBlocks.js";

const MONTHS = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
const MONTH = String.raw`(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sept|Sep|Oct|Nov|Dec)\.?`;
const DATE = new RegExp(
  String.raw`\b${MONTH}\s+(\d{1,2})(?:st|nd|rd|th)?,?\s+(\d{4})\b` +
  String.raw`|\b(\d{1,2})/(\d{1,2})/(\d{4}|\d{2})\b` +
  String.raw`|\b(\d{4})-(\d{2})-(\d{2})\b`,
  "giu",
);
const TIME = String.raw`(\d{1,2}(?::\d{2})?\s*(?:a\.?\s?m\.?|p\.?\s?m\.?|a|p)(?![a-z])|\d{1,2}:\d{2}(?!\s*[ap]\.?m)|noon|midnight)`;
const TIME_AFTER = new RegExp(String.raw`^\s*,?\s*(?:\(\s*)?(?:at\s+)?${TIME}\s*\)?`, "iu");
const TIME_BEFORE = new RegExp(String.raw`(?:^|\s)\(?${TIME}\)?\s*(?:on\s+)?,?\s*$`, "iu");
const RANGE = /^\s*,?\s*(?:to|through|thru|until|till|and ending|ending|-|\u{2013}|\u{2014})\s*(?:on\s+)?$/iu;

const pad = (n) => String(n).padStart(2, "0");
const valid = (y, m, d) => {
  const x = new Date(y, m - 1, d, 12);
  return x.getFullYear() === y && x.getMonth() === m - 1 && x.getDate() === d;
};

function dateOf(m) {
  let y, mo, d;
  if (m[1]) { mo = MONTHS.indexOf(m[1].slice(0, 3).toLowerCase()) + 1; d = Number(m[2]); y = Number(m[3]); }
  else if (m[4]) { mo = Number(m[4]); d = Number(m[5]); y = Number(m[6]); if (y < 100) y += 2000; }
  else { y = Number(m[7]); mo = Number(m[8]); d = Number(m[9]); }
  return mo >= 1 && valid(y, mo, d) ? `${y}-${pad(mo)}-${pad(d)}` : "";
}

/**
 * The coverage blocks an agreement's text states as a range of two dates,
 * each with its time when one is written beside it: [{ start, end,
 * startTime?, endTime? }] (times as 24-hour "HH:MM"), in the order written.
 */
export function coverageBlocksFromText(text) {
  const src = String(text || "");
  const dates = [];
  for (const m of src.matchAll(DATE)) {
    const date = dateOf(m);
    if (!date) continue;
    const at = m.index, to = m.index + m[0].length;
    const after = src.slice(to, to + 40).match(TIME_AFTER);
    const before = src.slice(Math.max(0, at - 30), at).match(TIME_BEFORE);
    dates.push({
      date, at, to,
      tail: after ? to + after[0].length : to,
      time: toClock(after?.[1]) || toClock(before?.[1]),
      head: before ? at - before[0].length : at,
    });
  }
  const out = [];
  for (let i = 0; i + 1 < dates.length; i++) {
    const a = dates[i], b = dates[i + 1];
    if (!RANGE.test(src.slice(a.tail, b.head))) continue;
    if (b.date < a.date) continue;
    out.push({ start: a.date, end: b.date, ...(a.time ? { startTime: a.time } : {}), ...(b.time ? { endTime: b.time } : {}) });
    i += 1;
  }
  return out;
}

/**
 * Coverage periods with any time the model left out filled from the
 * agreement's text: a period the text states with times (same start date)
 * takes them, and with an end time, the text's end date (the date coverage
 * ends, not the day before). A period that already has a time is left as the
 * model read it. With no periods at all, the text's timed blocks are used.
 */
export function withStatedTimes(periods, text) {
  const stated = coverageBlocksFromText(text).filter((b) => b.startTime || b.endTime);
  if (!stated.length) return periods;
  if (!periods?.length) return stated;
  return periods.map((p) => {
    if (!p || p.startTime || p.endTime) return p;
    const b = stated.find((x) => x.start === p.start);
    if (!b) return p;
    return {
      ...p,
      ...(b.endTime ? { end: b.end } : {}),
      ...(b.startTime ? { startTime: b.startTime } : {}),
      ...(b.endTime ? { endTime: b.endTime } : {}),
    };
  });
}

const ISO_DAY = /^(\d{4})-(\d{2})-(\d{2})/;
const isoDay = (v) => { const m = String(v ?? "").trim().match(ISO_DAY); return m ? `${m[1]}-${m[2]}-${m[3]}` : ""; };

/**
 * Coverage blocks as a scan hands them in, in the shape every save writes
 * (coverageBlocks.js): { start, end, startTime?, endTime?, tz? }. Every path
 * that files an agreement runs its blocks through here: the Contracts form's
 * upload (docPrefill.js normalizeAgreementFields), the Files tab, and the
 * docs@ inbox (supabase/functions/_shared/intakeFiling.mjs).
 *
 *  - Times read as 24-hour "HH:MM" ("4pm", "7 AM"), or are dropped.
 *  - A time only on a block with its own start date, an end time only with
 *    an end date: a time on half a block would be a guess.
 *  - `text`, the agreement's own words when they are at hand (a Word or text
 *    upload), fills any time the model left out (withStatedTimes).
 *  - A start time with no end time is dropped: without an end time the end
 *    date is the last call day, as it always was (coverageBlocks.js).
 *  - A block with an end time carries `zone` (the device's, where the scan
 *    is saved) unless it already names a valid one; without `zone` (the
 *    inbox, which has no local clock) it carries none.
 *
 * `day` turns a scanned date into "YYYY-MM-DD" ("" when it is none);
 * docPrefill passes its isoDate, which also reads "October 16, 2026".
 */
export function normalizeCoveragePeriods(periods, { text = "", zone = "", day = isoDay } = {}) {
  let out = (Array.isArray(periods) ? periods : [])
    .map((p) => ({ start: day(p?.start), end: day(p?.end), startTime: toClock(p?.startTime), endTime: toClock(p?.endTime), tz: validZone(p?.tz) }))
    .filter((p) => p.start || p.end)
    .map((p) => ({
      start: p.start || p.end, end: p.end,
      ...(p.start && p.startTime ? { startTime: p.startTime } : {}),
      ...(p.start && p.end && p.endTime ? { endTime: p.endTime } : {}),
      ...(p.tz ? { tz: p.tz } : {}),
    }));
  if (text) out = withStatedTimes(out, text);
  const z = validZone(zone);
  return out.map(({ startTime, endTime, tz, ...rest }) => {
    if (!endTime) return rest;
    const zoneOf = tz || z;
    return { ...rest, ...(startTime ? { startTime } : {}), endTime, ...(zoneOf ? { tz: zoneOf } : {}) };
  });
}

/**
 * The blocks a scan may file, and the ones it may not: a block whose times
 * make it end at or before it starts covers nothing and would bill no call
 * day, so it is held back with the reason (n: its number in the list).
 * { kept, refused: [{ period, problem, label }] }.
 */
export function fileableCoveragePeriods(periods) {
  const kept = [], refused = [];
  (periods || []).forEach((p, i) => {
    const problem = periodProblem(p, i + 1);
    if (problem) refused.push({ period: p, problem, label: timedBlockLabel(p) || `${p.start} to ${p.end || p.start}` });
    else kept.push(p);
  });
  return { kept, refused };
}
