// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/coverageBlocks.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
/**
 * Coverage blocks with times.
 *
 * A locum agreement states each coverage block with times: "September 25,
 * 2026 (4pm) to September 28, 2026 (7am)", "November 5, 2026 (6am) to
 * November 12, 2026 (6am)". contract.coveragePeriods (the jsonb column
 * locum_contracts.coverage_periods; no column of its own) holds one object
 * per block:
 *
 *   { start: "YYYY-MM-DD", end: "YYYY-MM-DD", startTime?: "HH:MM", endTime?: "HH:MM", tz?: "America/Chicago" }
 *
 * Times are 24-hour wall-clock times where the work happens. `tz` (an IANA
 * zone) says which wall clock: the same block then covers the same moments
 * whichever device reads it, so an invoice built on a Pacific-time laptop
 * bills what one built on site does. Every save path stamps it (the
 * Contracts form, the Files tab); a block without one (filed by email, which
 * has no local clock) is read on this device's clock, as it always was.
 *
 * The END TIME decides what `end` means:
 *
 *  - No end time (every block saved before Sep 2026): `end` is the LAST
 *    CALL DAY, the call that ends the next morning at the contract's
 *    call-day start hour. That meaning is unchanged, and nothing below
 *    applies. A start time with no end time is ignored for the same reason
 *    (the Contracts form refuses one): read as a block starting at 4:00 PM
 *    it turned every call day over at 4:00 PM and kept the end date as a
 *    call day of its own.
 *  - An end time: `end` is the literal date coverage ends, at endTime. "Sep
 *    25 (4pm) to Sep 28 (7am)" is { start: "2026-09-25", startTime: "16:00",
 *    end: "2026-09-28", endTime: "07:00" }: three call days (Sep 25, 26 and
 *    27), not four. Without a start time the block starts on its start date
 *    at the end time.
 *
 * Inside a timed block the call day turns over at the block's end time: a 6
 * AM to 6 AM block files 6:15 AM work under that same day even when the
 * contract's call day starts at 7. The first call day starts at the block's
 * start moment (4:00 PM) and the last ends at its end moment (7:00 AM).
 * Outside every timed block the contract's own call-day start hour decides,
 * as it always has, except on a block's start date before it begins
 * (leadInCallDay): 5:30 AM before a 6:00 AM start files under the block's
 * first day, so work running into the block is split at its start.
 *
 * A call day is keyed by the calendar date its call starts on. The first
 * call day of a block is always the block's start date: a block starting
 * before the day's turnover (7:00 AM start, 5:00 PM turnover) opens with one
 * long call day rather than a short one filed under the day before.
 *
 * No imports: the email-inbound edge function copies this file (through
 * contractsForDate.js, scripts/sync-shared-app-modules.mjs).
 */

const pad = (n) => String(n).padStart(2, "0");
const ymd = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const DAY_KEY = /^\d{4}-\d{2}-\d{2}$/;
const isDay = (v) => DAY_KEY.test(String(v ?? ""));
const parts = (key) => key.split("-").map(Number);
const addDays = (key, n) => { const [y, m, d] = parts(key); return ymd(new Date(y, m - 1, d + n, 12)); };

// ── Time zones ───────────────────────────────────────────────────
// A zone "" is this device's own clock (the Date getters). Any other zone is
// read through Intl, which every browser and Deno carry.

const ZONES = new Map();
/** An IANA zone as the runtime names it ("US/Central" reads as "America/Chicago"), or "" when it is not one. */
export function validZone(tz) {
  if (typeof tz !== "string" || !tz.trim() || tz.length > 64) return "";
  if (ZONES.has(tz)) return ZONES.get(tz);
  let out = "";
  try { out = new Intl.DateTimeFormat("en-US", { timeZone: tz.trim() }).resolvedOptions().timeZone || ""; } catch { out = ""; }
  ZONES.set(tz, out);
  return out;
}

/** This device's zone, or "" when the runtime does not say. */
export function deviceZone() {
  try { return validZone(Intl.DateTimeFormat().resolvedOptions().timeZone || ""); } catch { return ""; }
}

const FORMATS = new Map();
const zoneFormat = (tz) => {
  if (!FORMATS.has(tz)) {
    FORMATS.set(tz, new Intl.DateTimeFormat("en-US", {
      timeZone: tz, hourCycle: "h23", year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit",
    }));
  }
  return FORMATS.get(tz);
};

// The wall clock at a moment: { key: "YYYY-MM-DD", minute (after midnight), second }.
const wallAt = (ms, tz) => {
  if (!tz) { const d = new Date(ms); return { key: ymd(d), minute: d.getHours() * 60 + d.getMinutes(), second: d.getSeconds() }; }
  const p = {};
  for (const x of zoneFormat(tz).formatToParts(new Date(ms))) p[x.type] = x.value;
  const h = Number(p.hour) % 24;
  return { key: `${p.year}-${p.month}-${p.day}`, minute: h * 60 + Number(p.minute), second: Number(p.second) };
};

// How far the zone's wall clock runs ahead of UTC at a moment, in ms.
const offsetAt = (ms, tz) => {
  const t = Math.floor(ms / 1000) * 1000;
  const w = wallAt(t, tz);
  const [y, m, d] = parts(w.key);
  return Date.UTC(y, m - 1, d, Math.floor(w.minute / 60), w.minute % 60, w.second) - t;
};

/**
 * Epoch ms of a wall-clock minute of the day on a calendar date, in a zone
 * ("" = this device). Resolved the way new Date(y, m, d, h, mi) resolves
 * this device's clock: an hour the clock skips (the spring-forward 2:30 AM)
 * moves forward, an hour it repeats (the fall-back 1:30 AM) is the first.
 */
const MOMENTS = new Map();
function momentOf(key, minute, tz = "") {
  const [y, m, d] = parts(key);
  const h = Math.floor(minute / 60), mi = minute % 60;
  if (!tz) return new Date(y, m - 1, d, h, mi).getTime();
  // A zone's moments never change, so each is worked out once.
  const memo = `${tz}|${key}|${minute}`;
  if (MOMENTS.has(memo)) return MOMENTS.get(memo);
  const wall = Date.UTC(y, m - 1, d, h, mi);
  const before = offsetAt(wall - 86400000, tz), after = offsetAt(wall + 86400000, tz);
  const hits = [wall - before, wall - after].filter((t) => offsetAt(t, tz) === wall - t).sort((a, b) => a - b);
  const out = hits.length ? hits[0] : wall - before;
  if (MOMENTS.size > 20000) MOMENTS.clear();
  MOMENTS.set(memo, out);
  return out;
}

/**
 * A time as "HH:MM" (24-hour), or "" when it is not a time. Reads what an
 * agreement or a model writes: "16:00", "4pm", "4 PM", "4:00 p.m.", "(7am)",
 * "0700", "noon", "midnight".
 */
export function toClock(v) {
  if (v == null) return "";
  const s = String(v).trim().toLowerCase().replace(/[().]/g, "").replace(/\s+/g, " ").trim();
  if (!s) return "";
  if (s === "noon") return "12:00";
  if (s === "midnight") return "00:00";
  let m = s.match(/^(\d{1,2})(?::(\d{2}))?(?::\d{2})? ?(am|pm|a|p)$/);
  if (m) {
    const h = Number(m[1]), mi = Number(m[2] || 0);
    if (h < 1 || h > 12 || mi > 59) return "";
    return `${pad((h % 12) + (m[3].startsWith("p") ? 12 : 0))}:${pad(mi)}`;
  }
  m = s.match(/^(\d{1,2}):(\d{2})(?::\d{2})?$/) || s.match(/^(\d{2})(\d{2})$/);
  if (m) {
    const h = Number(m[1]), mi = Number(m[2]);
    return h <= 23 && mi <= 59 ? `${pad(h)}:${pad(mi)}` : "";
  }
  return "";
}

/** Minutes after midnight for a time (anything toClock reads), or null. */
export function clockMinutes(v) {
  const c = toClock(v);
  if (!c) return null;
  const [h, m] = c.split(":").map(Number);
  return h * 60 + m;
}

/** "4:00 PM" for minutes after midnight, or for a moment (Date, ISO string or epoch ms) on a zone's clock ("" = this device). */
export function clockLabel(v, tz = "") {
  let min = v;
  if (typeof v !== "number" || v > 1440) min = wallAt(new Date(v).getTime(), validZone(tz)).minute;
  const h = Math.floor(min / 60), m = min % 60;
  return `${h % 12 === 0 ? 12 : h % 12}:${pad(m)} ${h < 12 ? "AM" : "PM"}`;
}

/** "Sep 25" for a moment, on a zone's calendar ("" = this device). */
export const monthDay = (ms, tz = "") => {
  const zone = validZone(tz);
  return new Date(ms).toLocaleDateString("en-US", { month: "short", day: "numeric", ...(zone ? { timeZone: zone } : {}) });
};

// The call day a moment falls in when the day turns over at `turnover`
// minutes after midnight on a zone's clock (the wall-clock rule, see
// billing.js deriveCallDay).
const turnoverDay = (ms, turnover, tz) => {
  const w = wallAt(ms, tz);
  return w.minute >= turnover ? w.key : addDays(w.key, -1);
};

/** True when a block states when it ends: an end date with an end time. A start time alone is no time (see the header). */
export function isTimedPeriod(p) {
  return !!p && isDay(p.start) && isDay(p.end) && clockMinutes(p.endTime) != null;
}

/** True when any of the contract's blocks states a time. Without one, nothing here changes anything. */
export function hasTimedPeriods(contract) {
  return (contract?.coveragePeriods || []).some(isTimedPeriod);
}

/**
 * A timed block as moments, or null for a block without times:
 * { period, tz, startMs, endMs, turnover (minutes after midnight), firstDay,
 * lastDay, valid }. valid is false when it ends at or before it starts; such
 * a block covers nothing (the contract form refuses to save one). A block on
 * a zone's clock reads the same on every device, so it is worked out once
 * per saved block (one on this device's clock is cheap to read).
 */
const ZONED_BLOCKS = new WeakMap();
export function timedBlock(p) {
  if (!isTimedPeriod(p)) return null;
  const tz = validZone(p.tz);
  if (!tz) return readBlock(p, "");
  const sig = `${p.start}|${p.end}|${p.startTime}|${p.endTime}|${tz}`;
  const hit = ZONED_BLOCKS.get(p);
  if (hit?.sig === sig) return hit.block;
  const block = readBlock(p, tz);
  ZONED_BLOCKS.set(p, { sig, block });
  return block;
}
function readBlock(p, tz) {
  const turnover = clockMinutes(p.endTime);
  const startMs = momentOf(p.start, clockMinutes(p.startTime) ?? turnover, tz);
  const endMs = momentOf(p.end, turnover, tz);
  const firstDay = p.start;
  const last = turnoverDay(endMs - 1, turnover, tz);
  return { period: p, tz, startMs, endMs, turnover, firstDay, lastDay: last > firstDay ? last : firstDay, valid: endMs > startMs };
}

/** The contract's valid timed blocks, earliest start first. */
export function timedBlocks(contract) {
  return (contract?.coveragePeriods || []).map(timedBlock).filter((b) => b && b.valid).sort((a, b) => a.startMs - b.startMs);
}

/** The zone the contract's timed blocks are stated in ("" = this device's clock). */
export function contractZone(contract) {
  return timedBlocks(contract).find((b) => b.tz)?.tz || "";
}

/** The timed block a moment falls inside (start inclusive, end exclusive), or null. */
export function timedBlockAt(contract, at) {
  const ms = new Date(at).getTime();
  if (!Number.isFinite(ms)) return null;
  return timedBlocks(contract).find((b) => ms >= b.startMs && ms < b.endMs) || null;
}

/** The call day of a moment inside a timed block, or null when it is outside every timed block. */
export function timedCallDay(contract, at) {
  const b = timedBlockAt(contract, at);
  if (!b) return null;
  const k = turnoverDay(new Date(at).getTime(), b.turnover, b.tz);
  return k < b.firstDay ? b.firstDay : k > b.lastDay ? b.lastDay : k;
}

/** The call days of a timed block, in order. */
export function blockCallDays(b) {
  const out = [];
  if (!b?.valid) return out;
  for (let k = b.firstDay, i = 0; k <= b.lastDay && i < 1000; k = addDays(k, 1), i++) out.push(k);
  return out;
}

/** The timed block whose call days include this call day, or null. */
export function blockForCallDay(contract, dayKey) {
  if (!isDay(dayKey)) return null;
  return timedBlocks(contract).find((b) => dayKey >= b.firstDay && dayKey <= b.lastDay) || null;
}

/** When one call day of a timed block runs: { startMs, endMs }. */
export function callDayWindow(b, dayKey) {
  return {
    startMs: dayKey <= b.firstDay ? b.startMs : momentOf(dayKey, b.turnover, b.tz),
    endMs: dayKey >= b.lastDay ? b.endMs : momentOf(addDays(dayKey, 1), b.turnover, b.tz),
  };
}

/** "call 4:00 PM Sep 25 to 7:00 AM Sep 26": the window a timed call day covers, for the invoice. */
export function callDayWindowText(b, dayKey) {
  const w = callDayWindow(b, dayKey);
  return `call ${clockLabel(w.startMs, b.tz)} ${monthDay(w.startMs, b.tz)} to ${clockLabel(w.endMs, b.tz)} ${monthDay(w.endMs, b.tz)}`;
}

/** Whether a period (timed or not) has this call day. An untimed block keeps its old meaning: start through end. */
export function periodHasCallDay(p, dayKey) {
  if (!p?.start || !dayKey) return false;
  const b = timedBlock(p);
  if (b) return b.valid && dayKey >= b.firstDay && dayKey <= b.lastDay;
  return dayKey >= p.start && dayKey <= (p.end || p.start);
}

/**
 * The call day for a moment on a timed block's start date, before the block
 * begins (5:30 AM on Nov 5 before a 6:00 AM start): the block's first call
 * day. `fallbackDay` is the call day the contract's own start hour gives the
 * moment; when that is itself a call day of some block (the block before
 * this one), it stands and this returns null, as it does for any moment not
 * on a later block's start date. Filed under the block's first day, work
 * that runs into the block is shared out at its start (billing.js
 * coveragePartsOf) instead of billing whole under a day that is no call day.
 */
export function leadInCallDay(contract, at, fallbackDay) {
  const ms = new Date(at).getTime();
  if (!Number.isFinite(ms) || !isDay(fallbackDay)) return null;
  if ((contract?.coveragePeriods || []).some((p) => periodHasCallDay(p, fallbackDay))) return null;
  const b = timedBlocks(contract).find((x) => ms < x.startMs && wallAt(ms, x.tz).key === x.firstDay);
  return b ? b.firstDay : null;
}

/**
 * Every moment strictly inside (s, en) where a timed block's call day may
 * turn over: its start and end moments, its own turnover time on each day
 * inside it, and the midnight its start date begins (see leadInCallDay).
 * billing.js callDayCuts keeps the ones where the call day really changes.
 */
export function blockTurnoversWithin(contract, s, en) {
  const out = [];
  for (const b of timedBlocks(contract)) {
    const lead = momentOf(b.firstDay, 0, b.tz);
    for (const t of [lead, b.startMs, b.endMs]) if (t > s && t < en) out.push(t);
    const from = Math.max(s, b.startMs), to = Math.min(en, b.endMs);
    if (!(to > from)) continue;
    for (let k = addDays(wallAt(from, b.tz).key, -1), i = 0; i < 400; k = addDays(k, 1), i++) {
      const t = momentOf(k, b.turnover, b.tz);
      if (t >= to) break;
      if (t > from) out.push(t);
    }
  }
  return out;
}

/**
 * The calendar dates a timed block touches, { start, end }, for "is this
 * contract in force on this date" (the pickers and the schedule guard): Sep
 * 25 4:00 PM to Sep 28 7:00 AM touches Sep 25 through Sep 28; a block ending
 * at midnight does not touch the day it ends on. null for a block without
 * times (callers keep their own reading of it).
 */
export function timedSpan(p) {
  const b = timedBlock(p);
  if (!b) return null;
  if (!b.valid) return { start: p.start, end: p.start };
  return { start: wallAt(b.startMs, b.tz).key, end: wallAt(b.endMs - 1, b.tz).key };
}

/** "Sep 25, 4:00 PM to Sep 28, 7:00 AM" for a timed block (on its own zone's clock), or null for one without times. */
export function timedBlockLabel(p) {
  const b = timedBlock(p);
  if (!b) return null;
  return `${monthDay(b.startMs, b.tz)}, ${clockLabel(b.startMs, b.tz)} to ${monthDay(b.endMs, b.tz)}, ${clockLabel(b.endMs, b.tz)}`;
}

const shortDay = (key) => { const [y, m, d] = parts(key); return new Date(y, m - 1, d, 12).toLocaleDateString("en-US", { month: "short", day: "numeric" }); };

/**
 * What a block bills as, said the way the Contracts form shows it under the
 * block: "Sep 25, 4:00 PM to Sep 28, 7:00 AM · 3 call days: Sep 25 to Sep
 * 27" with times; without, "3 call days: Sep 25 to Sep 27" (the end date is
 * the last call day). "" for a block with no start date yet or one that
 * covers nothing (periodProblem says why).
 */
export function blockSummary(p) {
  if (!p || !isDay(p.start)) return "";
  const b = timedBlock(p);
  let days;
  if (b) {
    if (!b.valid) return "";
    days = blockCallDays(b);
  } else {
    const end = isDay(p.end) ? p.end : p.start;
    if (end < p.start) return "";
    days = [];
    for (let k = p.start, i = 0; k <= end && i < 1000; k = addDays(k, 1), i++) days.push(k);
  }
  const count = `${days.length} call ${days.length === 1 ? "day" : "days"}: ${shortDay(days[0])}${days.length > 1 ? ` to ${shortDay(days.at(-1))}` : ""}`;
  return b ? `${timedBlockLabel(p)} \u{b7} ${count}` : count;
}

/**
 * How a block reads in a list: "Sep 25, 4:00 PM to Sep 28, 7:00 AM" with
 * times; without, "<start> – <end>" through formatDate (helpers.js), the way
 * the lists have always written it.
 */
export function coveragePeriodText(p, formatDate) {
  return timedBlockLabel(p) ?? `${formatDate(p.start)}${p.end && p.end !== p.start ? " \u{2013} " + formatDate(p.end) : ""}`;
}

/**
 * A block as saved: times kept only when they read as times ("HH:MM"), so a
 * block without times saves exactly what it always did. A block with an end
 * time carries the zone its times are on: `zone` when given (the Contracts
 * form's), else the one it already had.
 */
export function savedPeriod(p, zone = "") {
  const { startTime, endTime, tz, ...rest } = p || {};
  const st = toClock(startTime), et = toClock(endTime);
  const out = { ...rest, ...(st ? { startTime: st } : {}), ...(et ? { endTime: et } : {}) };
  const z = isTimedPeriod(out) ? validZone(zone) || validZone(tz) : "";
  return z ? { ...out, tz: z } : out;
}

/** Why a coverage block cannot be saved (n: its number in the list), or "". */
export function periodProblem(p, n) {
  if ((toClock(p?.startTime) || toClock(p?.endTime)) && !isDay(p?.start)) return `Block ${n} has a time but no start date.`;
  if (toClock(p?.endTime) && !isDay(p?.end)) return `Block ${n} has an end time but no end date. Enter the date coverage ends.`;
  if (toClock(p?.startTime) && !toClock(p?.endTime)) return `Block ${n} has a start time but no end time. Enter when coverage ends.`;
  const b = timedBlock(p);
  if (b && !b.valid) return `Block ${n} ends before it starts (${timedBlockLabel(p)}). Check its dates and times.`;
  return "";
}

/**
 * Every stretch of time the contract's blocks cover, as [startMs, endMs)
 * pairs: a timed block from its start to its end moment, an untimed block
 * from its start date at `hour` to the morning after its last call day.
 */
export function coveredIntervals(contract, hour) {
  const out = [];
  for (const p of contract?.coveragePeriods || []) {
    if (!p || !isDay(p.start)) continue;
    const b = timedBlock(p);
    if (b) { if (b.valid) out.push([b.startMs, b.endMs]); continue; }
    const end = isDay(p.end) && p.end >= p.start ? p.end : p.start;
    out.push([momentOf(p.start, hour * 60), momentOf(addDays(end, 1), hour * 60)]);
  }
  return out.sort((a, b) => a[0] - b[0]);
}

// Milliseconds of [a, z) that no interval covers.
const uncovered = (a, z, intervals) => {
  if (!(z > a)) return 0;
  let left = z - a, at = a;
  for (const [s, e] of intervals) {
    const from = Math.max(s, at), to = Math.min(e, z);
    if (to > from) { left -= to - from; at = to; }
  }
  return Math.max(0, left);
};
const coveredAt = (t, intervals) => intervals.some(([s, e]) => t >= s && t < e);

/**
 * How a span of work filed under one of block b's call days sits against
 * the block, in milliseconds: before its start moment, inside it, after its
 * end moment. Time another block covers (two blocks back to back) counts as
 * inside, as a crossing entry always has. A zero-length span is an instant
 * and weighs 1 on the side it falls.
 */
export function spanAgainstBlock(s, en, b, intervals = []) {
  if (!(en > s)) {
    const out = !coveredAt(s, intervals);
    const before = out && s < b.startMs ? 1 : 0, after = out && s >= b.endMs ? 1 : 0;
    return { before, inside: 1 - before - after, after };
  }
  const before = s < b.startMs ? uncovered(s, Math.min(en, b.startMs), intervals) : 0;
  const after = en > b.endMs ? uncovered(Math.max(s, b.endMs), en, intervals) : 0;
  return { before, inside: en - s - before - after, after };
}
