// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/identifierGate.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
// The identifier gate: one rule for every path that decides whether a label
// or a value is a patient identifier, a Social Security or taxpayer number, a
// full date of birth, or an account, encounter, licence or passport number.
//
// customCategories.js applies it to every scan, Vera and upload write, and
// re-exports it; the support view (supabase/functions/_shared/memberView.mjs)
// applies it to what an administrator may read. Pure, imports nothing, so
// scripts/sync-shared-app-modules.mjs copies it verbatim for the edge
// functions and plain node tests import it.

// ── Identifiers that must never reach the cloud ───────────────────────────
// CredentialDOMD is no-PHI by design. "File everything" on an unclassifiable
// document is exactly how 1,380 MRNs reached case logs in August 2026, so every
// fact passes this gate on the way in. It matches PHRASES, not bare words:
// "Patient Safety Committee" is a real reappointment item and must survive.
const IDENTIFIER_LABELS = [
  [/\b(mrn|medical\s+record(\s+(number|no\.?|#))?|med\s+rec)\b|\bmr\s*#/i, "a medical record number"],
  [/\bchart\s*(#|no\.?|number)/i, "a medical record number"],
  [/^\s*(patient|pt)(\s+name)?\s*:?\s*$|\bpt\s+(name|id|number)\b/i, "a patient identifier"],
  [/\bpatient\s+(name|id|identifier|number|no\.?|dob|date\s+of\s+birth|sticker|label|address|phone)\b/i, "a patient identifier"],
  // The spellings hospital exports use: "Patient Last Name", "PatientLastName",
  // "Patient's Name", "Pt. ID", "Patient #". Still a phrase, so "Patient
  // Safety Committee" is never caught.
  [/\b(patient|pt)(?:[^\sa-z0-9]?s)?\.?\s*(?:(?:first|last|full|middle|legal|given|family|sur)\s*)?(?:name|id|identifier|number|no)\b|\b(patient|pt)\.?\s*#/i, "a patient identifier"],
  [/\b(social\s+security|ssn|soc\.?\s*sec\.?|ss\s*no\.?)\b|\bss\s*#/i, "a Social Security number"],
  // An individual's taxpayer ID is their SSN; a W-9 is uploaded constantly by
  // locum physicians. Withheld on the label, whatever the number looks like.
  [/\b(tin|taxpayer\s+id(entification)?(\s+(number|no\.?))?|tax\s*id(\s+(number|no\.?))?)\b/i, "a Social Security number"],
  [/\b(date\s+of\s+birth|birth\s*date|dob|d\s*o\s*b)\b|^\s*(born|birthday)\s*$/i, "a full date of birth"],
  // A "#" that ends the cell has no word boundary after it, so the tail is
  // spelled out: "Acct #", "Hospital Account #" and "Encounter #" all match.
  [/\b(account|acct)\.?\s*(?:number\b|no\b|#)/i, "an account number"],
  [/\bencounter\s*(?:number\b|no\b|id\b|#)/i, "an encounter number"],
  [/\b(driver'?s?\s+licen[cs]e|passport)\s*(number|no\.?|#)?\b/i, "a driver's licence or passport number"],
];
// Three digit groups split by any separator: 123-45-6789, 123 45 6789,
// 123.45.6789, en or em dashes. A bare nine-digit run is NOT enough on its
// own: badge, policy and licence numbers are often nine digits.
const DASHES = "\\-\u2010-\u2015";
const SSN_VALUE = new RegExp(`(?<!\\d)\\d{3}[\\s.${DASHES}]\\d{2}[\\s.${DASHES}]\\d{4}(?!\\d)`);
const SSN_WORDS = /\b(ssn|ss\s*#|social\s+security|soc\.?\s*sec|tin|taxpayer|tax\s*id)\b/i;
const NINE_DIGITS = /(?<!\d)\d{3}\D{0,3}\d{2}\D{0,3}\d{4}(?!\d)/;
// Keyword then a number or date inside free text: "MRN 00481234", "DOB 3/14/61".
const VALUE_MARKERS = [
  [/\b(mrn|mr\s*#|medical\s+record(\s+(number|no\.?|#))?)\s*[:#]?\s*\d/i, "a medical record number"],
  [/\b(dob|d\.\s*o\.\s*b\.?|date\s+of\s+birth)\s*[:#]?\s*\d/i, "a full date of birth"],
];

// Labels arrive as "Date of Birth", "dateOfBirth", "date_of_birth" or
// "D.O.B."; match them all the same way.
function normalizeLabel(label) {
  return String(label || "")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/(\b\w)\./g, "$1")
    .replace(/[_\-/]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function identifierReason(label, value) {
  const l = normalizeLabel(label);
  const v = String(value ?? "");
  for (const [re, why] of IDENTIFIER_LABELS) if (re.test(l)) return why;
  if (SSN_VALUE.test(v)) return "a Social Security number";
  if (SSN_WORDS.test(`${l} ${v}`) && NINE_DIGITS.test(v)) return "a Social Security number";
  for (const [re, why] of VALUE_MARKERS) if (re.test(v)) return why;
  return null;
}
