// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/intakeRecords.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
// Facts a forwarded email states about the physician, as records.
//
// On 2026-09-28 the owner forwarded to docs@ an agency consultant's letter
// confirming that the agency's malpractice policy covers his emergency care
// ($1,000,000 per incident, $3,000,000 aggregate) with the signed master
// services agreement attached. It asked for nothing. His rule: "the docs was
// supposed to enter the malpractice into the app and not create a email
// back". So an email that asks nothing is ENTERED as records and nobody is
// emailed: email-inbound writes the record itself when the forward is
// positively authenticated, and otherwise stores a proposal the physician
// adds with one tap (supabase/functions/_shared/intakeFacts.mjs decides what
// the email states; src/utils/intakeProposals.js applies a tap).
//
// This file is the part both sides share, so a record the server writes and
// the same record added from the app are one shape:
//   EMAIL_FIELDS     the columns an email may fill, per section, and what
//                    kind of value each holds. No identifying number is
//                    among them (no policy, licence, certificate, DEA or NPI
//                    number): an email never writes one.
//   amountsIn, datesIn, amountValue, dateValue
//                    amounts and dates as the email writes them, read to one
//                    form ($1,000,000 == 1000000 == $1 million; 03/01/2026 ==
//                    March 1, 2026 == 2026-03-01)
//   recordFromFields the record to add, as the app's own add would store it
//   matchRecord      the record already on file that a fact is about
//   appendChanges    what a fact adds to a record on file: empty fields
//                    filled, a note appended, nothing overwritten, and an
//                    expiration already there never moved
//   recordSummary    the line the physician reads
//
// Pure: plain node tests import it, and scripts/sync-shared-app-modules.mjs
// copies it for the edge functions.

import { INSURANCE_TYPES, PRIVILEGE_TYPES, LICENSE_TYPES_MD, LICENSE_TYPES_DO, CME_CATEGORIES_MD, CME_CATEGORIES_DO } from "../constants/credentialTypes.js";
import { STATE_NAMES } from "../constants/states.js";
import { normalizeLifecycle } from "./lifecycle.js";

/** The sections an email may add a record to, or append a note to. */
export const RECORD_SECTIONS = Object.freeze(["insurance", "privileges", "licenses", "cme", "locumContracts"]);

/**
 * The columns an email may fill, by section, and the kind of each:
 *   type    one of the section's own types (SECTION_TYPES)
 *   text    a short name; its proper names and numbers must be the email's
 *   money   an amount, stored as plain digits (the columns are text)
 *   date    YYYY-MM-DD, written in the email in any common form
 *   state   a two-letter code
 *   number  a count (CME hours)
 *   notes   a short summary; its names and numbers must be the email's
 * A contract is never made from an email's text (its rates bill invoices):
 * locumContracts takes a note on a contract already on file, nothing else.
 */
export const EMAIL_FIELDS = Object.freeze({
  insurance: Object.freeze({ type: "type", name: "text", provider: "text", coveragePerClaim: "money", coverageAggregate: "money", effectiveDate: "date", expirationDate: "date", notes: "notes" }),
  privileges: Object.freeze({ type: "type", name: "text", facility: "text", city: "text", state: "state", appointmentDate: "date", expirationDate: "date", notes: "notes" }),
  licenses: Object.freeze({ type: "type", name: "text", state: "state", issuedDate: "date", expirationDate: "date", notes: "notes" }),
  cme: Object.freeze({ title: "text", category: "type", hours: "number", date: "date", provider: "text", notes: "notes" }),
  locumContracts: Object.freeze({ notes: "notes" }),
});

const uniq = (xs) => [...new Set(xs)];
export const SECTION_TYPES = Object.freeze({
  insurance: Object.freeze([...INSURANCE_TYPES]),
  privileges: Object.freeze([...PRIVILEGE_TYPES]),
  licenses: Object.freeze(uniq([...LICENSE_TYPES_MD, ...LICENSE_TYPES_DO])),
  cme: Object.freeze(uniq([...CME_CATEGORIES_MD, ...CME_CATEGORIES_DO])),
});

// Sections with a status source column (migration 20260925030000).
const SOURCE_SECTIONS = new Set(["insurance", "privileges", "licenses"]);
// NOT NULL columns and what an unread one becomes, as the app's forms default.
const TYPE_DEFAULTS = Object.freeze({ insurance: { type: "Other" }, privileges: { type: "Other" }, licenses: { type: "Other" }, cme: { category: "Other" } });

export const SECTION_LABEL = Object.freeze({ insurance: "Insurance", privileges: "Privileges", licenses: "Licenses", cme: "CME", locumContracts: "Contracts" });
export const FIELD_LABEL = Object.freeze({
  type: "Type", name: "Name", provider: "Provider", coveragePerClaim: "Per claim", coverageAggregate: "Aggregate",
  effectiveDate: "Effective", expirationDate: "Expires", notes: "Notes", facility: "Facility", city: "City", state: "State",
  appointmentDate: "Appointed", issuedDate: "Issued", title: "Title", category: "Category", hours: "Hours", date: "Date",
  statusSource: "Source",
});

/** The field kind of `key` in `section`, or "" when an email may not fill it. */
export const fieldKind = (section, key) => (EMAIL_FIELDS[section] && Object.hasOwn(EMAIL_FIELDS[section], key) ? EMAIL_FIELDS[section][key] : "");

// ─── Amounts ─────────────────────────────────────────────────────────────────

const SCALE = { thousand: 1e3, k: 1e3, million: 1e6, mil: 1e6, m: 1e6, mm: 1e6, billion: 1e9, b: 1e9, bn: 1e9 };
// "$1,000,000", "$1M", "$1.5 million", "1,000,000", "1 million", "$250k".
// A bare run of digits with no "$", no thousands commas and no scale word is
// not an amount: it is as likely to be a policy or licence number.
const AMOUNT_RE = /\$\s?(\d{1,3}(?:,\d{3})+|\d+)(\.\d+)?(?:\s?(thousand|million|billion|mil|mm|bn|[kmb])\b)?|\b(\d{1,3}(?:,\d{3}){1,4})(\.\d{2})?(?!\d)|\b(\d+(?:\.\d+)?)\s?(thousand|million|billion)\b/gi;

function amountFrom(intPart, frac, scaleWord) {
  const n = parseFloat(`${String(intPart).replace(/,/g, "")}${frac || ""}`);
  if (!Number.isFinite(n)) return null;
  const scale = scaleWord ? SCALE[String(scaleWord).toLowerCase()] || 1 : 1;
  const v = Math.round(n * scale);
  return v > 0 && v <= 1e12 ? String(v) : null;
}

/** Every amount written in `text`: [{ value: "1000000", index, end }]. */
export function amountsIn(text) {
  const out = [];
  const s = String(text ?? "");
  for (const m of s.matchAll(AMOUNT_RE)) {
    const v = m[1] !== undefined ? amountFrom(m[1], m[2], m[3]) : m[4] !== undefined ? amountFrom(m[4], m[5], null) : amountFrom(m[6], "", m[7]);
    if (v) out.push({ value: v, index: m.index, end: m.index + m[0].length });
  }
  return out;
}

/** One amount as plain digits ("$1,000,000", "1000000", "1 million" -> "1000000"), or null. */
export function amountValue(v) {
  const s = String(v ?? "").trim();
  if (/^\d+(?:\.\d+)?$/.test(s)) return amountFrom(s, "", null);
  const found = amountsIn(s);
  return found.length === 1 ? found[0].value : null;
}

// ─── Dates ───────────────────────────────────────────────────────────────────

const MONTHS = { jan: 1, feb: 2, mar: 3, apr: 4, may: 5, jun: 6, jul: 7, aug: 8, sep: 9, sept: 9, oct: 10, nov: 11, dec: 12 };
const MONTH = "(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|june?|july?|aug(?:ust)?|sept?(?:ember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)";
const DATE_RES = [
  [/\b(\d{4})-(\d{1,2})-(\d{1,2})\b/g, (m) => [m[1], m[2], m[3]]],
  [/\b(\d{1,2})\/(\d{1,2})\/(\d{4}|\d{2})\b/g, (m) => [m[3], m[1], m[2]]],
  [new RegExp(`\\b${MONTH}\\.?\\s+(\\d{1,2})(?:st|nd|rd|th)?,?\\s+(\\d{4})\\b`, "gi"), (m) => [m[3], MONTHS[m[1].slice(0, m[1].toLowerCase().startsWith("sept") ? 4 : 3).toLowerCase()], m[2]]],
  [new RegExp(`\\b(\\d{1,2})(?:st|nd|rd|th)?\\s+(?:of\\s+)?${MONTH}\\.?,?\\s+(\\d{4})\\b`, "gi"), (m) => [m[3], MONTHS[m[2].slice(0, m[2].toLowerCase().startsWith("sept") ? 4 : 3).toLowerCase()], m[1]]],
];

export const validIsoDate = (s) => {
  if (typeof s !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(s)) return false;
  const t = Date.parse(`${s}T00:00:00Z`);
  if (Number.isNaN(t) || new Date(t).toISOString().slice(0, 10) !== s) return false;
  const y = Number(s.slice(0, 4));
  return y >= 1950 && y <= 2100;
};

function isoFrom(y, m, d) {
  let year = Number(y);
  if (String(y).length === 2) year = year <= 79 ? 2000 + year : 1900 + year;
  const iso = `${String(year).padStart(4, "0")}-${String(Number(m)).padStart(2, "0")}-${String(Number(d)).padStart(2, "0")}`;
  return validIsoDate(iso) ? iso : null;
}

/** Every date written in `text`, read to YYYY-MM-DD: [{ iso, index, end }]. MM/DD/YYYY, as US mail writes it. */
export function datesIn(text) {
  const s = String(text ?? "");
  const out = [];
  for (const [re, parts] of DATE_RES) {
    for (const m of s.matchAll(re)) {
      const [y, mo, d] = parts(m);
      const iso = mo ? isoFrom(y, mo, d) : null;
      if (iso && !out.some((o) => o.index === m.index)) out.push({ iso, index: m.index, end: m.index + m[0].length });
    }
  }
  return out.sort((a, b) => a.index - b.index);
}

/** One date as YYYY-MM-DD, from any form datesIn reads, or null. */
export function dateValue(v) {
  const s = String(v ?? "").trim();
  if (validIsoDate(s)) return s;
  const found = datesIn(s);
  return found.length === 1 ? found[0].iso : null;
}

/** "2026-03-01" -> "03/01/2026". */
export function usDate(iso) {
  if (!validIsoDate(iso)) return String(iso ?? "");
  const [y, m, d] = iso.split("-");
  return `${m}/${d}/${y}`;
}

/** "$1,000,000" from "1000000". */
export const dollars = (digits) => {
  const n = Number(String(digits ?? "").replace(/[^0-9]/g, ""));
  return Number.isFinite(n) && n > 0 ? `$${n.toLocaleString("en-US")}` : String(digits ?? "");
};

// ─── States ──────────────────────────────────────────────────────────────────

/** A two-letter code from "CO", "co" or "Colorado", or "". */
export function stateCode(v) {
  const s = String(v ?? "").trim();
  if (!s) return "";
  const up = s.toUpperCase();
  if (Object.hasOwn(STATE_NAMES, up)) return up;
  const hit = Object.entries(STATE_NAMES).find(([, name]) => name.toLowerCase() === s.toLowerCase());
  return hit ? hit[0] : "";
}

/** "Colorado" from "CO", or "". */
export const stateName = (code) => (Object.hasOwn(STATE_NAMES, String(code ?? "")) ? STATE_NAMES[code] : "");

// ─── The record ──────────────────────────────────────────────────────────────

const blank = (v) => v === null || v === undefined || (typeof v === "string" && !v.trim());

/** Only the keys an email may fill for `section`, blanks dropped. */
export function emailFields(section, fields) {
  const out = {};
  for (const [k, v] of Object.entries(fields && typeof fields === "object" ? fields : {})) {
    if (k === "statusSource" ? !SOURCE_SECTIONS.has(section) : !fieldKind(section, k)) continue;
    if (blank(v)) continue;
    out[k] = v;
  }
  return out;
}

/**
 * The record to add, as the app's own add stores it (AppContext addItem runs
 * it through prepareRecord, which this matches): the section's type default
 * for a NOT NULL column the email left empty, an active lifecycle on a
 * licence, privilege or policy, and nothing that is not a column. email-
 * inbound adds user_id, created_at and updated_at; the app's sync layer adds
 * the same three.
 */
export function recordFromFields(section, fields, { id } = {}) {
  const f = emailFields(section, fields);
  const record = { ...(TYPE_DEFAULTS[section] || {}), ...f, id };
  if (section === "cme" && record.hours !== undefined) {
    const n = Number(record.hours);
    if (Number.isFinite(n)) record.hours = n; else delete record.hours;
  }
  if (SOURCE_SECTIONS.has(section)) {
    record.lifecycleStatus = "active";
    record.dateUnknown = false;
    if (!("statusSource" in record)) record.statusSource = null;
  }
  return normalizeLifecycle(section, record);
}

// ─── Is it on file already? ──────────────────────────────────────────────────

const NOISE = new Set(["the", "inc", "llc", "llp", "pc", "pllc", "pa", "corp", "corporation", "co", "company", "ltd", "of", "and", "group"]);
const words = (v) => String(v ?? "").toLowerCase().normalize("NFKD").replace(/\p{M}/gu, "")
  .replace(/\([^)]*\)/g, " ").replace(/[^a-z0-9]+/g, " ").split(" ").filter((w) => w && !NOISE.has(w));
/** "Quillfeather Staffing (through its insurer)" -> "quillfeather staffing". */
export const nameKey = (v) => words(v).join(" ");
const sameName = (a, b) => {
  const x = nameKey(a), y = nameKey(b);
  if (!x || !y) return false;
  if (x === y) return true;
  // One name written out inside the other, as whole words, two words or more:
  // "Quillfeather Staffing" and "Quillfeather Staffing Services".
  const [short, long] = x.length <= y.length ? [x, y] : [y, x];
  return short.split(" ").length >= 2 && ` ${long} `.includes(` ${short} `);
};
const sameAmount = (a, b) => { const x = amountValue(a), y = amountValue(b); return !!x && x === y; };
const sameText = (a, b) => nameKey(a) !== "" && nameKey(a) === nameKey(b);
const sameDay = (a, b) => !!a && !!b && String(a).slice(0, 10) === String(b).slice(0, 10);

/**
 * The record on file (camelCase rows) that these fields are about, or null.
 *   insurance     the same carrier or agency and the same limits; with no
 *                 limits read, the same carrier and the same type
 *   privileges    the same facility (and no other state)
 *   licenses      the same type in the same state (the same name when
 *                 neither has a state)
 *   cme           the same title on the same date
 *   locumContracts  never by its fields: only a record the reading named
 */
export function matchRecord(section, fields, rows) {
  const f = fields || {};
  const list = (Array.isArray(rows) ? rows : []).filter((r) => r && typeof r === "object" && r.id);
  const hit = (pred) => list.find(pred) || null;
  switch (section) {
    case "insurance": {
      const limits = !blank(f.coveragePerClaim) || !blank(f.coverageAggregate);
      return hit((r) => sameName(f.provider || f.name, r.provider || r.name)
        && (limits
          ? (blank(f.coveragePerClaim) || sameAmount(f.coveragePerClaim, r.coveragePerClaim))
            && (blank(f.coverageAggregate) || sameAmount(f.coverageAggregate, r.coverageAggregate))
          : sameText(f.type, r.type)));
    }
    case "privileges":
      return hit((r) => sameName(f.facility, r.facility) && (blank(f.state) || blank(r.state) || stateCode(f.state) === stateCode(r.state)));
    case "licenses":
      return hit((r) => sameText(f.type, r.type)
        && (blank(f.state) && blank(r.state) ? sameText(f.name, r.name) : stateCode(f.state) !== "" && stateCode(f.state) === stateCode(r.state)));
    case "cme":
      return hit((r) => sameText(f.title, r.title) && sameDay(f.date, r.date));
    default:
      return null;
  }
}

// A note's own "Source: ..." line names when it was read, not what it says:
// the same letter forwarded twice must not append its note twice.
const noteBody = (s) => String(s ?? "").split("\n").filter((l) => !/^\s*\(?source:/i.test(l)).join(" ")
  .toLowerCase().replace(/[^a-z0-9$]+/g, " ").trim();

/**
 * What these fields add to `existing` (a camelCase record): every empty
 * field filled, the note appended when the record's notes do not already
 * say it, and nothing already there changed. An expiration on file is never
 * moved: a misread date that extends a licence switches off its reminder.
 * Returns { changes, keys } (camelCase; keys is what changed).
 */
export function appendChanges(section, existing, fields) {
  const ex = existing || {};
  const f = emailFields(section, fields);
  const changes = {};
  for (const [k, v] of Object.entries(f)) {
    if (k === "notes") continue;
    if (blank(ex[k])) changes[k] = k === "hours" ? Number(v) : v;
  }
  if (!blank(f.notes)) {
    const was = String(ex.notes ?? "").trim();
    if (!was) changes.notes = f.notes;
    else if (!noteBody(was).includes(noteBody(f.notes))) changes.notes = `${was}\n\n${f.notes}`;
  }
  return { changes, keys: Object.keys(changes) };
}

// ─── What the physician reads ────────────────────────────────────────────────

/** One field as a line: "Per claim: $1,000,000". */
export function fieldLine(key, value) {
  const label = FIELD_LABEL[key] || key;
  if (key === "coveragePerClaim" || key === "coverageAggregate") return `${label}: ${dollars(value)}`;
  if (/Date$/.test(key) || key === "date") return `${label}: ${usDate(String(value ?? ""))}`;
  return `${label}: ${String(value ?? "")}`;
}

/** The record in a few words: "Insurance: Quillfeather Staffing (through its insurer), $1,000,000 per claim, $3,000,000 aggregate". */
export function recordSummary(section, fields) {
  const f = fields || {};
  const parts = [];
  switch (section) {
    case "insurance":
      parts.push(f.provider || f.name || f.type || "Policy");
      if (!blank(f.coveragePerClaim)) parts.push(`${dollars(f.coveragePerClaim)} per claim`);
      if (!blank(f.coverageAggregate)) parts.push(`${dollars(f.coverageAggregate)} aggregate`);
      if (validIsoDate(f.effectiveDate)) parts.push(`effective ${usDate(f.effectiveDate)}`);
      if (validIsoDate(f.expirationDate)) parts.push(`expires ${usDate(f.expirationDate)}`);
      break;
    case "privileges":
      parts.push([f.facility || f.name || "Privileges", f.type].filter(Boolean).join(", "));
      if (validIsoDate(f.expirationDate)) parts.push(`through ${usDate(f.expirationDate)}`);
      break;
    case "licenses":
      parts.push([f.type || f.name || "License", stateCode(f.state)].filter(Boolean).join(", "));
      if (validIsoDate(f.expirationDate)) parts.push(`expires ${usDate(f.expirationDate)}`);
      break;
    case "cme":
      parts.push(f.title || "CME");
      if (!blank(f.hours)) parts.push(`${f.hours} hours`);
      if (validIsoDate(f.date)) parts.push(usDate(f.date));
      break;
    default:
      parts.push("a note");
  }
  return `${SECTION_LABEL[section] || "Record"}: ${parts.filter(Boolean).join(", ")}`.replace(/\s*[\u2013\u2014]\s*/g, ", ");
}
