// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/outgoingText.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
/**
 * The last check on text that leaves the app: a share, an email, a text
 * message, a support ticket, an error report.
 *
 * CredentialDOMD keeps no Social Security numbers outside the encrypted,
 * device-only Protected Identity section, and nothing is meant to send one.
 * But a number typed into a note, a Travel & IDs "Number" field or a message
 * goes wherever that text goes. Anything shaped like an SSN is replaced
 * before it is handed to the share sheet, the mail app, the SMS app or the
 * server. Copying an SSN on purpose from Protected Identity does not pass
 * through here.
 *
 * Pure and dependency-free: the error reporter imports it, and that module
 * must work when everything else is broken.
 */

const DASHES = "\\-\u{2010}-\u{2015}";
// Three digit groups split by a space, dot or dash: 123-45-6789, 123 45 6789,
// 123.45.6789. A phone number (3-3-4) and a date (4-2-2) do not match.
const SSN_GROUPED = new RegExp(`(?<![\\d${DASHES}])\\d{3}[\\s.${DASHES}]\\d{2}[\\s.${DASHES}]\\d{4}(?![\\d${DASHES}])`, "g");
// Nine digits in a row only when an SSN word sits right before them: a bare
// nine-digit run is also a policy, badge or licence number.
const SSN_LABELLED = /\b(ssn|s\.s\.n\.?|ss\s*#|soc(?:ial)?\.?\s*sec(?:urity)?(?:\s*(?:no\.?|number|#))?|tin|taxpayer\s+id(?:entification)?(?:\s+(?:no\.?|number))?)(\s*[:#]?\s*)\d{9}(?!\d)/gi;

export const SSN_REMOVED = "[SSN removed]";

/** Whether the text holds anything shaped like a Social Security number. */
export function hasSsnShape(text) {
  const s = String(text ?? "");
  SSN_GROUPED.lastIndex = 0; SSN_LABELLED.lastIndex = 0;
  const found = SSN_GROUPED.test(s) || SSN_LABELLED.test(s);
  SSN_GROUPED.lastIndex = 0; SSN_LABELLED.lastIndex = 0;
  return found;
}

/** The text with every SSN-shaped value replaced. Anything else is untouched. */
export function scrubSsn(text) {
  if (text == null) return text;
  return String(text)
    .replace(SSN_LABELLED, (_m, word, gap) => `${word}${gap}${SSN_REMOVED}`)
    .replace(SSN_GROUPED, SSN_REMOVED);
}

// Outgoing text never carries an em dash (ticket 821d2f76). On-screen labels
// from describeItem join their parts with one, and an LLM-written cover note
// can carry them anywhere. A dash that opens a line is dropped, one right
// before punctuation or at a line's end is dropped, and one between words
// becomes a comma. Line breaks are kept; en dashes (ranges) are untouched.
// Lives here rather than in helpers.js so the invoice email the server sends
// (src/utils/invoiceEmail.js, copied to the edge) applies the same rule.
export function plainDashes(text) {
  return String(text ?? "")
    .replace(/^[ \t]*\u{2014}[ \t]*/gmu, "")
    .replace(/[ \t]*\u{2014}[ \t]*(?=[,.;:!?)]|$)/gmu, "")
    .replace(/[ \t]*\u{2014}[ \t]*/gu, ", ");
}

/**
 * Whether the last word of a name (after `sep`, a comma or a space) is the
 * degree itself rather than part of the name. After a comma it always is.
 * After a space it is when it is written exactly as the degree (dots aside:
 * "md" with "md", "D.O." with "DO"), or when it is not shaped like an
 * ordinary word, one capital then small letters ("PhD", "PA-C", "MBChB",
 * "MD", "D.O."). "Do" with DO is shaped like a surname and differs in case,
 * so it stays part of the name.
 */
function tailIsDegree(sep, word, degree) {
  const bare = (s) => s.replace(/\./g, "");
  return sep.startsWith(",") || bare(word) === bare(degree) || !/^[A-Z]?[a-z]+$/.test(word);
}

/**
 * "Jordan Rivera, DO" from a name and a degree, without printing the degree
 * twice when the name already ends with it ("Jordan Rivera, DO" or "Jordan
 * Rivera DO" typed into the name field, as the license-name prompt invites).
 * Dots and case are ignored when comparing, so "D.O." matches "DO". Whether
 * the last word is the degree at all follows tailIsDegree, so a surname that
 * spells a degree ("Ann Do" with DO) still gets its degree: "Ann Do, DO",
 * while "Casey Example PhD" with PhD reads once. "" with no name.
 */
export function withDegree(name, degree) {
  const n = String(name ?? "").replace(/\s+/g, " ").trim();
  const d = String(degree ?? "").replace(/\s+/g, " ").trim();
  if (!n) return "";
  if (!d) return n;
  const key = (s) => s.replace(/\./g, "").toLowerCase();
  const m = n.match(/(,\s*|\s)([^\s,]+)$/);
  return m && key(m[2]) === key(d) && tailIsDegree(m[1], m[2], d) ? n : `${n}, ${d}`;
}

/**
 * A name a caller already joined to its degree, with a degree printed twice
 * collapsed to one: "Jordan Rivera, DO, DO" or "Jordan Rivera DO, DO" (a
 * name typed with its degree, then ", DO" appended by a send site that does
 * not use withDegree) reads "Jordan Rivera, DO" / "Jordan Rivera DO". The
 * word before the appended degree is split off the way withDegree reads a
 * name (on spaces or commas). A comma-separated word is a degree as typed;
 * a space-separated one counts on withDegree's rule (tailIsDegree), so a
 * surname that happens to spell one ("Ann Do, DO") is left alone while
 * "Casey Example PhD, PhD" and "Pat Sample PA-C, PA-C" read once. Dots and
 * case are ignored when comparing ("D.O., DO").
 */
export function oneDegree(name) {
  const n = String(name ?? "").replace(/\s+/g, " ").trim();
  const m = n.match(/^(.*\S),\s*([A-Za-z][A-Za-z.-]{0,9})$/);
  if (!m) return n;
  const prev = m[1].match(/(,\s*|\s)([A-Za-z][A-Za-z.-]{0,9})$/);
  if (!prev) return n;
  const key = (s) => s.replace(/\./g, "").toLowerCase();
  return key(prev[2]) === key(m[2]) && tailIsDegree(prev[1], prev[2], m[2]) ? m[1] : n;
}
