// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/scannerCore.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
// The document scanner's pure half: the prompt, the request it rides in, and
// the checks every reply passes before anything is filed.
//
// Two callers read documents with it. The app (src/utils/documentScanner.js)
// sends a physician's upload through geminiCall, and the email-inbound edge
// function sends an attachment that arrived at docs@ or cme@ through the
// shared key. One prompt and one validator for both, so a certificate is read
// the same way however it arrived. The edge function cannot import from src/,
// so scripts/sync-shared-app-modules.mjs copies this file (and everything it
// imports) under supabase/functions/_shared/app/, and
// scripts/shared-app-modules.test.mjs fails when a copy drifts from here.
//
// Pure: no network, no DOM, no clock. Every import is a relative path with its
// extension, which is what Deno needs.

import { geminiJsonConfig, geminiResponseText } from "./geminiModel.js";
import { normalizeScanDates } from "./scanDates.js";
import { RECEIPT_DOC_TYPE, RECEIPT_CATEGORIES, normalizeReceipt } from "./receiptScan.js";

// "cv" is a CLASSIFICATION only. A CV holds many records across many
// sections and this pipeline returns one record for one section, so a cv
// result is never filed here: it is handed to the CV import
// (src/utils/cvScan.js) instead. Deliberately absent from SECTION_META and
// FIELD_DEFS for the same reason.
export const VALID_DOC_TYPES = ["license", "cme", "privilege", "insurance", "healthRecord", "education", "agreement", "travel", RECEIPT_DOC_TYPE, "cv", "other", "unknown"];

// A physician's own document that fits no built-in type. It is filed into one
// of their own categories (custom_records) rather than dropped. See
// src/utils/customCategories.js.
export const OTHER_DOC_TYPE = "other";

export const CV_DOC_TYPE = "cv";


// Category names are the physician's own text and go into a prompt, so they
// are capped and stripped of anything that could read as markup or quotes.
export function categoryHints(categories) {
  return (Array.isArray(categories) ? categories : [])
    .map(c => String(typeof c === "string" ? c : c?.name || "").replace(/["`{}<>\\]/g, "").replace(/\s+/g, " ").trim().slice(0, 60))
    .filter(Boolean).slice(0, 30);
}

export function normalizeOther(extracted) {
  const e = extracted && typeof extracted === "object" && !Array.isArray(extracted) ? { ...extracted } : {};
  const facts = Array.isArray(e.facts) ? e.facts : [];
  e.facts = facts
    .filter(f => f && typeof f === "object" && f.label != null && f.value != null && String(f.value).trim() !== "")
    .slice(0, 200)
    .map(f => ({ label: String(f.label).slice(0, 80), value: typeof f.value === "string" ? f.value : JSON.stringify(f.value) }));
  const sc = e.suggestedCategory && typeof e.suggestedCategory === "object" ? e.suggestedCategory : {};
  e.suggestedCategory = {
    name: String(sc.name || "").slice(0, 80),
    icon: String(sc.icon || "").slice(0, 8),
    fields: (Array.isArray(sc.fields) ? sc.fields : []).map(x => String(typeof x === "string" ? x : x?.label || "")).filter(Boolean).slice(0, 12),
  };
  return e;
}

export function validateResponse(parsed) {
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return null;
  // A type string the model invented used to throw "could not identify", and
  // everything it had read was lost. Keep what it read, as an "other" document
  // the physician files into one of their own categories.
  if (!VALID_DOC_TYPES.includes(parsed.documentType)) {
    if (typeof parsed.documentType !== "string" || !parsed.extracted || typeof parsed.extracted !== "object") return null;
    const invented = parsed.documentType;
    parsed.documentType = OTHER_DOC_TYPE;
    const ex = parsed.extracted;
    const KEEP = ["name", "issuer", "number", "issuedDate", "expirationDate"];
    const human = (k) => String(k).replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[_-]+/g, " ").replace(/^./, c => c.toUpperCase());
    // MOVE every other field into facts (never copy it): each value appears
    // once, under a readable label the identifier gate can recognise.
    const kept = Object.fromEntries(KEEP.filter(k => ex[k] != null && ex[k] !== "").map(k => [k, ex[k]]));
    parsed.extracted = { ...kept, facts: [...(Array.isArray(ex.facts) ? ex.facts : []),
      ...Object.entries(ex).filter(([k, v]) => !["facts", "suggestedCategory", ...KEEP].includes(k) && v != null && v !== "" && typeof v !== "object")
        .map(([k, v]) => ({ label: human(k), value: String(v) }))],
      suggestedCategory: ex.suggestedCategory || { name: invented } };
  }
  if (parsed.extracted && typeof parsed.extracted !== "object") return null;
  if (parsed.confidence && !["high", "medium", "low"].includes(parsed.confidence)) {
    parsed.confidence = "low";
  }
  // A receipt's fields feed money rows, so they are cleaned here once
  // (amount, ISO date, currency code, card last-4, a category from our list)
  // rather than trusting the model's formatting.
  if (parsed.documentType === RECEIPT_DOC_TYPE) parsed.extracted = normalizeReceipt(parsed.extracted);
  if (parsed.documentType === OTHER_DOC_TYPE) parsed.extracted = normalizeOther(parsed.extracted);
  parsed.extracted = normalizeScanDates(parsed.extracted);
  return parsed;
}

export function parseModelJson(data) {
  const text = geminiResponseText(data);
  const clean = text.replace(/```json|```/g, "").trim();
  return JSON.parse(clean);
}

export const SYSTEM_PROMPT = (degreeType, categories = []) => `You are a medical credential document analyzer. Given an image of a document a physician uploaded (a credential, or an expense receipt from their work travel), you must:
1. Classify the document type
2. Extract all relevant fields
3. Return ONLY valid JSON (no markdown, no backticks, no explanation)

Document types and their fields:
- "license": Any license, registration, certification, or permit. This includes state medical licenses, DEA, board certifications, BLS/ACLS/ATLS, and vendor/device or procedure training certificates (e.g. Globus, Medtronic, Stryker course-completion or product-training certificates) that do NOT carry CME credit hours.
  Fields: type (MUST be one of the exact values listed below), name (display name), licenseNumber, state (2-letter), issuedDate (YYYY-MM-DD), expirationDate (YYYY-MM-DD)
  REQUIRED "type" values — use EXACTLY one of these strings:
${degreeType === "DO" ? `    "State Medical License (DO)", "State Medical License (MD-equiv)", "DEA Registration", "State Controlled Substance", "Board Certification (AOA)", "Board Certification (ABMS)", "COMLEX", "USMLE", "BLS Certification", "ACLS Certification", "ATLS Certification", "Fluoroscopy Permit", "Laser Safety Certificate", "Certification", "Other"` : `    "State Medical License", "DEA Registration", "State Controlled Substance", "Board Certification (ABMS)", "ECFMG Certificate", "USMLE", "BLS Certification", "ACLS Certification", "ATLS Certification", "Fluoroscopy Permit", "Laser Safety Certificate", "Certification", "Other"`}
- "cme": CME certificate, continuing education credit, conference attendance — ONLY use this type if the document contains EXPLICIT credit-designation language (e.g. "designates this activity for a maximum of X AMA PRA Category 1 Credit(s)", an AOA Category 1-A/1-B/2-A/2-B statement, or an equivalent accredited CME/CE credit-hour statement). A vendor/device/procedure training or course-completion certificate that has NO credit-hour designation statement is "license" with type "Certification", NOT "cme" — do not classify as "cme" just because the document looks like a certificate or award.
  Fields: title, category (MUST be EXACTLY one of: ${degreeType === "DO" ? '"AOA Category 1-A", "AOA Category 1-B", "AOA Category 2-A", "AOA Category 2-B", "AMA PRA Category 1"' : '"AMA PRA Category 1", "AMA PRA Category 2"'} — read the certificate's credit designation statement; AMA PRA Category 1 Credit(s) is the most common), hours (number), date (YYYY-MM-DD), provider, certificateNumber, topics (array — ONLY values from this list that the activity content clearly covers: "Pain Management", "Opioid Prescribing", "Controlled Substances", "Ethics", "Infection Control", "Patient Safety", "Medical Errors Prevention", "Risk Management", "Suicide Prevention", "Cultural Competency", "Implicit Bias", "End-of-Life Care", "Geriatric Medicine", "Domestic Violence", "Child Abuse Recognition", "Human Trafficking", "Pharmacology", "Telemedicine", "Sexual Harassment Prevention", "HIV/AIDS", "Palliative Care", "Mental Health", "Substance Use Disorders", "Prescriptive Practice", "Trauma-Informed Care"; use [] if none apply — these tags satisfy state CME mandates, so only tag what the certificate actually covers)
  READING A FILL-IN CERTIFICATE. The standard ACCME template prints a sentence with ruled blanks and puts the answers ON the blanks, so the words and the values interleave. Read the ANSWER, not the label:
    * "has participated in the ____ titled ____" gives the ACTIVITY FORMAT on the first blank (Live activity, Enduring material, Journal-based CME) and the TITLE on the second. The title is the second blank. Never return "Live activity" or "Enduring material" as the title; that is the format, and it belongs in notes if anywhere.
    * "and is awarded ____ AMA PRA Category 1 Credit(s)" gives HOURS on the blank. The number sits to the LEFT of the credit wording and belongs to it.
    * "Date of Completion: ____" is the date field. Use it even when the title itself names other dates.
  A title often contains the meeting's own dates and city ("CICT 2026 held on June 24-25 in Newport Beach, CA"). Keep them in the title verbatim and do NOT use them as the completion date.
  TWO-DIGIT YEARS. A date written 07/25/26 is MM/DD/YY: return 2026-07-25. Read 00 to 79 as 2000 to 2079 and 80 to 99 as 1980 to 1999. Never emit a year like 0026.
  PROVIDER is the organisation that issued and is accredited for the activity, usually in the letterhead or logo and repeated in the accreditation sentence ("CMEsolutions, LLC" from "CMEsolutions is accredited by the ACCME"). It is never "ACCME" or "AMA": those accredit the provider, they do not run the activity.
- "privilege": Hospital privilege letter, appointment letter, credentialing approval
  Fields: type, name, facility, state (2-letter), appointmentDate (YYYY-MM-DD), expirationDate (YYYY-MM-DD)
- "insurance": Malpractice/liability insurance certificate, policy declaration, coverage summary, or a wallet-style proof-of-insurance/ID card issued by the carrier
  Fields: type, name, provider, policyNumber, coveragePerClaim, coverageAggregate, effectiveDate (YYYY-MM-DD), expirationDate (YYYY-MM-DD)
- "healthRecord": Vaccination card/record, TB test result, fit test certificate, immunization record, titer result
  Fields: category (MUST be exactly "Vaccination", "TB Test", or "Fit Test"), type (specific vaccine/test name), name (display name), dateAdministered (YYYY-MM-DD — use MOST RECENT dose date for multi-dose vaccines), expirationDate (YYYY-MM-DD — ONLY for TB tests and fit tests that have a true expiration; do NOT set for vaccinations), result (for TB tests: "Negative"/"Positive"/"Indeterminate"), lotNumber (from most recent dose), facility (from most recent dose)
  IMPORTANT for vaccinations: Do NOT put vaccine vial expiration dates ("Exp" printed on vial labels) into expirationDate. Vial expiration is NOT the vaccination record's expiration. Most vaccinations do not expire — omit expirationDate for vaccinations entirely.
  For multi-dose vaccines (COVID-19, Hepatitis B, etc.): ALSO include a "doses" array with ALL doses visible on the card. Each dose object: { doseNumber: 1, date: "YYYY-MM-DD", manufacturer: "...", lotNumber: "...", facility: "..." }. Extract EVERY dose shown — read all handwritten entries carefully. The main dateAdministered/lotNumber/facility fields should reflect the MOST RECENT dose.
  Vaccination types: "Hepatitis B", "MMR (Measles, Mumps, Rubella)", "Varicella (Chickenpox)", "Influenza (Flu)", "COVID-19", "Tdap (Tetanus, Diphtheria, Pertussis)", "Meningococcal", "Polio (IPV)", "Hepatitis A", "HPV", "Other"
  TB Test types: "PPD/TST (Skin Test)", "QuantiFERON-TB Gold", "T-SPOT.TB", "Chest X-Ray", "Other"
  Fit Test types: "N95 Respirator", "PAPR (Powered Air-Purifying)", "Half-Face Respirator", "Full-Face Respirator", "Other"
- "education": Diploma, degree certificate, graduation certificate, fellowship completion, residency completion, training certificate
  Fields: type (MUST be one of: "Doctor of Osteopathic Medicine (DO)", "Doctor of Medicine (MD)", "Bachelor of Science (BS)", "Bachelor of Arts (BA)", "Master of Science (MS)", "Master of Public Health (MPH)", "Fellowship Certificate", "Residency Certificate", "Internship Certificate", "Other"), name (display name, e.g. "DO Diploma - PCOM"), institution (school/program name), graduationDate (YYYY-MM-DD), fieldOfStudy (specialty or major), honors (e.g. "Cum Laude")
  IMPORTANT: Diplomas and degrees do NOT expire. Do NOT put the graduation date in expirationDate. Use the graduationDate field instead.
- "agreement": Locum tenens agreement, physician services agreement, independent contractor agreement, employment/coverage contract with a hospital or staffing agency
  Fields: facility (hospital/practice the physician works AT), location (facility city and state, e.g. "Lafayette, CO"), agency (staffing agency if any), billTo (billing/AP email if listed), startDate (YYYY-MM-DD, earliest coverage start), endDate (YYYY-MM-DD, latest coverage end), coveragePeriods (array — one {"start":"YYYY-MM-DD","end":"YYYY-MM-DD"} object for EVERY separate scheduled coverage block or date range in the agreement, e.g. [{"start":"2026-07-28","end":"2026-08-10"},{"start":"2026-09-14","end":"2026-09-21"}]; a single continuous assignment is one entry), hourlyRate (number, $/hr for regular non-call work), callStipend (number — flat amount per on-call day, e.g. "$3000 for the first 4 hours" -> 3000), stipendHours (number of hours the stipend covers, e.g. 4), overageHourlyRate (number, $/hr for call time BEYOND the stipend hours), callHourlyRate (number, only if flat hourly call pay with no stipend), orientationFee (number, one-time orientation payment — CHECK CAREFULLY: orientation/onboarding/EMR-training compensation is often buried in a rate schedule, fee table, exhibit, or addendum near the END of the agreement; phrases include "orientation", "onboarding", "EMR training", "credentialing day". If orientation is a flat amount, put it here. If orientation is paid HOURLY, put the hourly dollar rate in orientationHourlyRate instead), orientationHourlyRate (number, $/hr for orientation/onboarding time when paid hourly), incrementMinutes (billing increment if stated, e.g. 15), minCallMinutes (minimum billable minutes per call if stated), notes (1-2 sentence summary of other key terms, INCLUDING any orientation pay arrangement not captured above). Numbers must be plain numbers without $ or commas. Read ALL pages including exhibits and rate schedules before answering.
- "travel": Government ID or travel document — driver's license (INCLUDING a notarized copy of one), passport, Global Entry or Known Traveler card, TSA PreCheck, REAL ID, visa, or an airline/hotel/rental membership card. Credentialing packets often include notarized ID copies — a notary stamp on a driver's license or passport copy still means "travel", never "unknown".
  Fields: type (MUST be one of: "Driver\u2019s License", "Passport", "Known Traveler (TSA PreCheck)", "Global Entry", "Visa", "Airline loyalty", "Hotel loyalty", "Rental car membership", "Other"), name (display label, e.g. "CA Driver's License — notarized copy"), provider (issuing state, country, or company), number (document or membership number), expirationDate (YYYY-MM-DD), notes (e.g. "notarized copy, notarized 2026-07-30")
- "receipt": An expense receipt, invoice, folio, or charge slip for money the physician paid: tolls (INCLUDING toll, PlatePass, TollPass or e-Toll charges billed by a rental car company such as Alamo, Hertz, Avis, Enterprise, National or Budget), rental car, fuel, rideshare or taxi, airfare or baggage fees, hotel or lodging, parking, meals; also licensing or registration fees, CME or conference registration, society dues, supplies, or software the physician paid for. A printed or emailed receipt, a phone screenshot of one, and a rental "toll administration" statement are all "receipt". A receipt is NEVER "license", "agreement", or "cme" even when it names the physician or a course.
  Fields: merchant (the business paid, cleaned: "Alamo Rent A Car", not a card-processor prefix), date (YYYY-MM-DD transaction date; for a multi-day rental or hotel stay use the return / checkout date), total (number, the grand total actually paid including tax, fees and tip; plain number, no $ or commas), currency (ISO 4217 code such as "USD"; assume USD when only a $ sign is shown), category (MUST be exactly one of: ${RECEIPT_CATEGORIES.map(c => `"${c}"`).join(", ")}; toll charges on a rental car invoice are "Tolls", not "Rental car"), last4 (the last four digits of the card if printed, e.g. "4321"), paymentMethod (card brand or method if printed: "Visa", "Mastercard", "Amex", "Discover", "Debit", "Cash"), description (short: what was bought, e.g. "Toll charges, Denver rental Aug 12-15"), notes
- "other": a physician's OWN document that is none of the types above: e.g. a hospital ID badge, an award or honor, a parking or facility access permit, a vendor or badge-access credentialing registration, a radiation dosimetry report. NEVER use "other" when the document is any type listed above: a board certification, DEA or BLS is still "license"; a vendor, device, procedure or course-completion certificate without CME credit is still "license" with type "Certification"; a fellowship, residency or internship certificate is still "education"; a titer or drug screen is still "healthRecord".
  Fields: name (display label of the item, never a person's name), issuer, number, issuedDate (YYYY-MM-DD), expirationDate (YYYY-MM-DD),
  suggestedCategory: { name (a PLURAL, reusable kind of document, e.g. "Hospital ID Badges"; if one of the physician's existing categories listed below fits, return ITS EXACT NAME), icon (one emoji), fields (array of 2 to 8 labels for facts that recur on this kind of document) },
  facts: array of { label, value } for EVERY other data point printed on it, so nothing is lost. Repeat a label when the document repeats it.
  NEVER include a patient's name, MRN, medical record number, diagnosis or date of birth, and never the physician's Social Security number, full date of birth, or any account number. Leave those out entirely.
- "unknown": Cannot determine document type

The physician is ${degreeType === "DO" ? "a DO (Doctor of Osteopathic Medicine)" : degreeType === "MD" ? "an MD" : "an MD or DO (degree not yet specified in their profile; classify from the document itself)"}.
Return JSON: { "documentType": "...", "confidence": "high"|"medium"|"low", "extracted": { ...fields }, "notes": "..." }
Use YYYY-MM-DD dates. Omit fields that are not visible. Use 2-letter state abbreviations.
If the document is a curriculum vitae or resume (a multi-section document listing this physician's own education, training, positions, licenses, publications and memberships), classify it as "cv", extract NOTHING, and return { "documentType": "cv", "confidence": "high", "extracted": {}, "notes": "" }. It is read elsewhere.
${categories.length ? `The physician's existing categories (reuse one for an "other" document when it fits): ${categories.map(c => `"${c}"`).join(", ")}.\n` : ""}IMPORTANT: the "name" field is a DISPLAY LABEL describing the credential itself (e.g. "CO Medical License", "DEA Registration", "MMR Vaccination", "DO Diploma - PCOM") — NEVER the physician's own name. Do not put a person's name in "name".`;

// What the model is told alongside the file. Kept word for word from the
// analyzers that used to spell them out inline.
export const SCAN_IMAGE_TEXT = "Analyze this document (a medical credential or an expense receipt). Return only JSON.";
export const scanPdfText = (degreeType) => `Analyze this document (a medical credential or an expense receipt)${degreeType ? ` for a ${degreeType}` : ""}. Return ONLY JSON.`;

/**
 * The generateContent body for one credential scan. `parts` is the file (an
 * inlineData part, or the extracted text) followed by the instruction text.
 * @param {{ degreeType?: string, categories?: Array<string | { name?: string }>, parts: object[] }} input
 */
export function scanRequestBody({ degreeType, categories = [], parts }) {
  return {
    systemInstruction: { parts: [{ text: SYSTEM_PROMPT(degreeType, categoryHints(categories)) }] },
    contents: [{ parts }],
    generationConfig: geminiJsonConfig(8192),
  };
}
