// GENERATED by scripts/sync-shared-app-modules.mjs from src/utils/scanSplit.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
// What a scan read, split into what a record can hold and what it cannot.
//
// Pure, and imported by two very different callers: the app (DocAttach, the
// credential forms, via docPrefill.js) and the email-inbound edge function,
// which files a forwarded document with the same rules. The edge function
// cannot import from src/, so scripts/sync-shared-app-modules.mjs copies this
// file under supabase/functions/_shared/app/ and
// scripts/shared-app-modules.test.mjs fails when the copy drifts. Every import
// is a relative path with its extension.

import { identifierReason, sanitizeText } from "./customCategories.js";

const isBlank = (v) => v == null || v === "" || (Array.isArray(v) && v.length === 0);

/**
 * Merge analyzer output into form state: fill blanks only, never overwrite a
 * value the physician already typed. An empty array counts as blank, so a
 * form that opens with coveragePeriods: [] still takes the contract's dates.
 */
export function mergeExtracted(prev, extracted) {
  const merged = { ...(prev || {}) };
  if (!extracted || typeof extracted !== "object" || Array.isArray(extracted)) return merged;
  for (const [k, v] of Object.entries(extracted)) {
    if (!isBlank(v) && isBlank(merged[k])) merged[k] = v;
  }
  return merged;
}

const humanLabel = (k) => String(k).replace(/([a-z])([A-Z])/g, "$1 $2").replace(/[_-]+/g, " ").replace(/^./, c => c.toUpperCase());

/**
 * Split what a scan read into what the form can hold and what it cannot.
 *
 * A form writes every key it holds as a database column, and one key the table
 * does not have rejects the WHOLE record, which then lives on one device only.
 * That already happened: travel_docs has no country or state column, so a
 * scanned passport put those in the form and the record never reached the
 * cloud. Keys outside `allowedKeys` go to customFields instead, which every
 * credential table has, so nothing is lost and nothing is rejected. An "other"
 * document's facts are flattened the same way, and its suggested category is
 * dropped: that belongs to the uploader, not to a form.
 *
 * allowedKeys null means "this caller does not know its fields": then only the
 * keys that can never be columns (facts, suggestedCategory) are diverted.
 * Identifiers are withheld either way.
 */
export function splitScanned(extracted, allowedKeys = null) {
  const placed = {};
  const extras = {};
  const withheld = [];
  if (!extracted || typeof extracted !== "object" || Array.isArray(extracted)) return { placed, extras, withheld };
  const allowed = allowedKeys ? new Set(allowedKeys) : null;
  const putExtra = (label, value) => {
    const text = sanitizeText(Array.isArray(value) ? value.join(", ") : value);
    if (!text) return;
    const why = identifierReason(label, text);
    if (why) { withheld.push({ label: String(label), reason: why }); return; }
    const base = sanitizeText(label, 40) || "Detail";
    let k = base, n = 2;
    while (Object.hasOwn(extras, k)) k = `${base} (${n++})`;
    extras[k] = text;
  };
  for (const [k, v] of Object.entries(extracted)) {
    if (isBlank(v) || k === "suggestedCategory") continue;
    if (k === "facts" && Array.isArray(v)) {
      for (const f of v) if (f && typeof f === "object" && !isBlank(f.value)) putExtra(f.label, f.value);
      continue;
    }
    if (allowed === null || allowed.has(k)) {
      const why = typeof v === "string" ? identifierReason(k, v) : null;
      if (why) { withheld.push({ label: humanLabel(k), reason: why }); continue; }
      placed[k] = v;
    } else {
      putExtra(humanLabel(k), typeof v === "object" && !Array.isArray(v) ? JSON.stringify(v) : v);
    }
  }
  return { placed, extras, withheld };
}

/** mergeExtracted plus splitScanned: blanks-only fill, overflow to customFields. */
export function mergeScanned(prev, extracted, allowedKeys = null) {
  const { placed, extras, withheld } = splitScanned(extracted, allowedKeys);
  const merged = mergeExtracted(prev, placed);
  if (Object.keys(extras).length) {
    const current = merged.customFields && typeof merged.customFields === "object" ? merged.customFields : {};
    merged.customFields = { ...extras, ...current }; // never overwrite a detail already on the record
  }
  return { form: merged, extraCount: Object.keys(extras).length, withheld };
}
