// GENERATED by scripts/generate-assistant-sources.mjs. Dates are copied source metadata, not a live check.
export const ASSISTANT_SOURCES = {
  "reviewScope": "General physician CME resources and product guidance checked on this date. Individual course acceptance and every jurisdiction’s current rules have not been verified. Source checks are not regulatory approval.",
  "generalSources": [
    {
      "id": "accme-directory",
      "title": "ACCME: find an accredited provider",
      "url": "https://accme.org/cme-provider-directory/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "ama-credit",
      "title": "AMA PRA credit requirements",
      "url": "https://www.ama-assn.org/education/ama-pra-credit-system/ama-pra-credit-system-requirements",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "ama-designation",
      "title": "AMA: checking activity credit statements",
      "url": "https://www.ama-assn.org/education/ama-pra-credit-system/how-decipher-cme-requirements",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "passport-search",
      "title": "CME Passport activity search",
      "url": "https://www.cmepassport.org/activity/search",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "passport-about",
      "title": "ACCME: how CME Passport works",
      "url": "https://accme.org/for-physicians/about-cme-passport/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "accme-moc",
      "title": "ACCME: CME for maintenance of certification",
      "url": "https://accme.org/data-reporting/maintenance-of-certification/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "abms",
      "title": "ABMS continuing-certification standards",
      "url": "https://abms.org/board-certification-standards/standards-for-continuing-certification/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "aoa-policies",
      "title": "AOA CME policies: 2025–2027 cycle",
      "url": "https://osteopathic.org/cme/cme-policies/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "aoa-faqs",
      "title": "AOA CME questions and reporting",
      "url": "https://osteopathic.org/cme/cme-faqs/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "aoa-search",
      "title": "AOA CME resources and search",
      "url": "https://osteopathic.org/cme/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "dea-mate",
      "title": "DEA MATE training questions and answers",
      "url": "https://www.deadiversion.usdoj.gov/faq/MATE_Act_faq.html",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "samhsa-mate",
      "title": "SAMHSA MATE training resources",
      "url": "https://www.samhsa.gov/substance-use/treatment/resources/mat-act/training-requirements",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "samhsa-pcss",
      "title": "SAMHSA PCSS-MOUD training",
      "url": "https://www.samhsa.gov/technical-assistance/pcss/pcss-moud",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "cdc-train",
      "title": "CDC TRAIN: current learning platform",
      "url": "https://www.cdc.gov/cdc-train/about/index.html",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "cdc-credit",
      "title": "CDC continuing-education credit types",
      "url": "https://www.cdc.gov/continuing-education/php/types-of-ce/index.html",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "ama-edhub",
      "title": "AMA Ed Hub: access, costs and claiming credit",
      "url": "https://edhub.ama-assn.org/pages/help",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "fsmb",
      "title": "FSMB: find your licensing board",
      "url": "https://www.fsmb.org/contact-a-state-medical-board/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "product-help",
      "title": "CredentialDOMD product walkthroughs",
      "url": "https://credentialdomd.com/help/",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "ama-category-two",
      "title": "AMA: understanding Category 2 credit",
      "url": "https://www.ama-assn.org/education/ama-pra-credit-system/what-know-about-other-kind-cme-credit",
      "recordedReview": "2026-09-19"
    },
    {
      "id": "mate-statute",
      "title": "U.S. Code: DEA registration and training, section 823(m)",
      "url": "https://uscode.house.gov/view.xhtml?edition=prelim&path=%2Fprelim%40title21%2Fchapter13%2Fsubchapter1%2FpartC",
      "recordedReview": "2026-09-19"
    }
  ],
  "renewalSources": {
    "AL": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.albme.gov/licensing/md-do/licensing-md-do-license-renewals/"
        },
        {
          "url": "https://www.albme.gov/licensing/md-do/license-types/full-license/"
        },
        {
          "url": "https://www.albme.gov/uploads/forms/reinstatement_application.pdf"
        },
        {
          "url": "https://www.albme.gov/uploads/pdfs/2025V40No3.pdf"
        }
      ]
    },
    "AK": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.commerce.alaska.gov/web/portals/5/pub/med0077.pdf"
        },
        {
          "url": "https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/StateMedicalBoard/FrequentlyAskedQuestions.aspx"
        },
        {
          "url": "https://professionallicense.alaska.gov/MYLICENSE"
        }
      ]
    },
    "AZ": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://azmd.gov/Licensure/Licensure/md-renewal-application"
        },
        {
          "url": "https://azmbfileblob.blob.core.windows.net/azmd/MD_202603301613_f455c80601cf49a8b5d602993d6557ec.pdf"
        },
        {
          "url": "https://azdo.gov/licensure-compact/do-renewal-application"
        }
      ]
    },
    "AR": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://armedicalboard.adh.arkansas.gov/"
        },
        {
          "url": "https://armedicalboard.adh.arkansas.gov/Professionals/pdf/Fees.pdf"
        },
        {
          "url": "https://armedicalboard.adh.arkansas.gov/Professionals/pdf/MD_AppPack.pdf"
        },
        {
          "url": "https://armedicalboard.adh.arkansas.gov/faq.aspx?type=4"
        }
      ]
    },
    "CA": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.mbc.ca.gov/Licensing/Physicians-and-Surgeons/Renew/"
        },
        {
          "url": "https://www.mbc.ca.gov/Licensing/Physicians-and-Surgeons/Renew/Current-status/Fees.aspx"
        },
        {
          "url": "https://www.mbc.ca.gov/Licensing/Physicians-and-Surgeons/Renew/Current-Status/"
        },
        {
          "url": "https://www.ombc.ca.gov/forms_pubs/osp_lic_renapp.pdf"
        }
      ]
    },
    "CO": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://dpo.colorado.gov/Medical"
        },
        {
          "url": "https://dpo.colorado.gov/Medical/Applications"
        },
        {
          "url": "https://dpo.colorado.gov/Medical/DRLicenseRequirements"
        },
        {
          "url": "https://dpo.colorado.gov/FAQ"
        }
      ]
    },
    "CT": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://portal.ct.gov/dph/practitioner-licensing--investigations/physician/physician-licensure"
        },
        {
          "url": "https://portal.ct.gov/dph/practitioner-licensing--investigations/renewal/health-care-practitioner-renewal-information"
        },
        {
          "url": "https://portal.ct.gov/dph/practitioner-licensing--investigations/plis/online-renewals"
        },
        {
          "url": "https://portal.ct.gov/dph/practitioner-licensing--investigations/renewal/online-renewal-information"
        }
      ]
    },
    "DE": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://dpr.delaware.gov/boards/medicalpractice/renewal/"
        },
        {
          "url": "https://dpr.delaware.gov/boards/medicalpractice/fees/"
        },
        {
          "url": "https://dpr.delaware.gov/boards/medicalpractice/physician-m-d-or-d-o-reapplication/"
        },
        {
          "url": "https://dpr.delaware.gov/boards/medicalpractice/"
        }
      ]
    },
    "DC": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://dchealth.dc.gov/bomed"
        },
        {
          "url": "https://dchealth.dc.gov/service/physician-licensing"
        },
        {
          "url": "https://dchealth.dc.gov/service/medicine-fee-schedule"
        },
        {
          "url": "https://dcregs.dc.gov/Common/DCMR/RuleDetail.aspx?RuleId=R0054495"
        }
      ]
    },
    "FL": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://flboardofmedicine.gov/medical-doctor-renewal/"
        },
        {
          "url": "https://flboardofmedicine.gov/fees/"
        },
        {
          "url": "https://floridasosteopathicmedicine.gov/renewals/osteopathic-physician-renewal/"
        },
        {
          "url": "https://floridasosteopathicmedicine.gov/fees/"
        }
      ]
    },
    "GA": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://medicalboard.georgia.gov/licensure-information/physician"
        },
        {
          "url": "https://medicalboard.georgia.gov/licensure-information/fee-schedule"
        },
        {
          "url": "https://medicalboard.georgia.gov/licensure-information/apply-or-renew-online"
        },
        {
          "url": "https://rules.sos.ga.gov/gac/360-2"
        }
      ]
    },
    "HI": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://cca.hawaii.gov/pvl/boards/medical/"
        },
        {
          "url": "https://cca.hawaii.gov/pvl/mypvl-licensee-dashboard-manage-your-license-online/"
        },
        {
          "url": "https://cca.hawaii.gov/pvl/boards/medical/medical-continuing-education-and-random-audit-information/"
        }
      ]
    },
    "ID": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://dopl.idaho.gov/bom/"
        },
        {
          "url": "https://dopl.idaho.gov/wp-content/uploads/2024/12/Fee-Changes_Medicine.pdf"
        },
        {
          "url": "https://dopl.idaho.gov/pressrelease/big-changes-are-on-the-way-stay-informed-about-important-licensure-updates-that-may-impact-your-renewal-cycle-27/"
        },
        {
          "url": "https://dopl.idaho.gov/bom/bom-licensing/"
        }
      ]
    },
    "IL": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://idfpr.illinois.gov/profs/physicians.html"
        },
        {
          "url": "https://idfpr.illinois.gov/content/dam/soi/en/web/idfpr/forms/dpr/2026-07-21-physician-renewal-extension-variance.pdf"
        },
        {
          "url": "https://idfpr.illinois.gov/content/dam/soi/en/web/idfpr/forms/dpr/2026physicianbatchrenewal.pdf"
        },
        {
          "url": "https://ilga.gov/Legislation/ILCS/Articles?ActID=1309&ChapterID=24"
        }
      ]
    },
    "IN": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.in.gov/pla/professions/physicians-home/physicians-licensing-information/"
        },
        {
          "url": "https://www.in.gov/pla/professions/physicians-home/"
        },
        {
          "url": "https://www.in.gov/pla/files/Top-Ten-FAQs-for-Physician-License-Renewals-drafted-October-2023.pdf"
        }
      ]
    },
    "IA": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://dial.iowa.gov/about/boards/medicine"
        },
        {
          "url": "https://dial.iowa.gov/licenses/health-professions/physicians"
        },
        {
          "url": "https://dial.iowa.gov/about-dial/boards-and-commissions/board-medicine/online-services"
        },
        {
          "url": "https://www.legis.iowa.gov/docs/iac/rule/06-11-2025.481.652.12.pdf"
        }
      ]
    },
    "KS": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.ksbha.ks.gov/departments/licensing/renewal-dates"
        },
        {
          "url": "https://www.ksbha.ks.gov/departments/licensing/license-fees"
        },
        {
          "url": "https://www.ksbha.ks.gov/departments/licensing/licensing-faqs/doctor-of-medicine-and-surgery"
        },
        {
          "url": "https://www.ksbha.ks.gov/departments/licensing/licensing-faqs/doctor-of-osteopathic-medicine-and-surgery"
        }
      ]
    },
    "KY": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://kbml.ky.gov/physician/Pages/default.aspx"
        },
        {
          "url": "https://kbml.ky.gov/Documents/Board%20Fees.pdf"
        },
        {
          "url": "https://kbml.ky.gov/newsletter/Documents/2026-01%20Winter.pdf"
        },
        {
          "url": "https://services.kbml.ky.gov/ebusiness/Login.aspx?mode=login"
        }
      ]
    },
    "LA": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.lsbme.la.gov/content/renewals"
        },
        {
          "url": "https://www.lsbme.la.gov/application-instructions-for-reinstatement-physicians"
        },
        {
          "url": "https://www.lsbme.la.gov/content/application-instructions-initial-licensure-physicians"
        },
        {
          "url": "https://www.law.cornell.edu/regulations/louisiana/La-Admin-Code-tit-46-SS-XLV-415"
        }
      ]
    },
    "ME": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.maine.gov/md/licensure/license-faq"
        },
        {
          "url": "https://www.maine.gov/md/licensure/md-license"
        },
        {
          "url": "https://licensing.web.maine.gov/cgi-bin/online/licensing/begin.pl?board_number=376"
        },
        {
          "url": "https://www.maine.gov/osteo/home"
        }
      ]
    },
    "MD": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.mbp.state.md.us/forms/2026_renewal_info.pdf"
        },
        {
          "url": "https://www.mbp.state.md.us/licensure_phyrenewals.aspx"
        },
        {
          "url": "https://www.mbp.state.md.us/resource_information/faqs/resource_faqs_physician_renewals.aspx"
        },
        {
          "url": "https://www.mbp.state.md.us/mbp_reinstate/default.aspx"
        }
      ]
    },
    "MA": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.mass.gov/how-to/renew-my-physician-full-license"
        },
        {
          "url": "https://www.mass.gov/service-details/board-of-registration-in-medicine-schedule-of-fees"
        },
        {
          "url": "https://www.mass.gov/info-details/general-physician-licensing-questions"
        },
        {
          "url": "https://www.mass.gov/info-details/full-license-renewal-faqs"
        }
      ]
    },
    "MI": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/medical/medical-doctor-licensing-guides-and-faqs/md-licensing-guide-and-faqs"
        },
        {
          "url": "https://www.michigan.gov/lara/-/media/Project/Websites/lara/bpl/Osteopathic-Medicine/Licensing-Info-and-Forms/DO-Licensing-Guide-FAQ-12626.pdf?rev=d0098c0f0662470ba66979c68ec33aa3&hash=F52133126DFBDA88F7976F38393F2B0A"
        },
        {
          "url": "https://www.michigan.gov/lara/bureau-list/bpl/health/additional-links/license-renewal-fees"
        },
        {
          "url": "https://www.legislature.mi.gov/Laws/MCL?objectName=MCL-333-16201"
        }
      ]
    },
    "MN": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://mn.gov/boards/medical-practice/renew/index.jsp"
        },
        {
          "url": "https://mn.gov/boards/medical-practice/licensing/administration/fees/index.jsp"
        },
        {
          "url": "https://mn.gov/boards/assets/MN%20BMP%20Account%20Codes%20Fee%20List%202025-Sep2_tcm21-78105.pdf"
        },
        {
          "url": "https://mn.gov/boards/medical-practice/renew/online-renew-post/index.jsp"
        }
      ]
    },
    "MS": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://www.msbml.ms.gov/licensure/md-do-permanent-renewal"
        },
        {
          "url": "https://www.msbml.ms.gov/licensure/fee-schedule"
        },
        {
          "url": "https://gateway.msbml.ms.gov/"
        }
      ]
    },
    "MO": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://pr.mo.gov/healingarts.asp"
        },
        {
          "url": "https://pr.mo.gov/physiciansandsurgeons.asp"
        },
        {
          "url": "https://mopro.mo.gov/license/s/"
        },
        {
          "url": "https://pr.mo.gov/boards/healingarts/375-0457.pdf"
        }
      ]
    },
    "MT": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://boards.bsd.dli.mt.gov/medical-examiners/"
        },
        {
          "url": "https://boards.bsd.dli.mt.gov/medical-examiners/license-information/renewal-process"
        },
        {
          "url": "https://boards.bsd.dli.mt.gov/medical-examiners/faq"
        },
        {
          "url": "https://boards.bsd.dli.mt.gov/medical-examiners/license-information/"
        }
      ]
    },
    "NE": {
      "recordedReview": "2026-08",
      "sources": [
        {
          "url": "https://dhhs.ne.gov/licensure/pages/medicine-and-surgery.aspx"
        },
        {
          "url": "https://dhhs.ne.gov/licensure/Pages/License-Renewals.aspx"
        },
        {
          "url": "https://dhhs.ne.gov/licensure/Documents/PhysOstPhysRenewal.pdf"
        },
        {
          "url": "https://dhhs.ne.gov/licensure/Documents/PhysOstPhysReinstatement.pdf"
        }
      ]
    },
    "NV": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://medboard.nv.gov/Licensees/Renewals/"
        },
        {
          "url": "https://medboard.nv.gov/uploadedFiles/medboardnvgov/content/Forms/Licensure%20Fees.pdf"
        },
        {
          "url": "https://www.leg.state.nv.us/NRS/NRS-630.html"
        },
        {
          "url": "https://www.leg.state.nv.us/NRS/NRS-633.html"
        }
      ]
    },
    "NH": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.oplc.nh.gov/board-medicine-license-fees"
        },
        {
          "url": "https://gc.nh.gov/rsa/html/XXX/310/310-8.htm"
        },
        {
          "url": "https://gc.nh.gov/rsa/html/XXX/329/329-16-a.htm"
        },
        {
          "url": "https://www.oplc.nh.gov/renew-your-license-online"
        }
      ]
    },
    "NJ": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.njconsumeraffairs.gov/documents/licenseprocess/bme-licensing-august-2017.pdf"
        },
        {
          "url": "https://www.njconsumeraffairs.gov/bme/Pages/FAQ.aspx"
        },
        {
          "url": "https://www.njconsumeraffairs.gov/bme"
        },
        {
          "url": "https://law.justia.com/codes/new-jersey/title-45/section-45-1-7-1/"
        }
      ]
    },
    "NM": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.nmmb.state.nm.us/licensing/"
        },
        {
          "url": "https://www.srca.nm.gov/parts/title16/16.010.0007.html"
        },
        {
          "url": "https://www.srca.nm.gov/parts/title16/16.010.0009.html"
        },
        {
          "url": "https://www.nmmb.state.nm.us/wp-content/uploads/2024/05/nmac-16.10.09-2022-02-08.pdf"
        }
      ]
    },
    "NY": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.op.nysed.gov/professions/physicians"
        },
        {
          "url": "https://www.op.nysed.gov/registration-renewal/online-registration-renewal"
        },
        {
          "url": "https://www.op.nysed.gov/about/frequently-asked-questions"
        },
        {
          "url": "https://www.op.nysed.gov/sites/op/files/documents/opfeechart.pdf"
        }
      ]
    },
    "NC": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.ncmedboard.org/licensing-registration/renewals/physicians"
        },
        {
          "url": "https://www.ncmedboard.org/resources-information/faqs/professional-faqs/renewals"
        },
        {
          "url": "https://www.ncmedboard.org/licensing-registration/renewals"
        },
        {
          "url": "https://www.ncmedboard.org/images/uploads/other_pdfs/NCMB_Fee_Schedule_08212026.pdf"
        }
      ]
    },
    "ND": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.ndbom.org/practitioners/physicians/current/renew-reactivate-instruct.asp"
        },
        {
          "url": "https://ndlegis.gov/api/acdata/pdf/50-02-07.1.pdf"
        },
        {
          "url": "https://www.ndbom.org/practitioners/physicians/faqs.asp"
        },
        {
          "url": "https://www.ndbom.org/practitioners/dashboard/index.asp"
        }
      ]
    },
    "OH": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://elicense.ohio.gov/"
        },
        {
          "url": "https://codes.ohio.gov/ohio-revised-code/section-4731.281"
        },
        {
          "url": "https://elicense.ohio.gov/OH_SupportPage"
        },
        {
          "url": "https://codes.ohio.gov/ohio-administrative-code/rule-4731-10-02"
        },
        {
          "url": "https://codes.ohio.gov/ohio-administrative-code/rule-4731-29-01"
        }
      ]
    },
    "OK": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.okmedicalboard.org/renew"
        },
        {
          "url": "https://www.okmedicalboard.org/licensing_faq"
        },
        {
          "url": "https://www.law.cornell.edu/regulations/oklahoma/OAC-435-10-7-10"
        },
        {
          "url": "https://www.law.cornell.edu/regulations/oklahoma/OAC-435-1-1-7"
        }
      ]
    },
    "OR": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.oregon.gov/omb/licensing/pages/renew.aspx"
        },
        {
          "url": "https://www.oregon.gov/omb/licensing/Documents/all-fees.pdf"
        },
        {
          "url": "https://secure.sos.state.or.us/oard/view.action?ruleNumber=847-008-0005"
        },
        {
          "url": "https://secure.sos.state.or.us/oard/view.action?ruleNumber=847-005-0005"
        }
      ]
    },
    "PA": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/medicine/renewal-information"
        },
        {
          "url": "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/osteopathic-medicine/renewal-information"
        },
        {
          "url": "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter16/s16.13.html"
        },
        {
          "url": "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter16/s16.15.html"
        }
      ]
    },
    "RI": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://health.ri.gov/licensing/physicians"
        },
        {
          "url": "https://rules.sos.ri.gov/regulations/part/216-10-05-2"
        },
        {
          "url": "https://rules.sos.ri.gov/regulations/part/216-40-05-1"
        },
        {
          "url": "http://webserver.rilegislature.gov/Statutes/TITLE5/5-37/5-37-10.htm"
        }
      ]
    },
    "SC": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://llr.sc.gov/med/renewals.aspx"
        },
        {
          "url": "https://llr.sc.gov/med/PDF/Renewal/2025-2027_LATE_Physician_Renewal_App.pdf"
        },
        {
          "url": "https://llr.sc.gov/med/PDF/Renewal/Renewal%20and%20Late%20Renewal%20Fees.pdf"
        },
        {
          "url": "https://www.scstatehouse.gov/code/t40c047.php"
        }
      ]
    },
    "SD": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.sdbmoe.gov/professions-physicians/professions-physicians-physician-license-md-do/"
        },
        {
          "url": "https://sdbmoe.gov/faqs/"
        },
        {
          "url": "https://sdlegislature.gov/api/Statutes/36-4-24.1.html"
        },
        {
          "url": "https://sdlegislature.gov/api/Statutes/36-4-24.2.html"
        }
      ]
    },
    "TN": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.tn.gov/health/licensure/me.html"
        },
        {
          "url": "https://www.tn.gov/content/dam/tn/health/healthprofboards/medicalexaminers/BME%20FAQs.pdf"
        },
        {
          "url": "https://publications.tnsosfiles.com/rules/0880/0880-02.20250617.pdf"
        },
        {
          "url": "https://www.tn.gov/health/licensure/ost.html"
        }
      ]
    },
    "TX": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.tmb.texas.gov/apply-renew/physician/physician-renewal"
        },
        {
          "url": "https://renewals.tmb.state.tx.us/ph/login.aspx"
        },
        {
          "url": "https://www.tmb.texas.gov/apply-renew/physician/license-cancellation-or-retirement-options-for-physicians"
        },
        {
          "url": "https://www.tmb.texas.gov/resources/for-applicants-and-licensees/continuing-education-tracking"
        }
      ]
    },
    "UT": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://commerce.utah.gov/dopl/physician-and-surgeon/renew-a-license/"
        },
        {
          "url": "https://dopl.utah.gov/osteopathic-physician-and-surgeon/renew-a-license/"
        },
        {
          "url": "https://commerce.utah.gov/wp-content/uploads/2022/11/fee-schedule.pdf"
        },
        {
          "url": "https://le.utah.gov/xcode/Title58/Chapter1/58-1-S308.html"
        }
      ]
    },
    "VT": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://www.healthvermont.gov/systems/board-medical-practice/applications-licensing-and-fees"
        },
        {
          "url": "https://www.healthvermont.gov/systems/board-medical-practice"
        },
        {
          "url": "https://legislature.vermont.gov/statutes/section/26/023/01400"
        },
        {
          "url": "https://legislature.vermont.gov/statutes/section/26/023/01401a"
        }
      ]
    },
    "VA": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://law.lis.virginia.gov/admincode/title18/agency85/chapter20/section22/"
        },
        {
          "url": "https://law.lis.virginia.gov/admincode/title18/agency85/chapter20/section230/"
        },
        {
          "url": "https://law.lis.virginia.gov/admincode/title18/agency85/chapter20/section240/"
        },
        {
          "url": "https://www.dhp.virginia.gov/Boards/Medicine/PractitionerResources/Fees/"
        }
      ]
    },
    "WA": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://wmc.wa.gov/licensing/renewals"
        },
        {
          "url": "https://wmc.wa.gov/licensing/fees"
        },
        {
          "url": "https://app.leg.wa.gov/wac/default.aspx?cite=246-919-990"
        },
        {
          "url": "https://app.leg.wa.gov/wac/default.aspx?cite=246-853-990"
        }
      ]
    },
    "WV": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://wvbom.wv.gov/2026MDRENEWALFAQ.asp"
        },
        {
          "url": "https://wvbom.wv.gov/2026MDTRADRENEWAL.asp"
        },
        {
          "url": "https://wvbom.wv.gov/2025MDRenewalLanding.asp"
        },
        {
          "url": "https://wvbom.wv.gov/practitioners/MD/renew/"
        }
      ]
    },
    "WI": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://dsps.wi.gov/Pages/Professions/Physician/Default.aspx"
        },
        {
          "url": "https://dsps.wi.gov/Credentialing/Renewal/RenewalDatesFees.pdf"
        },
        {
          "url": "https://dsps.wi.gov/Documents/NewsMedia/20250808FeeAdjustmentNewsRelease.pdf"
        },
        {
          "url": "https://docs.legis.wisconsin.gov/document/statutes/440.08(3)"
        }
      ]
    },
    "WY": {
      "recordedReview": "2026-08 (single-source)",
      "sources": [
        {
          "url": "https://wyomedboard.wyo.gov/physicians/renew-license"
        },
        {
          "url": "https://web.archive.org/web/20260608073314/https://wyomedboard.wyo.gov/physicians/renew-license"
        },
        {
          "url": "https://wyomedboard.wyo.gov/resources/fee-schedule"
        },
        {
          "url": "https://drive.google.com/uc?id=1ieX_JlIpAjqUvU5_DZC5gDv6c5xTtUfV&export=download"
        }
      ]
    }
  }
};
