// ============================================================================
// boardRequirements.js
// Comprehensive CME compliance database for board certification requirements.
// Covers ABMS MOC, AOA OCC, UCNS, and ABPS certification bodies,
// including primary boards and subspecialties.
// ============================================================================

// ----------------------------------------------------------------------------
// 1. MATE Act Requirement
// ----------------------------------------------------------------------------
export const MATE_ACT = {
  hours: 8,
  note: "MATE Act: 8 hrs treating/managing opioid & SUD patients (one-time, DEA renewal from June 2023)",
  oneTime: true,
};

// ----------------------------------------------------------------------------
// 2. AOA National CME Requirement
// ----------------------------------------------------------------------------
export const AOA_NATIONAL = {
  hours: 120,
  cycle: 3,
  cat1a: 30,
  notes: "AOA National: 120 hrs/3-yr cycle, min 30 hrs AOA Category 1-A",
};

// ----------------------------------------------------------------------------
// 3. ABMS Maintenance of Certification (MOC) – Primary Boards
// ----------------------------------------------------------------------------
export const ABMS_MOC = {
  ABAI: {
    name: "Allergy & Immunology",
    hours: 25,
    cycle: 1,
    unit: "AMA PRA Cat 1/year",
    assessment: "Longitudinal assessment or exam",
    notes: "Continuous certification",
  },
  ABA: {
    name: "Anesthesiology",
    hours: 250,
    cycle: 10,
    unit: "AMA PRA Cat 1/10yr",
    assessment: "Staged exam or MOCA Minute (longitudinal)",
    notes: "MOCA 2.0 program available",
  },
  ABCRS: {
    name: "Colon & Rectal Surgery",
    hours: 90,
    cycle: 5,
    unit: "AMA PRA Cat 1/5yr",
    assessment: "Exam every 10 years",
    notes: "50 SA credits required within the 90",
  },
  ABD: {
    name: "Dermatology",
    hours: 25,
    cycle: 1,
    unit: "Cat 1/year",
    assessment: "Continuous assessment",
    notes: "Annual requirement",
  },
  ABEM: {
    name: "Emergency Medicine",
    hours: 25,
    cycle: 1,
    unit: "AMA PRA Cat 1/year",
    assessment: "ConCert exam or MyEMCert (longitudinal)",
    notes: "Must be in field of practice",
  },
  ABFM: {
    name: "Family Medicine",
    hours: 200,
    cycle: 5,
    unit: "CME/5yr",
    assessment: "Longitudinal assessment or one-day exam",
    notes:
      "60 certification points also required; transitioning to 5-year cycle in 2025",
  },
  ABIM: {
    name: "Internal Medicine",
    hours: 200,
    cycle: 10,
    unit: "MOC points/10yr",
    assessment: "Knowledge Check-In or 10-year exam",
    notes: "Points system rather than strict credit hours",
  },
  ABMGG: {
    name: "Medical Genetics & Genomics",
    hours: 250,
    cycle: 10,
    unit: "AMA PRA Cat 1/10yr",
    assessment: "Exam",
    notes: "",
  },
  ABNS: {
    name: "Neurological Surgery",
    hours: 20,
    cycle: 1,
    unit: "AMA PRA Cat 1/year",
    assessment: "Oral exam + written exam",
    notes: "Annual requirement; relevant to neurosurgery practice",
  },
  ABNM: {
    name: "Nuclear Medicine",
    hours: 125,
    cycle: 5,
    unit: "AMA PRA Cat 1/5yr",
    assessment: "Exam",
    notes: "",
  },
  ABOG: {
    name: "Obstetrics & Gynecology",
    hours: 30,
    cycle: 1,
    unit: "ABOG articles/year",
    assessment: "Exam (Article-based assessment)",
    notes: "Article-based system rather than traditional CME",
  },
  ABOP: {
    name: "Ophthalmology",
    hours: 250,
    cycle: 10,
    unit: "AMA PRA Cat 1/10yr",
    assessment: "Quarterly Questions",
    notes: "",
  },
  ABOS: {
    name: "Orthopaedic Surgery",
    hours: 120,
    cycle: 3,
    unit: "ACCME Cat 1/3yr",
    assessment: "Exam or longitudinal assessment",
    notes: "Two 3-year cycles in a 6-year period",
  },
  ABOTO: {
    name: "Otolaryngology-HNS",
    hours: 25,
    cycle: 1,
    unit: "AMA PRA Cat 1/year",
    assessment: "Exam or longitudinal assessment",
    notes: "Annual requirement",
  },
  ABPath: {
    name: "Pathology",
    hours: 70,
    cycle: 2,
    unit: "AMA PRA Cat 1/2yr",
    assessment: "Exam or CertLink (longitudinal)",
    notes: "",
  },
  ABP: {
    name: "Pediatrics",
    hours: 40,
    cycle: 5,
    unit: "SA+QI points/5yr",
    assessment: "MOCA-Peds (longitudinal) or exam",
    notes: "Points-based system",
  },
  ABPMR: {
    name: "Physical Med & Rehab",
    hours: 150,
    cycle: 5,
    unit: "Cat 1/5yr",
    assessment: "Exam or longitudinal assessment",
    notes: "",
  },
  ABPS_BOARD: {
    name: "Plastic Surgery",
    hours: 150,
    cycle: 3,
    unit: "CME/3yr",
    assessment: "Exam",
    notes: "At least 60 must be Category 1",
  },
  ABPM: {
    name: "Preventive Medicine",
    hours: 20,
    cycle: 1,
    unit: "AMA PRA Cat 1/year",
    assessment: "LAP – 30 questions/year",
    notes:
      "Transitioning to annual attestation model; 6 credits relevant to ABPM cert",
  },
  ABPN: {
    name: "Psychiatry & Neurology",
    hours: 90,
    cycle: 3,
    unit: "Cat 1/3yr",
    assessment: "Exam or Article-Based CC",
    notes: "8 SA CME credits required",
  },
  ABR: {
    name: "Radiology",
    hours: 75,
    cycle: 1,
    unit: "AMA PRA Cat 1/year",
    assessment: "OLA (Online Longitudinal Assessment)",
    notes: "Continuous; 3-year rolling average maintained",
  },
  ABS: {
    name: "Surgery",
    hours: 150,
    cycle: 5,
    unit: "CME/5yr",
    assessment: "Exam",
    notes: "",
  },
  ABTS: {
    name: "Thoracic Surgery",
    hours: 150,
    cycle: 5,
    unit: "AMA Cat 1/5yr",
    assessment: "Exam",
    notes: "75 must be in cardiothoracic surgery",
  },
  ABU: {
    name: "Urology",
    hours: 90,
    cycle: 3,
    unit: "CME/3yr",
    assessment: "Exam or LLL pathway",
    notes: "30 must be Category 1",
  },
};

// ----------------------------------------------------------------------------
// 4. ABMS Subspecialty Certifications
// ----------------------------------------------------------------------------
export const ABMS_SUBSPECIALTIES = [
  // ---- ABA – Anesthesiology Subspecialties ----
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Adult Cardiac Anesthesiology",
    cmeReq: "250 Cat 1/10yr",
    cycle: 10,
    assessment: "MOCA Minute",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Critical Care Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABIM", "ABEM", "ABS"],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Hospice and Palliative Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABFM", "ABIM", "ABPN", "ABPeds", "ABPMR", "ABEM"],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Neurocritical Care",
    cmeReq: "Follows primary board + ABNS adds NeuCC module",
    cycle: null,
    assessment: "Exam by ABPN even years",
    coSponsors: ["ABPN", "ABEM", "ABIM", "ABNS"],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Pain Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPN", "ABPMR", "ABR", "ABFM", "ABEM"],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Pediatric Anesthesiology",
    cmeReq: "250 Cat 1/10yr",
    cycle: 10,
    assessment: "MOCA Minute",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "ABA",
    name: "Sleep Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABIM", "ABFM", "ABPeds", "ABPN", "ABOTO"],
    notes: "",
  },

  // ---- ABD – Dermatology Subspecialties ----
  {
    parent: "Dermatology",
    parentCode: "ABD",
    name: "Dermatopathology",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "Continuous assessment",
    coSponsors: ["ABPath"],
    notes: "",
  },
  {
    parent: "Dermatology",
    parentCode: "ABD",
    name: "Micrographic Dermatologic Surgery",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "Continuous assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Dermatology",
    parentCode: "ABD",
    name: "Pediatric Dermatology",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "Continuous assessment",
    coSponsors: [],
    notes: "",
  },

  // ---- ABEM – Emergency Medicine Subspecialties ----
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Anesthesiology Critical Care Medicine",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "ConCert or MyEMCert",
    coSponsors: ["ABA"],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Emergency Medical Services",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "ConCert or MyEMCert",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Internal Medicine–Critical Care Medicine",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "ConCert or MyEMCert",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Medical Toxicology",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPeds", "ABPM"],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Neurocritical Care",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "Exam",
    coSponsors: ["ABPN", "ABA", "ABIM", "ABNS"],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Pediatric Emergency Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPeds"],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Sports Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABFM", "ABIM", "ABPeds", "ABPMR"],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "ABEM",
    name: "Undersea and Hyperbaric Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPM"],
    notes: "",
  },

  // ---- ABFM – Family Medicine Subspecialties ----
  {
    parent: "Family Medicine",
    parentCode: "ABFM",
    name: "Adolescent Medicine",
    cmeReq: "200 CME/5yr",
    cycle: 5,
    assessment: "Longitudinal assessment or exam",
    coSponsors: ["ABPeds", "ABIM"],
    notes: "",
  },
  {
    parent: "Family Medicine",
    parentCode: "ABFM",
    name: "Geriatric Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABIM"],
    notes: "",
  },
  {
    parent: "Family Medicine",
    parentCode: "ABFM",
    name: "Hospice and Palliative Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABIM", "ABPN", "ABPeds", "ABPMR", "ABEM"],
    notes: "",
  },
  {
    parent: "Family Medicine",
    parentCode: "ABFM",
    name: "Pain Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABPN", "ABPMR", "ABR", "ABEM"],
    notes: "",
  },
  {
    parent: "Family Medicine",
    parentCode: "ABFM",
    name: "Sleep Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABIM", "ABPeds", "ABPN", "ABOTO"],
    notes: "",
  },
  {
    parent: "Family Medicine",
    parentCode: "ABFM",
    name: "Sports Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM", "ABIM", "ABPeds", "ABPMR"],
    notes: "",
  },

  // ---- ABIM – Internal Medicine Subspecialties ----
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Adolescent Medicine",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: ["ABFM", "ABPeds"],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Adult Congenital Heart Disease",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Adv Heart Failure & Transplant Cardiology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Cardiovascular Disease",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Clinical Cardiac Electrophysiology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Critical Care Medicine",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: ["ABA", "ABEM", "ABS", "ABOG"],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Endocrinology, Diabetes & Metabolism",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Gastroenterology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Geriatric Medicine",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: ["ABFM"],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Hematology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Hospice and Palliative Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABFM", "ABPN", "ABPeds", "ABPMR", "ABEM"],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Infectious Disease",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Interventional Cardiology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Medical Oncology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Nephrology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Neurocritical Care",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: ["ABPN", "ABA", "ABEM", "ABNS"],
    notes: "Requires CCM cert + NCC fellowship",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Pulmonary Disease",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Rheumatology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Sleep Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABFM", "ABPeds", "ABPN", "ABOTO"],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Sports Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM", "ABFM", "ABPeds", "ABPMR"],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "ABIM",
    name: "Transplant Hepatology",
    cmeReq: "200 MOC pts/10yr",
    cycle: 10,
    assessment: "Knowledge Check-In or exam",
    coSponsors: [],
    notes: "",
  },

  // ---- ABMGG – Medical Genetics & Genomics Subspecialties ----
  {
    parent: "Medical Genetics & Genomics",
    parentCode: "ABMGG",
    name: "Medical Biochemical Genetics",
    cmeReq: "250 Cat 1/10yr",
    cycle: 10,
    assessment: "Exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Medical Genetics & Genomics",
    parentCode: "ABMGG",
    name: "Molecular Genetic Pathology",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPath"],
    notes: "",
  },

  // ---- ABNS – Neurological Surgery Subspecialties ----
  {
    parent: "Neurological Surgery",
    parentCode: "ABNS",
    name: "Neurocritical Care",
    cmeReq: "20 Cat 1/yr + NeuCC Adaptive Learning Tool + case submission",
    cycle: 1,
    assessment: "NeuCC Adaptive Learning Tool + case submission",
    coSponsors: ["ABPN", "ABA", "ABEM", "ABIM"],
    notes: "",
  },

  // ---- ABOG – Obstetrics & Gynecology Subspecialties ----
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "ABOG",
    name: "Complex Family Planning",
    cmeReq: "30 articles/yr",
    cycle: 1,
    assessment: "Article-based assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "ABOG",
    name: "Critical Care Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABIM", "ABEM", "ABS"],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "ABOG",
    name: "Gynecologic Oncology",
    cmeReq: "30 articles/yr",
    cycle: 1,
    assessment: "Article-based assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "ABOG",
    name: "Maternal–Fetal Medicine",
    cmeReq: "30 articles/yr",
    cycle: 1,
    assessment: "Article-based assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "ABOG",
    name: "Reproductive Endocrinology & Infertility",
    cmeReq: "30 articles/yr",
    cycle: 1,
    assessment: "Article-based assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "ABOG",
    name: "Urogynecology & Reconstructive Pelvic Surgery",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABU"],
    notes: "",
  },

  // ---- ABOS – Orthopaedic Surgery Subspecialties ----
  {
    parent: "Orthopaedic Surgery",
    parentCode: "ABOS",
    name: "Orthopaedic Sports Medicine",
    cmeReq: "120 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or longitudinal assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Orthopaedic Surgery",
    parentCode: "ABOS",
    name: "Surgery of the Hand",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPS", "ABS"],
    notes: "",
  },

  // ---- ABOTO – Otolaryngology-HNS Subspecialties ----
  {
    parent: "Otolaryngology-HNS",
    parentCode: "ABOTO",
    name: "Complex Pediatric Otolaryngology",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "Exam or longitudinal assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Otolaryngology-HNS",
    parentCode: "ABOTO",
    name: "Neurotology",
    cmeReq: "25 Cat 1/yr",
    cycle: 1,
    assessment: "Exam or longitudinal assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Otolaryngology-HNS",
    parentCode: "ABOTO",
    name: "Sleep Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABFM", "ABIM", "ABPeds", "ABPN"],
    notes: "",
  },

  // ---- ABPath – Pathology Subspecialties ----
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Blood Banking/Transfusion Medicine",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Clinical Informatics",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPM"],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Cytopathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Dermatopathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: ["ABD"],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Hematopathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Neuropathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Chemical Pathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Forensic Pathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Medical Microbiology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Molecular Genetic Pathology",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABMGG"],
    notes: "",
  },
  {
    parent: "Pathology",
    parentCode: "ABPath",
    name: "Pediatric Pathology",
    cmeReq: "70 Cat 1/2yr",
    cycle: 2,
    assessment: "Exam or CertLink",
    coSponsors: [],
    notes: "",
  },

  // ---- ABP – Pediatrics Subspecialties ----
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Adolescent Medicine",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: ["ABFM", "ABIM"],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Child Abuse Pediatrics",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Developmental-Behavioral Pediatrics",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Hospice and Palliative Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABFM", "ABIM", "ABPN", "ABPMR", "ABEM"],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Medical Toxicology",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM", "ABPM"],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Neonatal-Perinatal Medicine",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Cardiology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Critical Care Medicine",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Emergency Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM"],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Endocrinology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Gastroenterology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Hematology-Oncology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Hospital Medicine",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Infectious Diseases",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Nephrology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Pulmonology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Rheumatology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Pediatric Transplant Hepatology",
    cmeReq: "40SA+40QI pts/5yr",
    cycle: 5,
    assessment: "MOCA-Peds or exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Sleep Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABFM", "ABIM", "ABPN", "ABOTO"],
    notes: "",
  },
  {
    parent: "Pediatrics",
    parentCode: "ABP",
    name: "Sports Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM", "ABFM", "ABIM", "ABPMR"],
    notes: "",
  },

  // ---- ABPMR – Physical Med & Rehab Subspecialties ----
  {
    parent: "Physical Med & Rehab",
    parentCode: "ABPMR",
    name: "Brain Injury Medicine",
    cmeReq: "150 Cat 1/5yr",
    cycle: 5,
    assessment: "Exam or longitudinal assessment",
    coSponsors: ["ABPN"],
    notes: "",
  },
  {
    parent: "Physical Med & Rehab",
    parentCode: "ABPMR",
    name: "Neuromuscular Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPN"],
    notes: "",
  },
  {
    parent: "Physical Med & Rehab",
    parentCode: "ABPMR",
    name: "Pain Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABPN", "ABR", "ABFM", "ABEM"],
    notes: "",
  },
  {
    parent: "Physical Med & Rehab",
    parentCode: "ABPMR",
    name: "Pediatric Rehabilitation Medicine",
    cmeReq: "150 Cat 1/5yr",
    cycle: 5,
    assessment: "Exam or longitudinal assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Physical Med & Rehab",
    parentCode: "ABPMR",
    name: "Spinal Cord Injury Medicine",
    cmeReq: "150 Cat 1/5yr",
    cycle: 5,
    assessment: "Exam or longitudinal assessment",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Physical Med & Rehab",
    parentCode: "ABPMR",
    name: "Sports Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM", "ABFM", "ABIM", "ABPeds"],
    notes: "",
  },

  // ---- ABPS_BOARD – Plastic Surgery Subspecialties ----
  {
    parent: "Plastic Surgery",
    parentCode: "ABPS_BOARD",
    name: "Surgery of the Hand",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABOS", "ABS"],
    notes: "",
  },

  // ---- ABPM – Preventive Medicine Subspecialties ----
  {
    parent: "Preventive Medicine",
    parentCode: "ABPM",
    name: "Addiction Medicine",
    cmeReq: "20 Cat 1/yr",
    cycle: 1,
    assessment: "LAP",
    coSponsors: [],
    notes: "6 relevant to ABPM",
  },
  {
    parent: "Preventive Medicine",
    parentCode: "ABPM",
    name: "Clinical Informatics",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPath"],
    notes: "",
  },
  {
    parent: "Preventive Medicine",
    parentCode: "ABPM",
    name: "Medical Toxicology",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM", "ABPeds"],
    notes: "",
  },
  {
    parent: "Preventive Medicine",
    parentCode: "ABPM",
    name: "Undersea and Hyperbaric Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABEM"],
    notes: "",
  },

  // ---- ABPN – Psychiatry & Neurology Subspecialties ----
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Addiction Psychiatry",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Brain Injury Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPMR"],
    notes: "",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Child and Adolescent Psychiatry",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Clinical Neurophysiology",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Consultation-Liaison Psychiatry",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Epilepsy",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Forensic Psychiatry",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Geriatric Psychiatry",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Neurocritical Care",
    cmeReq: "ABPN administers NCC exam for all boards",
    cycle: null,
    assessment: "NCC exam",
    coSponsors: ["ABA", "ABEM", "ABIM", "ABNS"],
    notes: "",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Neurodevelopmental Disabilities",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Neuromuscular Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABPMR"],
    notes: "",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Pain Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABPMR", "ABR", "ABFM", "ABEM"],
    notes: "",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Sleep Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABFM", "ABIM", "ABPeds", "ABOTO"],
    notes: "",
  },
  {
    parent: "Psychiatry & Neurology",
    parentCode: "ABPN",
    name: "Vascular Neurology",
    cmeReq: "90 Cat 1/3yr",
    cycle: 3,
    assessment: "Exam or Article-Based CC",
    coSponsors: [],
    notes: "8 SA CME",
  },

  // ---- ABR – Radiology Subspecialties ----
  {
    parent: "Radiology",
    parentCode: "ABR",
    name: "Neuroradiology",
    cmeReq: "75 Cat 1/yr",
    cycle: 1,
    assessment: "OLA",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Radiology",
    parentCode: "ABR",
    name: "Nuclear Radiology",
    cmeReq: "75 Cat 1/yr",
    cycle: 1,
    assessment: "OLA",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Radiology",
    parentCode: "ABR",
    name: "Pain Medicine",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABA", "ABPN", "ABPMR", "ABFM", "ABEM"],
    notes: "",
  },
  {
    parent: "Radiology",
    parentCode: "ABR",
    name: "Pediatric Radiology",
    cmeReq: "75 Cat 1/yr",
    cycle: 1,
    assessment: "OLA",
    coSponsors: [],
    notes: "",
  },

  // ---- ABS – Surgery Subspecialties ----
  {
    parent: "Surgery",
    parentCode: "ABS",
    name: "Complex General Surgical Oncology",
    cmeReq: "150 CME/5yr",
    cycle: 5,
    assessment: "Exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "ABS",
    name: "Pediatric Surgery",
    cmeReq: "150 CME/5yr",
    cycle: 5,
    assessment: "Exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "ABS",
    name: "Surgery of the Hand",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABOS", "ABPS"],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "ABS",
    name: "Surgical Critical Care",
    cmeReq: "150 CME/5yr",
    cycle: 5,
    assessment: "Exam",
    coSponsors: [],
    notes: "Also pathway to NCC",
  },

  // ---- ABTS – Thoracic Surgery Subspecialties ----
  {
    parent: "Thoracic Surgery",
    parentCode: "ABTS",
    name: "Congenital Cardiac Surgery",
    cmeReq: "150 Cat 1/5yr",
    cycle: 5,
    assessment: "Exam",
    coSponsors: [],
    notes: "75 must be in cardiothoracic surgery",
  },

  // ---- ABU – Urology Subspecialties ----
  {
    parent: "Urology",
    parentCode: "ABU",
    name: "Pediatric Urology",
    cmeReq: "90 CME/3yr",
    cycle: 3,
    assessment: "Exam or LLL pathway",
    coSponsors: [],
    notes: "30 must be Category 1",
  },
  {
    parent: "Urology",
    parentCode: "ABU",
    name: "Urogynecology",
    cmeReq: "Follows primary board",
    cycle: null,
    assessment: "Follows primary board",
    coSponsors: ["ABOG"],
    notes: "",
  },
];

// ----------------------------------------------------------------------------
// 5. AOA Osteopathic Continuous Certification (OCC) – Primary Boards
// ----------------------------------------------------------------------------
export const AOA_OCC = {
  AOBA: {
    name: "Anesthesiology",
    timeLimited: { hours: 120, cat1: 0, specReq: "15 Cat 1-A in anesthesiology" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "15 Cat 1-A in anesthesiology" },
  },
  AOBD: {
    name: "Dermatology",
    timeLimited: { hours: 120, cat1: 0, specReq: "25 specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "25 specialty-specific" },
  },
  AOBEM: {
    name: "Emergency Medicine",
    timeLimited: { hours: 120, cat1: 0, specReq: "60 specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "60 specialty-specific" },
  },
  AOBFP: {
    name: "Family Practice",
    timeLimited: {
      hours: 120,
      cat1: 40,
      specReq: "30 Cat 1-A + additional 30 Cat 1-A or 1-B",
    },
    nonTimeLimited: {
      hours: 120,
      cat1: 40,
      specReq: "30 Cat 1-A + additional 30 Cat 1-A or 1-B",
    },
  },
  AOBIM: {
    name: "Internal Medicine",
    timeLimited: { hours: 120, cat1: 0, specReq: "30 Cat 1-A in IM" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "30 Cat 1-A in IM" },
  },
  AOBNP: {
    name: "Neurology & Psychiatry",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBNMM: {
    name: "Neuromusculoskeletal Medicine",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBOG: {
    name: "Obstetrics & Gynecology",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBOO: {
    name: "Ophthalmology & Otolaryngology",
    timeLimited: { hours: 60, cat1: 0, specReq: "25 specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "25 specialty-specific" },
  },
  AOBOS: {
    name: "Orthopedic Surgery",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBP: {
    name: "Pediatrics",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBPM: {
    name: "Preventive Medicine",
    timeLimited: { hours: 60, cat1: 0, specReq: "24 specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "48 specialty-specific" },
  },
  AOBPMR: {
    name: "Physical Medicine & Rehabilitation",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBR: {
    name: "Radiology",
    timeLimited: {
      hours: 120,
      cat1: 0,
      specReq: "specialty-specific",
      note: "SAMs credits count toward CME",
    },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
  AOBS: {
    name: "Surgery",
    timeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
    nonTimeLimited: { hours: 120, cat1: 0, specReq: "specialty-specific" },
  },
};

// ----------------------------------------------------------------------------
// 6. AOA Subspecialty Certifications
// ----------------------------------------------------------------------------
export const AOA_SUBSPECIALTIES = [
  // ---- AOBA – Anesthesiology Subspecialties ----
  {
    parent: "Anesthesiology",
    parentCode: "AOBA",
    name: "Critical Care",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "15 Cat 1-A in anesthesiology",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "AOBA",
    name: "Pain Management",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "15 Cat 1-A in anesthesiology",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Anesthesiology",
    parentCode: "AOBA",
    name: "Pediatric Anesthesiology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "15 Cat 1-A in anesthesiology",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBD – Dermatology Subspecialties ----
  {
    parent: "Dermatology",
    parentCode: "AOBD",
    name: "Dermatopathology",
    type: "CAQ/Conjoint",
    cmeReq: "120 hrs/3yr",
    specCME: "25 specialty-specific",
    assessment: "OCC exam",
    coSponsors: ["Pathology"],
    notes: "",
  },
  {
    parent: "Dermatology",
    parentCode: "AOBD",
    name: "MOHS Micrographic Surgery",
    type: "CAQ",
    cmeReq: "120 hrs/3yr",
    specCME: "25 specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Dermatology",
    parentCode: "AOBD",
    name: "Pediatric Dermatology",
    type: "CAQ",
    cmeReq: "120 hrs/3yr",
    specCME: "25 specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBEM – Emergency Medicine Subspecialties ----
  {
    parent: "Emergency Medicine",
    parentCode: "AOBEM",
    name: "Emergency Medical Services",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "60 specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Emergency Medicine",
    parentCode: "AOBEM",
    name: "Medical Toxicology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "60 specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBFP – Family Practice Subspecialties ----
  {
    parent: "Family Practice",
    parentCode: "AOBFP",
    name: "Geriatric Medicine",
    type: "CAQ",
    cmeReq: "120 hrs/3yr",
    specCME: "40 specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBIM – Internal Medicine Subspecialties ----
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Cardiology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Clinical Cardiac Electrophysiology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Critical Care Medicine",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Endocrinology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Gastroenterology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Geriatric Medicine",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Hematology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Infectious Disease",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Interventional Cardiology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Nephrology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Oncology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Pulmonary Disease",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Internal Medicine",
    parentCode: "AOBIM",
    name: "Rheumatology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "30 Cat 1-A in IM",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBNP – Neurology & Psychiatry Subspecialties ----
  {
    parent: "Neurology & Psychiatry",
    parentCode: "AOBNP",
    name: "Child/Adolescent Neurology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Neurology & Psychiatry",
    parentCode: "AOBNP",
    name: "Child/Adolescent Psychiatry",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Neurology & Psychiatry",
    parentCode: "AOBNP",
    name: "Geriatric Psychiatry",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Neurology & Psychiatry",
    parentCode: "AOBNP",
    name: "Neurophysiology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBOG – Obstetrics & Gynecology Subspecialties ----
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "AOBOG",
    name: "Female Pelvic Med/Reconstructive Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "AOBOG",
    name: "Gynecologic Oncology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "AOBOG",
    name: "Maternal & Fetal Medicine",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Obstetrics & Gynecology",
    parentCode: "AOBOG",
    name: "Reproductive Endocrinology & Infertility",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBOO – Ophthalmology & Otolaryngology Subspecialties ----
  {
    parent: "Ophthalmology & Otolaryngology",
    parentCode: "AOBOO",
    name: "Otolaryngic Allergy",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBOS – Orthopedic Surgery Subspecialties ----
  {
    parent: "Orthopedic Surgery",
    parentCode: "AOBOS",
    name: "Hand Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Orthopedic Surgery",
    parentCode: "AOBOS",
    name: "Orthopedic Sports Medicine",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBPa – Pathology Subspecialties ----
  {
    parent: "Pathology",
    parentCode: "AOBPa",
    name: "Forensic Pathology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBP – Pediatrics Subspecialties ----
  {
    parent: "Pediatrics",
    parentCode: "AOBP",
    name: "Neonatology",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- AOBPM – Preventive Medicine Subspecialties ----
  {
    parent: "Preventive Medicine",
    parentCode: "AOBPM",
    name: "Occupational Medicine",
    type: "CAQ",
    cmeReq: "120 hrs/3yr",
    specCME: "50 Cat 1-A in Occ/Env Med",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "10yr cert cycle",
  },

  // ---- AOBS – Surgery Subspecialties ----
  {
    parent: "Surgery",
    parentCode: "AOBS",
    name: "General Vascular Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "AOBS",
    name: "Neurological Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "DO pathway for neurosurgery",
  },
  {
    parent: "Surgery",
    parentCode: "AOBS",
    name: "Plastic & Reconstructive Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "AOBS",
    name: "Thoracic/Cardiovascular Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "AOBS",
    name: "Urological Surgery",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },
  {
    parent: "Surgery",
    parentCode: "AOBS",
    name: "Surgical Critical Care",
    type: "subspecialty",
    cmeReq: "120 hrs/3yr",
    specCME: "specialty-specific",
    assessment: "OCC exam",
    coSponsors: [],
    notes: "",
  },

  // ---- Conjoint Certifications (multi-board, AOA-wide) ----
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Addiction Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBFP", "AOBIM", "AOBNP", "AOBPM"],
    notes: "",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Allergy & Immunology",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBIM", "AOBP"],
    notes: "",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Correctional Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBFP", "AOBIM", "AOBPM"],
    notes: "Unique to AOA",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Hospice and Palliative Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBEM", "AOBFP", "AOBIM", "AOBNMM", "AOBNP", "AOBPMR"],
    notes: "",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Pain Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBEM", "AOBFP", "AOBIM", "AOBNMM", "AOBNP", "AOBPMR"],
    notes: "",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Sleep Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBFP", "AOBIM", "AOBNP", "AOBOO"],
    notes: "",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Sports Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBEM", "AOBFP", "AOBIM", "AOBNMM", "AOBP", "AOBPMR"],
    notes: "",
  },
  {
    parent: "Conjoint",
    parentCode: "Conjoint",
    name: "Undersea and Hyperbaric Medicine",
    type: "conjoint",
    cmeReq: "Follows primary + conjoint",
    specCME: "Follows primary + conjoint",
    assessment: "Conjoint exam",
    coSponsors: ["AOBEM", "AOBFP", "AOBIM", "AOBPM"],
    notes: "",
  },
];

// ----------------------------------------------------------------------------
// 7. UCNS (United Council for Neurologic Subspecialties) Certifications
// ----------------------------------------------------------------------------
export const UCNS_CERTS = [
  {
    name: "Autonomic Disorders",
    exam: "Biennial (odd years)",
    certReq: "Annual reading + 25-question quiz (80% min)",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "Since 2003",
  },
  {
    name: "Behavioral Neurology & Neuropsychiatry",
    exam: "Biennial (odd years)",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "",
  },
  {
    name: "Clinical Neuromuscular Pathology",
    exam: "Biennial (odd years)",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "",
  },
  {
    name: "Geriatric Neurology",
    exam: "Biennial",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "",
  },
  {
    name: "Headache Medicine",
    exam: "Biennial (odd years)",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "",
  },
  {
    name: "Interventional Neurology",
    exam: "Biennial (odd years)",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "",
  },
  {
    name: "Neonatal Neurocritical Care",
    exam: "Biennial",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "Newer subspecialty",
  },
  {
    name: "Neurocritical Care",
    exam: "Biennial (odd years)",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "UCNS NCC since 2007; separate from ABMS NCC",
  },
  {
    name: "Neuroimaging",
    exam: "Biennial",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "ASN assuming accreditation",
  },
  {
    name: "Neuro-oncology",
    exam: "Biennial",
    certReq: "Annual reading + quiz",
    annualFee: "$175/yr",
    cmeNote: "Relies on primary board CME",
    eligibility: "ABMS/AOA/RCPSC primary cert required",
    notes: "",
  },
];

// ----------------------------------------------------------------------------
// 8. ABPS (American Board of Physician Specialties) Certifications
//    Uniform requirements across all ABPS specialties:
//      - 8-year cycle
//      - Avg 50 hrs CME/yr
//      - Avg 50 SA questions/yr
//      - 7.5 hrs medical ethics (AAPS-approved)
//      - Recertification exam every 8 years
// ----------------------------------------------------------------------------
export const ABPS_CERTS = [
  {
    name: "Administrative Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Anesthesiology",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Dermatology",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Diagnostic Radiology",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Disaster Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "Unique to ABPS",
  },
  {
    name: "Emergency Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Family Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Family Medicine Obstetrics",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "Unique to ABPS",
  },
  {
    name: "Gastrointestinal Endoscopy",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "Unique to ABPS",
  },
  {
    name: "General Surgery",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Geriatric Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Hospital Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Integrative Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "Unique to ABPS",
  },
  {
    name: "Internal Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "Alternative to ABIM, no MOC points",
  },
  {
    name: "Interventional Pain Management",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Obstetrics & Gynecology",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Ophthalmology",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Orthopedic Surgery",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Plastic & Reconstructive Surgery",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Psychiatry",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Radiation Oncology",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "",
  },
  {
    name: "Urgent Care Medicine",
    cycle: 8,
    cmePerYear: 50,
    ethicsHours: 7.5,
    notes: "Unique to ABPS",
  },
];
