// GENERATED by scripts/generate-app-rules.mjs from data/app-rules/national.json. Do not edit.
// Change the data and run: node scripts/generate-app-rules.mjs
export const CERTIFICATION_RULES_META = {
 "generatedFrom": "data/app-rules/national.json",
 "verifiedAt": "2026-10-01"
};
export const CERTIFICATION_RULES = {
 "NCCPA": {
  "body": "NCCPA",
  "profession": "pa",
  "name": "NCCPA",
  "fullName": "National Commission on Certification of Physician Assistants",
  "unit": "credits",
  "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/",
  "unverified": [],
  "cycleYears": 2,
  "cites": {
   "cycleYears": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "total": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "cat1Min": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "cat1Accepted": {
    "cite": "NCCPA CME page, CME Types",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "category2Note": {
    "cite": "AAPA CME FAQs",
    "url": "https://www.aapa.org/education/cme-faqs/"
   },
   "saMultiplier": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "piBonusCap": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "windowStart": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   },
   "deadline": {
    "cite": "NCCPA Maintain Certification",
    "url": "https://www.nccpa.net/maintain-certification/"
   },
   "exam": {
    "cite": "NCCPA Maintain Certification",
    "url": "https://www.nccpa.net/maintain-certification/"
   },
   "panreLa": {
    "cite": "NCCPA Maintain Certification",
    "url": "https://www.nccpa.net/maintain-certification/"
   },
   "panreLaCredits": {
    "cite": "NCCPA Maintain Certification",
    "url": "https://www.nccpa.net/maintain-certification/"
   },
   "newCertificantNote": {
    "cite": "NCCPA CME page",
    "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/"
   }
  },
  "total": 100,
  "cat1Min": 50,
  "cat1Accepted": [
   "AAPA Category 1 CME",
   "AMA PRA Category 1",
   "AOA Category 1-A",
   "AAFP Prescribed Credit",
   "NCCPA PANRE-LA (Category 1 Self-Assessment)"
  ],
  "category2Note": "Nursing-only contact hours count only as Category 2 for PAs.",
  "saMultiplier": 1.5,
  "piBonusCap": 20,
  "windowStart": {
   "month": 5,
   "day": 1,
   "yearsBeforeExpiration": 2
  },
  "deadline": "11:59 p.m. PT on December 31 of the expiration year",
  "exam": "Pass PANRE or PANRE-LA by the end of year 10 of the maintenance cycle.",
  "panreLa": "PANRE-LA: apply in year 6; 12 quarters across years 7 to 9; if not passed, up to three PANRE attempts in year 10.",
  "panreLaCredits": 2,
  "newCertificantNote": "New certificants count CME from their issue date (NCCPA). Set CME Cycle Start on this record if this is your first cycle.",
  "mayCount": [],
  "status": "verified"
 },
 "AANPCB": {
  "body": "AANPCB",
  "profession": "np",
  "name": "AANPCB",
  "fullName": "American Academy of Nurse Practitioners Certification Board (NPCB)",
  "unit": "contact hours",
  "url": "https://candidateportal.aanpcert.org/recert",
  "unverified": [
   {
    "item": "Which CE providers AANPCB accepts (the handbook says CE from an accredited provider; AMA PRA Category 1 acceptance is not stated)",
    "why": "fact not verified: np.aanpcb.accepted_ce"
   }
  ],
  "cycleYears": 5,
  "cites": {
   "cycleYears": {
    "cite": "NPCB recertification page",
    "url": "https://candidateportal.aanpcert.org/recert"
   },
   "total": {
    "cite": "NPCB recertification page",
    "url": "https://candidateportal.aanpcert.org/recert"
   },
   "pharmacology": {
    "cite": "NPCB recertification page",
    "url": "https://candidateportal.aanpcert.org/recert"
   },
   "practiceHours": {
    "cite": "NPCB recertification page",
    "url": "https://candidateportal.aanpcert.org/recert"
   },
   "preceptingCap": {
    "cite": "NPCB FNP Renewal Handbook (06-04-2026), Preceptorship Hours",
    "url": "https://www.aanpcert.org/wp-content/uploads/FNP-Renewal-Handbook-06-04-2026.pdf"
   },
   "examRenewal": {
    "cite": "NPCB FNP, AGNP and ENP Renewal Handbooks (06-04-2026)",
    "url": "https://www.aanpcert.org/wp-content/uploads/AGNP-Renewal-Handbook-06-04-2026.pdf"
   }
  },
  "total": 100,
  "pharmacology": 25,
  "practiceHours": 1000,
  "preceptingCap": 25,
  "examRenewal": [
   "FNP-C",
   "A-GNP-C",
   "PMHNP-C",
   "ENP-C"
  ],
  "accepted": null,
  "mayCount": [
   "AMA PRA Category 1",
   "AAPA Category 1 CME"
  ],
  "status": "partial"
 },
 "ANCC": {
  "body": "ANCC",
  "profession": "np",
  "name": "ANCC",
  "fullName": "American Nurses Credentialing Center",
  "unit": "contact hours",
  "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf",
  "unverified": [],
  "cycleYears": 5,
  "cites": {
   "cycleYears": {
    "cite": "ANCC Certification Renewal Handbook, effective Sept 10, 2025, Version 2 Feb 10, 2026",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "total": {
    "cite": "ANCC Renewal Handbook (2025), Category 1",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "pharmacology": {
    "cite": "ANCC Renewal Handbook (2025), Category 1",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "formallyApprovedMin": {
    "cite": "ANCC Renewal Handbook (2025), Category 1",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "formallyApproved": {
    "cite": "ANCC Renewal Handbook (2025), Category 1",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "totalOnly": {
    "cite": "ANCC Renewal Handbook (2025), Category 1 item 3",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "developmentNote": {
    "cite": "ANCC Renewal Handbook (2025)",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf"
   },
   "upcoming": {
    "cite": "ANCC Renewal Handbook, Feb 2027",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certification-renewal-handbook_2027.pdf"
   },
   "noGrace": {
    "cite": "ANCC Renewal Handbook, Feb 2027",
    "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certification-renewal-handbook_2027.pdf"
   }
  },
  "total": 75,
  "pharmacology": 25,
  "formallyApprovedMin": 60,
  "formallyApproved": [
   "Accredited Nursing CE",
   "AMA PRA Category 1",
   "Joint Accreditation CE"
  ],
  "totalOnly": [
   "AAPA Category 1 CME",
   "Non-accredited CE",
   "State-Specific Required"
  ],
  "developmentNote": "Complete one of the eight professional development categories.",
  "upcoming": {
   "date": "2027-02-01",
   "text": "ANCC's renewal handbook effective February 1, 2027 requires all 75 contact hours to be accredited or formally approved (APRNs: 25 pharmacology) plus one pathway: 75 more contact hours, practice hours, or scholarship. Which handbook applies depends on when you apply."
  },
  "noGrace": "No grace period; renew on or before expiration.",
  "mayCount": [],
  "status": "verified"
 },
 "PNCB": {
  "body": "PNCB",
  "profession": "np",
  "name": "PNCB",
  "fullName": "Pediatric Nursing Certification Board",
  "unit": "contact hours",
  "url": "https://www.pncb.org/sites/default/files/resources/PNCB_Recert_Guide.pdf",
  "unverified": [
   {
    "item": "The dates the 15 yearly contact hours must fall between (PNCB says only within the accepted date range)",
    "why": "listed as not yet verified"
   }
  ],
  "annualHours": 15,
  "cites": {
   "annualHours": {
    "cite": "PNCB Recertification Guide, requirements table",
    "url": "https://www.pncb.org/sites/default/files/resources/PNCB_Recert_Guide.pdf"
   },
   "annualPracticeHoursCap": {
    "cite": "PNCB Recertification Guide, requirements table",
    "url": "https://www.pncb.org/sites/default/files/resources/PNCB_Recert_Guide.pdf"
   },
   "sevenYear": {
    "cite": "PNCB Recertification Guide, requirements table",
    "url": "https://www.pncb.org/sites/default/files/resources/PNCB_Recert_Guide.pdf"
   }
  },
  "annualPracticeHoursCap": 10,
  "sevenYear": "CPNP-PC and CPNP-AC: within each 7-year cycle, 4 Pediatric Updates modules (2 role-specific) and 15 contact hours of pediatric pharmacology.",
  "mayCount": [],
  "status": "partial"
 },
 "NCC": {
  "body": "NCC",
  "profession": "np",
  "name": "NCC",
  "fullName": "National Certification Corporation",
  "unit": "hours",
  "url": "https://www.nccwebsite.org/content/documents/cms/maintenance-core.pdf",
  "unverified": [],
  "cycleYears": 3,
  "cites": {
   "cycleYears": {
    "cite": "NCC 2026 Core Maintenance Catalog",
    "url": "https://www.nccwebsite.org/content/documents/cms/maintenance-core.pdf"
   },
   "planMin": {
    "cite": "NCC WHNP-BC coding book; NCC Core Maintenance Catalog (alternate maintenance)",
    "url": "https://www.nccwebsite.org/content/documents/cms/coding-book-whc.pdf"
   },
   "planMax": {
    "cite": "NCC WHNP-BC coding book; NCC Core Maintenance Catalog (alternate maintenance)",
    "url": "https://www.nccwebsite.org/content/documents/cms/coding-book-whc.pdf"
   },
   "ccaCredit": {
    "cite": "NCC WHNP-BC coding book; NCC Core Maintenance Catalog (alternate maintenance)",
    "url": "https://www.nccwebsite.org/content/documents/cms/coding-book-whc.pdf"
   },
   "excludedCategories": {
    "cite": "NCC WHNP-BC coding book",
    "url": "https://www.nccwebsite.org/content/documents/cms/coding-book-whc.pdf"
   },
   "ccaNote": {
    "cite": "NCC How and why page",
    "url": "https://www.nccwebsite.org/maintain-your-certification/how-and-why"
   }
  },
  "planMin": 15,
  "planMax": 50,
  "ccaCredit": 5,
  "excludedCategories": [
   "ACLS",
   "BLS"
  ],
  "ccaNote": "Only CE earned after the Continuing Competency Assessment counts, and the CCA itself earns 5 hours. Do not log the CCA as a CE entry.",
  "mayCount": [],
  "status": "verified"
 },
 "AACN": {
  "body": "AACN",
  "profession": "np",
  "name": "AACN",
  "fullName": "AACN Certification Corporation",
  "unit": "hours",
  "url": null,
  "unverified": [
   {
    "item": "AACN renewal rules",
    "why": "listed as not yet verified"
   }
  ],
  "mayCount": [],
  "status": "unverified"
 }
};
export const DEA_APP_RULES = {
 "mateHours": 8,
 "mateSchoolExemption": "PA or advanced practice nursing graduates within 5 years whose curriculum had 8 or more hours of substance use disorder training satisfy it."
};
export const APP_GENERAL_SOURCES = [
 {
  "name": "American Academy of Nurse Practitioners Certification Board (NPCB)",
  "url": "https://candidateportal.aanpcert.org/recert",
  "cite": "NPCB recertification page"
 },
 {
  "name": "American Academy of Nurse Practitioners Certification Board (NPCB)",
  "url": "https://www.aanpcert.org/wp-content/uploads/AGNP-Renewal-Handbook-06-04-2026.pdf",
  "cite": "NPCB FNP, AGNP and ENP Renewal Handbooks (06-04-2026)"
 },
 {
  "name": "American Academy of Nurse Practitioners Certification Board (NPCB)",
  "url": "https://www.aanpcert.org/wp-content/uploads/FNP-Renewal-Handbook-06-04-2026.pdf",
  "cite": "NPCB FNP Renewal Handbook (06-04-2026), Preceptorship Hours"
 },
 {
  "name": "National Commission on Certification of Physician Assistants",
  "url": "https://www.aapa.org/education/cme-faqs/",
  "cite": "AAPA CME FAQs"
 },
 {
  "name": "DEA Diversion Control Division",
  "url": "https://www.deadiversion.usdoj.gov/faq/MATE_Act_faq.html",
  "cite": "DEA MATE Act Q&A"
 },
 {
  "name": "DEA Diversion Control Division",
  "url": "https://www.deadiversion.usdoj.gov/pubs/docs/MATE_Training_Letter_Final.pdf",
  "cite": "Consolidated Appropriations Act 2023 (MATE Act); DEA letter to registrants"
 },
 {
  "name": "National Commission on Certification of Physician Assistants",
  "url": "https://www.nccpa.net/maintain-certification/",
  "cite": "NCCPA Maintain Certification"
 },
 {
  "name": "National Commission on Certification of Physician Assistants",
  "url": "https://www.nccpa.net/maintain-certification/continuing-medical-education/",
  "cite": "NCCPA CME page"
 },
 {
  "name": "National Certification Corporation",
  "url": "https://www.nccwebsite.org/content/documents/cms/coding-book-whc.pdf",
  "cite": "NCC WHNP-BC coding book"
 },
 {
  "name": "National Certification Corporation",
  "url": "https://www.nccwebsite.org/content/documents/cms/maintenance-core.pdf",
  "cite": "NCC 2026 Core Maintenance Catalog"
 },
 {
  "name": "National Certification Corporation",
  "url": "https://www.nccwebsite.org/maintain-your-certification/how-and-why",
  "cite": "NCC How and why page"
 },
 {
  "name": "American Nurses Credentialing Center",
  "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certification-renewal-handbook_2027.pdf",
  "cite": "ANCC Renewal Handbook, Feb 2027"
 },
 {
  "name": "American Nurses Credentialing Center",
  "url": "https://www.nursingworld.org/globalassets/certification/renewals/ancc-certrenewalrequirements.pdf",
  "cite": "ANCC Renewal Handbook (2025)"
 },
 {
  "name": "Pediatric Nursing Certification Board",
  "url": "https://www.pncb.org/sites/default/files/resources/PNCB_Recert_Guide.pdf",
  "cite": "PNCB Recertification Guide, requirements table"
 }
];
