export const CME_TOPICS = [
  "Pain Management",
  "Opioid Prescribing",
  "Controlled Substances",
  "Ethics",
  "Infection Control",
  "Patient Safety",
  "Medical Errors Prevention",
  "Risk Management",
  "Suicide Prevention",
  "Cultural Competency",
  "Implicit Bias",
  "End-of-Life Care",
  "Geriatric Medicine",
  "Domestic Violence",
  "Child Abuse Recognition",
  "Human Trafficking",
  "Pharmacology",
  "Telemedicine",
  "Sexual Harassment Prevention",
  "HIV/AIDS",
  "Palliative Care",
  "Mental Health",
  "Substance Use Disorders",
  "Prescriptive Practice",
  "Trauma-Informed Care",
  "General / No Specific Topic",
];
