// Comprehensive state CME requirements (from Feb 2026 CME Compliance Database)
// States with separate MD/DO boards have { md: {...}, do: {...} } structure.
// States with combined boards have a flat structure.
// States with NO CME requirement (IN, MT, SD) have total: 0.
//
// Provenance: every entry carries `source` (the statute or rule it came from).
// Entries checked against the regulator carry `verified: "YYYY-MM"` and, when
// the check loaded an official page, `sourceUrl` (the best primary-source URL
// for that rule set). Rules that are enacted but not yet in force, or pending
// board action, live in `upcoming: [ "..." ]` so the current numbers stay
// current and the physician still sees what is coming.
//
// PER-TOPIC provenance: a topic may carry its own `cite` and `url`. One
// `sourceUrl` per rule set is not enough to verify a single line, because a
// state's topics rarely share one authority: California's 50-hour total is
// 16 CCR 1336 while its 12-hour pain-management mandate is B&P 2190.5, and a
// physician reading "12 hrs Pain Management" was being pointed at a citation
// that does not govern that line. A topic without `cite`/`url` inherits the
// rule set's `source` and `sourceUrl`, and the UI says the link is the board's
// general page rather than the rule itself. Do not invent a URL: leave it to
// inherit when the primary source was not actually loaded.
//
// PERIODICITY is load-bearing, not cosmetic. A topic with no `period` is
// demanded EVERY renewal cycle. Several rules that the notes already described
// as one-time or multi-year carried no `period`, so the engine re-demanded
// them every cycle (Louisiana's one-time 3-hr CDS course, on a 1-year cycle,
// was being asked for annually). When adding a topic whose note says
// "one-time", "before first renewal", or "every N years", encode it.
// 2026-08-28 pass: periodicity + per-topic citations across the jurisdictions
// listed in docs/CME-RULES-CHANGELOG-2026-08.md. `verified` months were left
// as they stood except where this pass loaded the source itself.
// STATE_REQS_META dates the database as a whole. Full 2026-08 recheck:
// docs/CME-RULES-CHANGELOG-2026-08.md.
//
// `firstCycle` (optional) carries a state's FIRST-CYCLE proration as data, the
// way `cat1Accepted` carries credit types as data instead of a regex over the
// rule prose. Shapes:
//   { mode: "tiered", basis: "monthsFromIssueToExpiry",
//     tiers: [ { underMonths: N, hours: H }, ... ] }  // ascending underMonths
//   { mode: "fixed", hours: H, underMonths: N }       // single step
// The compliance engine reads it with the LICENSE ISSUE DATE (never a
// hand-entered cycle start) and shows the result BESIDE the full requirement
// with its citation. A state without the field owes its full number, always;
// showing a prorated alternative where no rule exists would invent a number.

export const STATE_REQS_META = {
  databaseDate: "2026-02",
  lastReviewed: "2026-08",
  reviewMethod: "primary-source recheck, every jurisdiction, 2026-08-17",
};

export const STATE_REQS = {
  AK: { total: 50, cycle: 2, cat1min: 50, cat1note: "All AMA Cat 1 or AOA Cat 1/2", topics: [
    { topic: "Opioid Prescribing", hours: 2.0, note: "2 hrs pain management & opioid use/addiction (DEA holders)" },
  ], notes: "2 hrs pain management & opioid use/addiction (DEA holders)", rollover: "No (max 15 hrs exemption per 5 yrs)", moc: "ABMS/AOA initial cert or recert accepted", source: "Alaska Admin. Code tit. 12, \u00a7 40.200", verified: "2026-08", sourceUrl: "https://www.commerce.alaska.gov/web/portals/5/pub/med0077.pdf" },
  AL: { total: 25, cycle: 1, cat1min: 25, cat1note: "All AMA PRA Cat 1", topics: [
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs controlled substance prescribing every 2 yrs (ACSC holders). Alabama's CME cycle is 1 year, so this is not owed every cycle.", period: { years: 2 }, cite: "Ala. Admin. Code r. 540-X-4-.09(8)" },
    { topic: "Ethics", hours: 2.0, note: "Board-designated professional boundaries course, one-time. ALBME designates a 2-hour on-demand course, Navigating Professional Boundaries in Medicine. Existing licensees by 12/31/2025, new licensees within 12 months of license issue; residents/fellows on limited license exempt.", period: "lifetime", cite: "Alabama Board of Medical Examiners, CME requirement" },
  ], notes: "2 hrs controlled substance prescribing every 2 yrs (ACSC holders); Board-designated professional boundaries course (one-time; existing licensees by 12/31/2025, new licensees within 12 months of license issue; residents/fellows on limited license exempt). ALBME designates a 2-hr on-demand course. The controlled substance hours are due every 2 yrs, not every 1-yr cycle.", rollover: "No", moc: "ABMS cert/MoC accepted as equivalent", source: "Ala. Admin. Code r. 540-X-14-.02; r. 540-X-4-.09(8) (controlled substance CME)", verified: "2026-08", sourceUrl: "https://www.albme.gov/resources/licensees/continuing-medical-education/licensure-cme-requirement" },
  AR: { total: 20, cycle: 1, cat1min: 10, cat1note: "50% must be Cat 1 in primary practice area", topics: [
    { topic: "Opioid Prescribing", hours: 1.0, note: "1 hr/yr prescribing opioids/benzodiazepines" },
    { topic: "Controlled Substances", hours: 3.0, note: "one-time 3 hrs prescribing ed (first 2 yrs)", period: "lifetime" },
  ], notes: "1 hr/yr prescribing opioids/benzodiazepines; one-time 3 hrs prescribing ed (first 2 yrs)", rollover: "No", moc: "No", source: "ASMB Rule 17 (CME) and Rule 2 (prescriber education), armedicalboard.org/professionals/pdf/mpa.pdf", verified: "2026-08", sourceUrl: "https://www.armedicalboard.org/professionals/pdf/mpa.pdf" },
  AZ: { md: { total: 40, cycle: 2, cat1min: 0, cat1note: "Not specified", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs opioid/SUD/addiction (DEA holders)" },
  ], notes: "3 hrs opioid/SUD/addiction (DEA holders)", rollover: "No", moc: "No", source: "Ariz. Admin. Code R4-16-102", verified: "2026-08", sourceUrl: "https://www.law.cornell.edu/regulations/arizona/Ariz-Admin-Code-SS-R4-16-102" }, do: { total: 40, cycle: 2, cat1min: 24, cat1note: "24 hrs AOA Cat 1-A; max 16 hrs AMA Cat 1", cat1Accepted: ["AOA Category 1-A"], topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs opioid/SUD/addiction (DEA holders)" },
  ], notes: "3 hrs opioid/SUD/addiction (DEA holders); the 24-hr minimum must be AOA Cat 1-A. Up to 16 of the 40 total may be AMA PRA Cat 1; that total-composition cap is not enforced by the compliance engine.", rollover: "No", moc: "No", source: "Ariz. Admin. Code R4-22-207", verified: "2026-08", sourceUrl: "https://www.law.cornell.edu/regulations/arizona/Ariz-Admin-Code-SS-R4-16-102" } },
  // CA pain management (B&P 2190.5), rechecked 2026-08-28: NOT repealed, no
  // sunset. leginfo shows the section operative, last amended by SB 1109 (Stats.
  // 2018, Ch. 693, Sec. 3, eff. 2019-01-01); MBC and OMBC both still publish it;
  // FSMB's Aug 2026 board-by-board overview lists it for CA-M and CA-O; no bill
  // in the 2025-26 session touches it. The "completed by December 31, 2006"
  // phrase in 2190.5(a)(1) is a lapsed transition date for physicians already
  // licensed in 2002, not an expiry: the operative rule is a rolling obligation
  // on every new licensee. It is one-time, which is what `period: "lifetime"`
  // encodes, so the app has never demanded these 12 hours twice.
  CA: { md: { total: 50, cycle: 2, cat1min: 50, cat1note: "All Cat 1 approved", topics: [
    { topic: "Pain Management", hours: 12.0, note: "One-time 12 hrs pain management and treatment of terminally ill and dying patients, due within 4 yrs of initial licensure or by the 2nd renewal, whichever comes first. Pathology and radiology specialists are exempt (2190.5(c)). For physicians licensed on or after Jan 1, 2019 the course must also cover risks of addiction associated with Schedule II drugs. Alternative: a one-time 12 credit-hr course in treatment and management of opiate-dependent patients, including 8 hrs buprenorphine training, satisfies this instead (BPC 2190.6); physicians qualified under the federal CARA of 2016 are deemed compliant.", period: "lifetime", cite: "Cal. Bus. & Prof. Code \u00a7 2190.5; alternative at \u00a7 2190.6", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=2190.5" },
    { topic: "Geriatric Medicine", hours: 0, note: "General internists and family physicians whose patient population is more than 25% aged 65 or older must complete at least 20% of their mandatory CME in geriatric medicine; the board publishes no fixed hour count", cite: "Medical Board of California, Continuing Medical Education" },
    { topic: "Implicit Bias", hours: 0, note: "AB 241 is a curriculum requirement on CME course providers and accrediting entities, not an hour requirement on the physician: courses must contain implicit bias content. There is no number of implicit bias hours to log and no separate certificate to produce at audit.", cite: "Cal. Bus. & Prof. Code \u00a7 2190.1 (AB 241, Stats. 2019, Ch. 417)" },
  ], notes: "One-time 12 hrs pain management/treatment of terminally ill and dying patients (within 4 yrs of initial licensure or by the 2nd renewal, whichever comes first; pathology and radiology exempt; a one-time 12-hr opiate-dependence course under BPC 2190.6 is an accepted alternative); geriatrics if >25% patients 65+; implicit bias is a curriculum requirement on CME providers under AB 241, not physician hours", rollover: "No", moc: "ABMS cert/recert = 4 yrs (100 hrs) credit", source: "Cal. Code Reg. tit. 16, \u00a7 1336 (50 hrs biennially); Cal. Bus. & Prof. Code \u00a7 2190.5 (pain management); \u00a7 2190.1 (AB 241)", verified: "2026-08", sourceUrl: "https://www.mbc.ca.gov/Licensing/Physicians-and-Surgeons/Renew/Current-Status/Continuing-Medical-Education.aspx" }, do: { total: 50, cycle: 2, cat1min: 20, cat1note: "20 hrs AOA Cat 1A or 1B", cat1Accepted: ["AOA Category 1-A", "AOA Category 1-B"], topics: [
    { topic: "Pain Management", hours: 12.0, note: "One-time 12 hrs pain management and treatment of terminally ill and dying patients, within 4 yrs of licensure or by the 2nd renewal, whichever comes first; pathology and radiology specialists exempt. Alternative: a one-time 12 credit-hr course in treatment and management of opiate-dependent patients, including 8 hrs buprenorphine training, satisfies this instead (BPC 2190.6).", period: "lifetime", cite: "Cal. Bus. & Prof. Code \u00a7 2190.5; alternative at \u00a7 2190.6", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=BPC&sectionNum=2190.5" },
    { topic: "Substance Use Disorders", hours: 1.0, note: "Min 1 hr on addiction to Schedule II drugs or opioids, due every renewal cycle. OMBC draws the contrast explicitly: unlike the one-time mandates, this is a condition of every renewal. It may also count toward the one-time 12-hr pain management course if taken during the cycle in which that course is due.", cite: "Cal. Bus. & Prof. Code \u00a7 2454.5(d) (SB 1109); OMBC CME document eff. 2025-10-01" },
    { topic: "Implicit Bias", hours: 0, note: "AB 241 is a curriculum requirement on CME providers and accrediting entities, not an hour requirement on the physician. OMBC states it plainly: CME accrediting entities have responsibility to create compliant curriculum.", cite: "Cal. Bus. & Prof. Code \u00a7 2190.1 (AB 241, Stats. 2019, Ch. 417)" },
  ], notes: "One-time 12 hrs pain management/terminally ill (within 4 yrs of licensure or by 2nd renewal, whichever comes first; pathology and radiology exempt; a one-time 12-hr opiate-dependence course under BPC 2190.6 is an accepted alternative); min 1 hr Schedule II/opioid addiction every renewal cycle; implicit bias is a curriculum requirement on CME providers under AB 241, not physician hours; practice management, technology and billing/coding coursework plus medical school teaching capped at 30% of required hours (BPC 2190.15). 50/2yr + 20 AOA 1-A/1-B verified vs OMBC 2026-07", rollover: "No", moc: "No", source: "OMBC (Cal. B&P Code \u00a7 2454.5); \u00a7 2190.5 (one-time pain management); \u00a7 2190.15 (practice management cap); \u00a7 2190.1 (AB 241)", verified: "2026-08", sourceUrl: "https://www.ombc.ca.gov/licensees/cme.pdf" } },
  CO: { total: 30, cycle: 2, cat1min: 30, cat1note: "All 30 hrs must be from accepted programs: AMA PRA Category 1 (ACCME), AAFP Prescribed credit, AOA Category 1-A, or programs required to maintain national board certification (not self-claimed). Applies to renewals on or after Jan 1 2026.", cat1Accepted: ["AMA PRA Category 1", "AOA Category 1-A"], firstCycle: {
    mode: "tiered", basis: "monthsFromIssueToExpiry",
    // DORA's published table, the same 22/15/10/5/0 this entry's `notes` field
    // already records. C.R.S. 12-240-130.5 commands the proration ("the board
    // shall adjust proportionately... to ensure that a physician is not
    // required to obtain thirty CME credit hours in fewer than twenty-four
    // months"); DORA implements it in these steps. The loaded table stops at
    // 20 months, so an initial license issued 20-24 months before expiration
    // is not covered here and owes the full 30 until that band is verified.
    tiers: [
      { underMonths: 4, hours: 0 },
      { underMonths: 6, hours: 5 },
      { underMonths: 12, hours: 10 },
      { underMonths: 18, hours: 15 },
      { underMonths: 20, hours: 22 },
    ],
    note: "First renewal on an initial CO license issued less than 24 months before expiration is prorated (22/15/10/5/0 hrs by time licensed). The board may also waive the first renewal entirely if you were licensed within 12 months of finishing training.",
    source: "C.R.S. 12-240-130.5; Colorado DORA Physician CME page",
  }, topics: [
  ], notes: "30 hrs accepted CME per 2-yr renewal. The 2-hr substance use disorder training requirement was REPEALED by SB 26-138 (signed 2026-06-02, eff. 2026-08-12); the Colorado Medical Board held its permanent rulemaking hearing on 2026-08-27 and the Board CME page no longer lists it. Do not complete it for renewal. Prorated for a first renewal under 24 months (22/15/10/5/0 hrs by time licensed). Board may audit up to 5% of physicians annually, oversampling non-board-certified. Board may waive first renewal if licensed within 12 months of finishing training. Verified vs DORA and CRS 12-240-130.5, 2026-08.", rollover: "No", moc: "Programs required to maintain national board certification count toward the 30 hrs", source: "HB 24-1153 (effective 2026-01-01)", verified: "2026-08", sourceUrl: "https://dpo.colorado.gov/Medical/CME", upcoming: [
    "Board stakeholder process (per CRS 12-240-130.5(7)(b)(II)) is considering required CME in health disparities and outcomes data, reproductive/sexual/gender-based health care, and explicit/implicit bias; no adopted rule or hour count found in loaded sources; any mandate must fit within the 30 hrs",
  ] },
  CT: { total: 50, cycle: 2, cat1min: 0, cat1note: "Not specified", topics: [
    { topic: "Infection Control", hours: 1.0, note: "infectious diseases including AIDS/HIV, first renewal in which CME is required, then once every 6 years", period: { years: 6 } },
    { topic: "Risk Management", hours: 1.0, note: "includes prescribing controlled substances and pain management, plus screening for inflammatory breast cancer, GI cancers and endometriosis; first renewal in which CME is required, then once every 6 years", period: { years: 6 } },
    { topic: "Sexual Assault", hours: 1.0, note: "first renewal in which CME is required, then once every 6 years", period: { years: 6 } },
    { topic: "Domestic Violence", hours: 1.0, note: "first renewal in which CME is required, then once every 6 years", period: { years: 6 } },
    { topic: "Cultural Competency", hours: 1.0, note: "includes systemic racism, explicit and implicit bias, racial disparities, and care of transgender and gender diverse persons; first renewal in which CME is required, then once every 6 years", period: { years: 6 } },
    { topic: "Behavioral Health", hours: 2.0, note: "mental health conditions common to veterans and their families (PTSD, suicide risk, depression, grief), or suicide prevention, or cognitive conditions (Alzheimer's, dementia, delirium); first renewal in which CME is required, then once every 6 years", period: { years: 6 } },
  ], notes: "Six mandated topics (infectious diseases, risk management, sexual assault, domestic violence, cultural competency, behavioral health) required in the first renewal in which CME is required and then once every 6 years. CME is not required for the first license renewal. Same rule for MD and DO.", rollover: "No (up to 10 hr waiver for Board service)", moc: "No", source: "Conn. Gen. Stat. \u00a7 20-10b", verified: "2026-08", sourceUrl: "https://portal.ct.gov/dph/practitioner-licensing--investigations/physician/continuing-medical-education" },
  DC: { total: 50, cycle: 2, cat1min: 50, cat1note: "All Cat 1; 10% (5 hrs) in public health priorities", topics: [
    { topic: "Cultural Competency", hours: 2.0, note: "2 hrs LGBTQ cultural competency" },
    { topic: "Pharmacology", hours: 0, note: "1 pharmacology course" },
  ], notes: "2 hrs LGBTQ cultural competency; 1 pharmacology course", rollover: "No", moc: "No", source: "D.C. Mun. Regs. tit.17, \u00a7 4607.4", verified: "2026-08", sourceUrl: "https://dchealth.dc.gov/bomed" },
  DE: { total: 40, cycle: 2, cat1min: 40, cat1note: "All AMA or AOA Cat 1", topics: [
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs controlled substance prescribing, chronic pain, or related topics biennially, required of every Delaware controlled substance registration (CSR) holder", cite: "24 Del. Admin. Code Uniform Controlled Substances Act Regs. 3.1" },
    { topic: "Delaware Controlled Substance Law", hours: 1.0, note: "One-time 1 hr course on Delaware controlled substance law, within the first year of CSR registration. Was described only inside the biennial line, so it was never checked on its own.", period: "lifetime", cite: "24 Del. Admin. Code Uniform Controlled Substances Act Regs. 3.1" },
  ], notes: "2 hrs controlled substance prescribing, chronic pain, or related topics biennially (every Delaware CSR holder); one-time 1 hr Delaware controlled substance law course within the first year of CSR registration", rollover: "No", moc: "No", source: "24 Del. Admin. Code 1700-12.0; 24 DE Admin Code Uniform Controlled Substances Act Regulations 3.1; 24 Del. C. 1713(d)", verified: "2026-08", sourceUrl: "https://dpr.delaware.gov/boards/medicalpractice/continuing-education-and-audit-information/", upcoming: [
    "Alzheimer's/dementia CE (24 Del. C. 1713(d)): 2 hrs of the 40 required at the 2027 renewal (cycle ending March 31, 2027) and each renewal after; exempt with attestation if no direct care of adults age 26+, no practice in Delaware, or previously completed in a prior period (so effectively one-time once done). Not yet reflected in Board regulation 1700-12.0.",
  ] },
  FL: { md: { total: 40, cycle: 2, cat1min: 0, cat1note: "Cat 1 for required topics", topics: [
    { topic: "HIV/AIDS", hours: 1.0, note: "1 hr HIV/AIDS, one-time, due by first renewal", period: "lifetime" },
    { topic: "Medical Errors Prevention", hours: 2.0, note: "2 hrs medical errors" },
    { topic: "Domestic Violence", hours: 2.0, note: "2 hrs domestic violence (every 3rd renewal)", period: { years: 6 } },
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs prescribing controlled substances, each renewal, DEA registrants only" },
    { topic: "Human Trafficking", hours: 1.0, note: "1 hr human trafficking, one-time (s. 456.0341; deadline was Jan 1, 2021; counts toward the 40)", period: "lifetime" },
  ], notes: "2 hrs medical errors; 2 hrs controlled substances (DEA registrants); 2 hrs domestic violence every 3rd renewal; 1 hr HIV/AIDS one-time by first renewal; 1 hr human trafficking one-time", rollover: "No", moc: "No", source: "Fla. Admin. Code. Ann. r. 64B8-13.005", verified: "2026-08", sourceUrl: "https://flboardofmedicine.gov/medical-doctor-renewal/" }, do: { total: 40, cycle: 2, cat1min: 20, cat1note: "20 hrs AOA Cat 1-A", topics: [
    { topic: "HIV/AIDS", hours: 1.0, note: "1 hr HIV/AIDS, one-time, no later than first renewal", period: "lifetime" },
    { topic: "Medical Errors Prevention", hours: 2.0, note: "2 hrs medical errors" },
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs prescribing controlled substances, each renewal, DEA registrants only" },
    { topic: "Florida Laws and Rules", hours: 1.0, note: "1 hr Florida Laws and Rules/Professional and Medical Ethics, each renewal" },
    { topic: "Domestic Violence", hours: 2.0, note: "2 hrs domestic violence, every third biennial renewal", period: { years: 6 } },
    { topic: "Human Trafficking", hours: 1.0, note: "1 hr human trafficking, one-time (s. 456.0341)", period: "lifetime" },
  ], notes: "2 hrs medical errors; 1 hr FL laws and rules/ethics; 2 hrs controlled substances (DEA registrants); 2 hrs domestic violence every 3rd renewal; 1 hr HIV/AIDS one-time by first renewal; 1 hr human trafficking one-time; max 8 hrs home study", rollover: "No", moc: "No", source: "Fla. Admin. Code. Ann. r. 64B15-13.001", verified: "2026-08", sourceUrl: "https://floridasosteopathicmedicine.gov/renewals/osteopathic-physician-renewal/" } },
  GA: { total: 40, cycle: 2, cat1min: 0, cat1note: "AMA Cat 1, AOA Cat 1, AAFP, ACOG, or ACEP Cat 1", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs Cat 1 controlled substance prescribing, one-time (active DEA holders who prescribe controlled substances; not required if meeting the 20 hr pain mgmt rule)", period: "lifetime" },
    { topic: "Sexual Harassment Prevention", hours: 2.0, note: "one-time 2 hr professional boundaries/sexual misconduct course", period: "lifetime" },
  ], notes: "one-time 3 hrs Cat 1 controlled substance prescribing (DEA holders); one-time 2 hr professional boundaries/sexual misconduct course; 20 hrs pain mgmt per cycle if 50% or more opioid pain patients and no pain/palliative certification", rollover: "No (waivers: up to 10 hrs per biennium for uncompensated care at 1 hr per 4 hrs worked; up to 8 hrs per biennium for Board peer review at 2 hrs per case)", moc: "Not addressed in rule; Board accepts only AMA Cat 1, AOA Cat 1, AAFP Prescribed, ACOG Cat 1 Cognates, ACEP Cat 1", source: "Ga. Comp. R. & Regs. 360-15-.01", verified: "2026-08", sourceUrl: "https://medicalboard.georgia.gov/professional-resources/continuing-education-and-other-required-training-physicians" },
  GU: { total: 50, cycle: 2, cat1min: 13, cat1note: "25% must be Cat 1 (13 of 50; statute and board form still disagree, confirm with the board)", topics: [], notes: "Board FAQ lists 50 credit hours per 2-year renewal cycle. 25 GAR \u00a711103(c)(2) (1997) still reads 100 hours with 25% Category I, and the GBME-9 CME report form reads 100 hours with 50 Category I. Confirm the current figure with the board. Renew by December 31 of odd-numbered years. CME requirement is deemed met with a current AMA PRA or similar accrediting certification (\u00a711103(d)).", rollover: "No", moc: "", source: "25 GAR Prof. & Voc. Regs \u00a7 11103(c)(2); GBME FAQ", verified: "2026-08", sourceUrl: "https://guamhplo.org/gbme/faqs" },
  HI: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1 or 1A", topics: [], notes: "MD renews by Jan 31 of even years, DO by June 30 of even years, both under the Hawaii Medical Board. First renewal after initial licensure: 20 hours. Meeting a specialty society or board CME requirement of 40+ hours, or a current AMA PRA, satisfies the requirement. Board certification alone, passing a board exam, membership, or teaching do not count.", rollover: "No", moc: "No", source: "Haw. Admin. R. \u00a716-85-33", verified: "2026-08", sourceUrl: "https://cca.hawaii.gov/pvl/boards/medical/physician-podiatrist-and-emt-continuing-education-requirements/" },
  IA: { total: 40, cycle: 2, cat1min: 40, cat1note: "All 40 hours must be Category 1 (or board-approved equivalent such as ABMS/AOA certification)", topics: [
    { topic: "Child Abuse Recognition", hours: 2.0, note: "2 hrs child abuse identification and reporting every 3 yrs (licensees who regularly provide primary health care to children, incl. EM, FM, GP, peds, psychiatry)", period: { years: 3 }, cite: "Iowa Admin. Code r. 481-654.3(1)(c)(1)" },
    { topic: "Dependent Adult Abuse", hours: 2.0, note: "2 hrs dependent adult abuse identification and reporting every 3 yrs (adult primary care providers)", period: { years: 3 }, cite: "Iowa Admin. Code r. 481-654.3(1)(c)(2)" },
    { topic: "Opioid Prescribing", hours: 2.0, note: "2 hrs Category 1 credit on CDC guidelines for opioid prescribing every 5 yrs (licensees who prescribed opioids in the prior license period)", period: { years: 5 }, cite: "Iowa Admin. Code r. 481-654.3(1)(d)(1)" },
    { topic: "End-of-Life Care", hours: 2.0, note: "2 hrs Category 1 credit for end-of-life care every 5 yrs (if regularly caring for actively dying patients)", period: { years: 5 }, cite: "Iowa Admin. Code r. 481-654.3(1)(e)" },
  ], notes: "2 hrs child abuse every 3 yrs (pediatric primary care providers, incl. EM, FM, GP, peds, psychiatry); 2 hrs dependent adult abuse every 3 yrs (adult primary care providers); 2 hrs opioid prescribing every 5 yrs (if prescribed); 2 hrs end-of-life care every 5 yrs (if regularly caring for actively dying patients)", rollover: "Yes (up to 20 hrs)", moc: "ABMS/AOA cert or recert = 50 hrs Cat 1", source: "Iowa Admin. Code r. 481-654.3 (formerly 653-11; transferred IAC Supp. 6/11/25)", verified: "2026-08", sourceUrl: "https://www.legis.iowa.gov/docs/iac/chapter/481.654.pdf" },
  ID: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1", topics: [], notes: "Not specified", rollover: "No", moc: "ABMS/AOA/RCPSC cert or recert accepted", source: "Idaho Admin. Code r. 22.01.01-079", verified: "2026-08", sourceUrl: "https://dopl.idaho.gov/bom/" },
  IL: { total: 150, cycle: 3, cat1min: 60, cat1note: "60 hrs Cat 1", topics: [
    { topic: "Sexual Harassment Prevention", hours: 1.0, note: "1 hr sexual harassment prevention (each cycle)", cite: "68 Ill. Admin. Code \u00a7 1285.110" },
    { topic: "Implicit Bias", hours: 1.0, note: "1 hr implicit bias (each cycle)", cite: "68 Ill. Admin. Code \u00a7 1285.110" },
    { topic: "Opioid Prescribing", hours: 1.0, note: "1 hr safe opioid prescribing each renewal cycle, only if you hold an Illinois controlled substance license", cite: "720 ILCS 570/315.5" },
    { topic: "Cultural Competency", hours: 1.0, note: "1 hr cultural competency, before the first renewal that requires CE then retaken once every 6 years (renewals on or after Jan 1, 2025)", period: { years: 6 }, cite: "IDFPR Continuing Education requirements" },
    { topic: "Alzheimer's Disease and Other Dementias", hours: 1.0, note: "1 hr Alzheimer's disease and other dementias, before the first renewal that requires CE then once every 6 years (renewals on or after Jan 1, 2025)", period: { years: 6 }, cite: "IDFPR Continuing Education requirements" },
    { topic: "Mandated Reporter Training", hours: 1.0, note: "1 hr mandated reporter training, at least once every 6 years, attested at each renewal. Was described in the state notes but had no line of its own, so it was never checked.", period: { years: 6 }, cite: "IDFPR Continuing Education requirements" },
  ], notes: "1 hr sexual harassment prevention (each cycle); 1 hr implicit bias (each cycle); 1 hr safe opioid prescribing each cycle if you hold an IL controlled substance license; 1 hr cultural competency and 1 hr Alzheimer's/dementia, each once every 6 years; 1 hr mandated reporter training every 6 years. All count toward the 150.", rollover: "No", moc: "Board cert/licensure CME from other states accepted", source: "Ill. Admin. Code tit.68, \u00a7 1285.110; 720 ILCS 570/315.5", verified: "2026-08", sourceUrl: "https://idfpr.illinois.gov/dpr/continuing-education.html", upcoming: [
    "2026 physician renewal deadline extended from July 31 to August 31, 2026 (IDFPR notice, one-time extension, not a rule change)",
  ] },
  IN: { total: 0, cycle: 0, cat1min: 0, cat1note: "", topics: [], notes: "No CME requirement", rollover: "No", moc: "", source: "No statutory CME requirement", verified: "2026-08", sourceUrl: "https://www.in.gov/pla/professions/physicians-home/physicians-licensing-information/" },
  KS: { total: 50, cycle: 1, cat1min: 20, cat1note: "20 Cat 1 per year (or 40/100 per 2/3-yr cycle)", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "1-3 hrs (per cycle length) pain mgmt/opioid prescribing/PDMP" },
  ], notes: "1-3 hrs (per cycle length) pain mgmt/opioid prescribing/PDMP", rollover: "No", moc: "No", source: "Kan. Admin. Regs. \u00a7 100-15-5", verified: "2026-08", sourceUrl: "https://sos.ks.gov/publications/Register/Volume-40/Issues/Issue%2016/04-22-21-49068.html" },
  KY: { total: 60, cycle: 3, cat1min: 30, cat1note: "30 hrs Cat 1", topics: [
    { topic: "Controlled Substances", hours: 4.5, note: "4.5 hrs Cat 1 KASPER/pain mgmt/addiction per cycle (controlled substance prescribers, prorated 3 or 1.5 hrs if first authorized mid-cycle)" },
    { topic: "Domestic Violence", hours: 3.0, note: "3 hrs domestic violence, one-time, within 3 yrs of initial licensure. Primary care physicians licensed after July 1, 1996: family/general practice, pediatrics, internal medicine, emergency medicine, OB/GYN, preventive medicine/public health.", period: "lifetime", cite: "Kentucky Board of Medical Licensure, CME requirements" },
    { topic: "Pediatric Abusive Head Trauma", hours: 1.0, note: "1 hr pediatric abusive head trauma, one-time, within 5 yrs of licensure (pediatrics, radiology, family medicine, emergency medicine, urgent care)", period: "lifetime", cite: "Kentucky Board of Medical Licensure, CME requirements" },
  ], notes: "4.5 hrs Cat 1 KASPER/pain mgmt/addiction per cycle (controlled substance prescribers, prorated 3 or 1.5 hrs if first authorized mid-cycle); 3 hrs domestic violence one-time (primary care); 1 hr pediatric abusive head trauma one-time (peds, radiology, FM, EM, urgent care); 12 hrs Cat 1 addiction medicine per cycle for buprenorphine prescribers (201 KAR 9:270)", rollover: "No", moc: "Yes (passing an ABMS or AOA board certification or recertification exam counts as 60 hrs Cat 1, satisfies full cycle)", source: "201 KAR 9:310", verified: "2026-08", sourceUrl: "https://kbml.ky.gov/cme/Pages/default.aspx" },
  LA: { total: 20, cycle: 1, cat1min: 20, cat1note: "All Cat 1", topics: [
    { topic: "Controlled Substances", hours: 3.0, note: "One-time 3 hr CDS prescribing CME, completed before the first renewal (CDS holders; exemption if no CDS prescribed in the prior year)", period: "lifetime", cite: "La. Admin. Code tit. 46, pt. XLV \u00a7 4005", url: "https://lsbme.la.gov/content/board-approved-cme-courses-cds-requirements" },
    { topic: "Nutrition / Metabolic Health", hours: 1.0, note: "1 hr nutrition/metabolic health every 4 yrs, counted within the 20 hrs; applies to physicians practicing family medicine, internal medicine, pediatrics, psychiatry, endocrinology, gastroenterology, cardiology, oncology, rheumatology, neurology, nephrology, dermatology, pulmonology, surgery, immunology, hematology, obstetrics, gynecology (eff. Jan 1, 2026)", period: { years: 4 }, cite: "La. Admin. Code tit. 46, pt. XLV \u00a7 447" },
    { topic: "Sickle Cell (Emergency Medicine)", hours: 1.0, note: "Physicians (and PAs) practicing emergency medicine: initial 1 hr board-approved course on treatment of sickle cell disease, then 1 hr refresher at least every 3 yrs (eff. Aug 1, 2024). Board-approved course to be posted on lsbme.la.gov; not located on the site during this check.", period: { years: 3 }, cite: "Louisiana State Board of Medical Examiners, sickle cell CME requirement (eff. 2024-08-01)" },
  ], notes: "One-time 3 hr CDS prescribing CME before first renewal (CDS holders; exemption if no CDS prescribed in prior year); one-time Laws and Rules Course before first renewal (hour-for-hour credit); 1 hr nutrition/metabolic health every 4 yrs for listed specialties (eff. Jan 1, 2026, counts within the 20); emergency medicine: 1 hr sickle cell initial then 1 hr every 3 yrs; ABMS/AOA certification or recertification within past year satisfies annual CME; CE Broker tracking mandatory; renewal in birth month.", rollover: "No", moc: "Yes: annual CME requirement does not apply to a physician certified or recertified by an ABMS member board or AOA-recognized specialty board within the past year (LAC 46:XLV.447.A.3). Note: initial-renewal Laws and Rules course and CDS CME are still required (\u00a7447 is subject to \u00a7449).", source: "La. Admin. Code tit. 46, pt. XLV \u00a7\u00a7435-449, \u00a74005; R.S. 37:1270(A)(8)", verified: "2026-08", sourceUrl: "https://www.lsbme.la.gov/content/board-orientations-online-courses", upcoming: [
    "Pending LAC 46:XLV.417/418/435/447 amendment (Notice of Intent Jan 2026 Register 52 LR 114, OLRP review Apr-May 2026): CME credit for medical review panel service and reporting updates; no change to the 20 hr total. Final adoption date not confirmed.",
  ] },
  MA: { total: 50, cycle: 2, cat1min: 0, cat1note: "Cat 1 or 2 (ACCME/AOA/AAFP accredited)", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs opioid/pain mgmt (if prescribing controlled substances)" },
    { topic: "Risk Management", hours: 10.0, note: "10 hrs risk mgmt (Cat 1 or 2, up to 7 hrs wellness/burnout count)" },
    { topic: "End-of-Life Care", hours: 2.0, note: "2 hrs end-of-life issues, one-time", period: "lifetime", cite: "BORIM Policy 17-05; Final Amended CME Guidelines" },
    { topic: "Electronic Health Records", hours: 3.0, note: "3 hrs EHR proficiency, may count toward risk management. Published BORIM summaries disagree on whether this is one-time or per cycle, so it is counted every cycle here, the stricter reading, until Policy 17-05 is read directly.", cite: "BORIM Policy 17-05 (periodicity unresolved)" },
    { topic: "Implicit Bias", hours: 2.0, note: "2 hrs implicit bias, one-time (adopted effective June 1, 2022, at initial licensure or renewal if not previously completed); counts toward risk management", period: "lifetime", cite: "BORIM Policy 2021-04, one-time 2.00 credits (eff. 2022-06-01)", url: "https://www.mass.gov/info-details/continuing-medical-education-on-implicit-bias-in-healthcare" },
    { topic: "Child Abuse Recognition", hours: 0, note: "Child abuse and neglect training, one-time, no hour minimum", period: "lifetime", cite: "BORIM Policy 17-05; Final Amended CME Guidelines" },
    { topic: "Domestic Violence", hours: 0, note: "Domestic and sexual violence training, DPH-approved course, one-time, no hour minimum", period: "lifetime", cite: "BORIM Policy 17-05; Final Amended CME Guidelines" },
    { topic: "Geriatric Medicine", hours: 1.0, note: "1 hr Alzheimer's/dementia, one-time, if serving adult populations", period: "lifetime", cite: "BORIM Policy 17-05; Final Amended CME Guidelines" },
  ], notes: "Per cycle: 3 hrs opioid/pain mgmt (if prescribing controlled substances); 10 hrs risk mgmt (Cat 1 or 2, up to 7 hrs wellness/burnout count); 2 hrs reading Board regs. One-time: 2 hrs end-of-life; 3 hrs EHR; 2 hrs implicit bias; 1 hr Alzheimer's (adult populations); child abuse training; domestic/sexual violence training", rollover: "No", moc: "Yes: ABMS/AOA board certification or recertification = 60 Cat 1 credits incl. 4 risk mgmt, applied to the cycle in which pass notice is received", source: "BORIM Policy 17-05 (amended 4/11/2024); Final Amended CME Guidelines (amended 4/11/2024); Policy 94-05 (amended 3/28/2024)", verified: "2026-08", sourceUrl: "https://www.mass.gov/info-details/general-physician-licensing-questions" },
  MD: { total: 50, cycle: 2, cat1min: 25, cat1note: "25 hrs Cat 1", topics: [
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs CE on prescribing or dispensing controlled dangerous substances, one-time, required by MDH OCSA for CDS registration (new or first renewal on or after Oct 1, 2018), not a Board of Physicians renewal requirement", period: "lifetime", cite: "MDH Office of Controlled Substances Administration; MBP 2026 renewal information" },
    { topic: "Implicit Bias", hours: 0, note: "One-time implicit bias training, ACCME-accredited or board-recognized. The Board states that licensees who completed an implicit bias program for a prior renewal are not required to complete another.", period: "lifetime", cite: "Md. Board of Physicians 2026 renewal information" },
    { topic: "Structural Racism", hours: 0, note: "One-time structural racism training, separate from implicit bias, for licensees renewing for the first time after April 1, 2026. ACCME-accredited or board-recognized program. Was bundled into the implicit bias line, so a physician who had done implicit bias but not this showed compliant.", period: "lifetime", cite: "Md. Health Occ. \u00a7 1-225; MBP 2026 renewal information" },
  ], notes: "2 hrs controlled substance prescribing CE, one-time, for CDS registration; one-time implicit bias training; one-time structural racism training at first renewal after April 1, 2026; CME requirement waived at first renewal after initial licensure", rollover: "No", moc: "Active time-limited ABMS/AOA cert accepted (within 5 yrs)", source: "COMAR 10.32.01.10", verified: "2026-08", sourceUrl: "https://www.mbp.state.md.us/forms/2026_renewal_info.pdf" },
  ME: { md: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs opioid prescribing every 2 yrs", cite: "32 M.R.S. \u00a7 3300-F(4)", url: "https://legislature.maine.gov/statutes/32/title32sec3300-F.html" },
  ], notes: "3 hrs opioid prescribing every 2 yrs", rollover: "No", moc: "Yes: current ABMS certification with MOC counts as the 40 Cat 1 hrs (lifetime certs excluded); 3 hrs opioid CME still required", source: "ME BLM Rules ch. 1 s. 11 (amended eff. Feb 3, 2026); 32 M.R.S. § 3300-F(4); ME BLM CME Information", verified: "2026-08", sourceUrl: "https://www.maine.gov/md/licensure/license-faq" }, do: { total: 100, cycle: 2, cat1min: 0, cat1note: "40 hrs osteopathic medical ed; primary care: all AOA Cat 1", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs opioid prescribing every 2 yrs, applies to DOs who prescribe opioids", cite: "32 M.R.S. \u00a7 2600-C" },
  ], notes: "3 hrs opioid prescribing every 2 yrs (DOs who prescribe opioids, 32 MRS 2600-C)", rollover: "No", moc: "No", source: "02 ME Code Rules \u00a7 383-14-1", verified: "2026-08", sourceUrl: "https://legislature.maine.gov/statutes/32/title32sec2600-C.html" } },
  MI: { md: { total: 150, cycle: 3, cat1min: 75, cat1note: "75 hrs Cat 1", topics: [
    { topic: "Ethics", hours: 1.0, note: "1 hr medical ethics" },
    { topic: "Pain Management", hours: 3.0, note: "3 hrs pain/symptom management" },
    { topic: "Implicit Bias", hours: 3.0, note: "1 hr of implicit bias training for EACH YEAR of the license cycle. Michigan physicians renew every 3 years, so a renewal owes 3 hrs. Hours earned in one cycle may not be carried forward. Initial licensure is a separate 2 hrs within the 5 years preceding issuance.", cite: "Mich. Admin. Code R 338.7004", url: "https://ars.apps.lara.state.mi.us/AdminCode/DownloadAdminCodeFile?FileName=R+338.7001+to+R+338.7005.pdf&ReturnHTML=True" },
    { topic: "Human Trafficking", hours: 0, note: "One-time human trafficking training. LARA treats it as a one-time training that is not part of the continuing education requirement, though a CE activity may satisfy it.", period: "lifetime", cite: "LARA human trafficking training requirement (one-time)" },
    { topic: "Opioid Awareness", hours: 0, note: "One-time opioids and controlled substance awareness training, controlled substance licensees only", period: "lifetime", cite: "Mich. Admin. Code R 338.3135" },
  ], notes: "1 hr medical ethics; 3 hrs pain/symptom management; 3 hrs implicit bias per 3-yr cycle (1 hr for each year of the cycle, R 338.7004; no carry-forward); one-time human trafficking; one-time opioid/controlled substance awareness training (controlled substance licensees)", rollover: "No", moc: "30 hrs for ABMS MOC activities", source: "LARA MD Licensing Guide", verified: "2026-08", sourceUrl: "https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/medical/medical-doctor-licensing-guides-and-faqs/md-licensing-guide-and-faqs" }, do: { total: 150, cycle: 3, cat1min: 60, cat1note: "60 hrs Cat 1, at least 40 of them AOA or MOA approved", topics: [
    { topic: "Ethics", hours: 1.0, note: "1 hr medical ethics" },
    { topic: "Controlled Substances", hours: 3.0, note: "3 hrs pain/symptom management (1 hr controlled substances)" },
    { topic: "Implicit Bias", hours: 3.0, note: "1 hr of implicit bias training for EACH YEAR of the license cycle. Michigan physicians renew every 3 years, so a renewal owes 3 hrs. Hours earned in one cycle may not be carried forward. Initial licensure is a separate 2 hrs within the 5 years preceding issuance.", cite: "Mich. Admin. Code R 338.7004", url: "https://ars.apps.lara.state.mi.us/AdminCode/DownloadAdminCodeFile?FileName=R+338.7001+to+R+338.7005.pdf&ReturnHTML=True" },
    { topic: "Human Trafficking", hours: 0, note: "One-time human trafficking training. LARA treats it as a one-time training that is not part of the continuing education requirement, though a CE activity may satisfy it.", period: "lifetime", cite: "LARA human trafficking training requirement (one-time)" },
    { topic: "Opioid Awareness", hours: 0, note: "One-time opioids and controlled substance awareness training, controlled substance licensees only", period: "lifetime", cite: "Mich. Admin. Code R 338.3135" },
  ], notes: "1 hr medical ethics; 3 hrs pain/symptom management (1 hr controlled substances); 3 hrs implicit bias per 3-yr cycle (1 hr for each year of the cycle, R 338.7004; no carry-forward); one-time human trafficking; one-time opioid/controlled substance awareness training (controlled substance licensees)", rollover: "No", moc: "No", source: "LARA DO Licensing Guide", verified: "2026-08", sourceUrl: "https://ars.apps.lara.state.mi.us/AdminCode/DownloadAdminCodeFile?FileName=R+338.111+to+R+338.143.pdf&ReturnHTML=True" } },
  MN: { total: 75, cycle: 3, cat1min: 75, cat1note: "All Cat 1", topics: [], notes: "Not specified", rollover: "No", moc: "ABMS/AOA/RCPSC cert or recert accepted", source: "Minnesota Rules, parts 5605.0100 and 5605.0300", verified: "2026-08", sourceUrl: "https://mn.gov/boards/medical-practice/licensing/continuing-ed/" },
  MO: { total: 50, cycle: 2, cat1min: 50, cat1note: "All AMA Cat 1, AOA Cat 1A/2A, or AAFP Prescribed (or 40 hrs AMA Cat 1/AOA 1A, each activity with post-test)", topics: [
    { topic: "Nutrition / Metabolic Health", hours: 1.0, note: "1 hr on the health benefits of nutrition, per 2-year cycle, within the 50 hrs; all licensees" },
  ], notes: "Cycle is fixed calendar: Jan 1 even year to Dec 31 odd year. Exempt in initial licensure period; residency/fellowship 60+ days in period counts as full compliance.", rollover: "No", moc: "ABMS cert/recert during reporting period accepted", source: "20 CSR 2150-2.125", verified: "2026-08", sourceUrl: "https://www.sos.mo.gov/cmsimages/adrules/csr/current/20csr/20c2150-2.pdf" },
  MP: { total: 50, cycle: 2, cat1min: 50, cat1note: "All Cat 1", topics: [], notes: "Not specified", rollover: "No", moc: "No", source: "Title 185-10-4215", verified: "2026-08", sourceUrl: "https://cnmilaw.org/pdf/admincode/T185/T185-10.pdf" },
  MS: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1", topics: [
    { topic: "Controlled Substances", hours: 8.0, note: "One-time 8-hour DEA training on opioid or other substance use disorders for licensees holding an active DEA registration; the 5-hour per-cycle prescribing requirement was removed from Rule 2.1. This is the same one-time federal training the MATE Act line tracks, not a second 8 hours.", period: "lifetime", cite: "30 Miss. Admin. Code Pt. 2610 Ch. 2, R. 2.1; Controlled Substances Act \u00a7 303" },
  ], notes: "DEA registrants: one-time 8-hour DEA opioid/SUD training satisfies the Board's controlled substance requirement. Licensees must keep CME in a Board-approved tracker (CE Broker, ACCME, ABMS, AOA); active ABMS/AOA certification exempts from the tracker. Cycle runs July 1 to June 30 of even years, certified at renewal in even years.", rollover: "No", moc: "No", source: "30 Miss. Admin. Code Pt. 2610 Ch. 2, Rule 2.1 (amended, effective Feb 27, 2026)", verified: "2026-08", sourceUrl: "https://www.msbml.ms.gov/licensure/cme-requirements" },
  MT: { total: 0, cycle: 0, cat1min: 0, cat1note: "", topics: [], notes: "No CME requirement", rollover: "No", moc: "", source: "No statutory CME requirement", verified: "2026-08", sourceUrl: "https://boards.bsd.dli.mt.gov/medical-examiners/faq" },
  NC: { total: 60, cycle: 3, cat1min: 60, cat1note: "All Cat 1 (in specialty/practice area)", topics: [
    { topic: "Controlled Substances", hours: 3.0, note: "3 hrs controlled substance prescribing" },
  ], notes: "3 hrs controlled substance prescribing", rollover: "No", moc: "ABMS/AOA/RCPSC recert/MOC = entire requirement", source: "N.C. Admin. Code tit. 21, r. 32R.0101", verified: "2026-08", sourceUrl: "https://www.ncmedboard.org/resources-information/faqs/professional-faqs/cme" },
  ND: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1", topics: [], notes: "Not specified", rollover: "No", moc: "ABMS/AOA/RCPSC cert/MOC exempt from CME", source: "N.D. Admin. Code 50-04-01 (hours in 50-04-01-01, MOC exemption in 50-04-01-02)", verified: "2026-08", sourceUrl: "https://www.ndbom.org/practitioners/physicians/current/cme.asp" },
  NE: { total: 50, cycle: 2, cat1min: 50, cat1note: "All Cat 1", topics: [
    { topic: "Opioid Prescribing", hours: 3.0, note: "3 hrs opioid prescribing (incl. 0.5 hr PDMP) biennially (controlled substance prescribers)" },
  ], notes: "3 hrs opioid prescribing (incl. 0.5 hr PDMP) biennially (controlled substance prescribers)", rollover: "Yes (up to 25 hrs)", moc: "AMA PRA or AOA CME Certification accepted", source: "Neb. Admin. R. & Regs. Tit. 172, Ch. 88", verified: "2026-08", sourceUrl: "https://dhhs.ne.gov/licensure/pages/medicine-and-surgery.aspx", upcoming: [
    "Neb. Rev. Stat. 38-145(6) opioid/PDMP CE requirement terminates January 1, 2029 unless extended",
  ] },
  NH: { total: 100, cycle: 2, cat1min: 40, cat1note: "40 hrs Cat 1; max 60 hrs Cat 2", topics: [
    { topic: "Pain Management", hours: 3.0, note: "3 hrs pain management/addiction disorders (NH-DEA holders)" },
  ], notes: "3 hrs pain management/addiction disorders (NH-DEA holders)", rollover: "No", moc: "ABMS board exam = 100 hrs Cat 1", source: "N.H. Rev. Stat. \u00a7 329:16-g", verified: "2026-08", sourceUrl: "https://www.law.cornell.edu/regulations/new-hampshire/N-H-Admin-Code-SS-Med-402.01" },
  NJ: { total: 100, cycle: 2, cat1min: 40, cat1note: "40 hrs Cat 1; 60 hrs Cat 1 or 2; 6 hrs cultural competence", topics: [
    { topic: "End-of-Life Care", hours: 2.0, note: "2 hrs end-of-life care" },
    { topic: "Opioid Prescribing", hours: 1.0, note: "1 hr opioid prescribing" },
    { topic: "Sexual Harassment Prevention", hours: 2.0, note: "2 hrs sexual misconduct prevention (eff. 2025)" },
    { topic: "Implicit Bias", hours: 1.0, note: "1 hr implicit bias (perinatal providers)" },
  ], notes: "2 hrs end-of-life care; 1 hr opioid prescribing; 2 hrs sexual misconduct prevention (eff. 2025); 1 hr implicit bias (perinatal providers)", rollover: "Yes, up to 25 excess credits into the next biennial period only", moc: "No", source: "N.J. Admin. Code 13:35-6.15; 13:35-6.25", verified: "2026-08", sourceUrl: "https://www.law.cornell.edu/regulations/new-jersey/N-J-A-C-13-35-6-15" },
  NM: { md: { total: 75, cycle: 3, cat1min: 75, cat1note: "All Cat 1", topics: [
    { topic: "Pain Management", hours: 5.0, note: "5 hrs pain management and controlled substance prescribing every triennial cycle (applies to licensees holding both a federal DEA registration and a NM controlled substance registration); counts toward the 75" },
  ], notes: "5 hrs pain management per triennial cycle (DEA and NM CSR holders); 1 hr review of NM Medical Practice Act and board rules, attested at renewal; CME may be earned July 1 through June 30 of the 3-year licensing period", rollover: "No", moc: "AMA PRA Cat 1; ABMS cert/recert or ABMS CME certificate; AOA active membership; osteopathic specialty board cert/recert; SPEX or COMVEX passage during the cycle", source: "N.M. Admin. Code 16.10.4.8, 16.10.4.10, 16.10.14.11", verified: "2026-08", sourceUrl: "https://www.srca.nm.gov/parts/title16/16.010.0004.html", upcoming: [
    "NM Medical Board IMLC implementation rules projected for board hearing Nov 5-6, 2026 (licensure, not CME)",
  ] }, do: { total: 75, cycle: 3, cat1min: 30, cat1note: "30 AOA Cat 1-A/1-B minimum; 45 may be AMA PRA Cat 1 or equivalent (CCME/AMA/ACCME/AAFP/AACOM/AAPS)", topics: [
    { topic: "Pain Management", hours: 6.0, note: "6 hrs pain management per triennial cycle; counts toward the 75; exempt if no NM controlled substance registration or not practicing in NM" },
  ], notes: "1 credit review of NM Osteopathic Medical Practice Act and board rules, attested at renewal; 6 hrs pain management for NM CSR holders; AOA membership, specialty board cert/recert, SPEX/COMVEX passage accepted", rollover: "No", moc: "AOA active membership, osteopathic specialty board cert/recert, SPEX/COMVEX passage accepted", source: "N.M. Admin. Code 16.17.3.9, 16.17.3.10", verified: "2026-08", sourceUrl: "https://www.srca.nm.gov/parts/title16/16.017.0003.html", upcoming: [
    "NM Medical Board IMLC implementation rules projected for board hearing Nov 5-6, 2026 (licensure, not CME)",
  ] } },
  NV: { md: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1", topics: [
    { topic: "Pain Management", hours: 2.0, note: "2 hrs ethics/pain mgmt/addiction each biennium" },
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs controlled substances/opioids/addiction per biennium, only if registered to dispense controlled substances (NRS 630.2535)" },
    { topic: "Suicide Prevention", hours: 2.0, note: "2 hrs suicide detection, intervention and prevention within 2 yrs of initial licensure, then once every 4 yrs", period: { years: 4 }, cite: "Nevada State Board of Medical Examiners, CME requirements" },
    { topic: "Cultural Competency", hours: 2.0, note: "2 hrs cultural competency and DEI every 2 yrs, psychiatrists only", cite: "NRS 630.2535; Nevada State Board of Medical Examiners CME requirements" },
    { topic: "HIV Stigma", hours: 2.0, note: "2 hrs stigma, discrimination and unrecognized bias toward persons with or at high risk of HIV, one-time, within 2 yrs after beginning to provide or supervise such care; MDs providing or supervising emergency medical services in a hospital or primary care", period: "lifetime", cite: "Nevada State Board of Medical Examiners, CME requirements" },
    { topic: "Substance Use Disorders", hours: 2.0, note: "2 hrs Screening, Brief Intervention and Referral to Treatment (SBIRT) within 2 yrs of initial licensure, one time only. Was described in the state notes but had no line of its own, so it was never checked.", period: "lifetime", cite: "Nevada State Board of Medical Examiners, CME requirements" },
  ], notes: "20 hrs in specialty; 2 hrs ethics/pain mgmt/addiction each biennium; 2 hrs controlled substances/opioids if registered to dispense; 2 hrs suicide prevention within 2 yrs then every 4 yrs; 2 hrs SBIRT one-time within 2 yrs of licensure; 2 hrs cultural competency/DEI (psychiatrists); 2 hrs HIV stigma one-time (EMS/primary care); up to 4 hrs double credit for geriatrics, medication management, rare diseases; WMD/bioterrorism no longer on board summary (NRS 630.253 text still shows 4 hrs within 2 yrs of licensure)", rollover: "No", moc: "No", source: "NRS 630.253, 630.2535; NAC 630.153", verified: "2026-08", sourceUrl: "https://medboard.nv.gov/uploadedFiles/mednvgov/content/Licensees/CME_Requirements_MDs_PAs_AAs.pdf" }, do: { total: 35, cycle: 1, cat1min: 10, cat1note: "10 AOA or AMA Cat 1A", topics: [
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs controlled substances/opioids/addiction annually, all DOs (NAC 633.250)" },
    { topic: "Suicide Prevention", hours: 2.0, note: "2 hrs evidence-based suicide prevention and awareness within 2 yrs of licensure, then 2 hrs every 4 yrs", period: { years: 4 }, cite: "Nevada State Board of Osteopathic Medicine, CME requirements" },
    { topic: "Pain Management", hours: 2.0, note: "2 hrs ethics, pain management or addiction care, even-numbered years only, so every other year", period: { years: 2 }, cite: "NRS 633.471(7)" },
    { topic: "Cultural Competency", hours: 2.0, note: "2 hrs cultural competency and DEI, biennially, psychiatrists and their supervised PAs only", period: { years: 2 }, cite: "NRS 633.471(12)" },
  ], notes: "2 hrs controlled substances/opioids/addiction annually (all DOs); 2 hrs suicide prevention within 2 yrs of licensure then every 4 yrs; 2 hrs ethics/pain mgmt/addiction (even years); 2 hrs cultural competency/DEI biennially (psychiatrists)", rollover: "No", moc: "No", source: "NRS 633.471; NAC 633.250", verified: "2026-08", sourceUrl: "https://bom.nv.gov/uploadedFiles/bomnvgov/content/Licensee/CME_Requirements.pdf" } },
  NY: { total: 0, cycle: 0, cat1min: 0, cat1note: "None (general)", topics: [
    { topic: "Pain Management", hours: 3.0, note: "3 hrs pain management, palliative care and addiction, once every 3 years, DEA-registered prescribers", period: { years: 3 }, cite: "N.Y. Pub. Health Law \u00a7 3309-a", url: "https://www.health.ny.gov/professionals/narcotic/mandatory_prescriber_education/" },
    { topic: "Child Abuse Recognition", hours: 2.0, note: "2 hrs child abuse and maltreatment identification and reporting, required of every applicant for licensure or a limited permit, so a one-time pre-licensure requirement rather than recurring CME. Existing mandated reporters must complete the updated curriculum by November 17, 2026.", period: "lifetime", cite: "NYSED physician license requirements (pre-licensure coursework)", url: "https://www.op.nysed.gov/professions/physicians/license-requirements" },
    { topic: "Infection Control", hours: 0, note: "Infection control and barrier precautions coursework, once every 4 years", period: { years: 4 }, cite: "NYSED physician license requirements", url: "https://www.op.nysed.gov/professions/physicians/license-requirements" },
  ], notes: "No CME requirement", rollover: "No", moc: "", source: "N.Y. Comp. Codes tit. 8, \u00a7\u00a7 59.12-13", verified: "2026-08", sourceUrl: "https://www.op.nysed.gov/professions/physicians/nysdoh-mandatory-prescriber-education" },
  OH: { total: 50, cycle: 2, cat1min: 50, cat1note: "All Cat 1", topics: [
    { topic: "Ethics", hours: 1.0, note: "1 hr duty to report" },
    { topic: "Pain Management", hours: 20.0, note: "20 hrs pain medicine (pain clinic operators, incl. addiction)" },
  ], notes: "1 hr duty to report; 20 hrs pain medicine (pain clinic operators, incl. addiction)", rollover: "No", moc: "No", source: "Ohio Admin. Code \u00a7\u00a7 4731-10-02", verified: "2026-08", sourceUrl: "https://codes.ohio.gov/ohio-administrative-code/rule-4731-10-02" },
  OK: { md: { total: 60, cycle: 3, cat1min: 60, cat1note: "All Cat 1", topics: [
    { topic: "Opioid Prescribing", hours: 1.0, note: "1 hr pain management or opioid use/addiction in EACH year preceding renewal (DEA holders). Oklahoma's cycle is 3 years; counted on a 1-year clock so the current year's hour is what is checked, rather than one hour anywhere in three.", period: { years: 1 }, cite: "OAC 435:10-15-1; 59 O.S. \u00a7 495a.1" },
  ], notes: "1 hr/yr pain management or opioid use/addiction (DEA holders); 1-hr training on provider rights/responsibilities every 2 yrs", rollover: "No", moc: "AMA PRA or ABMS cert/recert accepted", source: "59 O.S. \u00a7 495a.1; OAC 435:10-15-1", verified: "2026-08", sourceUrl: "https://www.okmedicalboard.org/cme/CMEguidelines.pdf" }, do: { total: 16, cycle: 1, cat1min: 16, cat1note: "16 AOA Cat 1 (AMA PRA Cat 1 accepted if ABMS certified)", topics: [
    { topic: "Controlled Substances", hours: 1.0, note: "1 hr/yr controlled substance prescribing (pain management, opioid use, or addiction) for DEA/OBNDD holders", cite: "OK Admin. Code 510:10-3-8" },
  ], notes: "1 hr/yr controlled substance prescribing (pain management, opioid use, or addiction) for DEA/OBNDD holders; 2 hr/yr medical marijuana CME if registered with OMMA as a recommending physician (63 O.S. 427.10); ABMS-certified DOs may use 16 AMA PRA Cat 1 hrs instead of AOA", rollover: "No", moc: "No", source: "OK Admin Code 510:10-3-8", verified: "2026-08", sourceUrl: "https://oklahoma.gov/osboe/resources/title-510/chapter-10/510-10-3.html" } },
  OR: { total: 60, cycle: 2, cat1min: 60, cat1note: "All AMA Cat 1 or AOA Cat 1A/2A", topics: [
    { topic: "Pain Management", hours: 1.0, note: "1 hr Oregon Pain Management Commission course at initial licensure and every 24 months (counts toward the 60 hrs)" },
    { topic: "Cultural Competency", hours: 2.0, note: "Average 1 hr per year (2 hrs per 2-yr cycle), audited every other renewal cycle (about 4 yrs); counts toward the 60 hrs; exempt: residents, Volunteer Camp licensees" },
  ], notes: "1 hr Pain Management Commission course every 24 months; cultural competency avg 1 hr/yr audited every other renewal; suicide risk assessment and dementia CME encouraged, not required", rollover: "No", moc: "ABMS/AOA-BOS recert/MOC accepted as alternative", source: "OAR 847-008-0070; 847-008-0075; 847-008-0077", verified: "2026-08", sourceUrl: "https://secure.sos.state.or.us/oard/view.action?ruleNumber=847-008-0070" },
  PA: { md: { total: 100, cycle: 2, cat1min: 20, cat1note: "20 hrs Cat 1", topics: [
    { topic: "Patient Safety", hours: 12.0, note: "12 hrs patient safety/risk management" },
    { topic: "Child Abuse Recognition", hours: 2.0, note: "2 hrs child abuse recognition and reporting" },
    { topic: "Pain Management", hours: 2.0, note: "2 hrs pain management, identification of addiction, or prescribing/dispensing opioids; applies only if you hold or use a DEA registration" },
    { topic: "Organ and Tissue Donation", hours: 2.0, note: "2 hrs organ and tissue donation and recovery process, one time within 5 years of initial licensure or of renewal/reactivation, Cat 1 or 2, counts toward the 100. The rule says so verbatim: this is a one-time requirement.", period: "lifetime", cite: "49 Pa. Code \u00a7 16.19 (one-time requirement)" },
  ], notes: "12 hrs patient safety/risk management; 2 hrs child abuse recognition and reporting; 2 hrs pain management/addiction/opioid prescribing (DEA registrants); 2 hrs organ and tissue donation one time within 5 years of licensure or renewal (eff. May 1, 2026)", rollover: "No", moc: "ABMS cert documentation accepted for Cat 1", source: "Pa. Code tit. 49, \u00a7 16.19", verified: "2026-08", sourceUrl: "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter16/s16.19.html", upcoming: [
    "Organ and tissue donation 2-hr one-time CE, effective 2026-05-01 (already in force); first deadline for existing licensees is within 5 years of their next renewal, i.e., MD renewal 12/31/2026 -> due by 2031",
  ] }, do: { total: 100, cycle: 2, cat1min: 20, cat1note: "20 hrs Cat 1-A", topics: [
    { topic: "Patient Safety", hours: 12.0, note: "12 hrs patient safety/risk management" },
    { topic: "Child Abuse Recognition", hours: 2.0, note: "2 hrs child abuse recognition and reporting" },
    { topic: "Pain Management", hours: 2.0, note: "2 hrs pain management, identification of addiction, or prescribing/dispensing opioids" },
    { topic: "Organ and Tissue Donation", hours: 2.0, note: "2 hrs organ and tissue donation and recovery process, one time within 5 years of initial licensure or of renewal, AOA Cat 1 or 2, counts toward the 100. Chapter 25 mirrors the Board of Medicine rule at 49 Pa. Code 16.19, which states the one-time wording verbatim.", period: "lifetime", cite: "49 Pa. Code \u00a7 25.271 (mirrors \u00a7 16.19)" },
  ], notes: "12 hrs patient safety/risk management; 2 hrs child abuse recognition and reporting; 2 hrs pain management/addiction/opioid prescribing; 2 hrs organ and tissue donation one time within 5 years of licensure or renewal (eff. May 1, 2026)", rollover: "No", moc: "No", source: "Pa. Code tit. 49, \u00a7 25.271", verified: "2026-08", sourceUrl: "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter25/s25.271.html", upcoming: [
    "Organ and tissue donation 2-hr one-time CE, effective 2026-05-01 (already in force); first deadline for existing licensees is within 5 years of their next renewal",
  ] } },
  PR: { total: 60, cycle: 3, cat1min: 0, cat1note: "No Category 1 minimum stated. Specialists and subspecialists: 30 credits in the specialty, 22 free topics, 8 compulsory. Generalists: 52 free topics plus 8 compulsory.", topics: [
    { topic: "Pain Management", hours: 3.0, note: "3 hrs pain mgmt" },
    { topic: "Ethics", hours: 3.0, note: "3 hrs bioethics (must include discrimination against elderly, women, disabled, LGBTTQ+ community, diversity and inclusion; Resolution 2023-195)" },
    { topic: "Dengue", hours: 3.0, note: "3 hrs dengue per cycle (Resolution 2024-83 of 30 Aug 2024)" },
    { topic: "Hypertension", hours: 1.0, note: "1 hr hypertension per cycle" },
    { topic: "Diabetes", hours: 1.0, note: "1 hr diabetes per cycle" },
  ], notes: "60 credits per 3-year cycle. Compulsory 8 credits: hypertension 1, diabetes 1, bioethics 3, dengue 3. Specialists: 30 credits in specialty plus 22 free topics. Generalists: 52 free topics. Autism: pediatricians 6 credits, physicians working directly with autism in specialized centers 15 credits. Non-emergency-medicine physicians who provide direct or indirect services in a hospital ER or primary level: 20 hrs life-support courses (ACLS, PALS, NALS, ATLS, BLS) per triennium. Residents/fellows in ACGME programs: residency certification plus bioethics 3 and dengue 3 only. Physicians residing in the US with a valid state license: exempt from these courses. Older Dept. of Health topics (Zika, vaccination, obesity, pain, antibiotics) were removed by OA 542.", rollover: "No", moc: "No", source: "JLDM Requisitos de renovacion 2025-2028 (salud.pr.gov/CMS/DOWNLOAD/6481); JLDM Resolucion 2025-162 (31 Oct 2025); Ley 139-2008 Art. 36-37", verified: "2026-08", sourceUrl: "https://www.salud.pr.gov/CMS/DOWNLOAD/6481" },
  RI: { total: 40, cycle: 2, cat1min: 40, cat1note: "All AMA Cat 1 or AOA Cat 1A", topics: [
    { topic: "Geriatric Medicine", hours: 1.0, note: "1 hr Alzheimer's/cognitive impairment, one-time over a career", period: "lifetime", cite: "R.I. Gen. Laws \u00a7 23-1.7-5" },
  ], notes: "1 hr Alzheimer's (one-time/career)", rollover: "No", moc: "ABMS MOC program = equivalent", source: "216-RICR-40-05-1.5.5", verified: "2026-08", sourceUrl: "https://rules.sos.ri.gov/regulations/part/216-40-05-1", upcoming: [
    "2026 H8545 (introduced May 13, 2026, on House calendar June 8, 2026) would amend RIGL 23-1.7-5 to require the 1-hour cognitive-impairment course each license renewal period instead of one-time, and extend it to PAs. Not enacted as of the codified statute loaded today; recheck after the 2026 session.",
  ] },
  SC: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1; 30 hrs in practice area", topics: [
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs controlled substance prescribing/monitoring" },
  ], notes: "2 hrs controlled substance prescribing/monitoring", rollover: "No", moc: "ABMS/AOA cert or added qualifications accepted", source: "SC Code \u00a7 40-47-40", verified: "2026-08", sourceUrl: "https://llr.sc.gov/med/PDF/Medical_CE_Reqs.pdf" },
  SD: { total: 0, cycle: 0, cat1min: 0, cat1note: "", topics: [], notes: "No CME requirement", rollover: "No", moc: "", source: "No statutory CME requirement", verified: "2026-08", sourceUrl: "https://www.sdbmoe.gov/professions-physicians/professions-physicians-physician-license-md-do/" },
  TN: { md: { total: 40, cycle: 2, cat1min: 40, cat1note: "All Cat 1", topics: [
    { topic: "Opioid Prescribing", hours: 2.0, note: "2 hrs controlled substance prescribing (incl. opioid/benzo/barbiturate/carisoprodol guidelines)" },
    { topic: "Pain Management", hours: 0, note: "pain management CME for intractable pain providers" },
  ], notes: "2 hrs controlled substance prescribing (incl. opioid/benzo/barbiturate/carisoprodol guidelines); pain management CME for intractable pain providers", rollover: "No", moc: "No", source: "Tenn. Comp. R. & Regs. 0880-02-.19", verified: "2026-08", sourceUrl: "https://www.tn.gov/content/dam/tn/health/healthprofboards/medicalexaminers/MDcmefaqs.pdf" }, do: { total: 40, cycle: 2, cat1min: 40, cat1note: "AOA Cat 1-A, 2-A and/or 1-B; no more than 20 hrs in Cat 1-B", topics: [
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs prescribing practices" },
  ], notes: "2 hrs prescribing practices", rollover: "No", moc: "No", source: "Tenn. Comp. R. & Regs. 1050-02-.12", verified: "2026-08", sourceUrl: "https://publications.tnsosfiles.com/rules/1050/1050-02.20220721.pdf" } },
  TX: { total: 48, cycle: 2, cat1min: 24, cat1note: "24 hrs AMA Cat 1 or AOA Cat 1A", topics: [
    { topic: "Ethics", hours: 2.0, note: "2 hrs medical ethics/professional responsibility (Cat 1/1A), every renewal, all physicians", cite: "22 Tex. Admin. Code \u00a7 161.35" },
    { topic: "Human Trafficking", hours: 1.0, note: "HHSC-approved human trafficking prevention course, direct patient care physicians, before first renewal then every 3rd renewal (every 6 yrs); TMB page states at least 1 hr; may count toward ethics; not covered by board cert/MOC", period: { years: 6 }, cite: "22 Tex. Admin. Code \u00a7 161.35 (TMB CE requirements)" },
    { topic: "Opioid Prescribing", hours: 2.0, note: "2 hrs opioid prescribing: within one year of license issuance and again at the second renewal, then no less than 2 hrs every 8 yrs", period: { years: 8 }, cite: "22 Tex. Admin. Code \u00a7 161.35 (TMB CE requirements)" },
    { topic: "Pain Management", hours: 10.0, note: "10 hrs pain management per 2-yr renewal cycle, for physicians who own or operate a pain management clinic. 22 TAC ch. 195 was repealed and reorganized into ch. 172; TMB states the requirement biennially under 22 TAC 172.3.", cite: "22 TAC \u00a7 172.3", url: "https://www.tmb.texas.gov/apply-renew/other-permits-and-licenses/pain-management-clinics/continuing-education-pain-management-clinics" },
    { topic: "Life of the Mother Act", hours: 0, note: "One-time TMB Life of the Mother Act course (SB 31), physicians providing obstetric care (OB/GYN, MFM, family medicine, emergency medicine and related); counts only as ethics credit", period: "lifetime", cite: "SB 31 (89th Leg.); TMB continuing education requirements" },
  ], notes: "2 hrs medical ethics/professional responsibility (all physicians); human trafficking prevention course (direct patient care, before first renewal then every 6 yrs); 2 hrs opioid prescribing (first 2 renewals, then every 8 yrs); 10 hrs pain mgmt per 2-yr period (pain clinic medical directors); one-time Life of the Mother Act course (obstetric care); nutrition training", rollover: "Yes: up to 48 excess credits carry forward to the next registration period only; required ethics, opioid, and human trafficking hours cannot be carried forward", moc: "Board cert/recert within 36 months before renewal presumes compliance for one renewal; current ABMS MOC or AOA OCC also accepted; covers ethics, does not cover human trafficking; opioid depends on specialty board", source: "Tex. Admin. Code tit. 22, \u00a7 161.35", verified: "2026-08", sourceUrl: "https://www.tmb.texas.gov/apply-renew/physician/continuing-education-requirements-for-physicians", upcoming: [
    "Nutrition and metabolic health CME (Occ. Code 156.061, SB 25): all physicians, applies to renewals filed on or after 1/1/2027; hours and content to be set by TMB rule (due by 12/31/2026), hours currently unknown",
    "Forensic evidence collection: 2 hrs per renewal for physicians treating patients in an ER setting, licenses expiring on or after 2/28/2027; no approved courses yet (SASTF approval required)",
    "Mandatory CE tracking via CE Broker for all TMB licensees begins 9/1/2026",
  ] },
  UT: { total: 40, cycle: 2, cat1min: 34, cat1note: "34 hrs Cat 1; max 6 hrs DOPL", topics: [
    { topic: "Controlled Substances", hours: 3.5, note: "3.5 hrs controlled substance prescribing" },
    { topic: "Suicide Prevention", hours: 0, note: "1 online suicide prevention training" },
  ], notes: "3.5 hrs controlled substance prescribing; 1 online suicide prevention training", rollover: "No (up to 15% from volunteer services)", moc: "No", source: "Utah Admin. Code R156-67-304", verified: "2026-08", sourceUrl: "https://commerce.utah.gov/dopl/physician-and-surgeon/renew-a-license/", upcoming: [
    "H.B. 301 (2026 General Session, enrolled) renumbers Utah Code 58-37-6.5 to 58-37-303 effective 05/06/2026; controlled substance CE content and 3.5 hr requirement unchanged. Consider updating any citation text that names 58-37-6.5 once DOPL updates its page.",
  ] },
  VA: { total: 30, cycle: 2, cat1min: 30, cat1note: "All 30 hrs must be Type 1 (accredited sponsor, e.g. AMA PRA Cat 1); Type 2 no longer counts", topics: [], notes: "30 Type 1 hrs per biennium (reduced from 60 eff. 2025-02-27). Exempt at first renewal after initial VA licensure. Board may designate up to 2 Type 1 hrs on a specific subject per \u00a7 54.1-2928.3; none published for 2026 renewals as of 2026-08-17", rollover: "No", moc: "Yes, conditional: specialty board recertification or AMA PRA accepted if the Board has proof the requirements equal or exceed the renewal requirement", source: "18VAC85-20-235 (eff. 2025-02-27); Va. Code \u00a7 54.1-2912.1; \u00a7 54.1-2928.3", verified: "2026-08", sourceUrl: "https://law.lis.virginia.gov/admincode/title18/agency85/chapter20/section235/" },
  VI: { total: 50, cycle: 2, cat1min: 50, cat1note: "All AMA Cat 1", topics: [], notes: "Not specified", rollover: "No", moc: "No", source: "https://www.fsmb.org/siteassets/advocacy/key-issues/continuing-medical-education-by-state.pdf" },
  VT: { md: { total: 30, cycle: 2, cat1min: 30, cat1note: "Not specified", topics: [
    { topic: "Pain Management", hours: 1.0, note: "1 hr hospice/palliative care/pain management" },
    { topic: "Controlled Substances", hours: 2.0, note: "2 hrs safe prescribing of controlled substances (DEA holders)" },
  ], notes: "1 hr hospice/palliative care/pain management; 2 hrs safe prescribing of controlled substances (DEA holders)", rollover: "No", moc: "No", source: "Vermont Board of Medical Practice Rules, Section 24 (13-141-001 Code Vt. R., eff. April 1, 2024)", verified: "2026-08", sourceUrl: "https://healthvermont.gov/systems/medical-practice-board/statutes-rules-policies-and-newsletters" }, do: { total: 30, cycle: 2, cat1min: 0, cat1note: "Not specified", topics: [], notes: "Not specified", rollover: "No", moc: "No", source: "26 V.S.A \u00a7 1836", verified: "2026-08", sourceUrl: "https://healthvermont.gov/systems/medical-practice-board/statutes-rules-policies-and-newsletters" } },
  WA: { md: { total: 200, cycle: 4, cat1min: 200, cat1note: "All 200 may be Cat 1; max 80 each of Cat 2-5", topics: [
    { topic: "Suicide Prevention", hours: 6.0, note: "One-time 6 hrs suicide assessment/treatment", period: "lifetime" },
    { topic: "Opioid Prescribing", hours: 1.0, note: "one-time 1 hr opioid prescribing", period: "lifetime" },
    { topic: "Cultural Competency", hours: 2.0, note: "2 hrs health equity every 4 years (WAC 246-919-445, eff 1/1/2024)", period: { years: 4 } },
  ], notes: "One-time 6 hrs suicide assessment/treatment; one-time 1 hr opioid prescribing; 2 hrs health equity every 4 yrs", rollover: "No", moc: "AMA PRA (2 of last 4 yrs), ABMS cert in last 4 yrs, or ABMS MOC participation accepted in lieu of 200 hrs", source: "WAC 246-919-430; 246-919-460; 246-919-435; 246-919-445; 246-919-875", verified: "2026-08", sourceUrl: "https://app.leg.wa.gov/wac/default.aspx?cite=246-919-430" }, do: { total: 150, cycle: 3, cat1min: 60, cat1note: "60 hrs Category 1A (AOA 1A per DOH page); remainder any approved category", topics: [
    { topic: "Suicide Prevention", hours: 6.0, note: "One-time 6 hrs suicide assessment/treatment", period: "lifetime" },
    { topic: "Opioid Prescribing", hours: 1.0, note: "one-time 1 hr opioid prescribing", period: "lifetime" },
    { topic: "Cultural Competency", hours: 2.0, note: "2 hrs health equity every 4 years (not per 3-yr cycle), WAC 246-853-075", period: { years: 4 } },
  ], notes: "One-time 6 hrs suicide assessment/treatment; one-time 1 hr opioid prescribing; 2 hrs health equity every 4 yrs", rollover: "No", moc: "ABOMS or ABMS cert/recert within last 6 yrs, current AOA CME certificate, or AMA PRA satisfies 150 hrs; state mandates still required", source: "WAC 246-853-080; 246-853-065; 246-853-075; 246-853-685", verified: "2026-08", sourceUrl: "https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/osteopathic-physician-and-surgeon/continuing-education" } },
  WI: { total: 30, cycle: 2, cat1min: 30, cat1note: "All Cat 1 (AMA or AOA)", topics: [
    { topic: "Opioid Prescribing", hours: 2.0, note: "2 hrs opioid/controlled substance prescribing (Board-approved not required)" },
  ], notes: "2 hrs opioid/controlled substance prescribing (Board-approved not required)", rollover: "No", moc: "No", source: "Wis. Admin. Code MED \u00a7 13.02", verified: "2026-08", sourceUrl: "https://dsps.wi.gov/Pages/Professions/Physician/CE.aspx" },
  WV: { md: { total: 50, cycle: 2, cat1min: 50, cat1note: "All Cat 1; 30 hrs in specialty", topics: [
    { topic: "Controlled Substances", hours: 3.0, note: "3 hrs Board-approved risk assessment/controlled substance prescribing training" },
  ], notes: "3 hrs Board-approved risk assessment/controlled substance prescribing training", rollover: "No", moc: "ABMS cert/recert or MOC; ACGME training year accepted", source: "W. Va. Code, \u00a7 30-3-12", verified: "2026-08", sourceUrl: "https://wvbom.wv.gov/Cont_Med_Education.asp" }, do: { total: 32, cycle: 2, cat1min: 16, cat1note: "16 hrs AOA Cat 1A or 1B", topics: [
    { topic: "Controlled Substances", hours: 3.0, note: "3 hrs Board-approved drug diversion/controlled substance prescribing" },
  ], notes: "3 hrs Board-approved drug diversion/controlled substance prescribing", rollover: "No", moc: "No", source: "W. Va. Code R. \u00a7 24-1-15", verified: "2026-08", sourceUrl: "https://wvbom.wv.gov/Cont_Med_Education.asp" } },
  WY: { total: 60, cycle: 3, cat1min: 60, cat1note: "All Cat 1 or 2 (AMA/AOA)", topics: [
    { topic: "Controlled Substances", hours: 1.0, note: "1 hr responsible prescribing of controlled substances or SUD treatment every 2 yrs (CSR holders). Wyoming's general CME cycle is 3 years, so this is counted on its own 2-year clock, not the 3-year one.", period: { years: 2 }, cite: "Wyo. Stat. \u00a7 33-26-202(b)(xiv)" },
  ], notes: "1 hr responsible prescribing of controlled substances or SUD treatment every 2 yrs (CSR holders)", rollover: "No", moc: "AMA PRA; ABMS cert accepted as equivalent", source: "WY Board of Medicine Rules Ch. 3, \u00a7 7", verified: "2026-08", sourceUrl: "https://wyomedboard.wyo.gov/resources/rules-and-regulations" },
};

export const DEFAULT_STATE_REQ = {
  total: 50, cycle: 2, cat1min: 0, cat1note: "", topics: [], notes: "Check your state medical board for specifics.", rollover: "No", moc: "", source: "", sourceUrl: "", upcoming: [],
};

export function getStateReq(st, deg) {
  const entry = STATE_REQS[st];
  if (!entry) return DEFAULT_STATE_REQ;
  if (entry.md || entry.do) {
    const r = deg === "DO" ? (entry.do || entry.md) : (entry.md || entry.do);
    return { hours: r.total, cycle: r.cycle, cat1min: r.cat1min, cat1note: r.cat1note, topics: r.topics, notes: r.notes, rollover: r.rollover, moc: r.moc, source: r.source, verified: r.verified, sourceUrl: r.sourceUrl, upcoming: r.upcoming };
  }
  return { hours: entry.total, cycle: entry.cycle, cat1min: entry.cat1min, cat1note: entry.cat1note, topics: entry.topics, notes: entry.notes, rollover: entry.rollover, moc: entry.moc, source: entry.source, verified: entry.verified, sourceUrl: entry.sourceUrl, upcoming: entry.upcoming };
}

export function getStateEntry(st, deg) {
  const entry = STATE_REQS[st];
  if (!entry) return DEFAULT_STATE_REQ;
  if (entry.md || entry.do) return deg === "DO" ? (entry.do || entry.md) : (entry.md || entry.do);
  return entry;
}

export function hasSeparateBoards(st) {
  const e = STATE_REQS[st];
  return e && (e.md || e.do);
}
