// The Supabase CLI workdir the lab starts the local stack from.
//
// Why a separate workdir: the Supabase CLI reads supabase/config.toml, and that
// is the file production's own procedures read too (`supabase db push`,
// `supabase functions deploy`, `supabase config push` from the main checkout,
// which is linked to production). The lab's settings (migrations and seeding
// off, the mock Clerk's token key trusted through auth.signing_keys_path) must
// never reach those commands: with migrations off, `db push` skips every
// migration and still reports the remote as up to date. So the repository has no
// supabase/config.toml; the lab keeps its settings in
// qa-lab/supabase-config.template.toml and writes its own copy into
// .generated/stack/supabase/config.toml, with the edge functions' lab
// environment added, and links the real supabase/functions next to it. The copy
// has no .temp/ folder, so it is not linked to any hosted project either:
// nothing started from it can reach production.
//
// The edge functions' environment (qa-lab/lib/functions-env.mjs) goes into the
// same generated config as [edge_runtime.secrets], so the functions `supabase
// start` serves already point at the mocks. (`supabase functions serve` fails
// to boot its main worker with CLI 2.109.1 on this machine: "failed to determine
// entrypoint", with or without an env file. The same env is also written to
// .generated/functions.env for when it works: `supabase functions serve
// --env-file qa-lab/.generated/functions.env --workdir qa-lab/.generated/stack`.)
//
// Two more things the lab does to the stack, both local:
//   * Loopback only. The stack's containers publish their ports (database,
//     Studio, gateway, Mailpit) on every interface by default, and the database
//     holds production's schema and function bodies with the default local
//     password. Before `supabase start` the lab creates the stack's Docker
//     network itself with com.docker.network.bridge.host_binding_ipv4 =
//     127.0.0.1 (the CLI reuses an existing network), so every port is published
//     on 127.0.0.1 only; startStack() refuses to go on if any lab container
//     still publishes a port on 0.0.0.0 or [::].
//   * Functions answer their own CORS. Local Kong runs its cors plugin on
//     /functions/v1/, which answers every preflight itself and stamps
//     "Access-Control-Allow-Origin: *" on every response, so a function's own
//     CORS headers never reach a browser. Hosted Supabase passes the function's
//     headers through. The lab removes that one plugin from the running Kong's
//     declarative config and reloads it (the container writes its config at
//     start, so this is redone after every start).
import { chmodSync, existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { FUNCTIONS_DIR, STACK_CONFIG, STACK_CONFIG_TEMPLATE, STACK_FUNCTIONS_LINK, STACK_SIGNING_KEYS, STACK_WORKDIR } from './paths.mjs';
import { labSecrets } from './lab-secrets.mjs';
import { projectId } from './config.mjs';

const HEADER = `# GENERATED by qa-lab/lib/stack.mjs from qa-lab/supabase-config.template.toml. Do not edit:
# it is rewritten on every qa:up / qa:lab. Added to the template: the edge functions' lab
# environment ([edge_runtime.secrets], lab-generated values only).
`;

const tomlString = (value) => {
  if (typeof value !== 'string' || /["\\\r\n\u0000-\u001f]/.test(value)) throw new Error('a lab function setting must be plain one-line text');
  return `"${value}"`;
};

/** The template, with the functions' environment added. Throws if the template no longer has the expected shape. */
export function stackConfigText(functionsEnv = null, source = readFileSync(STACK_CONFIG_TEMPLATE, 'utf8')) {
  const required = [
    [/^signing_keys_path = "\.\/signing_keys\.json"$/m, 'trust the lab token key (auth.signing_keys_path)'],
    [/^sql_paths = \[\]$/m, 'no seed paths (apply-schema.mjs seeds)'],
  ];
  for (const [pattern, why] of required) {
    if ((source.match(new RegExp(pattern.source, 'gm')) || []).length !== 1) throw new Error(`qa-lab/supabase-config.template.toml changed shape: ${pattern} must appear exactly once (${why})`);
  }
  if (/^\[edge_runtime\.secrets\]/m.test(source)) throw new Error('the template has its own [edge_runtime.secrets]; the lab cannot add its environment');
  let out = source;
  if (functionsEnv) {
    out += '\n# The QA lab\'s edge-function environment (qa-lab/lib/functions-env.mjs).\n[edge_runtime.secrets]\n'
      + Object.entries(functionsEnv).map(([k, v]) => { if (!/^[A-Z][A-Z0-9_]*$/.test(k)) throw new Error(`bad name ${k}`); return `${k} = ${tomlString(v)}`; }).join('\n') + '\n';
  }
  return HEADER + out;
}

/** Writes .generated/stack/ (idempotent). */
export function prepareStackWorkdir({ functionsEnv = null } = {}) {
  mkdirSync(path.dirname(STACK_CONFIG), { recursive: true });
  writeFileSync(STACK_CONFIG, stackConfigText(functionsEnv), { mode: 0o600 });
  chmodSync(STACK_CONFIG, 0o600);
  writeFileSync(STACK_SIGNING_KEYS, JSON.stringify([labSecrets().signingKey], null, 2) + '\n', { mode: 0o600 });
  chmodSync(STACK_SIGNING_KEYS, 0o600);
  const target = path.relative(path.dirname(STACK_FUNCTIONS_LINK), FUNCTIONS_DIR);
  let current = null;
  try { if (lstatSync(STACK_FUNCTIONS_LINK).isSymbolicLink()) current = readlinkSync(STACK_FUNCTIONS_LINK); else throw new Error(`${STACK_FUNCTIONS_LINK} exists and is not a link`); }
  catch (e) { if (e.code !== 'ENOENT') throw e; }
  if (current !== target) {
    if (current !== null) unlinkSync(STACK_FUNCTIONS_LINK);
    symlinkSync(target, STACK_FUNCTIONS_LINK);
  }
  return STACK_WORKDIR;
}

/** The workdir `supabase start/stop/status` use: always the lab's own (the repository has no supabase/config.toml). */
export function stackWorkdir() {
  return STACK_WORKDIR;
}

/** `supabase status -o json` for the running lab stack, or null when it is not running. */
export function stackStatus() {
  if (!existsSync(STACK_CONFIG)) return null;
  const r = spawnSync('supabase', ['status', '-o', 'json', '--workdir', STACK_WORKDIR], { encoding: 'utf8' });
  if (r.status !== 0) return null;
  const start = r.stdout.indexOf('{');
  if (start < 0) return null;
  try { return JSON.parse(r.stdout.slice(start)); } catch { return null; }
}

/** True when the running stack trusts the lab's token key (its anon key is signed with it). */
export function stackTrustsLabKey(status = stackStatus()) {
  if (!status?.ANON_KEY) return false;
  try {
    const header = JSON.parse(Buffer.from(status.ANON_KEY.split('.')[0], 'base64url').toString('utf8'));
    return header.alg === 'RS256' && header.kid === labSecrets().signingKey.kid;
  } catch { return false; }
}

/** True when the running edge runtime has exactly these values for every name in `functionsEnv`. */
export function edgeRuntimeHasEnv(functionsEnv) {
  const r = spawnSync('docker', ['inspect', `supabase_edge_runtime_${projectId()}`, '--format', '{{json .Config.Env}}'], { encoding: 'utf8' });
  if (r.status !== 0) return false;
  let env;
  try { env = JSON.parse(r.stdout.trim()); } catch { return false; }
  const have = new Map(env.map((kv) => [kv.slice(0, kv.indexOf('=')), kv.slice(kv.indexOf('=') + 1)]));
  return Object.entries(functionsEnv).every(([k, v]) => have.get(k) === v);
}

function cli(args) {
  const r = spawnSync('supabase', args, { stdio: 'inherit' });
  if (r.status !== 0) throw new Error(`supabase ${args[0]} failed (exit ${r.status})`);
}
function docker(args, { allowFail = false } = {}) {
  const r = spawnSync('docker', args, { encoding: 'utf8' });
  if (r.status !== 0 && !allowFail) throw new Error(`docker ${args.slice(0, 2).join(' ')} failed: ${(r.stderr || '').trim().slice(0, 300)}`);
  return r;
}

// ── Loopback only ───────────────────────────────────────────────────────────
export const LOOPBACK_OPTION = 'com.docker.network.bridge.host_binding_ipv4';
export const stackNetwork = () => `supabase_network_${projectId()}`;

/**
 * Published host addresses that are not loopback, from `docker ps --format
 * '{{.Names}}\t{{.Ports}}'` lines. "0.0.0.0:54322->5432/tcp, [::]:54322->5432/tcp"
 * yields both; "127.0.0.1:54322->5432/tcp" and unpublished "8080/tcp" yield nothing.
 */
export function exposedBindings(psText) {
  const out = [];
  for (const line of String(psText || '').split('\n')) {
    const [name, ports = ''] = line.split('\t');
    if (!name) continue;
    for (const m of ports.matchAll(/(\S+?):(\d+)->(\d+\/\w+)/g)) {
      const host = m[1];
      if (host !== '127.0.0.1' && host !== '[::1]' && host !== '::1') out.push(`${name} ${host}:${m[2]}->${m[3]}`);
    }
  }
  return out;
}

/** The lab containers' ports published on an address other than loopback (empty when none). */
export function labExposedPorts() {
  const r = docker(['ps', '--filter', `name=_${projectId()}$`, '--format', '{{.Names}}\t{{.Ports}}'], { allowFail: true });
  if (r.status !== 0) return [];
  return exposedBindings(r.stdout);
}

/** The stack network's host binding option ('' when unset), or null when the network does not exist. */
function networkBinding() {
  const r = docker(['network', 'inspect', stackNetwork(), '--format', `{{index .Options "${LOOPBACK_OPTION}"}}`], { allowFail: true });
  if (r.status !== 0) return null;
  const v = r.stdout.trim();
  return v === '<no value>' ? '' : v;
}

/** Creates the stack's network with the loopback binding (replacing one without it). Call with the stack stopped. */
export function ensureLoopbackNetwork() {
  const have = networkBinding();
  if (have === '127.0.0.1') return false;
  if (have !== null) docker(['network', 'rm', stackNetwork()]);
  docker(['network', 'create', '--driver', 'bridge', '-o', `${LOOPBACK_OPTION}=127.0.0.1`, '--label', 'credentialdomd.qa-lab=loopback', stackNetwork()]);
  return true;
}

// ── Functions answer their own CORS ─────────────────────────────────────────
const KONG = () => `supabase_kong_${projectId()}`;

/**
 * Kong's declarative config without the cors plugin on the functions-v1 service
 * (every other service keeps it, as hosted Supabase keeps CORS on REST, Auth and
 * Storage). Returns null when there is nothing to remove. Throws when the
 * service or its plugin list is not where the CLI puts it.
 */
export function kongWithoutFunctionsCors(yml) {
  const lines = String(yml).split('\n');
  const start = lines.findIndex((l) => /^  - name: functions-v1$/.test(l));
  if (start < 0) throw new Error('the local Kong config has no functions-v1 service (Supabase CLI changed its gateway config); see qa-lab/lib/stack.mjs');
  let end = lines.findIndex((l, i) => i > start && /^  - name: /.test(l));
  if (end < 0) end = lines.length;
  const cors = [];
  for (let i = start; i < end; i++) if (/^ {6}- name: cors$/.test(lines[i])) cors.push(i);
  if (!cors.length) return null;
  if (cors.length > 1) throw new Error('the functions-v1 service lists the cors plugin more than once');
  const i = cors[0];
  // A cors entry with its own config block would need that block removed too; the CLI's has none.
  if (lines[i + 1] && /^ {8}\S/.test(lines[i + 1])) throw new Error('the functions-v1 cors plugin has settings; update qa-lab/lib/stack.mjs');
  return [...lines.slice(0, i), ...lines.slice(i + 1)].join('\n');
}

/** Removes Kong's cors plugin from /functions/v1/ in the running gateway (idempotent). True when it changed Kong. */
export function passFunctionsCorsThrough() {
  const read = docker(['exec', KONG(), 'cat', '/home/kong/kong.yml']);
  const next = kongWithoutFunctionsCors(read.stdout);
  if (next === null) return false;
  const w = spawnSync('docker', ['exec', '-i', KONG(), 'sh', '-c', 'cat > /home/kong/kong.yml.qa && mv /home/kong/kong.yml.qa /home/kong/kong.yml && kong reload'], { input: next, encoding: 'utf8' });
  if (w.status !== 0) throw new Error(`could not reload the local Kong without its functions cors plugin: ${(w.stderr || w.stdout || '').trim().slice(0, 300)}`);
  return true;
}

/** True when the running Kong still answers function preflights itself (its plugin's method list gives it away). */
export async function kongAnswersFunctionPreflights(apiUrl = 'http://127.0.0.1:54321') {
  const r = await fetch(`${apiUrl}/functions/v1/qa-lab-cors-probe`, { method: 'OPTIONS', headers: { Origin: 'https://cors-probe.qa.credentialdomd.test', 'Access-Control-Request-Method': 'POST' }, signal: AbortSignal.timeout(15000) });
  await r.arrayBuffer().catch(() => {});
  return /TRACE,CONNECT/.test(r.headers.get('access-control-allow-methods') || '');
}

/**
 * Starts the local stack from the lab workdir. A stack already running without
 * the lab's token key, whose edge functions have a different environment, or
 * that publishes a port beyond loopback, is stopped (its data kept) and started
 * again: the CLI only reads these settings when it creates the containers.
 */
export function startStack({ functionsEnv = null } = {}) {
  prepareStackWorkdir({ functionsEnv });
  const status = stackStatus();
  if (status) {
    const reason = !stackTrustsLabKey(status) ? 'does not trust the lab token key yet'
      : functionsEnv && !edgeRuntimeHasEnv(functionsEnv) ? 'serves the edge functions with another environment'
        : labExposedPorts().length ? `publishes ports beyond loopback (${labExposedPorts().slice(0, 3).join(', ')})` : null;
    if (reason) {
      console.log(`qa-lab: the running stack ${reason}; restarting it (data is kept).`);
      cli(['stop', '--workdir', STACK_WORKDIR]);
    }
  }
  if (!stackStatus()) {
    if (ensureLoopbackNetwork()) console.log(`qa-lab: created the Docker network ${stackNetwork()} with ports published on 127.0.0.1 only.`);
    try { cli(['start', '--workdir', STACK_WORKDIR]); }
    catch {
      // Docker can take a moment to release the ports of a stack that just stopped.
      console.log('qa-lab: supabase start failed; retrying once in 10 seconds.');
      spawnSync('sleep', ['10']);
      ensureLoopbackNetwork();
      cli(['start', '--workdir', STACK_WORKDIR]);
    }
  }
  const after = stackStatus();
  if (!stackTrustsLabKey(after)) throw new Error('the local stack did not pick up the lab token key (auth.signing_keys_path); see qa-lab/README.md');
  if (functionsEnv && !edgeRuntimeHasEnv(functionsEnv)) throw new Error('the edge runtime did not pick up the lab environment ([edge_runtime.secrets]); see qa-lab/README.md');
  const exposed = labExposedPorts();
  if (exposed.length) {
    throw new Error(`refusing to go on: lab containers publish ports beyond this machine's loopback (${exposed.join(', ')}). `
      + `Anyone on the network could reach production's schema and function bodies with the default local password. Stop the stack (npm run qa:down) and start it again; see qa-lab/README.md "Loopback only".`);
  }
  if (passFunctionsCorsThrough()) console.log('qa-lab: the local gateway now passes the functions\' own CORS headers through (as hosted Supabase does).');
  return after;
}

/** Stops the local stack (keeps the data unless wipe). */
export function stopStack({ wipe = false } = {}) {
  if (!existsSync(STACK_CONFIG)) prepareStackWorkdir();
  cli(['stop', '--workdir', STACK_WORKDIR, ...(wipe ? ['--no-backup'] : [])]);
}
