// The Supabase CLI workdir the lab starts the local stack from.
//
// Why a separate workdir: the local stack must trust the mock Clerk's token key
// (auth.signing_keys_path), and that setting cannot live in supabase/config.toml.
// The CLI refuses to load a config whose signing-key file is missing, and that
// same config.toml is read by `supabase functions deploy` from a clean checkout,
// where the lab's key never exists. So the lab writes its own copy of
// config.toml into .generated/stack/supabase/ with that setting added, and
// links the real supabase/functions next to it. The copy has no .temp/ folder,
// so it is not linked to any hosted project either: nothing started from it can
// reach production.
//
// The edge functions' environment (qa-lab/lib/functions-env.mjs) goes into the
// same generated config as [edge_runtime.secrets], so the functions `supabase
// start` serves already point at the mocks. (`supabase functions serve` fails
// to boot its main worker with CLI 2.109.1 on this machine: "failed to determine
// entrypoint", with or without an env file. The same env is also written to
// .generated/functions.env for when it works: `supabase functions serve
// --env-file qa-lab/.generated/functions.env --workdir qa-lab/.generated/stack`.)
import { chmodSync, existsSync, lstatSync, mkdirSync, readFileSync, readlinkSync, symlinkSync, unlinkSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { FUNCTIONS_DIR, REPO_ROOT, STACK_CONFIG, STACK_FUNCTIONS_LINK, STACK_SIGNING_KEYS, STACK_WORKDIR, SUPABASE_CONFIG } from './paths.mjs';
import { labSecrets } from './lab-secrets.mjs';
import { projectId } from './config.mjs';

const HEADER = `# GENERATED by qa-lab/lib/stack.mjs from supabase/config.toml. Do not edit: it is rewritten
# on every qa:up / qa:lab. Differences from supabase/config.toml: the mock Clerk's token key
# is trusted (auth.signing_keys_path), seeding paths are cleared, and the edge functions get
# the lab environment ([edge_runtime.secrets], lab-generated values only).
`;

const tomlString = (value) => {
  if (typeof value !== 'string' || /["\\\r\n\u0000-\u001f]/.test(value)) throw new Error('a lab function setting must be plain one-line text');
  return `"${value}"`;
};

/** supabase/config.toml, rewritten for the lab. Throws if the file no longer has the expected shape. */
export function stackConfigText(functionsEnv = null, source = readFileSync(SUPABASE_CONFIG, 'utf8')) {
  const swaps = [
    [/^# signing_keys_path = "\.\/signing_keys\.json"$/m, 'signing_keys_path = "./signing_keys.json"'],
    [/^sql_paths = \[[^\]\n]*\]$/m, 'sql_paths = []'],
  ];
  let out = source;
  for (const [pattern, replacement] of swaps) {
    if ((out.match(new RegExp(pattern.source, 'gm')) || []).length !== 1) throw new Error(`supabase/config.toml changed shape: ${pattern} must match exactly once`);
    out = out.replace(pattern, replacement);
  }
  if (/^\[edge_runtime\.secrets\]/m.test(out)) throw new Error('supabase/config.toml has its own [edge_runtime.secrets]; the lab cannot add its environment');
  if (functionsEnv) {
    out += '\n# The QA lab\'s edge-function environment (qa-lab/lib/functions-env.mjs).\n[edge_runtime.secrets]\n'
      + Object.entries(functionsEnv).map(([k, v]) => { if (!/^[A-Z][A-Z0-9_]*$/.test(k)) throw new Error(`bad name ${k}`); return `${k} = ${tomlString(v)}`; }).join('\n') + '\n';
  }
  return HEADER + out;
}

/** Writes .generated/stack/ (idempotent). */
export function prepareStackWorkdir({ functionsEnv = null } = {}) {
  mkdirSync(path.dirname(STACK_CONFIG), { recursive: true });
  writeFileSync(STACK_CONFIG, stackConfigText(functionsEnv), { mode: 0o600 });
  chmodSync(STACK_CONFIG, 0o600);
  writeFileSync(STACK_SIGNING_KEYS, JSON.stringify([labSecrets().signingKey], null, 2) + '\n', { mode: 0o600 });
  chmodSync(STACK_SIGNING_KEYS, 0o600);
  const target = path.relative(path.dirname(STACK_FUNCTIONS_LINK), FUNCTIONS_DIR);
  let current = null;
  try { if (lstatSync(STACK_FUNCTIONS_LINK).isSymbolicLink()) current = readlinkSync(STACK_FUNCTIONS_LINK); else throw new Error(`${STACK_FUNCTIONS_LINK} exists and is not a link`); }
  catch (e) { if (e.code !== 'ENOENT') throw e; }
  if (current !== target) {
    if (current !== null) unlinkSync(STACK_FUNCTIONS_LINK);
    symlinkSync(target, STACK_FUNCTIONS_LINK);
  }
  return STACK_WORKDIR;
}

/** The workdir `supabase start/stop/status` should use: the lab's own once it exists. */
export function stackWorkdir() {
  return existsSync(STACK_CONFIG) ? STACK_WORKDIR : REPO_ROOT;
}

/** `supabase status -o json` for the running lab stack, or null when it is not running. */
export function stackStatus() {
  const r = spawnSync('supabase', ['status', '-o', 'json', '--workdir', stackWorkdir()], { encoding: 'utf8' });
  if (r.status !== 0) return null;
  const start = r.stdout.indexOf('{');
  if (start < 0) return null;
  try { return JSON.parse(r.stdout.slice(start)); } catch { return null; }
}

/** True when the running stack trusts the lab's token key (its anon key is signed with it). */
export function stackTrustsLabKey(status = stackStatus()) {
  if (!status?.ANON_KEY) return false;
  try {
    const header = JSON.parse(Buffer.from(status.ANON_KEY.split('.')[0], 'base64url').toString('utf8'));
    return header.alg === 'RS256' && header.kid === labSecrets().signingKey.kid;
  } catch { return false; }
}

/** True when the running edge runtime has exactly these values for every name in `functionsEnv`. */
export function edgeRuntimeHasEnv(functionsEnv) {
  const r = spawnSync('docker', ['inspect', `supabase_edge_runtime_${projectId()}`, '--format', '{{json .Config.Env}}'], { encoding: 'utf8' });
  if (r.status !== 0) return false;
  let env;
  try { env = JSON.parse(r.stdout.trim()); } catch { return false; }
  const have = new Map(env.map((kv) => [kv.slice(0, kv.indexOf('=')), kv.slice(kv.indexOf('=') + 1)]));
  return Object.entries(functionsEnv).every(([k, v]) => have.get(k) === v);
}

function cli(args) {
  const r = spawnSync('supabase', args, { stdio: 'inherit' });
  if (r.status !== 0) throw new Error(`supabase ${args[0]} failed (exit ${r.status})`);
}

/**
 * Starts the local stack from the lab workdir. A stack already running without
 * the lab's token key, or whose edge functions have a different environment,
 * is stopped (its data kept) and started again: the CLI only reads these
 * settings when it creates the containers.
 */
export function startStack({ functionsEnv = null } = {}) {
  prepareStackWorkdir({ functionsEnv });
  const status = stackStatus();
  if (status) {
    const reason = !stackTrustsLabKey(status) ? 'does not trust the lab token key yet'
      : functionsEnv && !edgeRuntimeHasEnv(functionsEnv) ? 'serves the edge functions with another environment' : null;
    if (reason) {
      console.log(`qa-lab: the running stack ${reason}; restarting it (data is kept).`);
      cli(['stop', '--workdir', STACK_WORKDIR]);
    }
  }
  if (!stackStatus()) {
    try { cli(['start', '--workdir', STACK_WORKDIR]); }
    catch {
      // Docker can take a moment to release the ports of a stack that just stopped.
      console.log('qa-lab: supabase start failed; retrying once in 10 seconds.');
      spawnSync('sleep', ['10']);
      cli(['start', '--workdir', STACK_WORKDIR]);
    }
  }
  const after = stackStatus();
  if (!stackTrustsLabKey(after)) throw new Error('the local stack did not pick up the lab token key (auth.signing_keys_path); see qa-lab/README.md');
  if (functionsEnv && !edgeRuntimeHasEnv(functionsEnv)) throw new Error('the edge runtime did not pick up the lab environment ([edge_runtime.secrets]); see qa-lab/README.md');
  return after;
}

/** Stops the local stack (keeps the data unless wipe). */
export function stopStack({ wipe = false } = {}) {
  cli(['stop', '--workdir', stackWorkdir(), ...(wipe ? ['--no-backup'] : [])]);
}
