import { useState, useMemo, memo } from "react";
import { useApp } from "../../context/AppContext";
import { AsclepiusIcon, ExternalLinkIcon } from "../shared/Icons";
import { copyToClipboard } from "../../utils/helpers";
import { shareCvPdf } from "../../utils/cvPdf";
import { buildCvContent } from "../../utils/cvContent";
import CvImportReview from "./CvImportReview";
import Modal from "../shared/Modal";


const CV_TEMPLATES = [
  { id: "clinical", name: "Clinical CV", description: "Standard format for hospital credentialing" },
  { id: "academic", name: "Academic CV", description: "Detailed format for academic positions" },
  { id: "locum", name: "Locum Tenens", description: "Compact format for locum assignments" },
];

function CVGenerator() {
  const { data, theme: T } = useApp();
  const [template, setTemplate] = useState("clinical");
  const [preview, setPreview] = useState(true);
  const [importing, setImporting] = useState(false);
  const [note, setNote] = useState("");

  const s = data.settings;

  const cvContent = useMemo(() => buildCvContent(data, template), [data, template]);


  // Generate plain text
  const generatePlainText = () => {
    const lines = [];
    const divider = "=".repeat(60);
    const subDivider = "-".repeat(40);

    cvContent.forEach(section => {
      if (section.type === "header") {
        lines.push(divider);
        lines.push(`  ${section.name}`);
        if (section.address) lines.push(`  ${section.address}`);
        if (section.email) lines.push(`  ${section.email}`);
        if (section.website) lines.push(`  ${section.website}`);
        if (section.phone) lines.push(`  ${section.phone}`);
        if (section.specialties.length > 0) {
          const names = section.specialties.map(id => id.split(":").pop());
          lines.push(`  ${section.fullDegree ? section.fullDegree + " \u2014 " : ""}${names.join(", ")}`);
        }
        lines.push(divider);
        lines.push("");
      } else {
        lines.push(section.title.toUpperCase());
        lines.push(subDivider);
        section.items.forEach(item => {
          const datePart = item.date ? `  [${item.date}]` : "";
          if (item.primary) lines.push(`${item.subhead ? "  " : "  "}${item.primary}${datePart}`);
          if (item.secondary) lines.push(`    ${item.secondary}`);
          if (item.detail) lines.push(`    ${item.detail}`);
        });
        lines.push("");
      }
    });

    lines.push(subDivider);
    lines.push(`Generated by CredentialDOMD | ${new Date().toLocaleDateString()}`);
    return lines.join("\n");
  };

  const flash = (msg) => { setNote(msg); setTimeout(() => setNote(""), 2500); };

  const handleCopyCV = async () => {
    await copyToClipboard(generatePlainText());
    flash("Copied — paste it anywhere.");
  };

  const handlePdfCV = async () => {
    try {
      const result = await shareCvPdf(cvContent, { name: s.name || "Physician", degree: s.degreeType || "" });
      if (result === "download") flash("PDF downloaded.");
      else if (result === "share") flash("PDF ready in the share sheet.");
    } catch (err) {
      flash(`Couldn't build the PDF: ${err.message}`);
    }
  };

  const hasData = data.licenses.length > 0 || data.education?.length > 0 || data.cme.length > 0;

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 4 }}>
        <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: T.text }}>CV Generator</h2>
      </div>
      <p style={{ margin: "0 0 16px", fontSize: 14, color: T.textMuted }}>
        Auto-generate a professional CV from your credential data.
      </p>

      {/* Template selector */}
      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        {CV_TEMPLATES.map(t => (
          <button key={t.id} onClick={() => setTemplate(t.id)} style={{
            flex: 1, padding: "12px 10px", borderRadius: 12,
            border: `1px solid ${template === t.id ? T.accent : T.border}`,
            backgroundColor: template === t.id ? T.accentGlow : T.card,
            cursor: "pointer", textAlign: "center",
          }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: template === t.id ? T.accent : T.text }}>{t.name}</div>
            <div style={{ fontSize: 12, color: T.textDim, marginTop: 2 }}>{t.description}</div>
          </button>
        ))}
      </div>

      {/* Action buttons */}
      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        <button onClick={handleCopyCV} style={{
          flex: 1, padding: "12px 16px", borderRadius: 12, border: "none",
          backgroundColor: T.accent, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer",
        }}>Copy to Clipboard</button>
        <button onClick={handlePdfCV} style={{
          flex: 1, padding: "12px 16px", borderRadius: 12, border: `1px solid ${T.border}`,
          backgroundColor: T.card, color: T.text, fontSize: 14, fontWeight: 600, cursor: "pointer",
        }}>Save PDF</button>
      </div>

      {note && (
        <div style={{ marginBottom: 12, padding: "9px 12px", borderRadius: 10, backgroundColor: T.accentDim, color: T.accent, fontSize: 13, fontWeight: 700 }}>{note}</div>
      )}

      {!hasData && (
        <div style={{ textAlign: "center", padding: "26px 18px", backgroundColor: T.card, borderRadius: 14, border: `1px solid ${T.border}`, boxShadow: T.shadow1 }}>
          <div style={{ marginBottom: 10 }}><AsclepiusIcon size={32} color={T.textDim} /></div>
          <div style={{ fontSize: 15, fontWeight: 600, color: T.text, marginBottom: 4 }}>Add credentials first</div>
          <div style={{ fontSize: 14, color: T.textMuted, marginBottom: 14 }}>Your CV will be auto-generated from the licenses, education, and other credentials you add.</div>
          {/* A physician who opened the CV generator with an empty record is
              holding a CV already. Reading theirs is the shortest way to fill
              this page. */}
          <button onClick={() => setImporting(true)} style={{
            padding: "11px 18px", borderRadius: 12, border: "none",
            backgroundColor: T.accent, color: "#fff", fontSize: 14.5, fontWeight: 800, cursor: "pointer",
          }}>Start from my CV</button>
        </div>
      )}

      <Modal open={importing} onClose={() => setImporting(false)} title="Start from your CV" width={880}>
        {/* The review keeps itself open after a save so it can say what it
            wrote; Done is what closes it. */}
        <CvImportReview onClose={() => setImporting(false)} />
      </Modal>

      {/* Preview */}
      {hasData && (
        <div>
          <button onClick={() => setPreview(!preview)} style={{
            padding: "6px 12px", fontSize: 13, fontWeight: 600, borderRadius: 8,
            border: `1px solid ${T.border}`, backgroundColor: "transparent", color: T.textMuted,
            cursor: "pointer", marginBottom: 10,
          }}>{preview ? "Hide Preview" : "Show Preview"}</button>

          {preview && (
            <div style={{
              backgroundColor: T.card, border: `1px solid ${T.border}`, borderRadius: 14,
              padding: "18px 20px", boxShadow: T.shadow1,
            }}>
              {cvContent.map((section, idx) => {
                if (section.type === "header") {
                  return (
                    <div key={idx} style={{ marginBottom: 16, paddingBottom: 12, borderBottom: `2px solid ${T.accent}`, textAlign: "center" }}>
                      <div style={{ fontSize: 20, fontWeight: 800, color: T.text }}>{section.name}</div>
                      {section.address && <div style={{ fontSize: 13, color: T.textMuted }}>{section.address}</div>}
                      <div style={{ fontSize: 13, color: T.textMuted, wordBreak: "break-word" }}>{[section.email, section.website, section.phone].filter(Boolean).join(" \u00b7 ")}</div>
                      {section.specialties.length > 0 && (
                        <div style={{ fontSize: 14, color: T.accent, fontWeight: 600, marginTop: 2 }}>
                          {`${section.fullDegree ? section.fullDegree + " — " : ""}${section.specialties.map(id => id.split(":").pop()).join(", ")}`}
                        </div>
                      )}
                    </div>
                  );
                }
                return (
                  <div key={idx} style={{ marginBottom: 14 }}>
                    <div style={{ fontSize: 15, fontWeight: 700, color: T.accent, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 8, borderBottom: `1px solid ${T.border}`, paddingBottom: 4 }}>
                      {section.title}
                    </div>
                    {section.items.map((item, i) => (
                      <div key={i} style={{ marginBottom: item.subhead ? 4 : 10, paddingLeft: item.subhead ? 0 : 10, marginTop: item.subhead ? 6 : 0 }}>
                        {item.primary && (
                          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                            <div style={{ fontSize: item.subhead ? 14 : 15, fontWeight: item.subhead ? 800 : 600, color: T.text }}>{item.primary}</div>
                            {item.date && <div style={{ fontSize: 12, color: T.textDim, flexShrink: 0, marginLeft: 10 }}>{item.date}</div>}
                          </div>
                        )}
                        {item.secondary && <div style={{ fontSize: 13, color: item.primary ? T.textMuted : T.text, lineHeight: 1.5 }}>{item.secondary}</div>}
                        {item.detail && <div style={{ fontSize: 13, color: T.textDim }}>{item.detail}</div>}
                      </div>
                    ))}
                  </div>
                );
              })}
              <div style={{ fontSize: 11, color: T.textDim, textAlign: "center", marginTop: 10, borderTop: `1px solid ${T.border}`, paddingTop: 8 }}>
                Generated by CredentialDOMD | {new Date().toLocaleDateString()}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default memo(CVGenerator);
