// GENERATED by scripts/sync-shared-app-modules.mjs from src/constants/credentialTypes.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
import { professionOf } from "./professions.js";

export const CERTIFICATION_TYPE = "Certification";

// Licence-section types that never expire: a course or device certification,
// and the licensing exams and the ECFMG certificate, which are passed or
// granted once. They save without a date, are never chased for one, and a
// leftover "not yet known" flag on them is not a question to resolve.
export const NON_EXPIRING_LICENSE_TYPES = Object.freeze([CERTIFICATION_TYPE, "USMLE", "COMLEX", "ECFMG Certificate"]);
// The PA and NP licensing exams, passed once. Kept apart from the list above
// so that list (and everything printed from it) is unchanged for MD and DO.
// NCCPA and every NP certification expire and are never here.
export const APP_NON_EXPIRING_LICENSE_TYPES = Object.freeze(["PANCE", "NCLEX-RN"]);
export function isInherentlyNonExpiringLicense(type) {
  const t = String(type || "");
  return NON_EXPIRING_LICENSE_TYPES.includes(t) || APP_NON_EXPIRING_LICENSE_TYPES.includes(t);
}

export const LICENSE_TYPES_MD = [
  "State Medical License",
  "DEA Registration",
  "State Controlled Substance",
  "Board Certification (ABMS)",
  "ECFMG Certificate",
  "USMLE",
  "BLS Certification",
  "ACLS Certification",
  "ATLS Certification",
  "Fluoroscopy Permit",
  "Laser Safety Certificate",
  CERTIFICATION_TYPE,
  "Other",
];

export const LICENSE_TYPES_DO = [
  "State Medical License (DO)",
  "State Medical License (MD-equiv)",
  "DEA Registration",
  "State Controlled Substance",
  "Board Certification (AOA)",
  "Board Certification (ABMS)",
  "COMLEX",
  "USMLE",
  "BLS Certification",
  "ACLS Certification",
  "ATLS Certification",
  "Fluoroscopy Permit",
  "Laser Safety Certificate",
  CERTIFICATION_TYPE,
  "Other",
];

// Physician assistant: the state PA licence (some states say "physician
// associate"), NCCPA certification and the PANCE.
export const LICENSE_TYPES_PA = [
  "State Physician Assistant License",
  "DEA Registration",
  "State Controlled Substance",
  "Prescriptive Authority",
  "Practice Agreement",
  "Board Certification (NCCPA)",
  "PANCE",
  "BLS Certification",
  "ACLS Certification",
  "PALS Certification",
  "ATLS Certification",
  "Fluoroscopy Permit",
  CERTIFICATION_TYPE,
  "Other",
];

// Nurse practitioner: the APRN licence or certificate and the RN licence
// (single state or multistate), national certification by its certifier.
export const LICENSE_TYPES_NP = [
  "APRN License (NP)",
  "RN License",
  "RN License (Multistate)",
  "DEA Registration",
  "State Controlled Substance",
  "Prescriptive Authority",
  "Practice Agreement",
  "Board Certification (AANPCB)",
  "Board Certification (ANCC)",
  "Board Certification (PNCB)",
  "Board Certification (NCC)",
  "Board Certification (AACN)",
  "NCLEX-RN",
  "BLS Certification",
  "ACLS Certification",
  "PALS Certification",
  "NRP Certification",
  CERTIFICATION_TYPE,
  "Other",
];

const byProfession = (deg, { md, d0, pa, np }) => {
  if (deg === "DO") return d0;
  const p = professionOf(deg);
  return p === "pa" ? pa : p === "np" ? np : md;
};

// Blank, MD and anything unrecognised keep the MD list, as before.
export const getLicenseTypes = (deg) => byProfession(deg, { md: LICENSE_TYPES_MD, d0: LICENSE_TYPES_DO, pa: LICENSE_TYPES_PA, np: LICENSE_TYPES_NP });

/** Every licence type any profession can file, for intake that does not know the profession. */
export const ALL_LICENSE_TYPES = Object.freeze([...new Set([...LICENSE_TYPES_MD, ...LICENSE_TYPES_DO, ...LICENSE_TYPES_PA, ...LICENSE_TYPES_NP])]);

export const PRIVILEGE_TYPES = [
  "Full Admitting Privileges",
  "Surgical Privileges",
  "Courtesy Privileges",
  "Temporary Privileges",
  "Telemedicine Privileges",
  "Emergency Privileges",
  "Consulting Privileges",
];

export const INSURANCE_TYPES = [
  "Medical Malpractice (Occurrence)",
  "Medical Malpractice (Claims-Made)",
  "Medical Professional Liability Coverage",
  "Tail Coverage",
  "General Liability",
  "Umbrella/Excess Liability",
  "Cyber Liability",
  "Workers Compensation",
  "Health Insurance (personal)",
  "Dental Insurance",
  "Vision Insurance",
  "Disability Insurance",
  "Life Insurance",
];

export const CME_CATEGORIES_MD = [
  "AMA PRA Category 1",
  "AMA PRA Category 2",
  "State-Specific Required",
  "MOC Part II (Lifelong Learning)",
  "MOC Part IV (Practice Improvement)",
  "Self-Assessment",
  "Grand Rounds",
  "Other",
];

export const CME_CATEGORIES_DO = [
  "AOA Category 1-A",
  "AOA Category 1-B",
  "AOA Category 2-A",
  "AOA Category 2-B",
  "AMA PRA Category 1",
  "AMA PRA Category 2",
  "OCC Component 2 (Lifelong Learning)",
  "OCC Component 4 (Practice Assessment)",
  "State-Specific Required",
  "Grand Rounds",
  "Other",
];

// PA credit categories by sponsor. Self-assessment and PI-CME are NCCPA
// activity types any Category 1 sponsor can carry, so they are an attribute
// of the entry (custom field "NCCPA Activity"), not a category. PANRE-LA
// quarters are credited by NCCPA itself and logged at the raw 2 credits.
export const CME_CATEGORIES_PA = [
  "AAPA Category 1 CME",
  "AMA PRA Category 1",
  "AOA Category 1-A",
  "AAFP Prescribed Credit",
  "NCCPA PANRE-LA (Category 1 Self-Assessment)",
  "Category 2 CME",
  "State-Specific Required",
  "Other",
];

// NP continuing education in contact hours, by accreditor.
export const CME_CATEGORIES_NP = [
  "Accredited Nursing CE",
  "AMA PRA Category 1",
  "AAPA Category 1 CME",
  "Joint Accreditation CE",
  "Non-accredited CE",
  "State-Specific Required",
  "Other",
];

export const getCMECategories = (deg) => byProfession(deg, { md: CME_CATEGORIES_MD, d0: CME_CATEGORIES_DO, pa: CME_CATEGORIES_PA, np: CME_CATEGORIES_NP });

/** Every CME or CE category any profession can log, for intake that does not know the profession. */
export const ALL_CME_CATEGORIES = Object.freeze([...new Set([...CME_CATEGORIES_MD, ...CME_CATEGORIES_DO, ...CME_CATEGORIES_PA, ...CME_CATEGORIES_NP])]);

// CME entry attributes stored in cme.custom_fields (jsonb, no migration).
export const PHARMACOLOGY_HOURS_FIELD = "Pharmacology Hours";
export const NCCPA_ACTIVITY_FIELD = "NCCPA Activity";
export const NCCPA_ACTIVITIES = Object.freeze(["Self-Assessment", "PI-CME"]);

// Case categories follow the ACGME Review Committee for Neurological Surgery's
// "Defined Case Categories" (effective 7/1/2019) so a case log groups the same
// way a residency case log and credentialing reviewers already expect.
export const CASE_CATEGORY_GROUPS = [
  {
    header: "Cranial",
    options: [
      "Cranial: Tumor General",
      "Cranial: Tumor Sellar/Parasellar",
      "Cranial: Trauma/Other",
      "Cranial: Decompressive Hemicraniectomy",
      "Cranial: Evacuation of Intraparenchymal Hematoma",
      "Cranial: Vascular Open",
      "Cranial: Vascular Endovascular",
      "Cranial: CSF Diversion/ETV/Other",
      "Cranial/Extracranial: Pain",
      "Cranial/Extracranial: Functional Disorder",
      "Cranial/Extracranial: Epilepsy",
    ],
  },
  {
    header: "Spinal",
    options: [
      "Spinal: Anterior Cervical",
      "Spinal: Posterior Cervical",
      "Spinal: Thoracic/Lumbar/Sacral/Instrumentation/Fusion",
      "Spinal: Lumbar Laminectomy/Laminotomy",
      "Spinal: Stimulation/Lesion/Pump/Other",
    ],
  },
  {
    header: "Peripheral Nerve & Other",
    options: ["Peripheral Nerve", "Radiosurgery", "Peripheral Device Management"],
  },
  {
    header: "Critical Care",
    options: [
      "Airway Management",
      "Angiography",
      "Arterial Line Placement",
      "CVP Line Placement",
      "EVD/Transdural Monitor Placement",
      "Lumbar/Other Puncture/Drain Placement",
      "Percutaneous Tap of CSF Reservoir",
    ],
  },
  {
    header: "Pediatric",
    options: [
      "Pediatric: Cranial Tumor",
      "Pediatric: Cranial Trauma/Other",
      "Pediatric: CSF Diversion/ETV/Other",
      "Pediatric: Spinal",
    ],
  },
  { header: "Other", options: ["Other"] },
];

/**
 * What the ACGME actually files under a category, in its own words.
 *
 * A surgeon logged a kyphoplasty, read down this list, and found nothing that
 * looked like one. He was right to: the category it belongs to is called
 * "Spinal: Stimulation/Lesion/Pump/Other", which names four things and then a
 * shrug, and a kyphoplasty is none of the four.
 *
 * The ACGME's own Institutional Case Report Form breaks that category into
 * five case types (Report Form rows A58-A62), and the last of them is
 * "Image-guided kyphoplasty/biopsy/injection". The category total at B63 sums
 * that row, so the placement is structural and not a reading of the layout.
 *
 * Only categories with a sourced breakdown appear here. The rest have no entry
 * rather than a guess, because a hint invented for a career case log is worse
 * than no hint.
 */
export const CASE_CATEGORY_HINTS = {
  "Spinal: Stimulation/Lesion/Pump/Other":
    "Spinal stimulation for pain or a functional disorder, cordotomy or intradural rhizotomy, sympathectomy, intrathecal pump, and image-guided kyphoplasty, biopsy or injection.",
};

export const CASE_CATEGORIES = CASE_CATEGORY_GROUPS.flatMap(g => g.options);

export const HEALTH_RECORD_CATEGORIES = ["Vaccination", "Titer / Immunity", "TB Test", "Drug Screen", "Fit Test"];

export const TITER_TYPES = [
  "Hepatitis B Surface Antibody (HBsAb)",
  "MMR Panel (Measles, Mumps, Rubella)",
  "Measles (Rubeola) IgG",
  "Mumps IgG",
  "Rubella IgG",
  "Varicella Zoster IgG",
  "Hepatitis C Antibody",
  "Other Titer",
];

export const TITER_RESULTS = ["Immune", "Not Immune", "Equivocal", "Negative", "Positive", "Pending"];

export const DRUG_SCREEN_TYPES = [
  "9-Panel Urine", "10-Panel Urine", "5-Panel Urine",
  "Hair Follicle", "Breath Alcohol", "Other",
];

export const DRUG_SCREEN_RESULTS = ["Negative", "Positive", "Dilute", "Pending", "Refused"];

export const VACCINATION_TYPES = [
  "Hepatitis B", "MMR (Measles, Mumps, Rubella)", "Varicella (Chickenpox)",
  "Influenza (Flu)", "COVID-19", "Tdap (Tetanus, Diphtheria, Pertussis)",
  "Meningococcal", "Polio (IPV)", "Hepatitis A", "HPV", "Other",
];

export const TB_TEST_TYPES = [
  "PPD/TST (Skin Test)", "QuantiFERON-TB Gold", "T-SPOT.TB",
  "Chest X-Ray", "Other",
];

export const FIT_TEST_TYPES = [
  "N95 Respirator", "PAPR (Powered Air-Purifying)", "Half-Face Respirator",
  "Full-Face Respirator", "Other",
];

export const TB_RESULTS = ["Negative", "Positive", "Indeterminate"];

export const EDUCATION_TYPES = [
  "Doctor of Osteopathic Medicine (DO)",
  "Doctor of Medicine (MD)",
  "Bachelor of Science (BS)",
  "Bachelor of Arts (BA)",
  "Master of Science (MS)",
  "Master of Public Health (MPH)",
  "Fellowship Certificate",
  "Residency Certificate",
  "Internship Certificate",
  "Other",
];

export const EDUCATION_TYPES_PA = [
  "Master of Physician Assistant Studies (MPAS)",
  "Master of Science in Physician Assistant Studies (MSPAS)",
  "Master of Medical Science (MMS)",
  "Master of Health Science (MHS)",
  "Bachelor of Science (BS)",
  "Bachelor of Arts (BA)",
  "Master of Science (MS)",
  "Master of Public Health (MPH)",
  "Postgraduate PA Program Certificate",
  "Other",
];

export const EDUCATION_TYPES_NP = [
  "Master of Science in Nursing (MSN)",
  "Doctor of Nursing Practice (DNP)",
  "Post-Graduate APRN Certificate",
  "Bachelor of Science in Nursing (BSN)",
  "Associate Degree in Nursing (ADN)",
  "Bachelor of Science (BS)",
  "Bachelor of Arts (BA)",
  "Master of Science (MS)",
  "Master of Public Health (MPH)",
  "NP Fellowship or Residency Certificate",
  "Other",
];

export const getEducationTypes = (deg) => {
  const p = professionOf(deg);
  return p === "pa" ? EDUCATION_TYPES_PA : p === "np" ? EDUCATION_TYPES_NP : EDUCATION_TYPES;
};

export const getHealthRecordTypes = (category) => {
  if (category === "Vaccination") return VACCINATION_TYPES;
  if (category === "Titer / Immunity") return TITER_TYPES;
  if (category === "TB Test") return TB_TEST_TYPES;
  if (category === "Drug Screen") return DRUG_SCREEN_TYPES;
  if (category === "Fit Test") return FIT_TEST_TYPES;
  return [];
};

/** Result choices for a health-record category (empty = free text). */
export const getHealthRecordResults = (category) => {
  if (category === "Titer / Immunity") return TITER_RESULTS;
  if (category === "Drug Screen") return DRUG_SCREEN_RESULTS;
  return [];
};

/** Screening / background-check report types. */
export const SCREENING_TYPES = [
  "Background Screening Report",
  "Drug Screen Report",
  "Occupational Health Panel",
  "OIG / SAM Exclusion Check",
  "Sanctions / Licensure Monitoring",
  "Fingerprinting / Livescan",
  "Other Screening",
];

export const SCREENING_RESULTS = ["Clear", "Review", "Complete", "Pending", "Flagged"];

export const WORK_HISTORY_TYPES = [
  "Full-Time Employed",
  "Part-Time Employed",
  "Independent Contractor",
  "Locum Tenens",
  "Academic Faculty",
  "Fellowship",
  "Residency",
  "Internship",
  "Military Service",
  "Volunteer",
  "Other",
];

export const REFERENCE_RELATIONSHIPS = [
  "Colleague/Peer",
  "Supervisor/Chair",
  "Partner/Co-Physician",
  "Residency Director",
  "Fellowship Director",
  "Department Head",
  "Medical Director",
  "Other",
];

// A PA or NP names the physician they practise with; MD and DO keep the list above.
export const getReferenceRelationships = (deg) => {
  const p = professionOf(deg);
  if (p !== "pa" && p !== "np") return REFERENCE_RELATIONSHIPS;
  return [...REFERENCE_RELATIONSHIPS.slice(0, -1), "Supervising/Collaborating Physician", "Other"];
};

export const MALPRACTICE_OUTCOMES = [
  "Dismissed/No Merit",
  "Settled - No Admission",
  "Settled - With Conditions",
  "Judgment for Defendant",
  "Judgment for Plaintiff",
  "Pending",
  "Other",
];

export const SECTION_META = {
  license: { label: "License / Certification", icon: "\ud83e\udea3", color: "#6366f1", section: "licenses" },
  cme: { label: "CME Credit", icon: "\ud83d\udcda", color: "#10b981", section: "cme" },
  privilege: { label: "Hospital Privilege", icon: "\ud83c\udfe5", color: "#f59e0b", section: "privileges" },
  insurance: { label: "Insurance Policy", icon: "\ud83d\udee1\ufe0f", color: "#ef4444", section: "insurance" },
  healthRecord: { label: "Health Record", icon: "\ud83d\udc89", color: "#ec4899", section: "healthRecords" },
  education: { label: "Education / Training", icon: "\ud83c\udf93", color: "#8b5cf6", section: "education" },
  agreement: { label: "Contract", icon: "\ud83d\udcdd", color: "#0ea5e9", section: "locumContracts" },
  travel: { label: "ID / Travel Document", icon: "\ud83e\udeaa", color: "#0891b2", section: "travelDocs" },
  // A receipt has two possible homes (Work > Expenses to bill an agency, or
  // the deduction ledger); the scan card picks, so no fixed section here.
  receipt: { label: "Expense Receipt", icon: "\ud83e\uddfe", color: "#d97706", section: null },
  // Fits no built-in section: filed into one of the physician's own
  // categories (custom_records). No fixed section, like a receipt.
  other: { label: "Other (your categories)", icon: "\ud83d\uddc2\ufe0f", color: "#64748b", section: null },
  unknown: { label: "Unrecognized Document", icon: "\u2753", color: "#6b7280", section: null },
};
