// GENERATED by scripts/sync-shared-app-modules.mjs from src/constants/expenseCategories.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
// Category chips on the Work > Expenses form (billable to a locums agency).
// Shared with the receipt scanner so a scanned toll slip or rental folio
// lands in the same vocabulary a typed expense uses, and the expense invoice
// labels the line the same way either way.
export const EXPENSE_CATEGORIES = [
  "Airfare", "Baggage", "Gas", "Hotel", "Meals", "Mileage", "Parking",
  "Rental car", "Rideshare / Taxi", "Tolls", "Other",
];
