// GENERATED by scripts/sync-shared-app-modules.mjs from src/constants/professionCopy.js. Do not edit.
// Change the source and run: node scripts/sync-shared-app-modules.mjs
// scripts/shared-app-modules.test.mjs fails when this copy drifts from its source.
// The words the app uses for the member's own profession (DESIGN 5.2).
// MD and DO keep every string they had. Audience "member": a blank profession
// reads as physician copy in the app. Audience "third-party" (share text,
// CV, invoices, the credential portal): a blank profession is neutral, since
// a document sent out never asserts what the member has not chosen.
import { professionOf } from "./professions.js";

const PHYSICIAN = Object.freeze({
  noun: "physician", nounCap: "Physician", licenseNoun: "medical license", ceNoun: "CME", unit: "hours",
  servicesPhrase: "physician services", profileHeading: "Physician Profile", tagline: "Physician Credentials",
  honorific: "Dr.", fallbackName: "Physician",
});
const PA = Object.freeze({
  noun: "physician assistant", nounCap: "Physician Assistant", licenseNoun: "physician assistant license", ceNoun: "CME", unit: "hours",
  servicesPhrase: "physician assistant services", profileHeading: "Profile", tagline: "PA Credentials",
  honorific: "", fallbackName: "Clinician",
});
const NP = Object.freeze({
  noun: "nurse practitioner", nounCap: "Nurse Practitioner", licenseNoun: "APRN or RN license", ceNoun: "CE", unit: "contact hours",
  servicesPhrase: "nurse practitioner services", profileHeading: "Profile", tagline: "NP Credentials",
  honorific: "", fallbackName: "Clinician",
});
const NEUTRAL = Object.freeze({
  noun: "clinician", nounCap: "Clinician", licenseNoun: "license", ceNoun: "CME", unit: "hours",
  servicesPhrase: "clinical services", profileHeading: "Profile", tagline: "Credentials",
  honorific: "", fallbackName: "Clinician",
});

export function professionCopy(degreeType, { audience = "member" } = {}) {
  const p = professionOf(degreeType);
  if (p === "physician") return PHYSICIAN;
  if (p === "pa") return PA;
  if (p === "np") return NP;
  return audience === "third-party" ? NEUTRAL : PHYSICIAN;
}
